### ISSUE TITLE
Generating synchronous methods and generating response classes generates invalid code

### ISSUE THREAD

**Issue by mortlDanske** [RicoSuter/NSwag#1069]
It seems that when selecting to generate sync methods along with response classes (/WrapResponses:true /GenerateSyncMethods:true) then the signature of the sync methods are wrong. The code simply does not build.

Example of some generated code (note that apart from the `Task` the async and sync method differ in wrapping with `SwaggerResponse`). Note that since the sync method simply uses the async method this will not build:
```cs
        /// <param name="tags">tags to filter by</param>
        /// <param name="limit">maximum number of results to return</param>
        /// <returns>pet response</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        public System.Collections.ObjectModel.ObservableCollection<Pet> FindPets(System.Collections.Generic.IEnumerable<string> tags, int? limit)
        {
            return System.Threading.Tasks.Task.Run(async () => await FindPetsAsync(tags, limit, System.Threading.CancellationToken.None)).GetAwaiter().GetResult();
        }
    
        /// <param name="tags">tags to filter by</param>
        /// <param name="limit">maximum number of results to return</param>
        /// <returns>pet response</returns>
        /// <exception cref="SwaggerException">A server side error occurred.</exception>
        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        public async System.Threading.Tasks.Task<SwaggerResponse<System.Collections.ObjectModel.ObservableCollection<Pet>>> FindPetsAsync(System.Collections.Generic.IEnumerable<string> tags, int? limit, System.Threading.CancellationToken cancellationToken)
        {
```

Example files:
[ErrorExample.zip](https://github.com/RSuter/NSwag/files/1491217/ErrorExample.zip)

**Comment by mortlDanske** [comment]
That was fast :-)

**Comment by elemarios** [comment]
Hello I was hoping this was the answer I was searching for but it's not. In my case with same configuration as described above the "return" is missing for the Synchronous method so it can't compile.

![1](https://user-images.githubusercontent.com/48031572/53442727-b26a0800-39e8-11e9-8317-5aef5c1d8175.png)

**Comment by RSuter** [comment]
@mortlDanske sorry, closed by mistake. Is this still an issue?

**Comment by elemarios** [comment]
It seems that I reopened this issue  sorry, @mortlDanske didn't . The title of the post is exactly what is happening to me (same configuration), but different issue. The **return** is missing in Synchronous method

**Comment by mortlDanske** [comment]
I'm unsure about how this is usually done - but I'd recon that this issue should be closed and a new one opened, since the issue elemarios experiences relates to a different bug in the source code?

**Comment by elemarios** [comment]
Hello @RicoSuter . The bug still continue even with last version of NswagStudio(12.0.18.0) , I was wondering if you'd had a chance to replicate it. I noticed this bug  still as Opened. Do I need to log a new bug?

**Comment by RicoSuter** [comment]
Should be fixed in the next version :-)
