### ISSUE TITLE
TypeScript Generation- enum as string literal

### ISSUE THREAD

**Issue by MgSam** [RicoSuter/NSwag#1188]
It would be great to have a feature that can take C# enums and instead of generating them as TypeScript enums, generate them as TypeScript string literals.

So for example, in the Web API (in C#):
``` C#
enum Dog
{
    Rover,
    Lassie,
    Fido,
    Cody
}
```

And the generated TypeScript code:

``` TypeScript
export type Dog = 'Rover' | 'Lassie' | 'Fido' | 'Cody';
```

This is useful because otherwise the user has to write something manually to convert from strings to the enum values (say when reading the value from a `select`). It's much easier to just keep everything as a string.

**Comment by RSuter** [comment]
I think if you use string based enums, you can just cast string to enum... see https://github.com/RSuter/NJsonSchema/wiki/Enums But yes, this feature makes sense with union string types. It must be implemented in NJsonSchema enabled with a new setting.

**Comment by trejjam** [comment]
I solved this with custom template `Enum.liquid`:
```liquid
{% if HasDescription -%}
/** {{ Description }} */
{% endif -%}
{% if ExportTypes %}export {% endif %}type {{ Name }} = {% for enumeration in Enums -%}{% if Enums.first.Value != enumeration.Value %} | {% endif %}{{ enumeration.Value }}{% endfor -%};
```
