### ISSUE TITLE
SwaggerToCSharpClientGenerator - Partial methods are not declared "public"

### ISSUE THREAD

**Issue by CodingDinosaur** [RicoSuter/NSwag#1301]
The partial methods generated by the SwaggerToCSharpClientGenerator are defaulting to internal access, which means that even though the class is public, the methods themselves cannot be implemented outside the assembly directly containing the generated code (without declaring "internalsvisibleto" ahead of time).

We generate NSWag clients and put them in Nuget packages, and the presence of these partial methods was one of the biggest appeals for using NSWag over other options.  However, because these methods are internal, they can't be implemented in consuming projects.

```csharp
partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);
partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);
```

I believe the relevant code is here:
https://github.com/RSuter/NSwag/blob/48533c361ac8c82d7f53415f3e36e0cad32cc0f0/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L54-L59

**Comment by RSuter** [comment]
How should it be changed?

**Comment by RSuter** [comment]
Partial classes and methods must be implemented in the same project and partial method cannot have a modifier: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/partial-method

**Comment by CodingDinosaur** [comment]
You're right of course, and I feel like a bit of an idiot -- of course partial is a compile-time construct and so attempting to implement in another assembly doesn't even make sense.

Perhaps I should turn this into a feature request then -- a way to maintain these or similar injection points but from another assembly.  I'm pretty busy at work right now so I haven't had a ton of time to look into this but a few thoughts:
- Perhaps the client class could take in an optional interface, say "IInjectionPoint" or some such - similar to a WCF message inspector - which would define these four methods.  This would allow for the creation of injection point classes that could be passed into the client class and called if present.

Pseudocode:
```csharp
public partial MyClientClass : BaseClientClass, IMyClientClass
{
  public string BaseUrl;
  private readonly HttpClient _httpClient;
  private readonly IInjectionPoint _injectionPoint;

  public MyClientClass(HttpClient httpClient, string baseUrl, IInjectionPoint injectionPoint = null)
  {
    _httpClient = httpClient;
    BaseUrl = baseUrl;
    _injectionPoint = injectionPoint;
  }

  public async Task<SwaggerResponse> MyGetRequestAsync(string myParam)
  {   
    // Other prep stuff, can also call partials
     _injectionPoint?.PrepareRequest(_httpClient, request, urlBuilder);
    var response = await _httpClient.SendAsync(request);
    _injectionPoint?.ProcessResponse(_httpClient, response);
    // Other post-call stuff...
  }
}

public interface IInjectionPoint
{
  void PrepareRequest(HttpClient client, HttpRequestMessage request, UrlBuilder urlBuilder);
  void ProcessResponse(HttpClient client, HttpResponseMessage response);
}
```

- Another route might be an option to change these from "partial" to "protected virtual" with empty implementations, so the client could be sub-classed and the methods overwritten.  I think I'm personally more partial to the compositional route, though.
- Would such methods need to live side by side with the partials or replace them?  I imagine we want to leave the existing partial methods intact as to not break anyone using the existing functionality, or maybe make them mutually exclusive to a setting for the injection interface methods?

Anyway, just some thoughts.  There may be a better approach entirely I just haven't considered yet -- overall I'm just looking for way to add extensibility points to do things like hook up to custom logging solutions, or make special considerations for certain kinds of data / services, etc.
