### ISSUE TITLE
How to display class in Swagger UI ?

### ISSUE THREAD

**Issue by seanmars** [RicoSuter/NSwag#1373]
Can i force to display some class to model?
Has any attributes to use?

**Comment by RSuter** [comment]
I dont really understand your question. But NSwag adds only dtos which are actually used or are referenced with the KnownTypeAttribute, but you can manually add more: https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors#sample-add-additional-types-from-an-assembly

**Comment by seanmars** [comment]
@RSuter 
I have a enum, and i want display the enum list and desc in the swagger ui. Has any way to do that? Thanks.

**Comment by RSuter** [comment]
So the enum is displayed but the descriptions arent? Can you post sample controller and spec?

**Comment by seanmars** [comment]
@RSuter 
Both not displayed, not bug.
Just want to know how to display the enum and the desc of each field.

**Comment by RSuter** [comment]
Actually swagger only supports enum values and the enum names are a custom extension of nswag for better code gen. Probably Swagger ui or redoc doesnt support this exrension (x-enumNames)
