### ISSUE TITLE
AspNetCoreToSwaggerGenerator and TestServer (CLI): Cannot resolve IApiDescriptionGroupCollectionProvider (.NET Core 2.0)

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NSwag#1413]
When executing the new AspNetCoreToSwaggerGenerator against a .NET Core 2.0 via CLI and TestServer, it cannot resolve IApiDescriptionGroupCollectionProvider:

![image](https://user-images.githubusercontent.com/2603405/41773402-3f98752c-761c-11e8-9f78-31bc1ed9fad6.png)

But examining the services object, it clearly has a IApiDescriptionGroupCollectionProvider registration, even with the correct type ($1):

![image](https://user-images.githubusercontent.com/2603405/41773505-90e324fe-761c-11e8-800b-a327550474d9.png)

Also this works for the .NET Core 2.1 sample project. 

Steps to reproduce: 

- Open NSwag.sln
- Select NSwag.ConsoleCore as startup project and select 2.0: 

![image](https://user-images.githubusercontent.com/2603405/41773608-e3ba0c42-761c-11e8-8b3e-75940f3b8708.png)

- In project debug settings, use the command line args: `run "MyPath\NSwag\samples\WithoutMiddleware\Sample.AspNetCore20\nswag_assembly.nswag"`
- Run project with all exceptions enabled (break on all exceptions)

The same works for `MyPath\NSwag\samples\WithoutMiddleware\Sample.AspNetCore21\nswag_assembly.nswag`

/cc @pranavkm @rynowak any idea why this is happening?

**Comment by Tratcher** [comment]
No, Host.Services is replaced by app services after Startup. And that service is pretty clearly in the Realized Services list.

**Comment by Ghostbird** [comment]
Any news on / workarounds for this? I'm currently stuck at this issue while trying to generate documentation from my .NET Core 2.1 API.

**Comment by RSuter** [comment]
@Ghostbird I think this problem here is only an issue with .NET Core <= 2.0, with 2.1+ it should work. What is your exception?

**Comment by Ghostbird** [comment]
Exception
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Mvc.ApiExplorer.IApiDescriptionGroupCollectionProvider' has been registered.
```
.NET Core version
```
dotnet --version
2.1.500
```
System info
```
uname -a
Linux gijsbertdebian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```
MsBuild configuration excerpt
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="12.0.4"/>
    <PackageReference Include="NSwag.SwaggerGeneration.AspNetCore" Version="12.0.4"/>
  </ItemGroup>
  <Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Core21) run nswag.json" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
</Project>
```
nswag.json
```json
{
  "runtime": "NetCore21",
  "defaultVariables": null,
  "swaggerGenerator": {
    "aspNetCoreToSwagger": {
      "project": "Api.csproj",
      "noBuild": true
    }
  },
  "codeGenerators": {}
}
```

**Comment by Ghostbird** [comment]
Found that it is the same issue solved [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/299#issuecomment-281722880).

When using `services.AddMvcCore()` instead of `services.AddMvC()` in `Startup.cs:ConfigureServices()`, you must do:
``` C#
services.AddMvcCore().AddApiExplorer()
```

**Comment by adam-ah** [comment]
Nice find, @Ghostbird!

For Google's sake, if you get 

> InvalidOperationException: API Explorer not registered in DI.

on startup, the solution is to add 

```
services.AddMvcCore().AddApiExplorer();
```

in ```public void ConfigureServices(IServiceCollection services)```
