### ISSUE TITLE
How to override JsonProperty annotations

### ISSUE THREAD

**Issue by joshstella75** [RicoSuter/NSwag#1415]
Is it possible to override or opt out on generating the JsonProperty annotations when generating the Client through _WebApi2Swagger_ or _Swagger2CsClient_?

Currently we use NSwag as a pass-through between our publicly facing and internal-use Web API's.  I would like to have the ability to set `Required = Newtonsoft.Json.Required.Default` or `Required = Newtonsoft.Json.Required.AllowNull` on my non-nullable properties.  This would allow us to automatically set the values of these properties to the default value if they came in as _null_ or _empty string_.

There doesn't seem to be a setting during either step of the generation to handle cases like this.  For the time being, we are using a SchemaProcessor to set any non-nullable properties to `IsRequired = false`.  Though this generates the properties as nullable in the Generated Client, this has the intended effect of setting the default values on these properties once it hits the actual API.

I can't help thinking that there _should_ be some way of overriding this behavior.  While this seems to work well, it would be more ideal to have the nullability of the properties in my DTO object match my API's return class.  Any thoughts or suggestions?

**Comment by Boomit2016** [comment]
Found a solution yet? I'm having the same problem...

**Comment by joshstella75** [comment]
Unfortunately, no.  We initially went with the SchemaProcessor to explicitly set properties certain properties to null.  But that seemed heavy handed.  I believe the solution in place currently was to have our API endpoints return dedicated DTO objects.  In some cases, some endpoints were returning the entity class, which produced less than ideal results.
