### ISSUE TITLE
msi Setup is not signed, antivirus prevents to install NSwag

### ISSUE THREAD

**Issue by paulovila** [RicoSuter/NSwag#1437]
As part of corporate network security, the NSwag setup can't be run, because the antivirus catches the msi as it thinks it is not properly signed. 
Is it possible to use a valid certificate to allow install it in a corporate network? 
Regards, PV

**Comment by RSuter** [comment]
This is on my todo list... can you use the binaries from the ZIP file in the meantime?

https://github.com/RSuter/NSwag/releases

**Comment by paulovila** [comment]
I've tried with downloading the zip file and then un-blocking it, but the antivirus quarantines it:
Scan type: Auto-Protect Scan
Event: Security Risk Found!
Security risk detected: WS.Reputation.1
File: C:\Users\paulo.vila\Downloads\NSwag\NSwagStudio.exe
Location: Quarantine
Action taken: Quarantine succeeded : Access denied
Date found: Thursday, July 5, 2018  10:10:36 AM

**Comment by RSuter** [comment]
> WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec's community of users and therefore are likely to be security risks. Detections of this type are based on Symantec's reputation-based security technology.

Low reputation? :-)

**Comment by paulovila** [comment]
yeah, it's funny the way they name it :) , even usb ports are locked down here in the office.

**Comment by RSuter** [comment]
Maybe you can install it via chocolatey to circumvent this? https://chocolatey.org/packages/NSwagStudio

**Comment by paulovila** [comment]
Unfortunately the file is also caught
