### ISSUE TITLE
How to configurate "toISOString()" to "toLocaleString()" in the toJSON function

### ISSUE THREAD

**Issue by ccccccmd** [RicoSuter/NSwag#1510]
in the service-proxies.ts (auto generate code)
when the type is **moment**
the auto gengerate code is **toISOString**
how to configurate it like **toLocaleString** or something else

my class is

export class Campaign implements ICampaign { 
startTime: moment.Moment | undefined; endTime: moment.Moment | undefined; id: number | undefined;
}

and the **toJSON** function:

toJSON(data?: any) { 
data = typeof data === 'object' ? data : {}; data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined; data["endTime"] = this.endTime ? this.endTime.**toISOString()** : <any>undefined; data["id"] = this.id; return data; 
}

thanks!

**Comment by RSuter** [comment]
At the moment, this is not possible and this is part of the ugliest code in the project: 

https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/DataConversionGenerator.cs#L92

**Comment by ccccccmd** [comment]
thanks a lot!

**Comment by MaximBalaganskiy** [comment]
It would be awesome to just have an option to specify a custom function instead of `toISOString`. 
This way a consumer could have his own formatter by monkey patching `Date`.
Currently, I just post process the clients to replace the function.

**Comment by kbiasci** [comment]
Hey @RicoSuter ,

I have to admit that I have the same issue.
Was there some progress made on this issue?

Thanks mate

**Comment by AlahmadiQ8** [comment]
we have the same issue. it would be great to have customization option on to string for dates
