### ISSUE TITLE
SwaggerToCSharpControllerGenerator: Generate Task<ActionResult<T>> for ASP.NET Core

### ISSUE THREAD

**Issue by altso** [RicoSuter/NSwag#1547]
Please add an ability to generate controller actions that return `ActionResult<T>`/`Task<ActionResult<T>>` for ASP.NET Core.

Ref: #1386

**Comment by RSuter** [comment]
What’s exactly the benefit of that?

**Comment by altso** [comment]
I believe it's the same as with `System.Net.Http.HttpResponseMessage` for ASP.NET WebAPI which is allowed right now (https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Controller.liquid#L94).

It gives you a better flexibility around http status codes.

```csharp
[HttpPut("resource/{id}")]
public async Task<ActionResult<Resource>> UpdateResource(int id, [FromBody] Resource resource)
{
    if (/* resource exists */)
    {
        if (/* custom validation (e.g. check for fields that could not be updated) */)
        {
            if (/* user is permitted to update this specific resource */)
            {
                // update resource and return an updated copy (e.g. last modified date field)
                var updatedResource = _resourceService.Update(resource);
                return Ok(updatedResource);
            }

            return Forbid();
        }

        return BadRequest();
    }

    return NotFound();
}
```

**Comment by optuuttila** [comment]
I actually played around this a bit and came up with this fork:
https://github.com/optuuttila/NSwag/commit/cef9ecc1693bde731a636c52173562a832e3ef6a

It results in following kind of generated code:
Interface:
        System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<MyModel>> MyMethodAsync(string param1, string param2);

Controller:
        public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<MyModel>> MyMethod(string param1, string param2)
        {
            return _implementation.MyMethodAsync(param1, param2);
        }

Obviously the code would need to be finalized (a PR for the NJsonSchema.CodeGeneration.CSharp package), but before doing any of that I just wanted to ask whether this is anything along the lines you would accept as an PR?

**Comment by RSuter** [comment]
Why in NJS? Just create a PR with WIP in the name and ill look into it, you can still improve it etc.

**Comment by optuuttila** [comment]
Ok, I'm very new to contributing to open source projects and I have no idea what NJS means, but I'll start creating the PR's. Thanks.

**Comment by RSuter** [comment]
NJS = NJsonSchema

**Comment by RicoSuter** [comment]
Closed by https://github.com/RicoSuter/NSwag/pull/1942
