### ISSUE TITLE
Problem when adding an api controller method with an IFormFile parameter

### ISSUE THREAD

**Issue by srollinet** [RicoSuter/NSwag#1550]
Hi,

I tried to add a new method in one of my controller. This method takes an `IFormFile` parameter
As soon as I add this method, there is a new `consumes` array in swagger.json which only contains the value `"multipart/form-data"`

Problem is when I generate the ts client, all the methods try to send multipart/form-data

I tried to create a simplified repro project, but I cannot reproduce it :(
Any idea about the cause?

This is the new controller

```
    [ApiVersion("1")]
    public class ConfigurationController : ApiControllerBase
    {
        [HttpPost, DisableRequestSizeLimit]
        public void UploadFile(IFormFile file)
        {
        }
    }
```

swagger.json before I add the controller (there is no consumes array)
Note: in my repro project, there is always a consumes array. Do you know what can prevent it to appear?
```
{
  "x-generator": "NSwag v11.18.6.0 (NJsonSchema v9.10.67.0 (Newtonsoft.Json v11.0.0.0))",
  "swagger": "2.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "produces": [
    "text/plain",
    "application/json",
    "text/json"
  ],
  ...
}
```

swagger.json when I add the new controller
```
{
  "x-generator": "NSwag v11.18.6.0 (NJsonSchema v9.10.67.0 (Newtonsoft.Json v11.0.0.0))",
  "swagger": "2.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "consumes": [
    "multipart/form-data"
  ],
  "produces": [
    "text/plain",
    "application/json",
    "text/json"
  ],
  ...
}
```

**Comment by RSuter** [comment]
Are you using UseSwagger*() or UseSwagger*WithApiExplorer()?

**Comment by srollinet** [comment]
I use NSwag.MSBuild / aspNetCoreToSwagger 11.18.7

I managed to reproduce it here.

[nswag_consumes_issue.zip](https://github.com/RSuter/NSwag/files/2321417/nswag_consumes_issue.zip)

I think the problem is not the IFormFile parameter itself, but the absence of the `consumes` array if I remove the `UploadController`

**Comment by miroga** [comment]
Hi,

do you have any update for this issue?
I'd like to upgrade to .net core 2.1 and this is blocking me.

**Comment by srollinet** [comment]
Hi, any news about this issue? I still have the problem with the last version and changing the compatibility version doesn't change anything

**Comment by srollinet** [comment]
Here is an updated version of the repro.

In UploadController, add or remove [SwaggerIgnore] and see how it affects the generated swagger.json file, and the TypeScript service.

[nswag_consumes_issue.zip](https://github.com/RicoSuter/NSwag/files/3030597/nswag_consumes_issue.zip)

**Comment by RicoSuter** [comment]
Please retest with v12.1.0 soon

**Comment by srollinet** [comment]
I can confirm that everything works now, thanks!
