### ISSUE TITLE
Is it possible to inject more interfaces in generated client constructor

### ISSUE THREAD

**Issue by adnangohar** [RicoSuter/NSwag#1571]
Hi, 

Is is possible to inject custom/own Interfaces/Classes in the constructor of the generated client like it is done for the HttpClient using the InjectHttpClient property ?

I have seen if we use ConfigurationClass we can inject a class but it requires a base class as well.

-Adnan

**Comment by adnangohar** [comment]
Hi,

Thank you for the response. The main problem that I was facing was logging request and response objects. I wanted to inject my ILogger in the client so that I can use the partial functions ProcessRequest and ProcessResponse to log the request and response. The configuration class did not help as it could only be used in base class. 

Anyway I moved to templates and fixed my scenario by having my own template :). Would be good to have an option to inject classes in the client. 

Thanks for a great library.

**Comment by RSuter** [comment]
I'd really like to improve the client generators and make them more extendable (e.g. option to generate partial methods OR use base class methods...). But the project is big and there or problems which are more important atm...

**Comment by RSuter** [comment]
Maybe we should close this issue and open a new one like "option to generate partial methods OR use base class methods" or do you come up with something better? Maybe an option to use ILogger in the packaged templates?
