### ISSUE TITLE
TypeScript change <any> to as any

### ISSUE THREAD

**Issue by dested** [RicoSuter/NSwag#1590]
TypeScript is moving away from casting via the bracket syntax in favor of the as syntax, primarily for tsx purposes. With babel7 now supporting typescript, but with no support for the bracket casting syntax, I believe it makes sense to move away from this syntax in favor of as.

**Comment by RSuter** [comment]
> With babel7 now supporting typescript, but with no support for the bracket casting syntax

How is it supporting TypeScript if it's missing that?

**Comment by dested** [comment]
Unfortunately that is a very good question. 

https://blogs.msdn.microsoft.com/typescript/2018/08/27/typescript-and-babel-7/

There are more than a few features that it outright does not support. The only one that nswag seems to break for is casting. Also things like async generators which still need babel plugins to support, but work out of the box for TypeScript. I would rate the support as "piss poor", but react native 57+ will use it exclusively.

**Comment by RSuter** [comment]
My question: Is the as operator supported in all ts versions?

**Comment by dested** [comment]
It goes back to 1.6 so it should be safe to implement. 

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-1-6.html

**Comment by MarcosMeli** [comment]
@RSuter can I take this issue and modify the angular template first ?

**Comment by MarcosMeli** [comment]
![image](https://user-images.githubusercontent.com/446796/49606177-666f7000-f971-11e8-8b57-a4ff20de1cc7.png)

tslint raise warning because this

**Comment by axel-habermaier** [comment]
Due to this issue, it is no longer possible to use NSwag with the latest version of create-react-app and TypeScript.

**Comment by RSuter** [comment]
So this is only a problem with babel’s typescript implementation? Documented here: https://devblogs.microsoft.com/typescript/typescript-and-babel-7/

**Comment by axel-habermaier** [comment]
The latest version of create-react-app has TypeScript support built-in based on Babel (whereas before, you would use a now-deprecated fork of create-react-app that actually used the standard TypeScript compiler). Since NSwag generates ``<any>null`` casts, for example, the generated clients don't compile anymore.

**Comment by RSuter** [comment]
Ok, i think it should be quite simple to replace all those <any> casts to “as any” casts in all templates...

**Comment by RSuter** [comment]
It seems that the as operator has been introduced in ts 1.6 - so this should not be a breaking change for any users. 

https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#new-tsx-file-extension-and-as-operator

**Comment by axel-habermaier** [comment]
Hold on a second... it seems this is now actually supported: https://babeljs.io/docs/en/babel-preset-typescript

It didn't work when I tried it out as I used a ``.tsx`` extension, where these casts are not supported even by the TypeScript compiler. With a ``.ts`` extension, it works with the latest create-react-app. Sorry about that!

**Comment by VoronFX** [comment]
Any plans on releasing fix for this? 
With some new `@babel/preset-typescript` options that comes from some out-of-the box React setups (e.g. razzle), this syntax is considered invalid as there no more distingushing between `.ts` and `.tsx` files 

Options that causing issues:
```
"@babel/preset-typescript",
      {
        "isTSX": true,
        "allExtensions": true
      }
```

**Comment by VoronFX** [comment]
I've made a PR for this by myself, please take a look above

**Comment by MohammadRoshani** [comment]
The Problem still exists:

![image](https://user-images.githubusercontent.com/42032036/198874847-abf848ba-9fa1-47b6-8d57-db82e1882c46.png)
![image](https://user-images.githubusercontent.com/42032036/198874841-5d63246b-b4d8-49c2-beb9-a58bd371fb59.png)

swagger:
`{
  "openapi": "3.0.1",
  "info": {
    "title": "TestWebApi",
    "version": "1.0"
  },
  "paths": {
    "/WeatherForecast": {
      "get": {
        "tags": [
          "WeatherForecast"
        ],
        "operationId": "GetWeatherForecast",
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/WeatherForecast"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "WeatherForecast": {
        "type": "object",
        "properties": {
          "date": {
            "type": "string",
            "format": "date-time"
          },
          "temperatureC": {
            "type": "integer",
            "format": "int32"
          },
          "temperatureF": {
            "type": "integer",
            "format": "int32",
            "readOnly": true
          },
          "summary": {
            "type": "string",
            "nullable": true
          }
        },
        "additionalProperties": false
      }
    }
  }
}`

Nswag:

`
{
  "runtime": "Default",
  "defaultVariables": null,
  "documentGenerator": {
    "fromDocument": {
      "url": "https://localhost:7062/swagger/index.html",
      "output": null,
      "newLineBehavior": "Auto"
    }
  },
  "codeGenerators": {
    "openApiToTypeScriptClient": {
      "className": "{controller}Service",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 4.3,
      "template": "Axios",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "withCredentials": false,
      "useSingletonProvider": false,
      "injectionTokenType": "OpaqueToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "OffsetMomentJS",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": true,
      "exportTypes": true,
      "wrapDtoExceptions": false,
      "exceptionClass": "ApiException",
      "clientBaseClass": null,
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": null,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromFirstTagAndPathSegments",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "enumStyle": "Enum",
      "useLeafType": false,
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateTypeCheckFunctions": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "useAbortSignal": false,
      "inlineNamedDictionaries": true,
      "inlineNamedAny": false,
      "includeHttpContext": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "TestService.tsx",
      "newLineBehavior": "Auto"
    }
  }
}
`

Generated file:

    `//----------------------
    // <auto-generated>
    //     Generated using the NSwag toolchain v13.17.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
    // </auto-generated>
    //----------------------
    
    /* tslint:disable */
    /* eslint-disable */
    // ReSharper disable InconsistentNaming
    
    import axios, { AxiosError } from 'axios';
    import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';
    
    import * as moment from 'moment';
    
    export class WeatherForecastService {
        private instance: AxiosInstance;
        private baseUrl: string;
        protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;
    
        constructor(baseUrl?: string, instance?: AxiosInstance) {
        
            this.instance = instance ? instance : axios.create();
        
            this.baseUrl = baseUrl !== undefined && baseUrl !== null ? baseUrl : "";
        
        }
    
        /**
         * @return Success
         */
        weatherForecast(  cancelToken?: CancelToken | undefined): Promise<WeatherForecast[]> {
            let url_ = this.baseUrl + "/WeatherForecast";
            url_ = url_.replace(/[?&]$/, "");
        
            let options_: AxiosRequestConfig = {
                method: "GET",
                url: url_,
                headers: {
                    "Accept": "text/plain"
                },
                cancelToken
            };
        
            return this.instance.request(options_).catch((_error: any) => {
                if (isAxiosError(_error) && _error.response) {
                    return _error.response;
                } else {
                    throw _error;
                }
            }).then((_response: AxiosResponse) => {
                return this.processWeatherForecast(_response);
            });
        }
    
        protected processWeatherForecast(response: AxiosResponse): Promise<WeatherForecast[]> {
            const status = response.status;
            let _headers: any = {};
            if (response.headers && typeof response.headers === "object") {
                for (let k in response.headers) {
                    if (response.headers.hasOwnProperty(k)) {
                        _headers[k] = response.headers[k];
                    }
                }
            }
            if (status === 200) {
                const _responseText = response.data;
                let result200: any = null;
                let resultData200  = _responseText;
                if (Array.isArray(resultData200)) {
                    result200 = [] as any;
                    for (let item of resultData200)
                        result200!.push(WeatherForecast.fromJS(item));
                }
                else {
                    result200 = <any>null;
                }
                return Promise.resolve<WeatherForecast[]>(result200);
            
            } else if (status !== 200 && status !== 204) {
                const _responseText = response.data;
                return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }
            return Promise.resolve<WeatherForecast[]>(null as any);
        }
    }
    
    export class WeatherForecast implements IWeatherForecast {
        date?: moment.Moment;
        temperatureC?: number;
        readonly temperatureF?: number;
        summary?: string | undefined;
    
        constructor(data?: IWeatherForecast) {
            if (data) {
                for (var property in data) {
                    if (data.hasOwnProperty(property))
                        (<any>this)[property] = (<any>data)[property];
                }
            }
        }
    
        init(_data?: any) {
            if (_data) {
                this.date = _data["date"] ? moment.parseZone(_data["date"].toString()) : <any>undefined;
                this.temperatureC = _data["temperatureC"];
                (<any>this).temperatureF = _data["temperatureF"];
                this.summary = _data["summary"];
            }
        }
    
        static fromJS(data: any): WeatherForecast {
            data = typeof data === 'object' ? data : {};
            let result = new WeatherForecast();
            result.init(data);
            return result;
        }
    
        toJSON(data?: any) {
            data = typeof data === 'object' ? data : {};
            data["date"] = this.date ? this.date.toISOString(true) : <any>undefined;
            data["temperatureC"] = this.temperatureC;
            data["temperatureF"] = this.temperatureF;
            data["summary"] = this.summary;
            return data;
        }
    }
    
    export interface IWeatherForecast {
        date?: moment.Moment;
        temperatureC?: number;
        temperatureF?: number;
        summary?: string | undefined;
    }
    
    export class ApiException extends Error {
        override message: string;
        status: number;
        response: string;
        headers: { [key: string]: any; };
        result: any;
    
        constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
            super();
        
            this.message = message;
            this.status = status;
            this.response = response;
            this.headers = headers;
            this.result = result;
        }
    
        protected isApiException = true;
    
        static isApiException(obj: any): obj is ApiException {
            return obj.isApiException === true;
        }
    }
    
    function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
        if (result !== null && result !== undefined)
            throw result;
        else
            throw new ApiException(message, status, response, headers, null);
    }
    
    function isAxiosError(obj: any | undefined): obj is AxiosError {
        return obj && obj.isAxiosError === true;
    }`
