### ISSUE TITLE
Add local Nuget's cache folder to reference paths resolves to the wrong path

### ISSUE THREAD

**Issue by darklajid** [RicoSuter/NSwag#1646]
Trying to fix some problems that probably are due to the work in progress state of the API explorer generation support I tried and enabled "Add local Nuget's cache folder to reference paths" (both for Reflection based generation and API explorer. Let's ignore the latter).

I get the error ```System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Users\Ben\.nuget\packages'```.

That folder doesn't exist. Compare:

```
C:\Users\Ben>dotnet nuget locals all --list
info : http-cache: C:\Users\Ben\AppData\Local\NuGet\v3-cache
info : global-packages: C:\Users\Ben\.nuget\packages\
info : temp: C:\Users\Ben\AppData\Local\Temp\NuGetScratch
info : plugins-cache: C:\Users\Ben\AppData\Local\NuGet\plugins-cache
```
and
```
C:\Users\Ben>echo %USERPROFILE%/.nuget/packages
C:\Users\Ben/.nuget/packages
```

Where is the D:\ (that drive does exist) coming from? How does NSwag resolve that path if not using either of the two ways above?

**Comment by darklajid** [comment]
I tried the assembly loading change (the built target creating a 'References' folder) and ran into other problems.. Ignoring that for now / assuming user errors: The linked implementation uses %HOMEPATH%. This is what 'set' lists here as my environment variables:

```
C:\Users\Ben>set | findstr HOME
HOMEDRIVE=C:
HOMEPATH=\Users\Ben
```

```\Users\Ben``` is a path rooted in the current drive in Windows, and if your current directory is ```D:\Some\Thing``` then ```\Users\Ben``` refers to ```D:\Users\Ben``` - on the wrong drive. That's not the value nuget uses / not based on the complete and correct path.

I assume that ```Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)``` wasn't possible for cross-platform reasons? Could it use %USERPROFILE% (contains the correct path) instead or would ``Environment.ExpandEnvironmentVariables("%HOMEDRIVE%%HOMEPATH%")``` and ```Environment.ExpandEnvironmentVariables("%HOME%")``` for linux respectively work as a potential replacement? That is, keeping the structure of the method, but adding HOMEDRIVE to the window side of things and wrapping the variable in % for expansion, then calling ExpandEnvironmentVariables instead of GetEnvironmentVariable?

**Comment by karm435** [comment]
We are facing a similar problem in Windows. It does not work for Devs who have code checked out of drive other than C drive.
