### ISSUE TITLE
ASP.Net Core - API Explorer: Order of parameters

### ISSUE THREAD

**Issue by jmatter** [RicoSuter/NSwag#1686]
After updating from v11.20.0 to v11.20.1 the order of the parameters in the generated Swagger JSON (OpenApi3) has changed:

Previously a parameter in the route (defined on the controller) was the first in the generated file, followed by the parameters defined in the action inside the controller.

Now the parameters inside the controller are listed first, and the general route param comes last.

This changes the param order in the resulting TypeScript client for Angular2+ which breaks the previous implementation of the client.

Is there a way to specify the param order?

**Comment by RSuter** [comment]
Probably a regression from this fix: https://github.com/RSuter/NSwag/commit/5b50dd9a8101bf8e418c15aba139366f83897162

**Comment by jmatter** [comment]
Before the update, the path parameter doesn't have a x-position property:
```
"parameters": [
          {
            "name": "layer",
            "in": "query",
            "required": true,
            "description": "Selected Layer",
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "x-position": 1
          },
          {
            "name": "periodId",
            "in": "query",
            "required": true,
            "description": "Period",
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "x-position": 2
          },
          {
            "name": "realmId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "nullable": false
          }
        ]
```

After the update:
```
"parameters": [
          {
            "name": "layer",
            "in": "query",
            "required": true,
            "description": "Selected Layer",
            "schema": {
              "type": "integer",
              "format": "int64"
            },
            "x-position": 1
          },
          {
            "name": "periodId",
            "in": "query",
            "required": true,
            "description": "Period",
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "x-position": 2
          },
          {
            "name": "realmId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            },
            "x-position": 3
          }
        ]
```

The path parameter without the x-position property was the first argument of the generated methods before. Now it is the last (because of x-position: 3).

The order doesn't really matter I think, as long as it won't change with future releases.

**Comment by RSuter** [comment]
Of course, the goal is to keep this stable. Because openapi does not specify all parameters in this array (body is defined in another property) we had to introduce this position in order to keep the order from the original controller operation. I hope the current implementation is fine and can be kept stable...
