### ISSUE TITLE
Build issues experienced in current master branch

### ISSUE THREAD

**Issue by Jehoel** [RicoSuter/NSwag#1702]
### Environment:

* Windows 10, version 1809
* Visual Studio 2017, version 15.8.8
* Visual Studio Installer shows ".NET Core cross-platform development" is selected under Workloads, but under Individual Components the ".NET Core runtime" checkbox is unchecked (weird...).
* Node.js 10.13.0 LTS with `npm` 6.4.1 installed and in my user PATH.
* Control Panel > Programs and Features reports I have:
  * Microsoft .NET Core SDK 2.1.402 (x64)
  * Microsoft .NET Core SDK 2.1.403 (x64)

I checked the ".NET Core runtime" item and installed it and restarted my computer, just to be sure.

### Steps to reproduce:

1. `git clone https://myfork.git` into `C:\git\forks\NSwag`
1. Open a Visual Studio 2017 Developer Command Prompt
1. `cd C:\git\forks\NSWag\build`
1. `00_Install.cmd` (this runs successfully)
1. `01_Build.bat`
1. The build fails.

The first errors come from this line of `01_Build.bat`:

    msbuild "%~dp0/../src/NSwag.sln" /p:Configuration=Release || goto :error

Errors include:

> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (default target) (8:5) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (Build target) (8:7) ->
> (CoreCompile target) ->
>   Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs(94,35): error CS1513: } expected [C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (default target) (8:5) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (Build target) (8:8) ->
>   Commands\SwaggerGeneration\AspNetCore\AspNetCoreToSwaggerCommand.cs(94,35): error CS1513: } expected [C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (default target) (8:5) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (Build target) (8:9) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. [C:\git\forks\NS
> wag\src\NSwag.Commands\NSwag.Commands.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (default target) (8:5) ->
> "C:\git\forks\NSwag\src\NSwag.Commands\NSwag.Commands.csproj" (Build target) (8:10) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\git\forks\NS
> wag\src\NSwag.Commands\NSwag.Commands.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Console\NSwag.Console.csproj" (default target) (20) ->
> (ImplicitlyExpandNETStandardFacades target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets(67,5): error
>  NETSDK1050: The version of Microsoft.NET.Sdk used by this project is insufficient to support references to libraries targeting .NET Standard 1.5 or higher.  Please in
> stall version 2.0 or higher of the .NET Core SDK. [C:\git\forks\NSwag\src\NSwag.Console\NSwag.Console.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (default target) (27) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (Build target) (27:2) ->
> (GenerateBuildDependencyFile target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\gi
> t\forks\NSwag\src\NSwag.Annotations\NSwag.Annotations.csproj'. This can indicate a missing project reference. [C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCo
> re.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (default target) (27) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (Build target) (27:3) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets(92,5): error : Cannot find project info for 'C:\gi
> t\forks\NSwag\src\NSwag.Annotations\NSwag.Annotations.csproj'. This can indicate a missing project reference. [C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCo
> re.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (default target) (27) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (Build target) (27:4) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. [C:\git\forks\NS
> wag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (default target) (27) ->
> "C:\git\forks\NSwag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj" (Build target) (27:5) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\git\forks\NS
> wag\src\NSwag.ConsoleCore\NSwag.ConsoleCore.csproj]
> 
> 
>   C:\git\forks\NSwag\src\NSwag.Sample.NetCoreAngular\NSwag.Sample.NetCoreAngular.csproj : error : Unable to locate the .NET Core SDK. Check that it is installed and th
> at the version specified in global.json (if any) matches the installed version.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Sample.NetCoreAngular\NSwag.Sample.NetCoreAngular.csproj" (default target) (29) ->
>   C:\git\forks\NSwag\src\NSwag.Sample.NetCoreAngular\NSwag.Sample.NetCoreAngular.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Sample.NetCoreAurelia\NSwag.Sample.NetCoreAurelia.csproj" (default target) (33) ->
>   C:\git\forks\NSwag\src\NSwag.Sample.NetCoreAurelia\NSwag.Sample.NetCoreAurelia.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Console.x86\NSwag.Console.x86.csproj" (default target) (34) ->
> (ImplicitlyExpandNETStandardFacades target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Microsoft\Microsoft.NET.Build.Extensions\Microsoft.NET.Build.Extensions.NETFramework.targets(67,5): error
>  NETSDK1050: The version of Microsoft.NET.Sdk used by this project is insufficient to support references to libraries targeting .NET Standard 1.5 or higher.  Please in
> stall version 2.0 or higher of the .NET Core SDK. [C:\git\forks\NSwag\src\NSwag.Console.x86\NSwag.Console.x86.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.SwaggerGeneration.AspNetCore.Tests\NSwag.SwaggerGeneration.AspNetCore.Tests.csproj" (default target) (36) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\git\forks\NS
> wag\src\NSwag.SwaggerGeneration.AspNetCore.Tests\NSwag.SwaggerGeneration.AspNetCore.Tests.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Sample.NETCore11\NSwag.Sample.NETCore11.csproj" (default target) (37) ->
>   C:\git\forks\NSwag\src\NSwag.Sample.NETCore11\NSwag.Sample.NETCore11.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Integration.NETCore11\NSwag.Integration.NETCore11.csproj" (default target) (38) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. [C:\git\forks\NS
> wag\src\NSwag.Integration.NETCore11\NSwag.Integration.NETCore11.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Sample.NETCore20\NSwag.Sample.NETCore20.csproj" (default target) (39) ->
>   C:\git\forks\NSwag\src\NSwag.Sample.NETCore20\NSwag.Sample.NETCore20.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Core.Tests\NSwag.Core.Tests.csproj" (default target) (40) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. [C:\git\forks\NS
> wag\src\NSwag.Core.Tests\NSwag.Core.Tests.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Sample.NETCore21\NSwag.Sample.NETCore21.csproj" (default target) (41) ->
>   C:\git\forks\NSwag\src\NSwag.Sample.NETCore21\NSwag.Sample.NETCore21.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.Web' specified could not be found.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.Sample.NETCore20.Part\NSwag.Sample.NETCore20.Part.csproj" (default target) (42) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.0.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.0. [C:\git\forks\NS
> wag\src\NSwag.Sample.NETCore20.Part\NSwag.Sample.NETCore20.Part.csproj]
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.SwaggerGeneration.AspNetCore.Tests.Web\NSwag.SwaggerGeneration.AspNetCore.Tests.Web.csproj" (default target) (43) ->
>   C:\git\forks\NSwag\src\NSwag.SwaggerGeneration.AspNetCore.Tests.Web\NSwag.SwaggerGeneration.AspNetCore.Tests.Web.csproj : error MSB4236: The SDK 'Microsoft.NET.Sdk.W
> eb' specified could not be found.
> 
> 
> "C:\git\forks\NSwag\src\NSwag.sln" (default target) (1) ->
> "C:\git\forks\NSwag\src\NSwag.AssemblyLoader.Tests\NSwag.AssemblyLoader.Tests.csproj" (default target) (44) ->
> "C:\git\forks\NSwag\src\NSwag.AssemblyLoader.Tests\NSwag.AssemblyLoader.Tests.csproj" (Build target) (44:2) ->
> (_CheckForUnsupportedNETCoreVersion target) ->
>   C:\Program Files (x86)\Microsoft Visual Studio 2017\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets(112,5): error : The current .
> NET SDK does not support targeting .NET Core 2.1.  Either target .NET Core 1.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.1. [C:\git\forks\NS
> wag\src\NSwag.AssemblyLoader.Tests\NSwag.AssemblyLoader.Tests.csproj]
> 
>     8 Warning(s)
>     22 Error(s)
> 
> Time Elapsed 00:00:12.22

The full `msbuild.log` output is about 23MB in size, I can attach it if you like.

The errors about not having the .NET Core 2.1 SDK installed are the strangest.

**Comment by RSuter** [comment]
Many project are multi framework targeting full net, core 1.0, core 1.1, core 2.1, maybe these sdks are all required? But i recently reinstalled my machine and cant remember if that was necessary... probably will have to do it again to update the dev guide.

**Comment by Jehoel** [comment]
The error about the `}` in `AspNetCoreToSwaggerCommand.cs` is because the `#if NET451` is non-exhaustive, it's visible when the `#if` branches are collapsed:

![image](https://user-images.githubusercontent.com/1693078/47884197-1428b580-dded-11e8-8690-6e4c0c09e0ba.png)

Oddly, this is the first error output, before any other errors about missing or incorrect SDKs. Where is `NET451` or `NETCOREAPP` or `NETSTANDARD` defined?

A fix for that would be to use `[#error](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-error)` in an `#else` block:

    #if NET451
        ...
    #elif NETCOREAPP || NETSTANDARD
        ...
    #else
        #error No build target symbols defined
    #endif

**Comment by Jehoel** [comment]
I'll create a VM with all the latest .NET Core SDKs installed (for 1.0, 1.1, 2.0, and 2.1) and see what happens...

**Comment by RSuter** [comment]
Strange, 

```
<TargetFrameworks>netcoreapp1.0;netcoreapp1.1;netcoreapp2.0;netcoreapp2.1;net451</TargetFrameworks>
```

should implicitely define those... the else case should not be possible.

**Comment by xt1** [comment]
Check the SDK version in src/global.json

`{ "sdk": {   "version": "2.1.300"  } }`

This version must be available in the list of SDKs installed:
`dotnet --list-sdks`
`2.1.403 [C:\Program Files\dotnet\sdk]`

Either install the missing SDK version, or tweak the `global.json` file to match what you have installed.

**Comment by RSuter** [comment]
maybe we can remove the global.json?

**Comment by RSuter** [comment]
@Jehoel I've removed global.json in PR #1736 - can you retry with latest?

**Comment by Jehoel** [comment]
@RSuter I'm busy this week, I can take another look at this next monday if that's okay.
