### ISSUE TITLE
Nswag studio: assembly specified YamlDotNet.Signed not found

### ISSUE THREAD

**Issue by dylanvdmerwe** [RicoSuter/NSwag#1750]
Trying to use the `ASP.NET Core via API Explorer` functionality in NSwagStudio v12.0 and I get the following exception:

![image](https://user-images.githubusercontent.com/2852839/48673039-f4f88a80-eb45-11e8-9f85-c22a52533b1d.png)

I can get the TypeScript to generate when using the Swagger Specification option. Not sure why I cannot use the API Explorer option. 

In `ConfigureServices` I have added `AddSwaggerDocument()` after `AddMvc()` as well as set the compatibility version. 

In `Configure` I have this after `UseMvc`:
```
    // Add OpenAPI/Swagger middlewares
            app.UseSwagger(); // Serves the registered OpenAPI/Swagger documents by default on `/swagger/{documentName}/swagger.json`
            app.UseSwaggerUi3(); // Serves the Swagger UI 3 web ui to view the OpenAPI/Swagger documents by default on `/swagger`
```

**Comment by RSuter** [comment]
Try to compile your app with

dotnet build /p:CopyLocalLockFileAssemblies=true

**Comment by RSuter** [comment]
Otherwise this looks like a publish bug, maybe i need to release a bug fix

**Comment by dylanvdmerwe** [comment]
I just tried with:
`<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>`

But I still get the same weird YamlDotNet.Signed error. I don't have a reference to this in any of my projects.

**Comment by RSuter** [comment]
Yes, nswag has a dep to this package. It seems that is missing in the installer...

**Comment by RSuter** [comment]
I’m offline and cant check right now, but you could try to save the nswag.json config file and run it with the nswag npm package

**Comment by RSuter** [comment]
I just checked on my PC, after updating NSwagStudio the Yaml dll was indeed missing... then i uninstall and reinstalled NSwagStudio and now it looks good... It seems that there is a problem in the WIX installer upgrade...

**Comment by dylanvdmerwe** [comment]
Uninstall and reinstall fixed the missing dll issue.

**Comment by ikaros88** [comment]
Can confirm that it is simply the missing dll after updating, i copied it from the .nuget folder into the NetCore21 folder and NSwagStudio resumed working.

**Comment by RSuter** [comment]
Very strange, there is no change on the installer project and i can't explain why there's now a file missing - but only after upgrade not normal install.

**Comment by IvanJosipovic** [comment]
Same issue after upgrade, remove/re-install fixed it.
![image](https://user-images.githubusercontent.com/9521987/48820147-74ce5280-ed08-11e8-8a53-8afea676ac1e.png)

**Comment by ranouf** [comment]
@IvanJosipovic thanks, I had the same issue and your solution worked for me!

**Comment by SeriousM** [comment]
yep. that worked for me too! 👍

**Comment by RSuter** [comment]
Does this also happen with the new patch releases?

**Comment by SeriousM** [comment]
Just updated today and only a reinstall worked for me.

**Comment by RSuter** [comment]
Ok thanks for replying. I have no idea how to fix this without this “workaround”.

**Comment by Anderman** [comment]
Updated today and had the same problem. Uninstall and install nswagstudio worked for me.

**Comment by IvanJosipovic** [comment]
The upgrade worked fine for me this time.

**Comment by RSuter** [comment]
From v11 or v12?

**Comment by IvanJosipovic** [comment]
> From v11 or v12?

From 12.0.0.0 to 12.0.4.0

**Comment by RSuter** [comment]
Yes, i expected/hoped that this works :-) thanks for reporting

**Comment by MadMonkey87** [comment]
For me it works in the studio, but not on the CLI...

I've checked the nswag bin directory and the YamlDotNet.Signed is actually there but it won't work, also not if I manually copy this dll into my applications bin folder.

(running on netcore22 btw)

**Comment by StevenSSparks** [comment]
Same issue today - 

Error:
  An assembly specified in the application dependencies manifest (dotnet-nswag.deps.json) was not found:
    package: 'YamlDotNet.Signed', version: '5.0.1'
    path: 'lib/netstandard1.3/YamlDotNet.dll'


Moving from 11 to 12

**Comment by coder8keyboard** [comment]
Uninstalling and reinstalling nswagstudio worked for me.

**Comment by StevenSSparks** [comment]
Yes - The uninstall and reinstall worked for me.  I have noticed some of the default UI settings are causing the functionality of the NSWAG studio to produce c# code that is different that previous versions.

**Comment by RSuter** [comment]
> I have noticed some of the default UI settings are causing the functionality of the NSWAG studio to produce c# code that is different that previous versions.

There are some breaking changes - hence the v12 tag. But with some tweaks you should be able to produce compatible code..
