### ISSUE TITLE
AddOpenApiDocument improvements

### ISSUE THREAD

**Issue by SebastianStehle** [RicoSuter/NSwag#1754]
I have some feature requests:

1. The AddOpenApiDocument method should contain an overload with IServiceProvider

https://github.com/RSuter/NSwag/blob/fad87aa07c0b7f5d0f37d553d869d342699a7eb0/src/NSwag.AspNetCore/Extensions/NSwagServiceCollectionExtensions.cs#L19

2. The AddOpenApiDocument should resolve all IDocumentProcessor and IOperationProcessor from the service provider and add it to the Generator settings.

**Comment by SebastianStehle** [comment]
> The action should provide the IServiceProvider?
Yes

> Not sure whether this is good idea as all processors are applied to all documents and you cannot control on a per-document basis
You do not have to register them then.

**Comment by SebastianStehle** [comment]
Can you provide a quick fix for me? I really need it because some of my processors have dependencies I cannot create my AddOpenApiDocument method because some classes that I would need are internal.

**Comment by RSuter** [comment]
It's probably not that simple because the action is now invoked inline in ConfigureServices but must be invoked lazily in Configure() or when IServiceProvider is available...

**Comment by SebastianStehle** [comment]
You get passed in the ServiceProvider (the `s`) ;)

**Comment by RSuter** [comment]
Nope, the IServiceCollection (i.e. not materialized IServiceProvider)

**Comment by RSuter** [comment]
You probably are not allowed to resolve services in ConfigureServices() but only after this method...

**Comment by SebastianStehle** [comment]
I will provide a PR in a few minutes.

**Comment by SebastianStehle** [comment]
See #https://github.com/RSuter/NSwag/pull/1755

The point is that your services are created lazily. Therefore the service provider is available.

**Comment by SebastianStehle** [comment]
Have you checked the PR?

**Comment by timvandenhof** [comment]
@RicoSuter This can be closed as the PR is merged and out in the wild.
