### ISSUE TITLE
Error TS2449: Class 'BaseClient' used before its declaration

### ISSUE THREAD

**Issue by alvarosinmarca** [RicoSuter/NSwag#1769]
Versions >=12.0.0.0, the class BaseClient is generated at the end of the file and TypeScript throw error "Error TS2449: Class 'BaseClient' used before its declaration".

**Comment by Wezea** [comment]
I'm also facing this issue. 

`Generated using the NSwag toolchain v12.0.1.0 (NJsonSchema v9.12.3.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)`

**Comment by RSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/49067490-880b8180-f224-11e8-9524-1536760fc1c4.png)

![image](https://user-images.githubusercontent.com/2603405/49067517-96f23400-f224-11e8-830a-eebb0d9181d7.png)

![image](https://user-images.githubusercontent.com/2603405/49067524-9fe30580-f224-11e8-9b13-ba643bbb311c.png)

**Comment by Wezea** [comment]
```xml
<Target Name="ClientBuildAndBundle" AfterTargets="Build" Condition="$(SkipCustomization)!='true'">
	<Copy SourceFiles="@(ReferencePath)" DestinationFolder="$(OutDir)References" />
	<Exec Command="$(NSwagExe_Core21) run $(SpaRoot)nswag.json /variables:Configuration=$(Configuration)" />
	<RemoveDir Directories="$(OutDir)References" Condition="$(SkipCustomization)!='true'" />
</Target>
```
```json
"codeGenerators": {
		"swaggerToTypeScriptClient": {
			"className": "{controller}Client",
			"moduleName": "",
			"namespace": "",
			"typeScriptVersion": 2.7,
			"template": "Fetch",
			"promiseType": "Promise",
			"httpClass": "Http",
			"injectionTokenType": "OpaqueToken",
			"dateTimeType": "Date",
			"nullValue": "Undefined",
			"generateClientClasses": true,
			"generateClientInterfaces": true,
			"generateOptionalParameters": false,
			"wrapDtoExceptions": false,
			"wrapResponses": false,
			"generateResponseClasses": false,
			"responseClass": "SwaggerResponse",
			"useTransformOptionsMethod": false,
			"useTransformResultMethod": false,
			"generateDtoTypes": true,
			"operationGenerationMode": "MultipleClientsFromOperationId",
			"markOptionalProperties": true,
			"generateCloneMethod": false,
			"typeStyle": "Interface",
			"extensionCode": "src/api/client.extensions.ts",
			"clientBaseClass": "BaseClient",
			"generateDefaultValues": true,
			"excludedTypeNames": [],
			"handleReferences": false,
			"generateConstructorInterface": true,
			"convertConstructorInterfaceData": false,
			"importRequiredTypes": true,
			"useGetBaseUrlMethod": true,
			"baseUrlTokenName": "API_BASE_URL",
			"queryNullValue": "",
			"output": "src/api/controllers.ts"
		}
	}
```

```javascript
// ...
function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if(result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}

export class BaseClient {

    public getBaseUrl = (path?: string) => {
        return getBaseUrl();
    }
}
// ...

```

**Comment by alvarosinmarca** [comment]
> What is the content of `client.extensions.ts`?

![image](https://user-images.githubusercontent.com/9324962/49088495-ae97df80-f259-11e8-9e42-98e2f9f534fd.png)

export class BaseClient {
	// Este método se ejecuta cada vez que realizamos una petición al servicio web
    protected transformOptions(options: any) {
        return Promise.resolve(options);
    }

    // Método que pinta la petición y respuesta
    protected transformResult(url: string, response: HttpResponseBase, processor: (response: HttpResponseBase) => any): Observable<any> {
        return processor(response);
    }
}

**Comment by RSuter** [comment]
Looks good to me (v12.0.1): 

![image](https://user-images.githubusercontent.com/2603405/49096750-80bb9680-f26b-11e8-9c4b-45742c587b09.png)

Output: 

![image](https://user-images.githubusercontent.com/2603405/49096691-61bd0480-f26b-11e8-976b-94f8688825ff.png)

**Comment by alvarosinmarca** [comment]
XD.

I created a new project with same settings the old project and it remains.

**Project Nswag:**
https://www.dropbox.com/s/rup20qufmu6qwx6/Config-Nswag-Problem-With-BaseClient.nswag?dl=1

**This my settings:** 
![image](https://user-images.githubusercontent.com/9324962/49099877-e3fcf700-f272-11e8-8231-c86045a1909e.png)

**Comment by alvarosinmarca** [comment]
![image](https://user-images.githubusercontent.com/9324962/49102421-1b6ea200-f279-11e8-8a3f-22a8a117d94a.png)

If i press ENTER next to the open bracket class, this character is generated.

Nswag is sensitive from version >=12.0.0.0

Thanks you help @RSuter

**Comment by RSuter** [comment]
This is not good. Will check it

**Comment by Wezea** [comment]
I'm still having this problem with with the latest v12.0.3.0

**Comment by RSuter** [comment]
The fix is not released yet.

**Comment by RSuter** [comment]
@Wezea do you think the fix https://github.com/RSuter/NJsonSchema/commit/a2fd2158785d956b1e010aea58a64884e24178c2 will solve your problem too?

**Comment by Wezea** [comment]
This is the `controller.ts` and `client.extension.ts`. The build chain setting I described [here](https://github.com/RSuter/NSwag/issues/1769#issuecomment-441983743)

The problem is still that the BaseClient is insert after the Client.



[api.zip](https://github.com/RSuter/NSwag/files/2628477/api.zip)

**Comment by jordan-ware** [comment]
I had accidentally added my base class to the `extendedClasses` property which resulted in this behavior... Doesn't appear you've done that, but thought I'd mention it for anyone else who might come along with this issue. Makes sense since extended classes need to be declared after the generated ones.

**Comment by maxotek** [comment]
12.2.5 was working fine for me. But, updating to 12.3.0 which was released 5 hours ago gives me the error `TS2449: Class 'Foo' used before its declaration.`

It seems the ordering of how the model classes are written in the output .ts file is not taking into account the inheritance between them.

**Comment by llusetti** [comment]
> 12.2.5 was working fine for me. But, updating to 12.3.0 which was released 5 hours ago gives me the error `TS2449: Class 'Foo' used before its declaration.`
> 
> It seems the ordering of how the model classes are written in the output .ts file is not taking into account the inheritance between them.

The same happened to me just now

**Comment by RicoSuter** [comment]
Will fix this soon

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/issues/2184
