### ISSUE TITLE
WebAPI action with complex type parameter containing enum array not generating valid Swagger definition

### ISSUE THREAD

**Issue by davidkeaveny** [RicoSuter/NSwag#1842]
I have a WebAPI 2 controller action that looks like this:

```
public IHttpActionResult Get([FromUri] ComplexType parameters)
{
    var result = Query(parameters);
    return Ok(result);
}
```

where `ComplexType` is defined as:

```
[DataContract]
public class ComplexType
{
    [DataMember]
    public int SomeInt { get; set; }
    [DataMember]
    public Statuses[] Status { get; set; }
}

[DataContract]
public enum Statuses
{
    [EnumMember(Value = "inactive")]
    Inactive = 0,
    [EnumMember(Value = "active")]
    Active = 1
}
```

The code works as expected, but when I use NSwagStudio 12.0.0 to generate the Swagger 2.0 definition, it generates code which is marked as invalid by editor.swagger.io:

```
        - type: array
          name: Status
          in: query
          description: >-
            The statuses to search by.
          collectionFormat: multi
          x-nullable: true
          items:
            $ref: '#/definitions/Statuses'
 ```

with the following errors:

```
Schema error at paths['/ExpenseApplications'].get.parameters[1]
should NOT have additional properties
additionalProperty: type, collectionFormat, items, name, in, description, x-nullable
Jump to line 1064
Schema error at paths['/ExpenseApplications'].get.parameters[1].in
should be equal to one of the allowed values
allowedValues: body, header, formData, path
Jump to line 1066
Schema error at paths['/ExpenseApplications'].get.parameters[1].collectionFormat
should be equal to one of the allowed values
allowedValues: csv, ssv, tsv, pipes
Jump to line 1070
Schema error at paths['/ExpenseApplications'].get.parameters[3].items
should NOT have additional properties
additionalProperty: $ref
Jump to line 1072
```

Finally, the NSchema definition for `Statuses` is rendered as:

```
  Statuses:
    type: string
    description: The status of an application.
    x-enumNames:
      - Inactive
      - Active
    enum:
      - Inactive
      - Active
```
This is preventing me from e.g. importing my API definition into Azure API Management. Any ideas what I'm doing wrong?

**Comment by davidkeaveny** [comment]
Looking at the Swagger 2.0 spec, query parameters will only accept arrays of primitive values, which enums apparently aren't regarded as. It seems happier to have the enum defined inline instead.

**Comment by ryankelley** [comment]
@davidkeaveny Did you find a work around for this by chance?

**Comment by davidkeaveny** [comment]
> @davidkeaveny Did you find a work around for this by chance?

Sorry, no I didn't. I'll probably want to revisit this soon, as I'm starting work on a new API project (using Core rather than Framework, but still the same issue would apply)

**Comment by davidkeaveny** [comment]
I've now moved on to an ASP.NET Core project and generating OpenApi 3 specifications; the issue is still here, although now the parser is only complaining about the `collectionFormat: multi`:

```
Structural error at paths./Jobs.get.parameters.3
should NOT have additional properties
additionalProperty: collectionFormat
Jump to line 47
```

**Comment by davidkeaveny** [comment]
In the end I gave up on the code-first approach, and went with design-first instead; that way the spec says exactly what I want to say. I can still use NSwag to generate client/contracts/controllers etc, so it's still all good here.
