### ISSUE TITLE
Typescript compilation error when using momentjs and TypeScript 3

### ISSUE THREAD

**Issue by jannikbuschke** [RicoSuter/NSwag#1859]
Using Typescript 3.* and momentjs for dates I get compile time errors.

Calls like `moment()` generate following error:
>Cannot invoke an expression whose type lacks a call signature. Type 'typeof moment' has no compatible call signatures.ts(2349)
>api.ts(9, 1): Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.

replacing `moment()` calls with `moment.default()` resolves the issue.

Im using following nswag.json
>{
  "runtime": "NetCore21",
  "defaultVariables": null,
  "swaggerGenerator": {
    "fromSwagger": {
      "url": "http://localhost:54408/swagger/v1/swagger.json",
      "output": null
    }
  },
  "codeGenerators": {
    "swaggerToTypeScriptClient": {
      "className": "{controller}Client",
      "moduleName": "",
      "namespace": "",
      "typeScriptVersion": 3.2,
      "template": "Fetch",
      "promiseType": "Promise",
      "httpClass": "HttpClient",
      "useSingletonProvider": false,
      "injectionTokenType": "OpaqueToken",
      "rxJsVersion": 6.0,
      "dateTimeType": "momentjs",
      "nullValue": "Undefined",
      "generateClientClasses": true,
      "generateClientInterfaces": false,
      "generateOptionalParameters": false,
      "exportTypes": true,
      "wrapDtoExceptions": false,
      "clientBaseClass": null,
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "protectedMethods": [],
      "configurationClass": null,
      "useTransformOptionsMethod": false,
      "useTransformResultMethod": false,
      "generateDtoTypes": true,
      "operationGenerationMode": "MultipleClientsFromOperationId",
      "markOptionalProperties": true,
      "generateCloneMethod": false,
      "typeStyle": "Class",
      "classTypes": [],
      "extendedClasses": [],
      "extensionCode": null,
      "generateDefaultValues": true,
      "excludedTypeNames": [],
      "handleReferences": false,
      "generateConstructorInterface": true,
      "convertConstructorInterfaceData": false,
      "importRequiredTypes": true,
      "useGetBaseUrlMethod": false,
      "baseUrlTokenName": "API_BASE_URL",
      "queryNullValue": "",
      "inlineNamedDictionaries": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": ".",
      "serviceSchemes": null,
      "output": "src/generated/api.ts"
    }
  }
}

**Comment by RSuter** [comment]
Is this a typescript version or momentjs version problem?

**Comment by jbuschke** [comment]
Actually the currently generated code seems not to be compliant with ES6. 
The import statement currently used (`import * as moment from "moment"`) is a module import, and modules are not allowed to be called (i.e. `moment()` is forbidden). All named exports of moment can be accesed through the importet object. The default export can be called via `moment.default()` (as far as I understand it)
ref1 https://stackoverflow.com/a/35706271/2017490
ref2 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

In my opinion the correct solution is to change `import * as moment from "moment"` to `import moment from "moment"`. So we just import the default export a name it moment.

**Comment by RSuter** [comment]
Where exactly do you see `moment()` rendered?

**Comment by jannikbuschke** [comment]
In the init(data?:any){} method

its not exactly moment() but `moment(data["started"].toString())`
`started` is a DateTime property in the backend

![image](https://user-images.githubusercontent.com/5894881/50784717-c62da380-12ae-11e9-8d7d-edd4c944c2b1.png)

**Comment by RSuter** [comment]
So what would be the correct code for `moment(data["started"].toString())` ?
Can you create a list of what has to be changed?

**Comment by p-ob** [comment]
I'm seeing this issue as well (targeting TypeScript 3.2 in my application, NSwag is told to use 2.8 as that is the latest option available). I don't know about any backwards compatibility issues that this change might cause, but simply changing `import * as moment from 'moment';` to `import moment from 'moment';` makes the errors further down with e.g. `moment(data["started"].toString())` go away.

**Comment by jannikbuschke** [comment]
agree changing to `import moment from 'moment';` should solve and should also be backwards compatible

**Comment by p-ob** [comment]
I've figured out where this issue comes from. In your tsconfig.json, you might have this property set:
`"allowSyntheticDefaultImports": true,`

This apparently causes the TS compiler error. I don't know if NSwag should do anything to fix this or not, but removing that entry (or setting it to false) got rid of the error for me.

**Comment by jannikbuschke** [comment]
I can confirm that setting `allowSyntheticDefaultImpotrs: false` resolve the issue.
Unfortunatly there is a reason I had set it to true (some other library I am depending on has a weird export definition).

As the currently generated code does not seem to adhere to es2016 I would vote to implement the changes.

**Comment by RSuter** [comment]
So we need to just change the import to 

    import moment from 'moment';

here: 

https://github.com/RSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/File.liquid#L55

and this is backward compatible and not a breaking change for anyone?

BTW: You can already override this template: https://github.com/RSuter/NSwag/wiki/Templates

**Comment by RSuter** [comment]
I've created a PR: https://github.com/RSuter/NSwag/pull/1901

Can you confirm that this will not break existing users?

**Comment by p-ob** [comment]
This is not a seamless upgrade that I can tell. If your tsconfig.json contains the following, you must do the `import moment from 'moment';` default import workflow:
```json
{
    "compilerOptions": {
        ...
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
         ...
    }
}
```

If you don't have the `"allowSyntheticDefaultImports"`, the default import won't work at all, and you'll continue to have to use the import * as moment from 'moment';

I can provide you a sample with more details if that helps. I have a suitable workaround for my project (I don't require the two options noted above). If you do decide to go forward with the change, at least the upgrade path is pretty easy.

I've attached some screenshots that I hope help: 
**With the above options, import * error**:
![image](https://user-images.githubusercontent.com/3483866/51421585-b8590780-1b65-11e9-92b8-c85c206eca9c.png)

**Without the above options, default import error**:
![image](https://user-images.githubusercontent.com/3483866/51421598-ef2f1d80-1b65-11e9-94ed-0d9607ff2051.png)

**Comment by jannikbuschke** [comment]
I tried to test against Typescript 2.9.2 and Typescript 2.7.2.
In Typescript 2.9 I could compile, however users with "allowSyntheticDefaultImports" **would indeed be broken**.

I couldnot test against 2.7 or older versions, as I get a lot of other errors (tsc checks node_modules, and many configs in tsconfig don't work).

What I also tested is leaving the `import * as moment from "moment"` as is and instead changing the `moment(xxx)` calls to `moment.default(xxx)`. This unfortunatly also **does not work** with Typescript 2.9 (works with Typescript 3.*)

Based on the above observations its maybe better to think about other alternatives.

**Comment by FreeFrags** [comment]
Any progress with this issue? as a workaround i now disabled "importRequiredTypes" and added extensioncode for the imports by hand

**Comment by RicoSuter** [comment]
The question is how we should solve this without breaking existing users? Do we need a new setting (i try to avoid that)?

**Comment by MariuszKogut** [comment]
@RicoSuter What about reading the tsconfig.json and tweak the import depending on allowSyntheticDefaultImports?

**Comment by RicoSuter** [comment]
I think that's not a good idea because we dont want to couple this to tsconfig.json (its also not part of the configuration etc.) maybe we should just add a AllowSyntheticDefaultImports to the TypeScript generator...

**Comment by mark-at-tusksoft** [comment]
I have temporarily fixed this by replacing the import with `import moment from 'moment-es6';` and adding that to my packages. Dependencies appear to require es6 modules for angular libraries.
I don't know if this is the ideal solution but it would be nice to have a boolean in the config to tell the generator to use the `moment-es6` package so I don't have to remind myself and my team to update it.

**Comment by RicoSuter** [comment]
You can replace the file template with one with te correct import but probably we should support that with a simple setting.

https://github.com/RicoSuter/NSwag/wiki/Templates

I also have angular 8 project (ts 3?) and i dont have problems with momientjs

**Comment by mark-at-tusksoft** [comment]
> I also have angular 8 project (ts 3?) and i dont have problems with momentjs

Can you generate a library `ng g library <LIBRARY_NAME>` and place your resulting service-proxies.ts under there and let me know if it compiles for you? I had issues with it but it's possible I messed something up.

**Comment by yyjazsf** [comment]
in my way, just disable
`esModuleInterop` in `tsconfig.json`

**Comment by renanaragao** [comment]
> in my way, just disable
> `esModuleInterop` in `tsconfig.json`

work

**Comment by tratefan** [comment]
Hi just adding my input as its Oct 2020 and this is still open.

From MY experience, **NO NEED** to disable `esModuleInterop` in `tsconfig.json` _(as answer before mine suggests)_

All I did was change the following import statement which caused the compilation error:
`import * as moment from 'moment';`
to
`import moment from 'moment';`

In my `tsconfig.json `the following options which i added myself are still set to `_true_`:
```
{
    "compilerOptions": {
        ...
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "allowSyntheticDefaultImports": true,
         ...
    }
}
```

(Also ran `npm audit fix` before compiling - _which we tend to ignore_)

Don't forget to stop app and run `npm install `again (just for extra measures).
Hope this helps 👍

**Comment by mauro1998** [comment]
This is still open :(
Had the same issue with ts-jest, disabling `esModuleInterop` works in my case but gives a bunch of warnings when running tests.
Workaround:
1. Keep `import * as moment from 'moment';` (autogenerated by nswag)
2. Update `tsconfig.spec.json`:
```
"compilerOptions": {
  "esModuleInterop": false,
  "allowSyntheticDefaultImports": true,
  ...
}
```

**Comment by devsienko** [comment]
> This is still open :( Had the same issue with ts-jest, disabling `esModuleInterop` works in my case but gives a bunch of warnings when running tests. Workaround:
> 
> 1. Keep `import * as moment from 'moment';` (autogenerated by nswag)
> 2. Update `tsconfig.spec.json`:
> 
> ```
> "compilerOptions": {
>   "esModuleInterop": false,
>   "allowSyntheticDefaultImports": true,
>   ...
> }
> ```
> 
> Hope it helps.

I created empty Angular 17 project and it doesn't work even with this tsconfig.spec.json fixes
