### ISSUE TITLE
Generating ASP.NET Core server code: multiple controllers

### ISSUE THREAD

**Issue by DrDeterminant** [RicoSuter/NSwag#1870]
Hello,

I would like to know whether it is possible to generate multiple controllers from a single Swagger Specification using nswag. The code generator option "className" can contain some place holder "{controller}". But I could not figure out how this is ever used.

**Comment by KrzysztofKielce** [comment]
Hi @RicoSuter,
Is it possible to split the generated output to multiple controllers in the same way it is done on editor.swagger.io side?

![image](https://user-images.githubusercontent.com/1174432/61932530-f1928a00-af83-11e9-8a19-5471a35a2c3d.png)


PS. NSwag is a great tool - thanks a tone!

**Comment by RicoSuter** [comment]
> create controllers based on the /tags/name values

You can implement an own operation name generator based on this rule, but then you’d need to build your own cli tool based on nswag libs because the cli cannot load custom generators atm

**Comment by KrzysztofKielce** [comment]
Hi, thanks for your response.
I see. How about adding it as an option to the default generator? (any guidance would be appreciated).

**Comment by RicoSuter** [comment]
Maybe its already there, see
https://github.com/RicoSuter/NSwag/tree/master/src/NSwag.CodeGeneration/OperationNameGenerators

**Comment by KrzysztofKielce** [comment]
Yes, it seems so. But after spending half an hour inspecting the code, I still do not know how to use them. Can you give me any clues, especially - if that is configurable or I rather need to modify something in code to use a custom OperationNameGenerator ?

**Comment by RicoSuter** [comment]
You can change to one of these predefined ones with this CLI param: 
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Commands/Commands/CodeGeneration/OpenApiToCSharpCommandBase.cs#L33

https://github.com/RicoSuter/NSwag/blob/85ae862fd6d68173a201a79e0ad06e0be2ec5de1/src/NSwag.Commands/Commands/CodeGeneration/OperationGenerationMode.cs

**Comment by KrzysztofKielce** [comment]
Awesome! Thank you.

**Comment by KrzysztofKielce** [comment]
The ticket seems to be resolved.
