### ISSUE TITLE
Dotnet Core 2.1 'No executable found matching command "dotnet-nswag"'

### ISSUE THREAD

**Issue by farlee2121** [RicoSuter/NSwag#1931]
From the dotnet cli, I run 
`dotnet add package NSwag.ConsoleCore`
 `dotnet restore`

To my understanding, this should register a cli tool `dotnet nswag`. However, running this command only returns `No executable found matching command "dotnet-nswag"`

Here is my dotnet cli version info

> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.503
>  Commit:    4c506e0f35
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17134
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\2.1.503\
> 
> Host (useful for support):
>   Version: 2.1.7
>   Commit:  cca5d72d48
> 
> .NET Core SDKs installed:
>   2.1.202 [C:\Program Files\dotnet\sdk]
>   2.1.500 [C:\Program Files\dotnet\sdk]
>   2.1.502 [C:\Program Files\dotnet\sdk]
>   2.1.503 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>

**Comment by 616b2f** [comment]
I have the same issue. I think it's because to use "dotnet nswag" the tools command name should be "dotnet-nswag" and not "nswag" as it is here https://github.com/RicoSuter/NSwag/blob/fc573a6975446a5ce282de392a7a836a07ff44f5/src/NSwag.ConsoleCore/NSwag.ConsoleCore.csproj#L20

Using only "nswag" in terminal works for me.
