### ISSUE TITLE
Aurelia BaseURL Injection Check

### ISSUE THREAD

**Issue by jordan-ware** [RicoSuter/NSwag#1941]
With the Aurelia template, Clients are prepared with String being injected for the BaseURL:
```
@inject(String, HttpClient)
export class CarService extends ServiceBase {
```
This is OK if you're setting up DI to inject your baseURL, however I don't want to do this because it means I would have to manually register every service in my DI container, e.g.
``` 
aurelia
    .use
    .instance(
      CarService,
      new CarService('http://path/to/my/base/url', aurelia.container.get(HttpClient))
    );
```
as mentioned here: https://github.com/aurelia/dependency-injection/issues/170

I've gone down the route of having a base class that implements `this.getBaseUrl("")` so I can manage this another way, however when this check is hit:

`this.baseUrl = baseUrl ? baseUrl : this.getBaseUrl("");`

It uses baseUrl which Aurelia automatically injects as a `new String()` which equates to *true*.
For my base class to handle this, I need a more verbose check on the baseUrl for validity, like below:

`this.baseUrl = baseUrl !== undefined && baseUrl !== null && baseUrl.length > 0 ? baseUrl : this.getBaseUrl("");`

I can't submit a PR just yet, but will do so later this evening when I can. Would this be an Aurelia only change? So as not to break other clients expected behaviours?

**Comment by jordan-ware** [comment]
![image](https://user-images.githubusercontent.com/14194954/52323466-9e07a080-2a24-11e9-8c2c-74ef471f9564.png)
Example of `""` evaluating as falsy, vs `new String()` evaluating as truthy.

**Comment by RSuter** [comment]
A PR is fine but we need to be very careful not to break anyone/other clients...

**Comment by jordan-ware** [comment]
I have been using the latest generator for Aurelia in my new project and have realised that this issue has been resolved.

The client uses the URL provided by my DI container.
`aurelia.use.instance(MyService, new MyService('http://myBaseUrl', aurelia.container.get(HttpClient)));`

When DI is removed, it's using the one I provide in my base class:
```export class ServiceBase {
    protected getBaseUrl(base: string, what: string): string {
        return "http://myBaseUrl";
    }
}```

This issue can be closed 🎉
