### ISSUE TITLE
Support array of nullable items

### ISSUE THREAD

**Issue by jeremyVignelles** [RicoSuter/NSwag#1951]
In my model, I have an array of nullable objects. Currently, I can say that the whole array property can be null, or that a sub property of an item is null, but as far as I know, there is no way to tell that items can be null.

Take this for example:
```
        [JsonProperty(Required = Required.Always)]
        public string[] NullableStrings { get; set; } = {"Hello", null, "World"};
```

There are in fact two issues:

1. I can't tell NSwag to generate a nullable item in the swagger.json (workaround below)
2. The typescript generator doesn't understand nullable items from swagger.json and doesn't generate `(string|null)[]` as expected

For the first issue, I have the following workaround:
```
                    services.AddOpenApiDocument(configure =>
                        {
                            configure.PostProcess = doc =>
                            {
                                doc.Components.Schemas["HelloWorldModel"]
                                    .ActualProperties["nullableStrings"]
                                    .Item
                                    .IsNullableRaw = true;
                            };
                        });
```

You can see that in action here : https://github.com/jeremyVignelles/TestNSwagNetCoreApp/tree/repro/array-of-nullables

**Comment by RSuter** [comment]
An array item is always generated as not nullable: 

![image](https://user-images.githubusercontent.com/2603405/52700059-7447ff80-2f77-11e9-9389-82c6ae7db4dd.png)

We need to create a new attribute in NJS so that you can change this parameter to true so that the elements are nullable (opt-in)

**Comment by jeremyVignelles** [comment]
Hi, any update on this?

**Comment by jeremyVignelles** [comment]
As far as I can see, the second issue is not resolved : Even with the attribute, NSwag generates `string[]` and ignores the `nullable: true` generated in the schema.

See https://github.com/jeremyVignelles/TestNSwagNetCoreApp/tree/repro/array-of-nullables for the updated example

**Comment by jeremyVignelles** [comment]
The typescript generator now propery generates (string|null)[], don't know the version that changed that, but I consider this fixed.

**Comment by jeremyVignelles** [comment]
For further reference, it seems to work when `[ItemsCanBeNull]` is set on the property.

```cs
        [JsonProperty(Required = Required.Always)]
        [ItemsCanBeNull]
        public string[] NullableStrings { get; set; } = {"Hello", null, "World"};
```

It still doesn't work with NRT only, see https://github.com/RicoSuter/Namotion.Reflection/issues/36
