### ISSUE TITLE
Automatically add "readonly" for properties?

### ISSUE THREAD

**Issue by Octoate** [RicoSuter/NSwag#2007]
Hi,
I am currently facing the problem that I have a method that handles a PUT request on an entity of my REST API. The entity, that can be modified by the PUT request, contains properties that are read only and only implement the getter and some that contain getter and setter:

    public class Example
    {
        [JsonProperty(PropertyName = "loop")]
        [ReadOnly(false)]
        public bool IsLooping
        {
            get => _sequence.IsLooping;
            set => _sequence.IsLooping = value;
        }

        public bool IsPaused => _sequence.IsPaused;
    }

In the generated documentation it is not possible to see whether the property is read only or you can write it. Is there a way to set that with an attribute or automatically document if a property is read/writeable or not? I tried using the [ReadOnly(false/true)] attribute from the System.ComponentModel but then I have to mark every property and I am not sure that this is the correct way to mark it. What is your preferred way to mark those properties?

**Comment by RSuter** [comment]
Ref: https://github.com/RSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L962

**Comment by RSuter** [comment]
I think it should only set the read only property if it is true as the default is false...

**Comment by Octoate** [comment]
Ah ok. It means that I have to set it manually for the property that only contains a getter, right? I just wanted to be sure that this is the way on how to do it. It might have been possible to analyze the property and set it to readonly=true automatically if it only contains a getter...

**Comment by RicoSuter** [comment]
ATM you could do this automatically with a custom schema processor and update all properties

**Comment by Octoate** [comment]
Ah, ok. I will have a look at this. Thanks for your help!
