### ISSUE TITLE
NSwag should not generate an attribute with the default value for query parameters in OAS 3.0

### ISSUE THREAD

**Issue by klacol** [RicoSuter/NSwag#2010]
We have a controller with this signature

```csharp
public IHttpActionResult GetBuildingsWithHseq(string expand = null, bool deactivated = false)
{}
```
NSwag generates an OAS 3.0 file with the query param "deactivated" like this:

```json
"/api/Hseq/Buildings": {
      "get": {
        "tags": [
          "Hseq"
        ],
        "summary": "Get a list of all buildings that have at minimum one HSEQ function attached",
        "operationId": "Hseq_GetBuildingsWithHseq",
        "parameters": [
          {
            "name": "expand",
            "in": "query",
            "description": "(optional) The csv list of properties to expand in result.",
            "schema": {
              "type": "string",
              "nullable": true
            },
            "x-position": 1
          },
          {
            "name": "deactivated",
            "in": "query",
            "description": "(optional) inclusive deactivated records.",
            "schema": {
              "type": "boolean"
            },
            "x-position": 2,
            "default": false
          }
```

This is not valid according to https://editor.swagger.io/ and https://speccy.io. A parameter has no attribute with the name "default". See also in the [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterObject).

NSwag should not generate the attribute "default" for query parameters in OAS 3.

**Comment by markafox** [comment]
the "default" attribute should be inside the "schema"
`{
            "name": "deactivated",
            "in": "query",
            "description": "(optional) inclusive deactivated records.",
            "schema": {
              "type": "boolean",
              "default": false
            },
            "x-position": 2
          }`

**Comment by anas2204** [comment]
I am facing the same issue. The "default" should be inside "schema" for query parameters.
