### ISSUE TITLE
Invalid type owner for DynamicMethod

### ISSUE THREAD

**Issue by gzannerini** [RicoSuter/NSwag#2047]
Hi have similar issue of issue https://github.com/RSuter/NSwag/issues/877, stacktrace is:

`
[ArgumentException:]
   NSwag.AspNet.Owin.Middlewares.<GenerateSwaggerAsync>d__9.MoveNext() +339
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter1.GetResult() +28
   NSwag.AspNet.Owin.Middlewares.<Invoke>d__8.MoveNext() +594
[AggregateException:]
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +26
   Microsoft.Owin.Host.SystemWeb.Infrastructure.ErrorState.Rethrow() +33
   Microsoft.Owin.Host.SystemWeb.CallContextAsyncResult.End(IAsyncResult result) +155
   Microsoft.Owin.Host.SystemWeb.OwinHttpHandler.EndProcessRequest(IAsyncResult result) +34
   System.Web.CallHandlerExecutionStep.InvokeEndHandler(IAsyncResult ar) +152
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +125
`

Library version:

```
<package id="Newtonsoft.Json" version="9.0.1" targetFramework="net46" />
<package id="NJsonSchema" version="9.13.27" targetFramework="net46" />
<package id="NSwag.AspNet.Owin" version="12.0.18" targetFramework="net46" />
<package id="NSwag.Core" version="12.0.18" targetFramework="net46" />
<package id="NSwag.SwaggerGeneration" version="12.0.18" targetFramework="net46" />
<package id="NSwag.SwaggerGeneration.WebApi" version="12.0.18" targetFramework="net46" />
```

Thanks

**Comment by RSuter** [comment]
Can you provide a sample project to repro this?

**Comment by gzannerini** [comment]
Hi, having dozens of Controller, trying to reproduce a minimal version and publishing on GitHub. In some days will ask for your help. Thanks for now.

**Comment by gzannerini** [comment]
Hi, unfortunately, I'm using third-party dlls overriding ApiController. For those dll I don't have the source code. You can close the issue, can't help you reproducing that.
