### ISSUE TITLE
nswag types2swagger throws an exception "The given schema type is not supported"

### ISSUE THREAD

**Issue by Serenya** [RicoSuter/NSwag#2049]
Environment: Mac OS Mojave 10.14.3
Installed .NET version: 2.2.104
.NET Core version of the project: 2.1
Version of node module of nswag: 12.0.18

In the package.json file of the project I have a command:

```
"preapi:gen": "nswag types2swagger /assembly:./path-to-project-dll.dll /classnames:namespace-plus-classname /output:Swagger.json",
```

When I run `yarn preapi:gen`, I get an exception: `System.ArgumentException: The given schema type is not supported.`.

After investigation of the source code of nswag project I realized that the exception was thrown by https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/SwaggerDocument.Serialization.cs#L43
and the reason of that might be because 
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Commands/Commands/SwaggerGeneration/TypesToSwaggerCommand.cs#L33
 references to unsupported SchemaType by nswag 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/JsonSchemaGeneratorSettings.cs#L32

**Comment by RicoSuter** [comment]
This is a bug and probably cannot work at the moment...

We need to change the type in the command class

**Comment by Serenya** [comment]
A workaround is to pass outputType argument /outputType:Swagger2
