### ISSUE TITLE
JsonSchemaDate Attribute does not generate "format: date"

### ISSUE THREAD

**Issue by k290** [RicoSuter/NSwag#2051]
I have a C# viewmodel using the NJsonSchema JsonSchemaDate attribute
```
    public class IdeaStageModel
    {
        [JsonSchemaDate]
        public DateTime? TargetDate { get; set; }
    }

```
or
```
    public class IdeaStageModel
    {
        [JsonSchema(JsonObjectType.String, Format = "date")]
        public DateTime? TargetDate { get; set; }
    }

```
However swagger,json is still generated with "date-time"

```
 "IdeaStageModel": {
      "type": "object",
      "properties": {
        "targetDate": {
          "format": "date-time",
          "type": "string"
        },
      }
    },
```

NSwag version: 12.0.18.0

This was previously resolved here: https://github.com/RicoSuter/NSwag/issues/1351

Edit: Sorry this might be an issue with Swashbuckle, as that is what generates the swagger.json. WIll update/edit/close this issue after confirming

**Comment by RicoSuter** [comment]
Yes, i’d expect thats a swashbuckle issue and should work when using nswag
