### ISSUE TITLE
Is it possible to exclude deprecated operations/parameters from generated client?

### ISSUE THREAD

**Issue by JyrkiHei** [RicoSuter/NSwag#2052]
We are using the latest nswag and generating Axios Typescript-client from OpenAPI 3.0 json.

**Comment by RicoSuter** [comment]
You can exclude some operations with a custom operation processor in the swagger generator config. In the client generator this is not (yet) possible... - you need to preprocess the spec

**Comment by JyrkiHei** [comment]
Ok, thanks!
