### ISSUE TITLE
Is it possible to replace some values with static values?

### ISSUE THREAD

**Issue by JyrkiHei** [RicoSuter/NSwag#2053]
We are using a schema where we deliver header-values 'username' & 'company' for logging purposes mainly and other variables are in querystring.

The header-values sent to API are basically static for every request on the client. Would it be possible to generate the client library so those header values would not go through function parameters but would be set as a global variables in the generated code?

We are using latest nswag to create Axios Typescript-client from OpenAPI 3.0 json.

**Comment by RicoSuter** [comment]
I’d think the best option would be to add a new setting like ExcludedParameterNames & you can add the static props to the base class or via extension code. What do you think?

**Comment by JyrkiHei** [comment]
That would sound like a good option to have. The issue that I'm trying to workaround here is that we have a REST method that has a parameter **u**serName in querystring and **U**serName in header for some reason... If nSwag would "respect" the casing given in the Swagger JSON, everything would work fine but would be ofcourse named wrongly.

Is there any way to respect the casing in the original json-file?

**Comment by RicoSuter** [comment]
NSwag automatically renames properties, parameters, etc to match the conventions of the target language... thats why you end up with this name clash... you could provide your own IParameterNameGenerator but then you’ll end up with two almost identcal parameters which is not nice either... wouldnt this new setting be a better solution?

**Comment by JyrkiHei** [comment]
Yeah, new setting would be better. Losing the naming convention would be bad. For now I think I have to download and modify the JSON before generating the client if that's even possible :(
