### ISSUE TITLE
the same function name in typescript client 

### ISSUE THREAD

**Issue by crashsol** [RicoSuter/NSwag#2056]
Generate methods with the same name and different parameters, but the same name function in JS overrides the previous method
![33](https://user-images.githubusercontent.com/17925647/55139127-fa0ebb80-516f-11e9-8b56-0ecf0e207cff.png)
![44](https://user-images.githubusercontent.com/17925647/55139316-6ab5d800-5170-11e9-9a36-9680bbc72473.png)

**Comment by RicoSuter** [comment]
Maybe you need to use another operation name generator setting as it seems the operation ids are not unique?

**Comment by crashsol** [comment]
> Maybe you need to use another operation name generator setting as it seems the operation ids are not unique?

I fix it  by use NSwag replace  Swashbuckle,it's really cool,thank you !!
