### ISSUE TITLE
Angular HTTPCLIENT

### ISSUE THREAD

**Issue by evanwellens** [RicoSuter/NSwag#2068]
I see NSwag studio supports outputting HTTPCLIENT for use with Angular. Is there a way to do this using command line as this is part of our build process ?

**Comment by RicoSuter** [comment]
Yes, you can create a config file (nswag.json) with NSwagStudio and run it via CLI (e.g. installed via NPM)

**Comment by evanwellens** [comment]
Many Thanks !!

**Comment by RicoSuter** [comment]
You should find everything in the wiki.
