### ISSUE TITLE
NSwagStudio v12.1.0.0 mis-generates `FileResponse` for regular response model

### ISSUE THREAD

**Issue by dmitry-pavlov** [RicoSuter/NSwag#2076]
@RicoSuter - NSwagStudio v12.1.0.0 mis-generates `FileResponse` for regular response model definition which points to a C# custom class type.

I can send you swagger.json file to reproduce the bug - ping me at me@dmitry-pavlov.com

**Comment by dmitry-pavlov** [comment]
I have downgraded to one of previous versions I had - `v12.0.7.0` and it generates response type correctly.  

Maybe [later versions](https://chocolatey.org/packages/NSwagStudio/) but before  `v12.1.0.0` also generate response types right, I didn't check that.

**Comment by RicoSuter** [comment]
Probably a regression of this commit: https://github.com/RicoSuter/NSwag/commit/85c5c2bfe4ede6c216246702e40cd6dd3b6e26a1

**Comment by RicoSuter** [comment]
v12.0.17+

**Comment by RicoSuter** [comment]
Is this a duplicate of https://github.com/RicoSuter/NSwag/issues/2080 ?

**Comment by DanielGunnars** [comment]
> Is this a duplicate of #2080 ?

I don't think so, I'm also experiencing this after fixing 2080.

**Comment by RicoSuter** [comment]
Weneed more details, eg a part of a swagger spec.

**Comment by dmitry-pavlov** [comment]
I have just sent the spec to mail@rsuter.com

**Comment by ljvanschie** [comment]
We're having the same issue. The Swagger spec defines the response as `"produces": ["*/*"]`, which causes NSwag to think it produces binary content.

**Comment by ljvanschie** [comment]
Also, `"produces": ["application/json;charset=UTF-8"]` makes NSwag think it returns binary content instead of json. It looks like file responses are the default/fallback now, whereas before it would default to json.

**Comment by RicoSuter** [comment]
> It looks like file responses are the default/fallback now, whereas before it would default to json.

Exactly, this is the regression - will check soon

**Comment by RicoSuter** [comment]
Created a PR, please review...

**Comment by Thieund** [comment]
I encountered the this issue with v13.6.1 & v13.6.2

**Comment by jeremyVignelles** [comment]
@Thieund is that the same issue as #2892 ?

**Comment by Thieund** [comment]
> @Thieund is that the same issue as #2892 ?

No. I'm returning a file, whether with type "file" or "byte", Promise<FileResponse> is generated, but FileResponse is missing. I'm using TypeScript client.

**Comment by Szymek364** [comment]
I have the same issue in version 13.6.2.0

**Comment by jeremyVignelles** [comment]
@Thieund @Szymek364 : Please open new issues then. We need a sample code (hosted on github) that reproduces the issue to investigate.
