### ISSUE TITLE
Cant create local copy using Swagger Specifiation

### ISSUE THREAD

**Issue by XxmonioxX** [RicoSuter/NSwag#2083]
Hello, 
i am mostly new using nswagstudio, have been reading a lot but i cannot comprend why is this error popping up when i try create a local copy of the swagger.json.
Seems like it's an error of certificate:
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS. ---> System.Security.Authentication.AuthenticationException: El certificado remoto no es válido según el procedimiento de validación.
   en System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en CallSite.Target(Closure , CallSite , Object )
   en NJsonSchema.Infrastructure.DynamicApis.<HttpGetAsync>d__16.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en NSwagStudio.ViewModels.SwaggerGenerators.SwaggerInputViewModel.<>c__DisplayClass8_0.<<LoadSwaggerUrlAsync>b__0>d.MoveNext() en C:\projects\nswag\src\NSwagStudio\ViewModels\SwaggerGenerators\SwaggerInputViewModel.cs:línea 27
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MyToolkit.Mvvm.ViewModelBase.<>c__DisplayClass14_0.<<RunTaskAsync>b__0>d.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   en MyToolkit.Mvvm.ViewModelBase.<RunTaskAsync>d__12`1.MoveNext()

PD: I'm sorry about th spanish specifications -_-

**Comment by RicoSuter** [comment]
Somehow it cannot access the url... can you access the url in a private browser window?

**Comment by RicoSuter** [comment]
Is there an invalid/self-signed/non public certificate?

**Comment by XxmonioxX** [comment]
> 
> 
> Somehow it cannot access the url... can you directly access the url in a private browser window?

Yes, i can access it in a private window
![capture](https://user-images.githubusercontent.com/38034128/55549374-f8944480-56d5-11e9-830f-1a02df863724.png)

**Comment by XxmonioxX** [comment]
> 
> 
> Is there an invalid/self-signed/non public certificate?
Now that i sent you the capture i saw the problem, MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT
