### ISSUE TITLE
JsonSchemaTypeAttribute throws more than one Element in Sequence Exception

### ISSUE THREAD

**Issue by ddrdoubled** [RicoSuter/NSwag#2097]
```
public class Test1 {
public string Name1 {get; set;}
}
```

```
public class Test2 {
public string Name2 {get; set;}
}
```

```
public class MainTest {
[JsonSchemaType(typeof(Test1), IsNullable = true)]
[JsonSchemaType(typeof(Test2), IsNullable = true)]
public object Test {get; set;}
}

```
fails in GeneratingSwaggerAysnc  with the Exception above: Sequence contains more than one element

probably due to using SingleOrDefault() extension somewhere

**Comment by RicoSuter** [comment]
This attribute cannot be used multiple times on the same property

**Comment by ddrdoubled** [comment]
How should OneOf than be implemented with object as the only base class?

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NJsonSchema/wiki/Inheritance

**Comment by ddrdoubled** [comment]
Ok, and how should I attach a KnownTypeAttribute(typeof(Test1)) to object class? Due to different Inheritance Hierarchies between Test1 and Test2 i am not able to have a common base class.

**Comment by RicoSuter** [comment]
This is not supported

**Comment by ddrdoubled** [comment]
Ok, understood, but please change AttributeUsage for JsonSchemaType then to Multiple = false, because this would be the correct way to implement it.
