### ISSUE TITLE
CustomStylesheetUri not working with ReDoc

### ISSUE THREAD

**Issue by tzimny** [RicoSuter/NSwag#2099]
Hi,

I tried to integrate ReDoc, which worked fine except that the CustomStylesheetUri property is not being processed.

I used it as following:
  ```
app.UseReDoc(options =>
      {
        options.CustomStylesheetUri = new Uri("../swagger-ui/custom-redoc.css", UriKind.Relative);
        options.Path = "/redoc";
        options.DocumentPath = "/api-docs-redoc/v1/docs.json";
      });
```

Seems like the property CustomStylesheetUri is ignored.

**Comment by RicoSuter** [comment]
Used in swagger ui here:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/SwaggerUi3/index.html#L104

We probably just need to do the same for redoc?

**Comment by silvairsoares** [comment]
If you are using ReDoc, you will probably have an html file with the default structure for generating the ReDoc graphical interface. In this case, you can reference your css file directly in the header tag of your html, something like:
`
    <!DOCTYPE html>
    
    <html>
    <head>
        <title>ReDoc</title>
        
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">

        
        <link rel="stylesheet" type="text/css" href="~/swagger-ui/custom.css">
        
        <style>
            body {
                margin: 0;
                padding: 0;
            }
        </style>
    </head>
    <body>
        <img src="~/images/logo.jpg" alt="ASP.NET" class="img-responsive" />
        <redoc spec-url='/swagger/v1/swagger.json' suppress-warnings></redoc>
        <script src="~/scripts/redoc.min.js"></script>
    </body>
    </html>
`

**Comment by RicoSuter** [comment]
That’s what we basically insert when the setting is set, no? See commit

**Comment by silvairsoares** [comment]
Hello, RicoSuter. Dude honored to interact with you, thank you for the NSwag. It spared me tens of hours of work.

So if I include the code snippet in my startup.cs:

    app.UseReDoc(options =>
    {
        options.CustomStylesheetUri = new Uri("~/swagger-ui/custom.css", UriKind.Relative);
        options.Path = "/redoc";
        options.DocumentPath = "/swagger/v1/swagger.json";
    });

The file "~/swagger-ui/custom.css" is not being inserted into the graphical interface of the redoc. Now, if I manually enter it into my static html file (<link rel="stylesheet" type="text/css" href="~/swagger-ui/custom.css">) it works perfectly. So that's what I'm doing here for now.

![Response](https://user-images.githubusercontent.com/18450095/58660892-e4974880-82fc-11e9-9b00-58c1ad51bd7f.png)

**Comment by RicoSuter** [comment]
Looks good to me: 

![image](https://user-images.githubusercontent.com/2603405/58661959-6604d000-8329-11e9-9773-96ceba780d71.png)

Maybe it's because the type="text/css" is missing?

**Comment by silvairsoares** [comment]
Actually, my template has the expression "type="text/css"" which is not present here (https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/SwaggerUi3/index.html# L104).
However, I did a test here, removing the expression "type="text/css"" and it continues to work here for me. So there still seems to be some problem.
If I use the recommended technique (

    app.UseReDoc(options =>
    {
        options.CustomStylesheetUri = new Uri("~/swagger-ui/custom.css", UriKind.Relative);
        options.Path = "/redoc";
        options.DocumentPath = "/swagger/v1/swagger.json";
    });

)

The reference is even created, but the file "custom.css" is not copied to the solution's virtual directory. There may be a problem copying the static files to the "wwwroot" directory. But this is just my guess.

![ResponseII](https://user-images.githubusercontent.com/18450095/58663973-0e07a280-8304-11e9-9b37-14dbc66f9763.png)


As I understand it, the .Net Core build engine only transfers the static files (css, js, img, etc.) to the "wwwroot" directory if these files are being referenced in any project view (which It makes a lot of sense to me.
But the ReDoc view (html) is only generated at runtime, so maybe this is the problem. For when the build process is running, the redoc view does not yet exist, so for .Net Core build, the css file does not need to be copied to the solution's virtual directory.

**Comment by RicoSuter** [comment]
Maybe you need to set the file type to Content?

**Comment by silvairsoares** [comment]
I did not understand your last suggestion.

Note: This issue is not preventing me from moving forward with my project. Well, I'm using a static html file and it's working perfectly for me. I just entered this discussion in an attempt to assist the tzimny user who opened the question.

**Comment by silvairsoares** [comment]
I just found a solution to the problem. At least here in my environment, what I had to do was this:

I changed the expression:
    `options.CustomStylesheetUri` = new Uri("~/swagger-ui/custom.css", UriKind.Relative);

For:
    `options.CustomStylesheetUri` = new Uri("~/swagger-ui/custom.css", UriKind.Relative);

So @tzimny, I advise you to insert your static files, directly into the "wwwroot" directory and do not use any prefix (".", ".." or "~") at the address of the files.
