### ISSUE TITLE
SwaggerToCSharpClientCommand generates 'Anonymous' name of enum type

### ISSUE THREAD

**Issue by Serenya** [RicoSuter/NSwag#2103]
Environment: MacOS
NSwag version: 12.1.0
Dotnet version: 2.2

**Precondition:** I have two controllers OrdersController. and ValuesController. Post action handler of OrdersController accept argument of type NewOrderModel. This type contains a Status property of a type ```List<OrderStatus>```, where OrderStatus is an enum.

**Problem:**  After running nswag via npm, it generates name of enum type equal to **Anonymous**, like here:

![image](https://user-images.githubusercontent.com/4124557/55973308-92836080-5c85-11e9-8b7b-2eb7b01e2431.png)

**Expected behavior:** Enum type name has to be equal ```<<PropertyName>>Enum```. This naming convention is implemented swagger codegen library https://github.com/swagger-api/swagger-codegen

See test project in attached:
[TestNswag.zip](https://github.com/RicoSuter/NSwag/files/3069820/TestNswag.zip)

**Comment by RicoSuter** [comment]
I agree, anonymous should be the last resort... ATM you could set the title property in the enum and it should be picked up...

**Comment by Serenya** [comment]
Rico, could you please give an example how Title property should be set?

**Comment by possum64** [comment]
I would raise the same issue with parameter enums such as for odata $select and $expand query param types, as they can easily be made unique and user friendly via a <<OperationId>>Enum naming scheme.

The same applies to numbered 'Response' classes - <<OperationId>>'Response' would be far more appropriate.

The incremented 'Anonymous' and 'Response' naming schemes are incredibly fragile as simply adding a new query param or method breaks everything.

**Comment by RicoSuter** [comment]
```
"items": {
  "title": "StatusEnum",
  "enum": [
    "Finished",
    "InProgress"
  ],
  "type": "string"
}
```

**Comment by Serenya** [comment]
@RicoSuter, do you know how can I configure it in C# to have `title` appended in the output?

**Comment by RicoSuter** [comment]
I don't know Swashbuckle (you can do everything/replace it with NSwag), but I think something like this

    private class AddEnumTitleSchemaFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaRegistry schemaRegistry, Type type)
        {
            if (type == typeof(Status))
            {
                schema.title = type.Name;
            }
        }
    }

**Comment by Serenya** [comment]
@RicoSuter, you've made my day :) Here is your sample with some adjustments to match Swashbuckle:

```
    public class AddEnumTitleSchemaFilter : ISchemaFilter
    {
        public void Apply(Schema schema, SchemaFilterContext context)
        {
            if (context.SystemType.IsEnum)
            {
                schema.Extensions.Add("title", context.SystemType.Name);
            }
        }
    }
```

**Comment by RicoSuter** [comment]
Also the type will use the array property's name instead of anonymous in the next version...

**Comment by jhughes23** [comment]
@RicoSuter, Above you said that in the next version that it would use the array property's name instead of anonymous. Do you have an idea of when that will be released?

**Comment by RicoSuter** [comment]
Should be in the latest version..

**Comment by jhughes23** [comment]
@RicoSuter, we are using "NJsonSchema", "9.13.36.0 (Newtonsoft.Json v9.0.0.0)" and got multiple Anonymous, Anonymous2, Anonymous3 classes for arrays instead of the class name matching the array property name.

**Comment by AndriyShatrov** [comment]
Hi, for a generated client I got 
System.Collections.Generic.IEnumerable<Anonymous> itemType
and many 
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.2.1.0 (Newtonsoft.Json v11.0.0.0)")]
    public enum Anonymous3....
I used the latest version. Will it be fixed, or I did something wrong?

**Comment by skironDotNet** [comment]
It's not schema filter for enum titles it is IParameterFilter for swagger "paths" section to contain title needed for enums to be generated in IEnumerable<EnumNameHere> for method arguments.

    public class SwaggerAddEnumTitleParameterFilter : IParameterFilter
    {
        public void Apply(IParameter parameter, ParameterFilterContext context)
        {
            if (parameter is NonBodyParameter)
            {
                var p = (NonBodyParameter)parameter;

                if (p.Type == "array")
                {
                    var genericType = context.PropertyInfo.PropertyType.GenericTypeArguments[0];
                    if (genericType.IsEnum)
                    {
                        p.Items.Extensions.Add("title", genericType.Name);
                        p.UniqueItems = true;
                    }
                }
            }
        }
    }

and in API use
```
            services.AddSwaggerGen(c =>
            {
                ...
                c.ParameterFilter<SwaggerAddEnumTitleParameterFilter>();
            }
```

This filter will result in Swagger like this
![image](https://user-images.githubusercontent.com/2981715/120672440-eb12aa80-c457-11eb-8a8e-3ad1cb8308cd.png)

**Comment by skironDotNet** [comment]
@RicoSuter a question about "title" when I generate "title" property with fully qualified name NSwag will not honor it, it will still use just enum name.
```
      "parameters": [{
                "someProp": {
                    "enum": ["Blank", "Yes", "No"],
                    "type": "string",
                    "title": "HUB.Echos.Contracts.Enums.YesNoOption"
                }
      }]
```

will result in just (c# abstract)
`methodX(YesNoOption someProp)`

I would like this to have FQN
`methodX(HUB.Echos.Contracts.Enums.YesNoOption someProp)`

Is there a way to configure NSwag to use FQN when using 'title'

**Comment by skironDotNet** [comment]
@RicoSuter  never mind my initial custom ITypeNameGenerator didn't consider the title

Included my code for others as an idea

```
     public class FullNamespaceTypeNameGenerator : ITypeNameGenerator
     {
        public string Generate(JsonSchema schema, string typeNameHint, IEnumerable<string> reservedTypeNames)
        {
            if (typeNameHint == null && schema.IsEnumeration)
            {
                if (schema.Title == null)
                    return "Anonymous";
                return schema.Title;
            }

            if (schema.IsEnumeration && !string.IsNullOrEmpty(schema.Title)) //<----- added this to make work as expected
                return schema.Title;                 //<----- added this to make work as expected

            return typeNameHint.Replace('[', '<').Replace(']', '>');
        }
    }

```
