### ISSUE TITLE
NSwag code generates the wrong type for enum attributes

### ISSUE THREAD

**Issue by possum64** [RicoSuter/NSwag#2107]
I have a DTO called 'Order' which contains an attribute called 'DistributionCenterRollup' that is defined to be of type DistributionCenterRollupType' via the schema reference below:

"$ref": "#/components/schemas/ChannelAdvisor.RestApi.V1.Models.DistributionCenterRollupType"

However, this attribute is incorrectly generated with the completely wrong type as shown below:

public DistributionCenterRollup DistributionCenterRollup { get; set; }

That is, the code generator appears to duplicate the attribute name for the enum type instead of using the referenced enum type. Obviously this will not work - but it does insidiously compile and run because a DistributionCenterRollup class containing the to/from JSON convertors is also generated - a (de)serialisation error inevitably occurs during code execution.

This is a show-stopper for me as I have a large number of referenced enum types in my JSON.

Hopefully this is a simple fix - even if someone could even point me to the relevant part of the code please, as if I could get this fixed the tool would be invaluable (instead of currently worthless :-(  )

**Comment by RicoSuter** [comment]
Can you post a sample spec? (This all is handled in njsonschema)

**Comment by RicoSuter** [comment]
But it looks correct and should use the referenced schema and schema name... looks like a special case or a bug

**Comment by possum64** [comment]
Its a bug.

I'd say there is an incorrect call somewhere that wrongly passes the attribute name instead of the attribute type name when the attribute is an enum.

Here's another plain example from my Order DTO. The type defined for OrderTaxType,  ShippingTaxType, and GiftOptionsTaxType is the same schema reference to the enum type 'TaxType' - but the generator ignores those type references (altho it does generate the TaxType enum class itself). Instead, it generates JSON convertor types for each attribute using the attribute name (which seems pointless), and then declares each attribute type as being the JSON convertor type instead of TaxType! (obviously that is not going to work):

![image](https://user-images.githubusercontent.com/24485260/56100632-9271b200-5f5e-11e9-9957-e0429c9f969e.png)


![image](https://user-images.githubusercontent.com/24485260/56100564-9a7d2200-5f5d-11e9-9e17-1411d8544c4b.png)

![image](https://user-images.githubusercontent.com/24485260/56100821-b1714380-5f60-11e9-98f3-791cfdf5431c.png)

Please also note that the generated code in the JSON convertor type also wrongly converts itself instead of TaxType! AFAIKS there should be only 1 convertor class per enum - not a converter class per enum attribute.

**Comment by RicoSuter** [comment]
The problem is probably the anyOf, try to remove it and use $ref directly or use oneOf... just to see if that solves the problem... i will then check how to handle this correctly...

**Comment by possum64** [comment]
Replacing anyOf with oneOf fixes the NSwag generation issue. Thanks.

However, this OpenAPI file was itself generated by Microsoft's OData to OpenAPI convertor, so unfortunately these 2 tools are incompatible at the moment...

**Comment by RicoSuter** [comment]
Fixed with the above commit, will be in the next version soon.

**Comment by possum64** [comment]
Excellent! Thanks Rico.
