### ISSUE TITLE
Order of processor pipeline when using operationProcessorTypes setting

### ISSUE THREAD

**Issue by bemayr** [RicoSuter/NSwag#2108]
Hello!
First of all thanks for this awesome tool and it's enormous flexibility!

I am currently trying to generate my SignalR messages using NSwag (along TypeScript and C# clients for the Web API), but I have the problem that the schemas for all DTOs are generated, even if I remove the operations using:
```csharp
public class SignalR : IOperationProcessor, IDocumentProcessor
{
    public async Task ProcessAsync(DocumentProcessorContext context)
    {
        var assembly = typeof(SomeSignalRMessageType).GetTypeInfo().Assembly;
        var types = assembly.ExportedTypes
            .Where(t => t.FullName.StartsWith("<...>.SignalR.Messages.", StringComparison.Ordinal) && (t.GetTypeInfo().IsClass || t.GetTypeInfo().IsEnum));

        foreach (var type in types)
        {
            if (!context.SchemaResolver.HasSchema(type, false))
            {
                await context.SchemaGenerator.GenerateAsync(type, null, context.SchemaResolver);
            }
        }
    }

    public Task<bool> ProcessAsync(OperationProcessorContext context) => Task.FromResult(false);
}
```

Is there a better way to utilizing NSwag to generate those types? It kind of feels a bit weird to exclude all operations and include my messages.
The problem I do have now is exactly like: https://stackoverflow.com/a/54895241, it seems that the processor pipeline is wrong when the `operationProcessorTypes` is used.
I can't really use `excludedTypeNames`, because I want to exclude all DTO types.

After further investigation I found out that in my C# generation there are also unnecessary DTO types generated, I also use the `operationProcessorTypes` setting there. Following the last hint in the _Document Processors and Operation Processors_ doesn't really work, because I am using multiple NSwag definitions in one project.

Do you have any hint or idea, or am I completely misusing NSwag here?
Thanks a lot in advance, Bernhard

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/SigSpec

**Comment by bemayr** [comment]
Thanks a lot, I'm gonna take a look into this!

**Comment by RicoSuter** [comment]
You need to add the processor at the begining of the list, ie Insert(0, ...
