### ISSUE TITLE
Json attributes ignored for query parameters

### ISSUE THREAD

**Issue by henrik-olsson-valtech** [RicoSuter/NSwag#2109]
I'm trying to generate complete documentation for an API. Some GET operations take a request parameter of a custom class. We have a custom model binder for these, which uses reflection to bind query parameters to properties. Now I would like to use `[JsonProperty]` and `[JsonIgnore]` for some properties to customize the generated Swagger/OpenAPI document, but that doesn't seem to work.

A very simple example would be:

    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        [HttpGet]
        public ActionResult<IEnumerable<string>> Get([FromQuery] MyGetRequest request)
        {
            return new string[] { "value1", "value2" };
        }

        [HttpPost]
        public ActionResult<IEnumerable<string>> Post([FromBody] MyPostRequest request)
        {
            return new string[] { "value1", "value2" };
        }
    }

    public class MyGetRequest
    {
        /// <summary>
        /// Summary for property 1
        /// </summary>
        public string Property1 { get; set; }

        /// <summary>
        /// Summary for property 2
        /// </summary>
        [JsonProperty("CustomName")]
        public string Property2 { get; set; }

        /// <summary>
        /// Summary for property 3
        /// </summary>
        [JsonIgnore]
        public string Property3 { get; }
    }

    public class MyPostRequest
    {
        /// <summary>
        /// Summary for property 1
        /// </summary>
        public string Property1 { get; set; }

        /// <summary>
        /// Summary for property 2
        /// </summary>
        [JsonProperty("CustomName")]
        public string Property2 { get; set; }

        /// <summary>
        /// Summary for property 3
        /// </summary>
        [JsonIgnore]
        public string Property3 { get; }
    }

This results in the following definition:
```
{
  "x-generator": "NSwag v12.1.0.0 (NJsonSchema v9.13.28.0 (Newtonsoft.Json v11.0.0.0))",
  "swagger": "2.0",
  "info": {
    "title": "My Title",
    "version": "1.0.0"
  },
  "host": "localhost:5000",
  "schemes": [
    "http"
  ],
  "produces": [
    "text/plain",
    "application/json",
    "text/json"
  ],
  "paths": {
    "/api/Values": {
      "get": {
        "tags": [
          "Values"
        ],
        "operationId": "Values_Get",
        "parameters": [
          {
            "type": "string",
            "name": "Property1",
            "in": "query",
            "description": "Summary for property 1",
            "x-nullable": true
          },
          {
            "type": "string",
            "name": "Property2",
            "in": "query",
            "description": "Summary for property 2",
            "x-nullable": true
          },
          {
            "type": "string",
            "name": "Property3",
            "in": "query",
            "description": "Summary for property 3",
            "x-nullable": true
          }
        ],
        "responses": {
          "200": {
            "x-nullable": true,
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "Values"
        ],
        "operationId": "Values_Post",
        "consumes": [
          "application/json-patch+json",
          "application/json",
          "text/json",
          "application/*+json"
        ],
        "parameters": [
          {
            "name": "request",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/MyPostRequest"
            },
            "x-nullable": false
          }
        ],
        "responses": {
          "200": {
            "x-nullable": true,
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "MyPostRequest": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "property1": {
          "type": "string",
          "description": "Summary for property 1"
        },
        "customName": {
          "type": "string",
          "description": "Summary for property 2"
        }
      }
    }
  }
}
```
The POST operation works as expected, with one body parameter with two properties `property1` and `customName` being generated. But the GET operation has three query parameters (should be two) named `Property1`, `Property2` and `Property3` (should be `property1` and `customName`). 

How can I fix this? I'm a little lost here. Must I implement a custom schema processor, operation processor or even document processor? I looked briefly at a custom document processor, but I cannot find a place to look for JsonProperty/JsonIgnore custom attributes in the document. Do I have to do that with reflection?

**Comment by RicoSuter** [comment]
Properties in a complex object via [FromQuery] are not serialized with the JSON serializer and thus these attributes do not work... you need to check the ASP.NET Core docs to figure out how to rename them (probably another attribute).

**Comment by henrik-olsson-valtech** [comment]
Thanks. I did find [FromQuery](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fromqueryattribute?view=aspnetcore-2.2) that has a name property. So I can rename now, but I still need to figure out how to hide/ignore a property.

**Comment by RicoSuter** [comment]
Maybe I implemented SwaggerIgnoreAttribute for these?

**Comment by henrik-olsson-valtech** [comment]
Yes! That works.
