### ISSUE TITLE
Cannot add DocumentProcessors from app.UseSwagger()

### ISSUE THREAD

**Issue by JakeStevenson** [RicoSuter/NSwag#2114]
I'm trying to add some DocumentProcessors, but I'm getting confused by the obsolete marking in the UseSwagger() extension method.

The documentation at https://github.com/RicoSuter/NSwag/wiki/Document-Processors-and-Operation-Processors seems shows it taking an argument of an Assembly, and an action with SwaggerSettings<WebApiToSwaggerGeneratorSettings> and I could use it like this:

`app.UseSwagger(typeof(Startup).Assembly, config => 
{
    config.GeneratorSettings.DocumentProcessors.Add(new OperationSecurityScopeProcessor("oauth2"));
}`

But now that seems to be marked as obsolete, and it says to use .UseSwagger() instead?  But if I use the method that does not take in an assembly it only has an argument of Action<SwaggerDocumentMiddlewareSettings>, and that doesn't seem to grant any access to processors.

What is the correct way to add document and operationprocessors?

**Comment by JakeStevenson** [comment]
I think I figured it out -- I ended up needed to find the aspnetcore middleware documentation on https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware

Most my searches took me to the wrong place.  Sorry for the confusion.

**Comment by RicoSuter** [comment]
Updated the wiki so that the sample is no longer using the deprecated method
