### ISSUE TITLE
API versioning sample for the most common use case (as existing samples are using deprecated functions)

### ISSUE THREAD

**Issue by hidegh** [RicoSuter/NSwag#2118]
There were a lot of changes around API versioning. It would be nice to have a **complete sample for a common issue**, which is:

1. having **multiple version** of API's 1, 2, 3 - config with **allowing unspecified** version
```
            services.AddApiVersioning(o =>
            {
                o.AssumeDefaultVersionWhenUnspecified = true;
                o.ApiVersionReader = new UrlSegmentApiVersionReader();
                o.DefaultApiVersion = new ApiVersion(2, 0);
            });
```
2. there might be a **Pascal to CamelCase change** in the JSON output (from a given version ongoing)
3. **NSwag tools** are used to generate type-script/angular code from the swagger document
4. And **swagger UI** is used for testing
5. Allow JWT token / basic auth. un UI (general) (sample)

**Current issues:**
1. **NSwag adds the non-versioned URL to all swagger document versions,** whereas non-versioned URL often refers either to latest or only to the 1st version
2. most samples are to some older (deprecated) NSwag version

**Comment by RicoSuter** [comment]
Did you have a look at this sample project?

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.AspNetCore.Tests.Web/Startup.cs

**Comment by hidegh** [comment]
Hi @RicoSuter 

Yes, that's the sample I'm using, **yet most of the problems I'm describing are present.**

I do have a V1 controller, where PascalCase is used by the JSON formatter (achieved by a simple formatter, inserted before the regular JSON formatter)
```
    public class PascalCaseJsonProfileFormatter : JsonOutputFormatter
    {
        public PascalCaseJsonProfileFormatter() : base(new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() }, ArrayPool<char>.Shared)
        {
            // NOTES:
            // https://codeopinion.com/asp-net-core-mvc-json-output-camelcase-pascalcase/
            // https://blog.maartenballiauw.be/post/2013/03/08/custom-media-types-for-aspnet-web-api-versioning.html
        }

        public override bool CanWriteResult(OutputFormatterCanWriteContext context)
        {
            var v = context.HttpContext.GetRequestedApiVersion();
            return v.MajorVersion < 2;
        }
    }
```

Any controller with API version > 1 or without version (assumes latest) uses camelCase (default JSON output contract).

**Now issues:**
1. T**he V1 Swagger docs does include the non-versioned URL's as well. Those URL without version number should fallback to latest version only,** in my case to V2, so those URI's should not be present on the V1 Swagger definition (nor UI).
2. **The V1 swagger docs uses a standard camelCase for property names (uses standard JSON output formatter) whereas it should have PascalCasing.** If the classic output response would be used to generate prperty names, then it'd be the PascalCaseJsonProfileFormatter that is used. But as the swagger json is not formated by the MVC outputformatter - and without a sample on how to set formatter on the swagger docs. generation - I end up with camelCase instead of PascalCase (see v1 swagger, GET /api/v1/Values vs the unwanted and included, but at least correct cased, GET api/Values). **The old, settable ContractResolver is deprecated!**

Still missing:
1. JWT token and basic username/password inpout generation for UI for the newest version (maybe a sample URL :)
2. Not sure if same issue (same class name, but diff. namespace) will be present with NSwag (haven't checked it yet)

We currently use Swashbuckle, but NSwag is more suited for generation (especially Angular2) - at least this where I got after my tests, su (:thumbsup).

Including my ugly (but working) sample, the GET /api/v1/Values, GET /api/v2/Values, GET /api/Values are those URI's worth to check...

[AspNetCoreFullNetSimpeWeb - NSwag.zip](https://github.com/RicoSuter/NSwag/files/3103013/AspNetCoreFullNetSimpeWeb.-.NSwag.zip)

**Comment by hidegh** [comment]
With the following code below now the generated swagger output can be fine tuned (authorization, casing)...

```
             services
               .AddSwaggerDocument(document =>
               {
                   /*
                    * Seems that a lot of configuration from inside the old (obsolete) app.UseSwaggerUi3(...) is moved here!
                    */

                   document.DocumentName = "v2";
                   document.ApiGroupNames = new[] { "2" };
                   document.IgnoreObsoleteProperties = true;

                   // Authentication https://github.com/RicoSuter/NSwag/issues/869
                   document.OperationProcessors.Add(new OperationSecurityScopeProcessor("JWT token"));
                   document.AddSecurity("JWT token", Enumerable.Empty<string>(),
                       new SwaggerSecurityScheme()
                       {
                           Type = SwaggerSecuritySchemeType.ApiKey,
                           Name = nameof(Authorization),
                           In = SwaggerSecurityApiKeyLocation.Header,
                           Description = "Copy this into  the value field: \nBearer {my long token}"
                       }
                   );

                   // Json serialization
                   document.SerializerSettings = new JsonSerializerSettings { ContractResolver = new CamelCasePropertyNamesContractResolver() };
               })
               .AddSwaggerDocument(document =>
                {
                    document.DocumentName = "v1";
                    document.ApiGroupNames = new[] { "1" };

                    // Json serialization
                    document.SerializerSettings = new JsonSerializerSettings { ContractResolver = new DefaultContractResolver() };
                })
                ;
```

**Comment by RicoSuter** [comment]
> Seems that a lot of configuration from inside the old (obsolete) app.UseSwaggerUi3(...) is moved here!
 
Yes, UseSwaggerUi3 is only used to configure/setup the web ui itself, the document itself is configured in AddSwaggerDocument/AddOpenApiDocument
