### ISSUE TITLE
How to pass additional parameters to Swagger UI

### ISSUE THREAD

**Issue by mj1856** [RicoSuter/NSwag#2125]
I'd like to be able to pass additional configuration parameters to Swagger UI as documented in https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

Since [the config](https://github.com/RicoSuter/NSwag/blob/a96606c7b3646c6c1e0c97d39c7a2d8a447ec6de/src/NSwag.AspNetCore/SwaggerUi3/index.html#L66-L88) is relatively fixed except for the specific settings that have been templated and passed through, there's not any clean way to do this.

Could you please add another property to the `SwaggerUi3Settings` class with a dictionary of additional settings to pass?  I can see that as SwaggerUI evolves, it would be a pain to match every setting that might be created to a separate property.

In my case, I need a way to set `withCredentials: true`, because I keep the swagger.json protected behind authentication.  Without this setting, the browser's `fetch` API won't pass through auth cookies, and the UI fails to fetch the swagger.json.

So, I'd settle for:

```csharp
app.UseSwaggerUi3(settings =>
{
  settings.FetchWithCredentials = true;
})
```

But I'm suggesting that perhaps it should be more extensible, like:
```csharp
app.UseSwaggerUi3(settings =>
{
  settings.AdditionalSettings.Add("withCredentials", true);
})
```

Thanks.

**Comment by RicoSuter** [comment]
See commit, is this ok?

**Comment by mj1856** [comment]
That works nicely.  Thanks!
