### ISSUE TITLE
Update Swagger UI

### ISSUE THREAD

**Issue by mj1856** [RicoSuter/NSwag#2132]
Hi.  Thanks for #2125, but I didn't realize that `withCredentials` was a new feature added in Swagger UI 3.22.0.  The current NSwag has version 3.20.8, so I can't use the feature still.

Would you please update the Swagger UI to the latest version (3.22.1)?

Thanks.

**Comment by RicoSuter** [comment]
v12.2.1

**Comment by mj1856** [comment]
Thanks! It works now!
