### ISSUE TITLE
How to specify date format on controller parameters?

### ISSUE THREAD

**Issue by mj1856** [RicoSuter/NSwag#2137]
I have several ASP.Net Core controllers with methods that accept a date parameter, such as:

```cs
[HttpGet]
public async Task<ActionResult<string>> Get(
    [BindRequired, FromQuery(Name = "date")] DateTime date
)
```

The generated schema ends up looking like this:
```json
"paths": {
    "/api/foo": {
      "get": {
        "parameters": [
          {
            "type": "string",
            "name": "date",
            "in": "query",
            "required": true,
            "format": "date-time",
            "x-nullable": false
          },
```

In my case, these dates are always *whole* dates, such as `"2019-04-23"`, so I'd like `"format": "date",` to appear in the schema, but I can't seem to figure out how to achieve that.  Is there an annotation attribute somewhere?

I can use `[JsonSchemaDate]` in my models for the output schema and that seems to work there.  But I can't seem to figure out an equivalent for the parameter schema.

Thanks.

**Comment by RicoSuter** [comment]
Cant you use the attribute on the parameter?

**Comment by RicoSuter** [comment]
Ah no: https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Annotations/JsonSchemaAttribute.cs

We need to change this here and i think it would just work...

**Comment by RicoSuter** [comment]
For now you could implement a custom operation processor which changes the parameter format and apply it to this operation

**Comment by mj1856** [comment]
Yes, the custom operation processor works for now.  Thanks.

**Comment by mj1856** [comment]
FYI, the update works great.  I can just apply `[JsonSchemaDate]` on the parameters now.

**Comment by simeyla** [comment]
@mj1856 I see like me you keep having the same issue! I think based on another post of yours you're also using moment.

Wondered if there a reliable way to use moment with `[JsonSchemaDate]` directly. 

I have a 'Next shipment date' and the problem I'm having is if somebody in New York picks `9/5/19` for a ship date then that actually becomes `9/4/19` for me when I parse it in California!

So for now I'm just putting `nextShipmentDate.format('YYYY-MM-DD')` when I send my date to the server - but this just seems wrong.

Or is there a way to tell `JsonSchemaDate` to parse as UTC?
