### ISSUE TITLE
Generated C# Client ConvertToString should be lenient to Enums

### ISSUE THREAD

**Issue by MikaelUmaN** [RicoSuter/NSwag#2140]
Using NSwagStudio v12.2.3.0

The ConvertToString method looks like:

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value is System.Enum)
            {
                string name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value;
                        }
                    }
                }
            }

This means that for an enum member declared as:

            /// <summary>
            /// Uses default
            /// </summary>
            [EnumMember]
            Default = -1,

We will get null. I propose the last part simply be written as:

                        return attribute.Value != null ? attribute.Value : name;

As a convenience that will work for most people.

**Comment by RicoSuter** [comment]
Why not `if (attribute != null && attribute.Value != null)`?
