### ISSUE TITLE
Proposal: Add configuration to skip propagating header parameter into generated client method

### ISSUE THREAD

**Issue by Serenya** [RicoSuter/NSwag#2149]
As a developer I'm using Nswag command `SwaggerToCSharpClientCommand` to generate client for my service.

Proposal: to introduce new configuration to skip propagating header into generated client method, e.g.:

for action handler `public async Task Create([FromHeader("Accept-Language")] string language, [FromBody] Order order)`, to have generated client method `public async Create(Order order)`

Reason: actual implementation of the client may seriously vary, and header parameter that are for all action handlers, e.g. "Accept-Language", could be defined on constructor level, to prevent code duplication.

**Comment by RicoSuter** [comment]
There is an option ExcludedParameterNames...

**Comment by Serenya** [comment]
I've forgot to check base class [SwaggerToCSharpClientCommand](https://github.com/RicoSuter/NSwag/blob/a207a4ec0838060a5f1f6dfb08bb118c05ee9641/src/NSwag.Commands/Commands/CodeGeneration/SwaggerToCSharpClientCommand.cs)... Thanks, Rico!

**Comment by Serenya** [comment]
Rico, only one point to the existing functionality, may be it should be treated as a bug:

- For action handler  `public async Task Create([FromBody] Order order, [FromHeader("Accept-Language")] string language)`
- I get client method generated with extra comman at the end `public async Create(Order order, )`

Should it be open as a separate bug report?

**Comment by SpyropoulosAntonis** [comment]
Hello Rico is it possible to add at the constructor a custom header via NSwag Studio ? and if yes how ?
