### ISSUE TITLE
Support generating ambient namespaces in TS

### ISSUE THREAD

**Issue by r-k-b** [RicoSuter/NSwag#2155]
Is it possible to generate [ambient namespaces (aka "internal modules")](https://www.typescriptlang.org/docs/handbook/namespaces.html#ambient-namespaces) by replacing the top-level 

- `export module foo {}` or `export namespace foo{}`

with

- `declare module foo {}` or `declare namespace foo{}`?

We have a large app that doesn't make it easy to use a module loader, so everything is in `script` tags and the use of top-level `import` / `export` / `require` is off the table, and instead we use triple-slash directives (`/// <reference path="./foo">`). NSwag allows us to generate almost completely suitable `.d.ts` files, except we need to do the replacement above each time.

---

Because ambient namespaces cannot(?) contain runtime code, I'm not sure about how an option to do the above should interact with others, such as `GenerateClientClasses`, or a `TypeStyle` of anything but `Interface`... Is there precedent?

(Maybe this option would make sense as an additional `TypeStyle`?)

Cf: #238, #828

**Comment by RicoSuter** [comment]
So this is mainly about adding a setting to change this line?

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/File.liquid#L68

For now you can easily change this template with a template override: 
https://github.com/RicoSuter/NJsonSchema/wiki/Templates

**Comment by r-k-b** [comment]
Ooh, _that's_ what the Templating setting is about! Thanks Rico, I'll check it out!
