### ISSUE TITLE
SwaggerUI doesn't render example values for a non-enumerable types

### ISSUE THREAD

**Issue by StasPerekrestov** [RicoSuter/NSwag#2156]
Hi,

It seems to me, there is an issue related to example values generation logic for asp.net controllers
when a controller returns a single value (in a case when OAS3 is used).

![image](https://user-images.githubusercontent.com/838093/57211996-fa119f00-6fea-11e9-9964-d5b1aefa5fd9.png)

The screenshot relates to this [code](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Sample.NETCore22/Controllers/PetController.cs#L75)

However, if you just for the sake of experiment change the return type from 
```
 [ProducesResponseType(typeof(Pet), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(SerializableError), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<Pet>> FindById(int petId)
        {
```

to 
```
ProducesResponseType(typeof(IEnumerable<Pet>), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(SerializableError), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<ActionResult<IEnumerable<Pet>>> FindById(int petId)
        {
```
it generates the expected example value

![image](https://user-images.githubusercontent.com/838093/57212447-6214b500-6fec-11e9-9e1b-cc3f19ca605e.png)

**Comment by StasPerekrestov** [comment]
For the Pet definition NSwag generates something like:
```
"responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "nullable": true,
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/Pet"
                    }
                  ]
                }
              }
            }
          },
...
```
I believe it should be
```
"responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                }
              }
            }
          },
        }
```

Please have a look at a [demo](https://app.swaggerhub.com/apis/StasPerekrestov/NswagOAS3SchemaIssue1/1#/Pet/Pet_FindById).

**Comment by RicoSuter** [comment]
Yes, this is because response reference types are nullable by default, see https://github.com/RicoSuter/NSwag/issues/2071

Try to set `DefaultResponseReferenceTypeNullHandling` to `ReferenceTypeNullHandling.NotNull` (maybe this should be the default - but it is not really correct and changing the default might break users)

**Comment by StasPerekrestov** [comment]
Oh, it looks like the issue relates to https://github.com/swagger-api/swagger-ui/issues/3803

**Comment by RicoSuter** [comment]
Yes, it's also a bug in Swagger UI: 

As pointed out in https://github.com/RicoSuter/NSwag/issues/2071 we should create an issue there that this syntax to describe nullability is supported: 

```
              "application/json": {
                "schema": {
                  "nullable": true,
                  "oneOf": [
                    {
                      "$ref": "#/components/schemas/Pet"
                    }
                  ]
                }
              }
```

**Comment by RicoSuter** [comment]
Is this correctly supported in ReDoc?

**Comment by StasPerekrestov** [comment]
Yeah, actually I don't use ReDoc, however today I poked the issue from many perspectives and turned on ReDoc. Well, I was a bit surprised, because it renders the expected output.

**Comment by StasPerekrestov** [comment]
BTW, feel free to close the issue

**Comment by RicoSuter** [comment]
Yeah, ReDoc is nice but I think it still does not support executing (Try Out) the operation so not an option for lots of people

**Comment by RicoSuter** [comment]
But could you solve your problem?

**Comment by StasPerekrestov** [comment]
Hm, something weird happens. It worked when I used a local build of NSwag.AspNetCore (from sources).
However, I cannot make it work using nuget 12.2.5. I'll give it another chance later today.

**Comment by RicoSuter** [comment]
There are no more commits after the v12.2.5 in master ATM

**Comment by StasPerekrestov** [comment]
Quite odd, recompiled with dll built from latest sources - it works. And it doesn't work with nuget packages. Mystique...

**Comment by RicoSuter** [comment]
The spec (JSON) is the same? Can you describe the diff?

**Comment by StasPerekrestov** [comment]
![image](https://user-images.githubusercontent.com/838093/57239470-a2982100-7034-11e9-8a9a-738a4fd7a39f.png)

**Comment by RicoSuter** [comment]
And what is the value of DefaultResponseReferenceTypeNullHandling? With NotNull it should not produce oneOf, is that correct?

https://github.com/RicoSuter/NSwag/commit/86a7d09a7eab6c97ca54b8fb7f064158878c668d

**Comment by StasPerekrestov** [comment]
Yeah :), I'm using
_NSwag\src\NSwag.AspNetCore_
`dotnet build -f netstandard2.0` to build it locally

BTW, I've created a demo repo https://github.com/StasPerekrestov/NSwagIssueDemo
`document.DefaultReferenceTypeNullHandling = ReferenceTypeNullHandling.NotNull;` is [set](https://github.com/StasPerekrestov/NSwagIssueDemo/blob/master/NSwagIssueDemo/Startup.cs#L33)

**Comment by StasPerekrestov** [comment]
Oh, my fault, sorry.
I used
`                t.DefaultReferenceTypeNullHandling = ReferenceTypeNullHandling.NotNull;`
instead of
                `t.DefaultResponseReferenceTypeNullHandling = ReferenceTypeNullHandling.NotNull;`

**Comment by RicoSuter** [comment]
@StasPerekrestov please have a look at this PR: https://github.com/RicoSuter/NSwag/pull/2215
