### ISSUE TITLE
AspNetCoreGenerator: MIME Types ignored

### ISSUE THREAD

**Issue by darman96** [RicoSuter/NSwag#2157]
When specifying the content-type of a controller/action via the ProducesAttribute a lot of MIME types are being ignored.
The only ones I got to work were: "application/json", "text/json" and "text/plain".
I didn't test all types but I know that "application/zip", "application/pdf" and "application/octet-stream" aren't working.

**Comment by RicoSuter** [comment]
I think you need to register your mime types here: 

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation.AspNetCore.Tests.Web/Startup.cs#L24

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation.AspNetCore.Tests.Web/CustomTextInputFormatter.cs

**Comment by darman96** [comment]
Ah thanks, didn't know I had to register the types.
It works now.

**Comment by RicoSuter** [comment]
Maybe we should document this here

https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware

or here

https://github.com/RicoSuter/NSwag/wiki/AspNetCoreToSwaggerGenerator

?

**Comment by darman96** [comment]
Since the second link is dead I would suggest to put it here: https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware
;)

**Comment by RicoSuter** [comment]
This is the correct link:
https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator

But how exactly would you enable eg application/zip so that it also works on requests (not only in the spec)?

**Comment by darman96** [comment]
Not sure what you mean. We now use a custom OutputFormatter which registers the MIME type so that out Swagger Page shows the correct type. 
The actual download via out API action did already work.

**Comment by RicoSuter** [comment]
It would be great if you could add a complete sample to the wiki.
