### ISSUE TITLE
Can multiple XML code documentation files be used?

### ISSUE THREAD

**Issue by stevenvolckaert** [RicoSuter/NSwag#2161]
_Note: I wasn't sure whether this question fits in the **NSwag** repo vs the **NJsonSchema** repo..._

The [XML Documentation page on the NJsonSchema repo](https://github.com/RicoSuter/NJsonSchema/wiki/XML-Documentation)  mentions it loads the .NET XML Documentation file automatically, using file name `$(AssemblyName).xml`.

**Is it possible to configure NSwag so it reads additional XML Doc files?**

Some background: I followed the docs on Microsoft Docs, and first got a working solution with the other Swagger provider, **Swashbuckle**. Only after some time it became clear that Swashbuckle can't be used to generate a C# or TypeScript client, something I'd like to use in our projects. So, I started looking into migrating to NSwag completely.

Below two configuration methods, the first for NSwag, the second for Swashbuckle. Is it possible to include multiple XML Doc files in NSwag's processing?

```
public static void AddSwaggerDocumentsForNSwag(this IServiceCollection services)
{
    // Docs @ https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware

    services.AddSwaggerDocument(options =>
    {
        options.Description = "The Document Signing Service allows to sign documents electronically.";
        options.DocumentName = "v1";
        options.Title = "Document Signing Service";
        options.Version = "v1";
    });
}

public static void AddSwaggerDocumentsForSwashbuckle(this IServiceCollection services)
{
    var executingAssemblySimpleName = Assembly.GetExecutingAssembly().GetName().Name;

    // Add Swagger generators
    services.AddSwaggerGen(options =>
    {
        options.ExampleFilters();

        // Define 1 or more Swagger documents
        options.SwaggerDoc("v1", new Info
        {
            Description = "The Document Signing Service allows to sign documents electronically.",
            Title = "Document Signing Service",
            Version = "v1",
        });

        // Set XML code docs for swagger.json and Swagger UI
        var pathToXmlDocumentsToLoad = AppDomain.CurrentDomain.GetAssemblies()
            .Where(x => x.FullName.StartsWith(executingAssemblySimpleName))
            .Select(x => x.GetPathToDocumentationFile())
            .ToList();

        pathToXmlDocumentsToLoad.ForEach(x => options.IncludeXmlComments(x));
    });

    // Add Swagger examples; see https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters
    // for more information
    services.AddSwaggerExamplesFromAssemblyOf<Examples.DocumentSigningRequestExamplesProvider>();
}

```

**Comment by RicoSuter** [comment]
At the moment there is no way to change the lookup pattern from the default .net you - only option for now is to change the xml output paths or copy the xml files to the dll output dir

**Comment by stevenvolckaert** [comment]
Thanks for your feedback, @RicoSuter!

**Comment by RicoSuter** [comment]
Is this an issue where we need to provide an extension point?

Ref: https://github.com/RicoSuter/Namotion.Reflection

**Comment by stevenvolckaert** [comment]
@RicoSuter I'm not following... What do you mean with _an extension point_?

Let me give an example for my use case; I think a little more context help illustrate what I'm trying to achieve.

Let's assume we have a ASP.NET Core 2.2 project `DocumentSigningService`; the controllers defined within all have XML code documentation, resulting in a `DocumentSigningService.xml` file when the project is compiled. This XML file is picked up by NSwag automatically and used to generate the Swagger / OpenAPI JSON document.

Now say I want to defined my DTO classes in a separate (e.g. .NET Standard) project called `DocumentSigningService.Models`, where the models also are annotated using XML code documentation tags.

If project `DocumentSigningService` has a depencency to `DocumentSigningService.Models` ( `<ProjectReference>` in the `.csproj` file), `DocumentSigningService.Models.xml` is copied to the output directory of `DocumentSigningService` (e.g. `bin/debug/netcoreapp22/`).

However, NSwag won't process `DocumentSigningService.Models.xml`, so the model classes remain undocumented in the Swagger / OpenAPI document.

**Comment by RicoSuter** [comment]
> However, NSwag won't process DocumentSigningService.Models.xml, so the model classes remain undocumented in the Swagger / OpenAPI document.

That is not correct - NSwag/NJsonSchema will search for the xml file for each type's assembly and not only use the xml of the entry assembly...

**Comment by stevenvolckaert** [comment]
@RicoSuter I tried again, and indeed, you are right. Sorry for the confusion, I'll close this issue.

Thanks again for your reponses!

**Comment by danielmeza** [comment]
@RicoSuter To extent Nanomotion.Reflection we can add public methods on XmlDocs to include types in the cache.
I have a diferent escenario where I need to load the xml file from assembly resource cause I'm hosting my app in an Xamarin Android application and there I cann't just publish a .xml file, then all mi resources are embebed inside the .dll, It will be grate to have a public method where I can add Xml documetns to it.

**Comment by danielmeza** [comment]
As work arround I create this extension method to add documents to the cache directly. 
``` csharp
        private static readonly Lazy<Dictionary<string, XDocument>> LazyCache = new Lazy<Dictionary<string, XDocument>>(() =>
        {
            var type = typeof(XmlDocsExtensions);
            var cacheField = type.GetField("Cache", BindingFlags.NonPublic | BindingFlags.Static);
            var value = cacheField.GetValue(null);

            return (Dictionary<string, XDocument>)value;
        });

        public static AspNetCoreOpenApiDocumentGeneratorSettings AddDocumentation(
            this AspNetCoreOpenApiDocumentGeneratorSettings settings,
            AssemblyName name, 
            XDocument xDocument)
        {
            var cache = LazyCache.Value;
            if (!cache.TryAdd(name.FullName, xDocument) && cache.TryGetValue(name.FullName, out var document) && document is null)
            {
                cache[name.FullName] = xDocument;
            };
            return settings;
        }

        public static AspNetCoreOpenApiDocumentGeneratorSettings AddDocumentation<T>(this AspNetCoreOpenApiDocumentGeneratorSettings settings, XDocument xDocument)
        {
            var type = typeof(T);
            settings.AddDocumentation(type.GetTypeInfo().Assembly.GetName(), xDocument);
            return settings;
        }


        public static AspNetCoreOpenApiDocumentGeneratorSettings AddDocumentationFromResource<T>(this AspNetCoreOpenApiDocumentGeneratorSettings settings)
        {
            var type = typeof(T);
            var assembly = type.GetTypeInfo().Assembly;
            var assemblyName = assembly.GetName();
            var documentationResource = assembly.GetManifestResourceNames().FirstOrDefault(r => r.EndsWith($"{assemblyName.Name}.xml"));
            if (!string.IsNullOrWhiteSpace(documentationResource))
            {
                using var documentStream = assembly.GetManifestResourceStream(documentationResource);
                var document = XDocument.Load(documentStream);
                settings.AddDocumentation(assemblyName, document);

            }
            return settings;
        }
```

In the startup
``` csharp
            services.AddOpenApiDocument((document, sp) =>
            {
                document.PostProcess = document =>
                {
                   ...
                };

                document.AddDocumentationFromResource<Startup>();
            });
```

And it work great! 
I maded the implementation in the PostProcess but since the PostProcess run after the documentation is merged thent it not work properly.
