### ISSUE TITLE
additionalProperties is generated with a boolean in swagger2

### ISSUE THREAD

**Issue by ling1726** [RicoSuter/NSwag#2170]
When using webapi2swagger with outputType set as swagger2 , the additionalProperties field is generated with a boolean set to false.

This is not correct for swagger2 since the boolean value was only introduced for this field in open api 3

**Comment by RicoSuter** [comment]
What't the alternative way to express this in Swagger 2?

**Comment by ling1726** [comment]
In Swagger 2 additionalProperties cannot take a boolean value. Either it is present, or it takes a Schema Object as value

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema-object

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schema-object

See the differences in spec in the above specifications (v2 and v3)

**Comment by RicoSuter** [comment]
So we should just disable generation of `"additionalProperties": false` because this is the default for Swagger 2? The default for OpenAPI 3/JSON Schema is true I think so there it is needed... correct?

**Comment by ling1726** [comment]
I agree with disabling the generation of this field in swagger 2.

I think you can disable it for OpenApi 3 too, since if it's not present the spec assumes that field is true.

On a broader note, how is this property generated if it does take a schema object in NSwag ?

**Comment by RicoSuter** [comment]
It is generated as a property with an object, e.g. `"additionalProperties": { ... }`

Currently it is only set to `false` because the default is `true` if it is true and has no schema then it is omitted. The big question is what are the defaults of this property for Swagger2/OpenAPI3/JSON Schema?

**Comment by ling1726** [comment]
The default is only `true` for OpenAPI3

Swagger2 has no notion of a boolean value for this property

**Comment by RicoSuter** [comment]
The question is the behavior...

**Comment by ling1726** [comment]
If you check here https://swagger.io/docs/specification/data-models/data-types/

you'll see that `additionalProperties: true` is equivalent to `additionalProperties: {}` which is the default behaviour. setting one of the two previous values, just makes this explicit

**Comment by RicoSuter** [comment]
> you'll see that additionalProperties: true is equivalent to additionalProperties: {} which is the default behaviour

How can I disable additional properties when not setting the property defaults to additionalProperties: {}?

**Comment by RicoSuter** [comment]
Ref https://github.com/swagger-api/swagger-core/issues/1437#issuecomment-226647555

**Comment by ling1726** [comment]
According to that issue thread in swagger, that would should mean that we can assume additionalProperties as `false` if it isn't present. If the field is present then it should be a JSON Schema.

Only in the OAS v3 spec is `additionalProperties: false` actually required. As seen in this PR https://github.com/OAI/OpenAPI-Specification/pull/1548

**Comment by RicoSuter** [comment]
Just nice, what a big mess these whole JSON Schema/Swagger 2/OpenAPI 3 specs are...

**Comment by ling1726** [comment]
I agree 👍 

My main issue here, is swagger v2 parsers/validators might fail at the generated swagger output, since they will not expect this field to have a boolean as a value

**Comment by RicoSuter** [comment]
Created a PR ... tests missing

**Comment by ling1726** [comment]
Cool, I'll take a look at it in a bit, unless you want to go ahead and merge it yourself ;)

**Comment by RicoSuter** [comment]
Please check/review the tests.
