### ISSUE TITLE
new version generates code that has compile errors for angular service

### ISSUE THREAD

**Issue by roscoedeemarutam** [RicoSuter/NSwag#2184]
Hi, I'm using the "Web API or ASP.NET Core via Reflection (deprecated)" option to generate my Angular Service code. 
Installing the latest version generates code that gives me compile errors in Angular. 
Class ‘Foo’ used before its declaration.(error TS2449). so the order in which classes are generated is not correct. I have to go in the generated code and move classes around to make the compiler happy! this offcourse is not ideal or even excepable :(

I have a few questions. 
What does deprecated actually mean? Is this option going to disappear? And if yes  I assume there is a different preferred way of handling this? What would be the preferred way?
Because if I try to use .net Assembly it generates completely different code which is not working for me. (no enum types were generated while they are properties on my input and output types) and I also get the error TS2449.
If I want to keep using the 12.2.4 version which generates the right code I will not be able to update code generation to future TS versions and RxJS versions, right?

Please advise on how to move forward with this?!

**Comment by kasparkallas** [comment]
I experienced the same issue with the newest update of `12.3.0`. I fixed it by downgrading to `12.2.5`.

The error is for a inherited generic class. The inheritance goes like this:
BaseClass
BaseClass<T> : BaseClass
ConcreteClass : BaseClass<TConcrete>

I did not investigate thoroughly though.

**Comment by RicoSuter** [comment]
Pretty sure its a regression of this pr: https://github.com/RicoSuter/NSwag/pull/2033

**Comment by RicoSuter** [comment]
Actually it’s because i removed this line and didnt add it again:

https://github.com/RicoSuter/NJsonSchema/commit/521519b482a71a9bd70cf13ea46c4a77fea4f73b#diff-2d5a539e462d39b4234c5350f3e7f250L23
