### ISSUE TITLE
Swagger UI error should be more descriptive

### ISSUE THREAD

**Issue by jvhih** [RicoSuter/NSwag#2186]
Based on the error from this [issue 2123](https://github.com/RicoSuter/NSwag/issues/2123).

I was using a property that wasn't marked deprecated and the error displayed on the UI and console were unable to point me in the right direction as to what was wrong.

When using IServiceCollection.AddOpenApiDocument() I was adding an IOperationProcessor that was setting a parameter that is deprecated for Open API.

The following was causing me an issue:
```
public class SampleHeaderOperationProcessor : IOperationProcessor
{
    public Task<bool> ProcessAsync(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.Add(
            new SwaggerParameter {
                Name = "Sample",
                Kind = SwaggerParameterKind.Header,
                Type = NJsonSchema.JsonObjectType.String,    // problem line
                IsRequired = false,
                Description = "This is a test header",
                Default = "{{\"field1\": \"value1\", \"field2\": \"value2\"}}"
            });

        return Task.FromResult(true);
    }
}
```

The following fixed it:
```
public class SampleHeaderOperationProcessor : IOperationProcessor
{
    public Task<bool> ProcessAsync(OperationProcessorContext context)
    {
        context.OperationDescription.Operation.Parameters.Add(
            new SwaggerParameter {
                Name = "Sample",
                Kind = SwaggerParameterKind.Header,
                Schema = new JsonSchema4 { Type = NJsonSchema.JsonObjectType.String },    // solution line
                IsRequired = false,
                Description = "This is a test header",
                Default = "{{\"field1\": \"value1\", \"field2\": \"value2\"}}"
            });

        return Task.FromResult(true);
    }
}
```

[The unhelpful error](https://i.stack.imgur.com/EjKlV.png).

Possible solutions:

1. Mark the field as obsolete with a description saying to use the 'Schema' property for Open API or
2. Update the UI with something a little more descriptive instead of simply displaying "Could not render this component, see the console."

**Comment by RicoSuter** [comment]
This should be created here: https://github.com/swagger-api/swagger-ui
