### ISSUE TITLE
How to format a property as password with NSwag?

### ISSUE THREAD

**Issue by klacol** [RicoSuter/NSwag#2193]
How to create a password-formated property from C#?

We need something like this:

```
        - name: password
          in: query
          required: true
          schema:
            type: string
            nullable: true
            format : password
```

Thanks!

**Comment by RicoSuter** [comment]
Do you want this spec generated from a parameter/property?

**Comment by RicoSuter** [comment]
[JsonSchemaTypeAttribute]

**Comment by klacol** [comment]
> Do you want this spec generated from a parameter/property?

yes, thanks, we will try that.
