### ISSUE TITLE
Axios array is not recognized as an array in NodeJs at NSwag.CodeGeneration.TypeScript + possible fix

### ISSUE THREAD

**Issue by Arsync** [RicoSuter/NSwag#2199]
WebAPI returns JSON array, content-type header is `"application/json; charset=utf-8"`.

Autogenerated by NSwag code (TypeScriptClient for Axios) runs twice - with server side rendering (SSR) by NodeJS and in a browser:
```
 if (status === 200) {

  const _responseText = response.data;

  let result200: any = null;
  let resultData200  = _responseText;

  if (resultData200 && resultData200.constructor === Array) {

    result200 = [] as any;

    for (let item of resultData200)
      result200!.push(item);
  }

  return result200;
}
```
So `resultData200.constructor === Array` without any changes become `false` at NodeJs and `true` in a browser.

In both cases `response.data` looks like `['value1', 'value2']`, status code 200.

babel.config.js:
```
module.exports = {
  presets: [[ '@vue/app', { useBuiltIns: false } ]]
  plugins: [
    '@babel/plugin-syntax-dynamic-import'
  ]
}
```
Anyway,
```
  var arr = [ 'a', 'b' ];
  console.log(`Check this: ${arr.constructor === Array}`);
```
is `true` in NodeJs and in a browser. So, what's going on?

[Best answer](https://stackoverflow.com/questions/28467266/can-i-use-obj-constructor-array-to-test-if-object-is-array) can help: there are a few scenarios where it can return a different value, but Array.isArray will work.

Root of evil is deep inside of TS-generator - in a DataConversionGenerator.

Anyway, when I replaced the `resultData200.constructor === Array` to `Array.isArray(resultData200)`, it was started to work!

**Comment by RicoSuter** [comment]
Please check the PR.

**Comment by Arsync** [comment]
> Please check the PR.
Ok, it solves the problem. So, it was in liquid templates.

**Comment by RicoSuter** [comment]
For now, you can just override the template with a local one until the fix is merged + released.

**Comment by RicoSuter** [comment]
So can we merge this PR? Is it safe?

**Comment by Arsync** [comment]
I still don't have enough experience to answer «yes, it is safe for all cases». I've override templates and now this PR works for me - both at server and client.

**Comment by RicoSuter** [comment]
Too late 🙂 but to me it looks safe (ES 5)
