### ISSUE TITLE
The schema reference path has not been resolved. Worked in previos versions

### ISSUE THREAD

**Issue by PaulSokolov** [RicoSuter/NSwag#2211]
I can send you the file and test code to reproduce this issue. It happens in the latest version of sources

**Comment by RicoSuter** [comment]
Please provide more info: Sample code, actual/expected.

**Comment by PaulSokolov** [comment]
CustomTest.cs paste in  NSwag.CodeGeneration.CSharp

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PaulSokolov** [comment]
@RicoSuter  sent you an email with subject Issue #2211

**Comment by PaulSokolov** [comment]
@RicoSuter have you got it?

**Comment by RicoSuter** [comment]
Why do you send them by mail? is it confidential? Please post a repro here..

**Comment by PaulSokolov** [comment]
@RicoSuter yes, it is. But I think it`s a bug after last changes so it`s important to fix I think. And to say truly I work on modification of your program to resolve oneOf stuff by marker interface. But now it`s a stopper for me. Or maybe you have in plans to resolve oneOf, I saw a lot of issues on this theme here

**Comment by RicoSuter** [comment]
Please provide samples and repros here...
Is this related to this PR? https://github.com/RicoSuter/NSwag/pull/2215

**Comment by PaulSokolov** [comment]
`{
  "openapi": "3.0.0",
  "info": {
    "title": "API",
    "description": "# Introduction",
    "contact": {
      "email": "email@email.com"
    },
    "version": "1.0-draft",
    "x-logo": {
      "url": "",
      "altText": "Petstore logo"
    }
  },
  "servers": [
    {
      "url": "/api/v2",
      "description": "server"
    }
  ],
  "paths": {
    "/subscriptions/{subscriptionId}": {
      "get": {
        "tags": [
          "subscriptions"
        ],
        "summary": "get subscription details",
        "operationId": "subscriptions_details",
        "responses": {
          "200": {
            "description": "Subscription list response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Subscription"
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          }
        }
      },
      "delete": {
        "tags": [
          "subscriptions"
        ],
        "summary": "delete subscription",
        "operationId": "subscriptions_delete",
        "responses": {
          "204": {
            "$ref": "#/components/responses/Deleted"
          },
          "401": {
            "$ref": "#/components/responses/Unauthorized"
          },
          "403": {
            "$ref": "#/components/responses/Forbidden"
          },
          "409": {
            "$ref": "#/components/responses/Conflict"
          }
        }
      },
      "parameters": [
        {
          "name": "subscriptionId",
          "in": "path",
          "required": true,
          "schema": {
            "$ref": "#/components/schemas/EntityId"
          }
        }
      ]
    }
  },
  "components": {
    "schemas": {
      "Subscription": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        }
      },
      "EntityId": {
        "format": "secret",
        "type": "string",
        "example": "851D64D0-86DF-4BEC-8BA0-C81E326D735A"
      },
      "Created": {
        "type": "object",
        "properties": {
          "id": {
            "description": "entity id",
            "type": "string"
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "message": {
            "description": "error description",
            "type": "string"
          }
        }
      }    
    },
    "responses": {
      "Unauthorized": {
        "description": "Access token is missing or invalid",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "NotFound": {
        "description": "NotFound",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "Forbidden": {
        "description": "Forbidden",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      },
      "Created": {
        "description": "Resource created",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Created"
            }
          }
        }
      },
      "Deleted": {
        "description": "Resource deleted"
      },
      "Conflict": {
        "description": "Conflict",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Error"
            }
          }
        }
      }
    },
    "parameters": {
      "offsetParam": {
        "name": "$after",
        "in": "query",
        "description": "The continuation cursor",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "limitParam": {
        "name": "$count",
        "in": "query",
        "description": "The numbers of items to return.",
        "required": false,
        "schema": {
          "default": 20,
          "minimum": 1,
          "type": "integer"
        }
      },
      "exportFormatParam": {
        "name": "format",
        "in": "query",
        "description": "The numbers of items to return.",
        "required": false,
        "schema": {
          "enum": [
            "csv",
            "pdf",
            "xls"
          ],
          "type": "string"
        }
      },
      "orgIdParam": {
        "name": "orgId",
        "in": "path",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/EntityId"
        }
      },
      "organizationFilter": {
        "name": "orgId",
        "in": "query",
        "description": "filter by organizationId",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/EntityId"
        }
      },
      "locationFilter": {
        "name": "locationId",
        "in": "query",
        "description": "filter by locationId",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/EntityId"
        }
      },
      "stationFilter": {
        "name": "stationId",
        "in": "query",
        "description": "filter by stationId",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/EntityId"
        }
      },
      "fromTimeFilter": {
        "name": "from",
        "in": "query",
        "description": "filter by time",
        "required": false,
        "schema": {
          "format": "date-time",
          "type": "string"
        }
      },
      "untilTimeFilter": {
        "name": "until",
        "in": "query",
        "description": "filter by time",
        "required": false,
        "schema": {
          "format": "date-time",
          "type": "string"
        }
      },
      "userFilter": {
        "name": "userId",
        "in": "query",
        "description": "filter by userId",
        "required": false,
        "schema": {
          "$ref": "#/components/schemas/EntityId"
        }
      }
    },
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "description": "HTTP bearer authorization description",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearer": []
    }
  ],
  "tags": [
    {
      "name": "users_invitations",
      "description": "invitations invitations invitations invitations invitations invitations",
      "x-displayName": "users invitations"
    },
    {
      "name": "vehicles",
      "description": "Vehicles can be owned by register user accounts or organization accounts.\n"
    },
    {
      "name": "locations",
      "description": ""
    },
    {
      "name": "common",
      "description": ""
    },
    {
      "name": "users",
      "description": ""
    },
    {
      "name": "stations",
      "description": ""
    },
    {
      "name": "organizations",
      "description": ""
    },
    {
      "name": "sessions",
      "description": ""
    },
    {
      "name": "subscriptions",
      "description": ""
    }
  ]
}`

`var path = "api.json";
                var document = await OpenApiDocument.FromFileAsync(path);
                var itemsToMark = document.Components.Schemas.Where(i => i.Value.OneOf.Any() || i.Value.ActualProperties.Where(p => p.Value.OneOf.Any()).Any()).ToList();



                var command = new OpenApiToCSharpControllerCommand();
                command.Input = document;
                command.UseCancellationToken = true;
                command.GenerateDataAnnotations = true;
                command.HandleReferences = true;
                command.GenerateDefaultValues = false;
                command.GenerateJsonMethods = false;
                var result = await command.RunAsync();`
Stack trace:

   at NJsonSchema.JsonSchema.GetActualSchema(IList`1 checkedSchemas)
   at NSwag.OpenApiParameter.get_ActualSchema() in C:\NSwag\src\NSwag.Core\OpenApiParameter.cs:line 169
   at NSwag.CodeGeneration.CSharp.Models.CSharpOperationModel.ResolveParameterType(OpenApiParameter parameter) in C:\NSwag\src\NSwag.CodeGeneration.CSharp\Models\CSharpOperationModel.cs:line 229
   at NSwag.CodeGeneration.CSharp.Models.CSharpOperationModel.<>c__DisplayClass5_0.<.ctor>b__5(OpenApiParameter parameter) in C:\NSwag\src\NSwag.CodeGeneration.CSharp\Models\CSharpOperationModel.cs:line 76
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NSwag.CodeGeneration.CSharp.Models.CSharpOperationModel..ctor(OpenApiOperation operation, CSharpGeneratorBaseSettings settings, CSharpGeneratorBase generator, CSharpTypeResolver resolver) in C:\NSwag\src\NSwag.CodeGeneration.CSharp\Models\CSharpOperationModel.cs:line 74
   at NSwag.CodeGeneration.CSharp.Models.CSharpControllerOperationModel..ctor(OpenApiOperation operation, CSharpControllerGeneratorSettings settings, CSharpControllerGenerator generator, CSharpTypeResolver resolver) in C:\NSwag\src\NSwag.CodeGeneration.CSharp\Models\CSharpControllerOperationModel.cs:line 25
   at NSwag.CodeGeneration.CSharp.CSharpControllerGenerator.CreateOperationModel(OpenApiOperation operation, ClientGeneratorBaseSettings settings) in C:\NSwag\src\NSwag.CodeGeneration.CSharp\CSharpControllerGenerator.cs:line 87
   at NSwag.CodeGeneration.ClientGeneratorBase`3.<>c__DisplayClass16_0.<GetOperations>b__1(<>f__AnonymousType0`3 tuple) in C:\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 158
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GetOperations(OpenApiDocument document) in C:\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 148
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateAllClientTypes() in C:\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 102
   at NSwag.CodeGeneration.CSharp.CSharpControllerGenerator.GenerateAllClientTypes() in C:\NSwag\src\NSwag.CodeGeneration.CSharp\CSharpControllerGenerator.cs:line 54
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile(ClientGeneratorOutputType outputType) in C:\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 73
   at NSwag.CodeGeneration.ClientGeneratorBase`3.GenerateFile() in C:\NSwag\src\NSwag.CodeGeneration\ClientGeneratorBase.cs:line 65
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpControllerCommand.<RunAsync>b__23_0() in C:\NSwag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpControllerCommand.cs:line 94
   at NSwag.Commands.CodeGeneration.SwaggerToCSharpControllerCommand.RunAsync() in C:\NSwag\src\NSwag.Commands\Commands\CodeGeneration\OpenApiToCSharpControllerCommand.cs:line 90
   at NSwag.CodeGeneration.CSharp.Tests.CSharpNewFeaturesTests.When_body_is_binary_then_stream_is_used_as_parameter_in_CSharp() in C:\NSwag\src\NSwag.CodeGeneration.CSharp.Tests\CustomTest.cs:line 34

The schema reference path '#/components/schemas/EntityId' has not been resolved.

**Comment by RicoSuter** [comment]
Ref https://github.com/RicoSuter/NJsonSchema/issues/1004
