### ISSUE TITLE
Disabling Annotations

### ISSUE THREAD

**Issue by john-larson** [RicoSuter/NSwag#2213]
I am using nswag.exe swagger2csclient with the `generatedataannotations:false` option in MSBuild but it still generates annotations such as `[Newtonsoft.Json.JsonProperty("id", Required = Newtonsoft.Json.Required.Always)] `for properties and `[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.14.1.0 (Newtonsoft.Json v11.0.0.0)")]` for classes. How can I disable this?

**Comment by RicoSuter** [comment]
You can only disable validation annotations, i.e. newtonsoft.json attributes cannot be disabled because serialization would no longer work correctly without them.

**Comment by john-larson** [comment]
OK, thanks for the info.
