### ISSUE TITLE
How to set DefaultPropertyNameHandling in NSwag v12.3.1?

### ISSUE THREAD

**Issue by Desomph** [RicoSuter/NSwag#2216]
Since the newest version of the Swagger this code (because of GeneratorSettings) is now obsolete:
``` C#
 app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, settings =>
        {
            settings.GeneratorSettings.DefaultPropertyNameHandling =
                PropertyNameHandling.CamelCase;
        });
```
Instead, we should use:
```  C#
services.AddSwaggerDocument(cfg =>
        {
           ...
        });
```
However, I have no idea where to set-up the camel case thing now. Can anyone help me with this?

**Comment by RicoSuter** [comment]
DefaultPropertyNameHandling is deprecated because you should just change the json serializer so that the spec AND serializer work the same:

```
// configureservices
            services.AddMvc()
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                });

services.AddSwaggerDocument();

// configure
app.UseOpenApi();
app.UseSwaggerUi3();
```

**Comment by Desomph** [comment]
Using your code:

Sending request, and receiving JSON response look to me like properties are always lower cased. However, when opening Swagger UI in browser, looks like the property names are actually upper cased.

![Annotation 2019-06-07 142843](https://user-images.githubusercontent.com/11526902/59104218-437a4480-8931-11e9-96eb-c5eac9578298.png)

Not sure if this is just UI bug, or the code is not working as intended, here's part of JSON code:

```JSON
{
    "type": "integer",
    "name": "Size",
    "in": "query",
    "format": "int32",
    "maximum": 100.0,
    "minimum": 1.0,
    "x-nullable": false
}
```

**Comment by RicoSuter** [comment]
Query params do not use the json serializer but can be renamed with the FromQuery(.. attribute

**Comment by Desomph** [comment]
Alright, thanks a lot!

**Comment by mcquiggd** [comment]
A question - what if we are not using Mvc ? For example, I am using NSwag in Azure Functions.

**Comment by RicoSuter** [comment]
You should be able to change the contract resolver via the generator settings
