### ISSUE TITLE
ASP.NET non-Core support

### ISSUE THREAD

**Issue by eolamisan** [RicoSuter/NSwag#2217]
What is the Asp .Net non-Core support road-map?
When will the below tab be removed?
What will be the workflow for Asp .Net Web Api non-Core projects when the below tab will be removed?

![image](https://user-images.githubusercontent.com/4191912/59132547-7decdd00-8943-11e9-9863-d914ff4d102d.png)

**Comment by RicoSuter** [comment]
I don’t plan to remove this tab as long as it’s feasible to maintain asp.net support... it’s mainly deprecated for core projects. However I personally will not put a lot of work into improving the legacy asp.net generator... as long as this is still used by people i’ll keep it - no worries, but new features will only lang in the core generator.

**Comment by eolamisan** [comment]
![image](https://user-images.githubusercontent.com/4191912/60521427-44469200-9cb5-11e9-8f54-5dacfe84e099.png)
Great, looks like the deprecation plan has been dropped

**Comment by RicoSuter** [comment]
Yeah, but please dont use it for asp.net core
