### ISSUE TITLE
Default value for parameters aren't working in OpenAPI v3

### ISSUE THREAD

**Issue by Place1** [RicoSuter/NSwag#2227]
Currently the swaggerToCSharpController doesn't correctly generate default values for parameters. I've been debugging NSwag locally and while i've struggled to find the root cause i've noticed a few things that might be relevant:

- [HasDefault](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration/Models/ParameterModelBase.cs#L67) returns false breaking [TypeInControllerInterface](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Models/CSharpParameterModel.cs#L46)
- [_parameter.Default](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration/Models/ParameterModelBase.cs#L70) is null but `_parameter.ActualSchema.Default` is `"10"`

I've included an example spec below.

```
openapi: 3.0.0

info:
  title: My API
  version: 0.0.0

paths:
  /Api/Endpoint/:
    get:
      tags:
        - Endpoint
      summary: list resource
      operationId: example
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            format: int32
            default: 10
```

**Comment by RicoSuter** [comment]
For OpenAPI 3 it's `_parameter.ActualSchema.Default` - for Swagger 2 it's `_parameter.Default`...

Maybe we should add new property to `OpenApiParameter` and use that:

    ActualDefault => _parameter.Default ?? _parameter.ActualSchema?.Default;

**Comment by Place1** [comment]
@RicoSuter that sounds like a good idea to me :D would you like me to submit a PR? or are you happy to do it for me 😅

**Comment by RicoSuter** [comment]
Maybe we should always use `_parameter.ActualSchema.Default`? Or will this break swagger 2?

**Comment by RicoSuter** [comment]
Is this ok? We should also add tests.

**Comment by RicoSuter** [comment]
v13.0.1

**Comment by pwen090** [comment]
@RicoSuter Hello, we are using latest versions of NSwag via build commands $(NSwagExe_Core31) and our swagger.json has schema type integer with a default of 10 same as @Place1  but the generated code is not generating with the default value. It is just generating as OurAPI(int? number). Any ideas of what we should check? We do have generateDefaultValues set to true in our nswag.

**Comment by RicoSuter** [comment]
Can you provide a simple sample spec?

**Comment by 2Meister4Eder** [comment]
Hello @RicoSuter, sorry to re-activate this old issue, however I seem to have the same one. 

In my C#-Controller I have specified a parameter string xyz = "". The swagger json looks correct, I'm getting schema -> default: "". SwaggerUI shows the default string correctly. NSwag json has generateDefaultValues = true. It does not change anything when I use any other string instead of an empty string as default. 

I'm using the following version: Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0))
