### ISSUE TITLE
Does NSwag allow the usage of the "URLS" configuration parameter for the Swagger-UI?

### ISSUE THREAD

**Issue by klacol** [RicoSuter/NSwag#2231]
The Swagger-UI and the configuration options are well documented by Smartbear here:

https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

The parameter ```URLS``` does allow to switch between multiple API specification files.

> Array. An array of API definition objects ([{url: "<url1>", name: "<name1>"},{url: "<url2>", name: "<name2>"}]) used by Topbar plugin. When used and Topbar plugin is enabled, the url parameter will not be parsed. Names and URLs must be unique among all items in this array, since they're used as identifiers.

Can this parameter be accessed with NSwag OpenAPI Generator from C#?

**Comment by RicoSuter** [comment]
You can define multiple specs:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/SwaggerUi3Settings.cs#L104

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs#L111

**Comment by etask-ps** [comment]
> https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs#L111

should this also work with OWIN Middleware?

**Comment by klacol** [comment]
ok, thanks
