### ISSUE TITLE
NullReferenceException in generated CSharp Client Code

### ISSUE THREAD

**Issue by marcBalta** [RicoSuter/NSwag#2234]
The generated code with the default settings of the CSharp Client mode throws a NullReferenceException when the server WebApi returns  status=400 and ReadResponseString is false.

Then ObjectResponseResult will be initizialized with Text set to null which in turn will be used to inialize ApiExceptions response field.  The class ApiException does then the following, which leads then to a NullReferenceException
``` response.Substring(0, response.Length >= 512 ? 512 : response.Length ```

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NSwag/pull/1976

**Comment by RicoSuter** [comment]
Will patch ASAP

**Comment by RicoSuter** [comment]
v13.0.1

**Comment by marcBalta** [comment]
That was fast. Thanks!

**Comment by Gakk** [comment]
@RicoSuter: Is this error introduced again? We are using **NSwag 13.2.0** and gets **`NullReferenceException`** on timeout from server, as this don't have any content/response.

This is my response on timeout:
`{ StatusCode: 408, ReasonPhrase: 'Request Timeout', Version: 1.1, Content: <null>, Headers: {} }`

Generated client has this code:
```c#
if (status_ != "200" && status_ != "204")
{
    var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
    throw new ApiException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, responseData_, headers_, null);
}
```

When `response._Content` is `null`, then `responseData` gets `null`.

`Null` is sent as third parameter `response` to `ApiException`'s constructor, where it results in **`NullReferenceException`** on **`response.Substring`**:

```
public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException) 
    : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + response.Substring(0, response.Length >= 512 ? 512 : response.Length), innerException)
```
