### ISSUE TITLE
Support for blazor serialiser: Microsoft.JSInterop.Json

### ISSUE THREAD

**Issue by dazinator** [RicoSuter/NSwag#2237]
I just checked out using nswag studio to generate a csharp client, for use within a blazor client side app.

Newtonsoft serializer is not available in blazor client side apps. However microsoft have provided the following json seriliasation mechanism for blazor apps based on             Microsoft.JSInterop.Json:

```
          var thing =  Microsoft.JSInterop.Json.Deserialize<T>(responseText);
          var json =  Microsoft.JSInterop.Json.Serialize(thing);
```

Sadly I couldn't find any `stream` based serialisation operations, so when using this serialiser, current methods that use newtonsoft with streams would have to be replaced by the above two (i.e convert to string first).

**Comment by danroth27** [comment]
You should be able to use Newtonsoft.Json in client-side Blazor apps. But the framework is switching to use the new System.Text.Json serializer.

@dougbu

**Comment by dougbu** [comment]
@dazinator what is the exact issue you're hitting? For example does adding a reference to NewtonSoft.Json to your client-side app lead to an error?

**Comment by dazinator** [comment]
@dougbo 
In earlier days, newtonsoft did have some issues running on client side blazor due to lack of Linq - I am guessing these are now probably resolved, however I still think this issue still makes sense as a feature request - add support for blazor's native JSON serialisation mechanism rather than force a dependency on newtonsoft.. 

One key reason for this suggestion (correct me if I am wrong) is that Blazor's native JSON serialiser will be chosen / created keeping client side file size in mind which is an important constraint for apps that must be downloaded to the client. Newtonsoft's json parser, although very powerful, was never designed from the get go to be light weight, with a light foot print, for optimal use in client side applications..

**Comment by RicoSuter** [comment]
Last time I tried Blazor it worked flawlessly with Newtonsoft.Json and the generated clients and models could be used without problems. 

I think it doesn't make much sense to support Blazor's serializer as it will eventually use System.Text.Json. 

However it makes sense to add an option to generate models (DTOs) to use System.Text.Json's serializer, this is tracked here: https://github.com/RicoSuter/NJsonSchema/issues/1013

I've created an epic regarding System.Text.Json support in overall: 
https://github.com/RicoSuter/NSwag/issues/2243

**Comment by dazinator** [comment]
@RicoSuter System.Text.Json works for me, closing
