### ISSUE TITLE
Update the version of Newtonsoft.Json to support the load of the type 'Newtonsoft.Json.Serialization.ISerializationBinder'

### ISSUE THREAD

**Issue by juanperezADD** [RicoSuter/NSwag#2238]
We are using NSwag 13.0.0 to generate the APIClient for the ASPNET.Core microservices.

One of them does not generate the APIClient because it returns the following error:
```
Unhandled Exception: System.AggregateException: One or more errores occurred. (Could not load type 'Newtonsoft.Json.Serialization.ISerializationBinder' from assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.)
```
The microservice uses the Newtonsoft.Json 12.0.1 version that includes the type ISerializationBinder (it was included in the 10.0.1). However, NSwag uses the Newtonsoft.Json 9.0.0 version, which doesn't have the ISerializationBinder type.

Could the Newtonsoft.Json package be updated to a compatible version?

Thank you in advance.

**Comment by RicoSuter** [comment]
Can you post a full stack trace?

**Comment by juanperezADD** [comment]
We have implemented a console application "ProxyGenerator" that uses the NSwag packages to generate the APIClient. 

This project adds the following references:
- NSwag.AspNetCore
- NSwag.CodeGeneration.CSharp
- NSwag.Generation.WebApi

As a workaround, if we add the Newtonsoft.Json 12.0.1 package to the console application, we force NSwag APIs to use the new version of the Newtonsoft.Json and the failing microservice can already generate the APIClient correctly.

We can work with this configuration but it would be better if NSwag had the Newtonsoft.Json updated.

Full stack trace:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Could not load type 'Newtonsoft.Json.Seria 
lization.ISerializationBinder' from assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=38ad4fe6 
b2a6aeed' . ) 
System.TypeLoadException: Could not load type 'Newtonsoft.Json.Serialization.ISerializationBinder' from 
assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=38ad4fe6b2a6aeed ' 
at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes) 
at System.Reflection.RuntimeAssembly.GetExportedTypes() 
at NSwag.Generation.WebApi.WebApiOpenApiDocumentGenerator.GetControllerClasses(Assembly assembly) 
at ProxyGenerator.Program.GenerateApiClientAsync(String servicesDllLocation, String services 
DllFolder, String outputFolder, List`1 importedNamespaces, Boolean excludeWebControllers, Boolean generateDTOs, String pr 
xyNamespace) in D:\ProxyGenerator\Program.cs:line 113 
at ProxyGenerator.Program.<>c__ DisplayClass0_0.<<Main>>b__1>d.MoveNext() in D:\ProxyGenera
tor\Program.cs:line 78 
--- End of inner exception stack trace --- 
at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) 
at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) 
at ProxyGenerator.Program.Main(String[] args) in D:\ProxyGenera
tor\Program.cs:line 87 
````

**Comment by RicoSuter** [comment]
> As a workaround, if we add the Newtonsoft.Json 12.0.1 package to the console application, we force NSwag APIs to use the new version of the Newtonsoft.Json and the failing microservice can already generate the APIClient correctly.

This is the intended way...

> We can work with this configuration but it would be better if NSwag had the Newtonsoft.Json updated.

We keep the version low on purpose - so that users still on older versions of Newtonsoft.Json can still use NSwag and are not forced to upgrade. You can always enforce a newer version (like you do now) but you cannot enforce a lower version...

**Comment by juanperezADD** [comment]
Ok, I understand the reasons. Thanks for your time.
