### ISSUE TITLE
OpenApiTag description tag

### ISSUE THREAD

**Issue by stephaneworkspace** [RicoSuter/NSwag#2242]
Hello

I'm using 13.0.1 and [SwaggerTag("Entity", Description = "My entity")] is obsolete now

I use OpenApiTag, but I don't find

````
Description = ""
````

in OpenApiTag interface. Will you add it in the next release for version 13.

Thanks in advance  for your work on this awesome library

Best regards
Stéphane

**Comment by RicoSuter** [comment]
It inherits from SwaggerTagAttribute so the property should be there...

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Annotations/OpenApiTagAttribute.cs

**Comment by RicoSuter** [comment]
Or is it missing in the spec?

**Comment by stephaneworkspace** [comment]
it's missing in OpenApiTagAttribute.cs

when I click with Ctrl on [OpenApiTag("Test")] in controller

````
namespace NSwag.Annotations
{
    //
    // Résumé :
    //     Specifies the tags for an operation.
    [AttributeUsage(AttributeTargets.Class | AttributeTargets.Method, AllowMultiple = true)]
    public class OpenApiTagAttribute : SwaggerTagAttribute
    {
        //
        // Résumé :
        //     Initializes a new instance of the NSwag.Annotations.SwaggerTagAttribute class.
        public OpenApiTagAttribute(string name);
    }
}
````

no description in this interface

**Comment by RicoSuter** [comment]
But it inherits from the "old" SwaggerTagAttribute...

Use `[OpenApiTag("Entity", Description = "My entity")]`?

**Comment by stephaneworkspace** [comment]
sorry for derangement, it's works, it's my fault... i make certainly a mistake on my keyboard
