### ISSUE TITLE
get with array resturns 415

### ISSUE THREAD

**Issue by kejto** [RicoSuter/NSwag#2246]
yaml:
  /documents/search:
    get:
      operationId: searchDocs
      parameters:
        - in: query
          name: order
          schema:
            type: array
            items:
              type: string

generated code:

```
[Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("documents/search", Name = "searchDocs")]
publicSystem.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<DokumentSbirkyZakladKolekce>> Search(System.Collections.Generic.IEnumerable<string> order)
```

its never hit with debugger and postman returns 415. I am calling GET:
https://localhost:5500/rest/documents/search?order=title&order=asd

**Comment by RicoSuter** [comment]
Would

    Search([FromQuery]System.Collections.Generic.IEnumerable<string> order)

work?

**Comment by kejto** [comment]
yes adding [FromQuery] is working

**Comment by kejto** [comment]
@RicoSuter will you release a fix for this? as I cannot be amending generated code
