### ISSUE TITLE
Question: Custom JsonInheritanceConverter for Swagger to C#

### ISSUE THREAD

**Issue by altso** [RicoSuter/NSwag#2254]
Is there any way to specify a custom `JsonInheritanceConverter` when generating C# client from swagger schema?

I tried overriding `JsonInheritanceConverter.liquid` by dropping it into `Templates` folder and specifying `"templateDirectory": "Templates",` in nswag config file, but as far as I can see it's not being used.

I also considered specifying custom `JsonConverter` for the type I interested in in `JsonSettings`, but according to the [documentation](https://www.newtonsoft.com/json/help/html/SerializationGuide.htm#JsonConverter) it will have the least priority, as my type is generated with `[Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "myDiscriminator")]` attribute.

I can provide a sample repo if needed.

**Comment by altso** [comment]
Actually, custom template works. Please let me know if there is a better way to do the same.

**Comment by RicoSuter** [comment]
What do you want to customize?

**Comment by altso** [comment]
I am consuming a non standard compliant schema where discriminator is not a string, but an array of strings that contains full hierarchy. For example, If `A -> B -> C`, discriminator of instance of `C` would be `['C', 'B', 'A']`. So I basically need to use the first item of the array as a _real_ discriminator.

**Comment by RicoSuter** [comment]
Ah ok, so this is a schema which cannot be correctly described with Swagger/OpenAPI? I think your approach is fine then..

**Comment by altso** [comment]
Ok, thanks for confirming.
