### ISSUE TITLE
Support for free form / additional properties in query string.

### ISSUE THREAD

**Issue by Choc13** [RicoSuter/NSwag#2257]
Hi,

I would like to have a controller with an action such as:

```
[HttpGet("Foo/{id}")]
public async Task<Foo> GetFoo(string id, [FromQuery] Dictionary<string, IEnumerable<string>> additionalProperties)
{
}
```

So that I can invoke it with a URL such as `foo/1?x=y&x=z`. ASP.NET Core supports this and populates the `additionalProperties` as expected with multiple values for the key `x`. 

However, when we invoke the endpoint from the swagger page, say with a value like

```
{
  x: [y, z]
}
```

The URL that is generated and invoked is `foo/1?x=y,z`, but the desired URL is `foo/1?x=y&x=z` as mentioned above. Which when bound in the controller leads to the `additionalProperties` dictionary containing `{ "x", ["y,z"] }` rather than the desired `{ "x", ["y", "z"] }`.

The schema for the `additionalProperaties` in the swagger file that is generated by NSwag looks like:

```
{
  "name": "additionalProperties",
  "in": "query",
  "schema": {
    "type": "object",
    "nullable": true,
    "additionalProperties": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "x-position": 6
}
```

And the swagger input for that param looks like:

![image](https://user-images.githubusercontent.com/2675431/59917270-6ddffd80-9419-11e9-9a59-cf7f87ab9a71.png)

Both of which seem to be OK to me, but it is just the way that the value for each additional property is being serialised that seems incorrect.

Is there a way to change this behaviour so that it treats each additional property as if it had `CollectionFormat = OpenApiParameterCollectionFormat.Multi`, as it would do if we had a non-free form parameter of type `IEnumerable<string>`, or is this not supported by NSwag? We are also generating a C# client and would like the same behaviour there too.

NSwag.AspNetCore version is 13.0.1 and we have enabled OpenApi3 schemas.

**Comment by gabbsmo** [comment]
@Choc13 Shooting from the hip here but have you tried binding the controller action to `IEnumerable<KeyValuePair<string, string>>`?

**Comment by Choc13** [comment]
@gabbsmo that's a good suggestion. I honestly can't remember anymore whether I did try that at the time. I'm not working on that problem at the moment, but it should be easy enough to setup a test application and give it a try? 

That type does actually seem like a more correct representation of HTTP query params and I suppose ASP.NET Core is perhaps just doing the `.GroupBy().ToDictionary()` call on that under the hood when binding to a `Dictionary<string, IEnumerable<string>>` controller parameter to remove a bit of boilerplate from developers. (Just a guess though, I suppose we could verify by looking at their source)

**Comment by Pzixel** [comment]
AFAIK you can change separator settings, to get ASP.Net behavior you need to specify `multi` as separator.
