### ISSUE TITLE
C# Client Generated Code Substring of null

### ISSUE THREAD

**Issue by pizzapeter** [RicoSuter/NSwag#2268]
The generated C# Client Code tries to make .Substring() on a parameter which is passed as null.

The initialization of the Exception (named as ApiException) (Generated from NSwagStudio)
![Annotation 2019-06-26 153021](https://user-images.githubusercontent.com/29860980/60184312-20ec9480-9828-11e9-9a38-fa0d619a49a8.png)

Here it tries to do a SubString() on the parameter passed as null: (Generated from NSwagStudio)
![Annotation 2019-06-26 153040](https://user-images.githubusercontent.com/29860980/60184353-2fd34700-9828-11e9-8a7c-83c8b6ebdef3.png)

**Comment by RicoSuter** [comment]
Should be fixed in v13.0.2

**Comment by pizzapeter** [comment]
regenerated with Version 13.0.2
problem still exists

**Comment by RicoSuter** [comment]
Can you try to manually add the null check here?

```
protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers)
{
    if (response.Content == null)
    {
        return new ObjectResponseResult<T>(default(T), string.Empty);
    }

    ...
```

**Comment by pizzapeter** [comment]
done!

**Comment by RicoSuter** [comment]
And does it work this way without null ref exception?

**Comment by pizzapeter** [comment]
didn't fix the problem!
response.Content isn't null and ReadResponseString is false, to it tries the else ..
wouldn't it fix the problem not to pass null or check for null before doing the SubString()?

**Comment by RicoSuter** [comment]
In which case are we passing null as text?
