### ISSUE TITLE
nswag new -> nswag.json already exists.

### ISSUE THREAD

**Issue by haymansfield** [RicoSuter/NSwag#2269]
Hi,

I've added nswag studio with Chocalatey:

NSwag command line tool for .NET 4.6.1+ WinX64, toolchain v13.0.2.0 (NJsonSchema v10.0.20.0 (Newtonsoft.Json v11.0.0.0))

Running "nswag new" in any folder is giving me "nswag.json already exists."

Am I missing something?

**Comment by jaybyrrd** [comment]
This is happening for me as well.

**Comment by SaebAmini** [comment]
Having the same issue. All 13.* versions have the same problem.

**Comment by olipo186** [comment]
Same issue here, but with NPM package.

Fresh install by `npm install -g nswag` and running `nswag new` gives me the following:

```
NSwag NPM CLI
NSwag command line tool for .NET Core NetCore21, toolchain v13.0.4.0 (NJsonSchema v10.0.21.0 (Newtonsoft.Json v11.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: /Users/me/.nvm/versions/node/v10.15.0/lib/node_modules/nswag/bin/binaries/NetCore21
nswag.json already exists.
Duration: 00:00:00.0142470
```

However, there's no `nswag.json` in cwd:
```
$ cat nswag.json
cat: nswag.json: No such file or directory
```

**Comment by jeremyVignelles** [comment]
Just opened #2406 before looking into the issues.

A workaround:
```
touch nswag.json
nswag new
```

**Comment by robert-ovens** [comment]
> Just opened #2406 before looking into the issues.
> 
> A workaround:
> 
> ```
> touch nswag.json
> nswag new
> ```

Legendary. Thanks @jeremyVignelles
