### ISSUE TITLE
CSharp client generated code changed "header" parameter data type for custom error class

### ISSUE THREAD

**Issue by alovera** [RicoSuter/NSwag#2276]
In prior versions of NSwagStudio, the exception class that was used for the "swaggerToCSharpClient" option could be initialized using a "headers" parameter of the type `Dictionary<string, IEnumerable<string>>`.

We were able to utilize this NSwag setting to define our custom error class outside of the generated code to prevent having multiple error classes defined for each controller or generated code.  Here's the previous class constructor that we used for this purpose:

`public HttpClientException(string message, int statusCode, string response, Dictionary<string, IEnumerable<string>> headers, Exception innerException) { ... }`

However, after updating the NSwagStudio to the latest version (v13.0.2.0) the generated code calls the method `ReadObjectResponseAsync(...)` to instantiate the error class where it changes the "headers" parameter type to `IReadOnlyDictionary<string, IEnumerable<string>>`:

`protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers)`

This change prevents our custom exception class from being instantiated in the `ReadObjectResponseAsync(...)` method forcing us to have to override the method in a derived class or to muck with the generated code.  The change in type to be read-only is simply not needed as the argument being passed into the method is already a `Dictionary<string, IEnumerable<string>>` type.

Can you please revert this back to using the original data type (e.g. NOT read-only)?  Since we have prior code generation mixed with new, the read-only change causes us a lot of headache.

**Comment by RicoSuter** [comment]
Can't you just change your custom exception class to take an IReadOnlyDictionary so that it works with the new and old code?

**Comment by alovera** [comment]
I suppose we can do that.  Our exception class is currently in a private NuGet repository that we share between teams.  We'll have to ensure that all of the teams are working with the latest library if they attempt to use a later version of the NSwagStudio than we were originally using to generate our proxies.  These types of breaking changes are getting more common in this NuGet world.
