### ISSUE TITLE
How to set variable assemblyPath?

### ISSUE THREAD

**Issue by kvansaders** [RicoSuter/NSwag#2288]
In the nswag.json file, there is a property assemblyPath.  If I try to build locally vs from the CI server, the build configuration will be different, hence a different assembly path in .net core 2.2.

Can the csproj target in nswag.msbuild override this value in the json file and use a variable based on the configuration?

**Comment by RicoSuter** [comment]
You can use "injected" variables, see https://github.com/RicoSuter/NSwag/wiki/CommandLine#document-variables

**Comment by kvansaders** [comment]
That's exactly what I was looking for, thanks.
