### ISSUE TITLE
How to remove Top level document security

### ISSUE THREAD

**Issue by dbartumeu** [RicoSuter/NSwag#2304]
I'm adding JWT authorization to the document:

```
 document.AddSecurity("JWT", 
    Enumerable.Empty<string>(),
    new OpenApiSecurityScheme {
    Type = OpenApiSecuritySchemeType.ApiKey,
    Name = "Authorization",
    In = OpenApiSecurityApiKeyLocation.Header,
    Description = "Type into the textbox: Bearer {your JWT token}."
});

document.OperationProcessors.Add(
    new AspNetCoreOperationSecurityScopeProcessor("JWT")
        //new OperationSecurityScopeProcessor("JWT")
);
```

and for some reason in the swagger.json it appends the security to the whole document. Ex:

```
...
"security": [
    {
      "JWT": []
    }
  ]
```

is there a way to remove that section?

**Comment by RicoSuter** [comment]
I think that this "security" section is always needed if "securitySchemes" are defined, no?

**Comment by dbartumeu** [comment]
I just want to put some context:
Values Endpoints don't need authorization at all. As you can see I have a security schemes definition and those endpoints remains without security.
![s1](https://user-images.githubusercontent.com/7924382/60918367-29e65880-a261-11e9-9645-989077887402.png)

If I add the security section it affects the entire doc. As you can see in the image. 
![s2](https://user-images.githubusercontent.com/7924382/60918369-29e65880-a261-11e9-8b4a-497d60ae68eb.png)

The only way to remove the security icon is append `securtity: []` in all endpoints definition. I dont know if there is a way to specify that, because i tried with `[AllowAnonymous]` and didn't work;

**Comment by RicoSuter** [comment]
Did you add AspNetCoreOperationSecurityScopeProcessor?

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware#add-oauth2-authorization-openapi-3

**Comment by RicoSuter** [comment]
I think you can also add the appender instead of AddSecurity without scopeNames

https://github.com/RicoSuter/NSwag/blob/85ae862fd6d68173a201a79e0ad06e0be2ec5de1/src/NSwag.AspNetCore/Extensions/NSwagSwaggerGeneratorSettingsExtensions.cs#L29

**Comment by dbartumeu** [comment]
I changed the code to:

```
document.DocumentProcessors.Add(
    new SecurityDefinitionAppender("JWT", Enumerable.Empty<string>(),
        new OpenApiSecurityScheme
    {
        Type = OpenApiSecuritySchemeType.ApiKey,
        Name = "Authorization",
        In = OpenApiSecurityApiKeyLocation.Header,
        Description = "Type into the textbox: Bearer {your JWT token}."
}));
```

and still getting the same issue.

**Comment by RicoSuter** [comment]
Remove the second enumerable parameter

**Comment by dbartumeu** [comment]
you mean like this?

```
document.DocumentProcessors.Add(
    new SecurityDefinitionAppender("JWT",
    new OpenApiSecurityScheme
    {
        Type = OpenApiSecuritySchemeType.ApiKey,
        Name = "Authorization",
        In = OpenApiSecurityApiKeyLocation.Header,
        Description = "Type into the textbox: Bearer {your JWT token}."
    })
);
```

**Comment by RicoSuter** [comment]
Yep, this way “security” should not be generated (not sure if this is correct though)

**Comment by dbartumeu** [comment]
Yes you are right but now is not generating security for controllers that require authentication

**Comment by dbartumeu** [comment]
And now i got it. Here is the final code:

```
document.OperationProcessors.Add(new AspNetCoreOperationSecurityScopeProcessor("JWT"));

document.DocumentProcessors.Add(
  new SecurityDefinitionAppender("JWT",
	new OpenApiSecurityScheme
	{
	  Type = OpenApiSecuritySchemeType.ApiKey,
	  Name = "Authorization",
	  In = OpenApiSecurityApiKeyLocation.Header,
	  Description = "Type into the textbox: Bearer {your JWT token}."
	})
);
```

**Comment by RicoSuter** [comment]
And this works as expected?

**Comment by dbartumeu** [comment]
yes, but i have a warning because the overload is obsolete.

**Comment by RicoSuter** [comment]
Ok, then both overloads are valid and obsolete has to be removed, right?

**Comment by RicoSuter** [comment]
Will create a pr for review tomorrow

**Comment by dbartumeu** [comment]
yes that's right. thank you so much for your help.

**Comment by RicoSuter** [comment]
Created PR: https://github.com/RicoSuter/NSwag/pull/2305
What do you think?
