### ISSUE TITLE
OwinMiddleware - OAS 3 - Request body example missing from swagger UI

### ISSUE THREAD

**Issue by KumG** [RicoSuter/NSwag#2312]
Hello,

Using the Nswag Owin Middleware with OpenApi 3 enabled, the request body for Post operations is missing from Swagger UI.

Is there something I'm missing ?

Thank you.

![swagger1](https://user-images.githubusercontent.com/15228098/61354640-e8facf00-a872-11e9-8b0b-e8c74c46ec21.png)
![swagger2](https://user-images.githubusercontent.com/15228098/61354679-0039bc80-a873-11e9-8841-a466568ba653.png)

**Comment by RicoSuter** [comment]
Isn't it nullable and thus reference via oneOf?

**Comment by KumG** [comment]
Thanks for the answer.

I used your sample for Owin Middleware and just add this method:

`        [HttpPost]
        public IHttpActionResult CreateProduct([FromBody] Product product)
        {
            return Ok();
        }`

I don't know exactly when "oneOf" should be generated in the swagger file...

**Comment by RicoSuter** [comment]
Can you post the generated spec?

**Comment by KumG** [comment]
[swagger.txt](https://github.com/RicoSuter/NSwag/files/3400955/swagger.txt)

**Comment by RicoSuter** [comment]
I think its correct but swagger ui does not support null/oneOf in request bodies. Maybe try adding [BindRequired] and [Required] to the parameter

**Comment by KumG** [comment]
It seems that the "[Required]" attribute is ignored with Web API.

We have another project with ASP.NET Core 2.2, and the requestBody is generated as without "oneOf" whether or not the "[Required]" attribute is set (always required):

`"requestBody": {
          "x-name": "customer",
          "description": "Customer definition",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Customer"
              }
            }
          },
          "required": true,
          "x-position": 1
        }`

Do you know why it is different with Web API ?

**Comment by RicoSuter** [comment]
Web API (legacy) is based on another Swagger/OpenAPI generator inside NSwag and is no longer being maintained... the FromBody handling is different in these two generators and might differ.

**Comment by nzacca** [comment]
@KumG This setting below worked for us.

```c#
app.UseSwaggerUi3(controllers, settings =>
{
    settings.GeneratorSettings.AllowNullableBodyParameters = false;
}
```

**Comment by KumG** [comment]
Yes, it seems to work, thank you!!
