### ISSUE TITLE
A path base can only be configured using IApplicationBuilder.UsePathBase()

### ISSUE THREAD

**Issue by taobaohi** [RicoSuter/NSwag#2330]
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-nswag?view=aspnetcore-2.2&tabs=visual-studio

System.InvalidOperationException:“A path base can only be configured using IApplicationBuilder.UsePathBase().”

**Comment by RicoSuter** [comment]
Can you provide more context? When does this show up? Do you have an example code?

**Comment by taobaohi** [comment]
sorry ,my code wrong!in launchSettings.json i lost "applicationUrl"
