### ISSUE TITLE
Yaml file generate

### ISSUE THREAD

**Issue by lalaka32** [RicoSuter/NSwag#2331]
Can you help me with generating yaml file, and creating api route for it.

**Comment by lalaka32** [comment]
with open api 3 support

**Comment by RicoSuter** [comment]
I think the middleware does not yet support yanl output, only json output.. need to add the NSwag.Core.Yaml package to NSwag.AspNetCore and output yaml when the extension is .yaml

**Comment by paulps** [comment]
Can you show sample how NSwag.Core.Yaml should be used?

**Comment by RicoSuter** [comment]
NSwag.Core.Yaml contains extension methods/static methods to read/write OpenApiDocument objects to/from YAML.

https://apimundo.com/organizations/nuget-org/nuget-feeds/public/packages/NSwag.Core.Yaml/versions/latest?tab=types&namespace=NSwag&type=NSwag.OpenApiYamlDocument

**Comment by RicoSuter** [comment]
app.UseOpenApi(p => p.Path = "/swagger/{documentName}/swagger.yaml");
            app.UseSwaggerUi3(p => p.DocumentPath = "/swagger/{documentName}/swagger.yaml");
