### ISSUE TITLE
Share Custom Templates

### ISSUE THREAD

**Issue by KrzysztofKielce** [RicoSuter/NSwag#2333]
Can you add a "Custom templates made by the Community" section to this wiki page https://github.com/RicoSuter/NSwag/wiki/Templates
?
The templates might be provided e.g. as URLs to separate small github repos provided by the community users.

That might be useful and possibly motivate people to share their custom templates.

Thoughts?

**Comment by RicoSuter** [comment]
I think that is a good idea... you can update the wiki with this section.

**Comment by KrzysztofKielce** [comment]
Done.
