### ISSUE TITLE
NullReferenceException caused by response.Substring call on null object

### ISSUE THREAD

**Issue by bencollinsuk** [RicoSuter/NSwag#2335]
I get a NullReferenceException when a deserialization exception is thrown. The try catch block throws a new exception as supplies the response parameter as null which causes a null reference exception here: 

`response.Substring(0, response.Length >= 512 ? 512 : response.Length)`

**Comment by RicoSuter** [comment]
Should be fixed in latest version:
https://github.com/RicoSuter/NSwag/commit/4ceb591a372caa2efffa2d4c28aa87a38a343476

**Comment by Numpsy** [comment]
I think i'm seeing a variant of this if a 204 response occurs with no content - the generated client code contains
```
if (status_ == "204") 
{
    string responseText_ = ( response_.Content == null ) ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
    throw new ApiException("X", (int)response_.StatusCode, responseText_, headers_, null);
}
```
And then the ApiException constructor calls Substring on the null responseText_.

This is with NSwag 13.1.3.

**Comment by Numpsy** [comment]
Is https://github.com/Numpsy/NSwag/commit/477bc1b0b8d95a175325317ac1d4f505a73bc214 a reasonable thing to do for the case i mention above?

**Comment by RicoSuter** [comment]
If this fixes the problem please create a pr

**Comment by Numpsy** [comment]
It fixes the NullReferenceException I was seeing at least (think the trying to throw at all is #1259?), I'll send a PR.
