### ISSUE TITLE
Load custom IOperationNameGenerator from custom assembly

### ISSUE THREAD

**Issue by ktmathe** [RicoSuter/NSwag#2340]
Hi,
I see that there is some ongoing development with this issue, so just wanted to ask is there an approximate release date for this.
#924 #551
I could imagine this as a possible solution:
Add a new value - **OperationGenerationMode.Custom** - in **OpenApiToCSharpCommandBase.OperationGenerationMode**. 
In that case **ClientGeneratorBaseSettings.OperationNameGenerator** should be loaded from a custom assembly and the class/assembly name could be set with a new configuration e.g **OpenApiToCSharpCommandBase.OperationNameGeneratorTypeName**.

**Comment by RicoSuter** [comment]
Quite some work to do and not requested much.
For now you’d need to write your own cli with the libs

**Comment by RicoSuter** [comment]
Closed as not required anymore as assembly loading feature has been dropped, only csproj loading is supported and with that you'll implement the processor directly in the app
