### ISSUE TITLE
Json returned from API not converted using Json.Net

### ISSUE THREAD

**Issue by FrikkinLazer** [RicoSuter/NSwag#2343]
Nswag version: 
NSwag command line tool for .NET Core NetCore21, toolchain v12.3.1.0 (NJsonSchema v9.14.1.0 (Newtonsoft.Json v11.0.0.0))
Dotnet core version:
3.0.100-preview7-012821
Swashbucle nuget pacakge:
Swashbuckle.AspNetCore 5.0.0-rc2

Steps to repro:
On command line:
dotnet new webapi 

Add the swagger endpoint following these instructions: 
https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio

Run the api, and generate a class using this command line:
nswag swagger2csclient /input:https://localhost:44375/swagger/v1/swagger.json /output:WorthWatchingAPIClient.cs /namespace:WorthWatchingAPIClient /ClientBaseClass:WWAPIClient /UseHttpClientCreationMethod:true /UseHttpRequestMessageCreationMethod:false /operationGenerationMode:SingleClientFromOperationId

(change the /input:xxxx, since the port will be different for you.)

The problem is that the client that is generated tries to do this with the response:
`result_ = (System.Collections.Generic.ICollection<WeatherForecast>)System.Convert.ChangeType(responseData_, typeof(System.Collections.Generic.ICollection<WeatherForecast>));`

Where previously, it would deserialize the response using Newtonsoft.Json.JsonConvert.DeserializeObject

When consuming a swagger endpoint in an older API (that is using Swashbuckle.AspnetCore 4.0.1) it works properly. But when consuming an API that uses Swashbuckle.AspNetCore 5.0.0-rc2 I am experiencing the issue above. I have tries downgrading to 4.0.1, but that version is not compatable with core 3.0.x.

What do I need to configure in the API, so that nswag realises taht it is in fact json coming back from the API, so that it deserialized it properly?

**Comment by FrikkinLazer** [comment]
I have found the problem. I updated the npm package, and it updated from v12.0.10.0, to v12.3.1.0, which is NOT the latest version. I think this happened because I did not call npm outdated, before updating the package. I thought I had the latest version of nswag command line, but I did not.

**Comment by RicoSuter** [comment]
Latest is v13
