### ISSUE TITLE
New OpenApiIgnoreAttribute does not work

### ISSUE THREAD

**Issue by chrisagzh** [RicoSuter/NSwag#2348]
SwaggerIgnoreAttribute is marked as obsolete and due to building with Warning As Errors we are forced to use OpenApiIgnoreAttribute instead. However, the attribute is currently not working because in `WebApitoSaggerGenerator.GenerateForControllerAsync` only the old "SwaggerIngoreAttribute" is being checked:

```
            var hasIgnoreAttribute = controllerType.GetTypeInfo()
                .GetCustomAttributes()
                .Any(a => a.GetType().Name == "SwaggerIgnoreAttribute");

            if (hasIgnoreAttribute)
                return false;

```

**Comment by RicoSuter** [comment]
I dont know where you got that code, but the in the current version (master) it is fixed: 

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation.WebApi/WebApiOpenApiDocumentGenerator.cs#L149
