### ISSUE TITLE
With a V1 and V2 version of an Endpoint, how do we generate a client with the V2 version only?

### ISSUE THREAD

**Issue by jameslavery** [RicoSuter/NSwag#2367]
We've got an endpoint _GetHistoricAttendance_, which we need now to have a V2 version, with different response data.

I've created a new Controller with a different route  of "api/v2".

When I generate the client, however, this now has _GetHistoricAttendance_ with the "api/v1" route, and _GetHistoricAttendance2_, with the "api/v2" route.

How can I set things up, and/or configure NSwag, so that it generates a client with the original endpoint  of _GetHistoricAttendance_, with the "api/v2" route?

I obviously want all the other endpoints to have "api/v1" as their routes.

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware#use-api-versioning

**Comment by jameslavery** [comment]
> See https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware#use-api-versioning

Thanks - that's exactly what I needed.
