### ISSUE TITLE
C# code generation: generated required collection property does not compile.

### ISSUE THREAD

**Issue by KrzysztofKielce** [RicoSuter/NSwag#2380]
The following yaml code:

	UserData:
		type: object
		required:
		  - owners
		properties:
		  first_name:
			type: string
			example: John
		  last_name:
			type: string
			example: Doe
		  owners:
			type: array
			items:
			  $ref: '#/definitions/UserDataOwner'
			  
Generates such a buggy property (this code does not compile):
			  
        [Newtonsoft.Json.JsonProperty("owners", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.List<UserDataOwner> Owners { get; set; } = new System.Collections.ObjectModel.Collection<UserDataOwner>();
		
It should be either:

        public System.Collections.Generic.List<UserDataOwner> Owners { get; set; } = new System.Collections.Generic.List<UserDataOwner>();

or:

        public System.Collections.ObjectModel.Collection<UserDataOwner> Owners { get; set; } = new System.Collections.ObjectModel.Collection<UserDataOwner>();

**Comment by RicoSuter** [comment]
You probably only changed the ArrayType but not the ArrayInstanceType

![image](https://user-images.githubusercontent.com/2603405/63956624-16988200-ca87-11e9-9eba-21b9abef0a08.png)

**Comment by KrzysztofKielce** [comment]
Thank you so much! This was the issue reason.
