### ISSUE TITLE
OpenApiDocument Fails to Deserialize with Path Level Description and Extension Values

### ISSUE THREAD

**Issue by alex-leroux** [RicoSuter/NSwag#2389]
Calling OpenApiDocument.FromJsonAsync with a definition containing a path like this...

		"/BatchPayments":
		{
			"x-related-model": "BatchPayments",
			"description": "Bundle multiple bills or invoices into one payment transaction.",
			"get":
			{
				"operationId": "getBatchPayments",
				"parameters":
				[
					{
						"in": "header",
						"name": "If-Modified-Since",
						"schema":
						{
							"type": "string",
							"format": "date-time"
						}
					},
				],
				"responses":
				{
					"200":
					{
						"content":
						{
							"application/json":
							{
								"schema":
								{
									"$ref": "#/components/schemas/BatchPayments"
								},
							}
						}
					}
				}
			},

...fails with the error:
"Unexpected initial token 'String' when populating object. Expected JSON object or array."
because of the "x-related-model" extension value and the "description" for BatchPayments.

The definition snippet above is from the Xero API definition at:
https://raw.githubusercontent.com/XeroAPI/Xero-OpenAPI/master/accounting-json/Xero_accounting_2.0.0_swagger.json

**Comment by jondmcelroy** [comment]
This appears to be fixed now: https://github.com/RicoSuter/NSwag/issues/2438

**Comment by jeremyVignelles** [comment]
Thanks @jondmcelroy, will close it now, feel free to reopen if that's not fixed for you
