### ISSUE TITLE
Where is the TS class generation code?

### ISSUE THREAD

**Issue by rossknudsen** [RicoSuter/NSwag#2398]
This project is really great and I'd love to contribute a new feature, time/date handling with Luxon.  We're currently using Moment for date handling but would like to try Luxon instead.

But I'm having difficulty understanding how the code is generated for the class-based API models.  The `init()` method initialises date fields like this:

```
this.createTime = data["CreateTime"] ? moment(data["CreateTime"].toString()) : <any>undefined;
```

If you could advise me on this, or even a PR that introduced one of the date handling options, then I can figure out how this all works.

**Comment by RicoSuter** [comment]
The used code is quite ugly (not clean), starting point here: https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.TypeScript/DataConversionGenerator.cs#L87

**Comment by rossknudsen** [comment]
Awesome, thanks.  I had a quick look.  Doesn't look too bad, but if/when I get a chance to make changes, I'll see if I can improve 😃
