### ISSUE TITLE
NSwag.MSBuild NetCore 3.0

### ISSUE THREAD

**Issue by grahamehorner** [RicoSuter/NSwag#2407]
Please advise if NSwag.MSBuild is supports .NET Core 3.0 if so we  have issues when using .NET Core 3.0 and NSwag.MSBuild in that the NSwag build task is throwing a System.IO.FileNotFoundException when running and referencing a build folder that is incorrect.

**Comment by RicoSuter** [comment]
NSwag.MSBuild does not yet support .NET Core 3.0

**Comment by robertsundstrom** [comment]
@ricosuter What is the ETA?

**Comment by robertsundstrom** [comment]
I have looked into the .NET project NSwag service generator support:

```xml
  <ItemGroup>
    <OpenApiReference Include="OpenAPIs\swagger.json" Namespace="BlazorApp1">
      <CodeGenerator>NSwagCSharp</CodeGenerator>
      <SourceUri>http://localhost:58687/swagger/v1/swagger.json</SourceUri>
    </OpenApiReference>
  </ItemGroup>
```

Any documentation of what the options are?

My client gets the name `swaggerClient` and not the name of the controller, why?

**Comment by RicoSuter** [comment]
The only docs so far: https://github.com/RicoSuter/NSwag/wiki/ServiceProjectReference

**Comment by mhartvig** [comment]
Hi Rico,
Any chance you have time to address this? With the release of 3.0 today (https://devblogs.microsoft.com/dotnet/announcing-net-core-3-0/), it would be nice to be able to upgrade asap.

**Comment by RicoSuter** [comment]
Duplicate of https://github.com/RicoSuter/NSwag/issues/1961

**Comment by RicoSuter** [comment]
I hope to look into this this week...

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NSwag/pull/2427

**Comment by RicoSuter** [comment]
Also supports NRT: 

![image](https://user-images.githubusercontent.com/2603405/65725507-21a8f700-e0b3-11e9-9a82-6cb139a12980.png)
