### ISSUE TITLE
Microsoft.AspNetCore.Mvc.NewtonsoftJson is required on .NET Core 3.0

### ISSUE THREAD

**Issue by thoemmi** [RicoSuter/NSwag#2429]
I've added the newest release **13.1.0** of **NSwag.AspNetCore** to a new .NET Core 3.0 web app. However, it failed with following exception, because it couldn't find **Microsoft.AspNetCore.Mvc.NewtonsoftJson**.

Because Newtonsoft.Json is not required by ASP.NET Core 3.0 anymore (they've written a new JSON stack), please consider adding **Microsoft.AspNetCore.Mvc.NewtonsoftJson** as a dependency to **NSwag.AspNetCore** when .NET Core 3.0 is targeted.

**Comment by RicoSuter** [comment]
Ref https://github.com/RicoSuter/NSwag/issues/2243
