### ISSUE TITLE
Error converting value "NetCore30" to type 'NSwag.Commands.Runtime'

### ISSUE THREAD

**Issue by mhartvig** [RicoSuter/NSwag#2432]
Hi,
Trying to use the new support for .net core 3.0, but I'm getting an error when trying to generate angular code doing build.

Empty project with the following configuration
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="nswag run /variables:Configuration=$(Configuration) /runtime:NetCore30" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="13.1.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>

```
nswag.json file looks like this:
`{
  "runtime": "NetCore30",
  "defaultVariables": null,
  "documentGenerator": {.....}`

Build fails with the following error
`Newtonsoft.Json.JsonSerializationException: Error converting value "NetCore30" to type 'NSwag.Commands.Runtime'. Path 'runtime', line 2, position 24. ---> System.ArgumentException: Requested value 'NetCore30' was not found.`

**Comment by mhartvig** [comment]
For good measures I've just tried to use https://github.com/JasonGT/NorthwindTraders/  mentioned in #1961 and this doesn't work either so it might be an issue with my machine.

**Comment by RicoSuter** [comment]
You also need to update NSwag.MSBuild in your project - not only NSwagStudio

**Comment by RicoSuter** [comment]
Can you post the full stacktrace?

**Comment by RicoSuter** [comment]
The dll in the nswag.msbuild 13.1.1 package looks fine: 

![image](https://user-images.githubusercontent.com/2603405/65795937-b3743b00-e16b-11e9-852a-19dc1d3cda06.png)

Did you do a project rebuild and/or a nuget restore etc?

**Comment by mhartvig** [comment]
Updated NSwagStudio to the newest version as well, though I don't normally use this and don't have it on our build server. Now I'm getting another error:

`1>------ Build started: Project: WebApplication4, Configuration: Debug Any CPU ------
1>WebApplication4 -> C:\Users\Martin\Source\Repos\WebApplication4\WebApplication4\bin\Debug\netcoreapp3.0\WebApplication4.dll
1>NSwag command line tool for .NET Core NetCore30, toolchain v13.1.1.0 (NJsonSchema v10.0.24.0 (Newtonsoft.Json v12.0.0.0))
1>Visit http://NSwag.org for more information.
1>NSwag bin directory: C:\Program Files (x86)\Rico Suter\NSwagStudio\NetCore30
1>
1>Executing file 'nswag.json' with variables 'Configuration=Debug'...
1>Launcher directory: C:\Program Files (x86)\Rico Suter\NSwagStudio\NetCore30
1>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
1> ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER))
1>File name: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
1>   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.CreateSettingsAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String workingDirectory)
1>   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
1>   at NSwag.Commands.Generation.OpenApiGeneratorCommandBase`1.CreateSettingsAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String workingDirectory)
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentWithApiDescriptionAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 298
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.GenerateDocumentAsync(AssemblyLoader assemblyLoader, IServiceProvider serviceProvider, String currentWorkingDirectory) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 280
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.<>c__DisplayClass0_0.<<Process>b__0>d.MoveNext() in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 30
1>--- End of stack trace from previous location where exception was thrown ---
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToOpenApiGeneratorCommandEntryPoint.Process(String commandContent, String outputFile, String applicationName) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs:line 29
1>
1>
1>   --- End of inner exception stack trace ---
1>   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
1>   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
1>   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
1>   at NSwag.AspNetCore.Launcher.Program.Main(String[] args) in C:\projects\nswag\src\NSwag.AspNetCore.Launcher\Program.cs:line 170
1>System.InvalidOperationException: Swagger generation failed with non-zero exit code '1'.
1>   at NSwag.Commands.Generation.AspNetCore.AspNetCoreToSwaggerCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Generation\AspNetCore\AspNetCoreToOpenApiCommand.cs:line 221
1>   at NSwag.Commands.NSwagDocumentBase.GenerateSwaggerDocumentAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocumentBase.cs:line 279
1>   at NSwag.Commands.NSwagDocument.ExecuteAsync() in C:\projects\nswag\src\NSwag.Commands\NSwagDocument.cs:line 81
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 86
1>   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in C:\projects\nswag\src\NSwag.Commands\Commands\Document\ExecuteDocumentCommand.cs:line 39
1>   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
1>   at NConsole.CommandLineProcessor.Process(String[] args, Object input)
1>   at NSwag.Commands.NSwagCommandProcessor.Process(String[] args) in C:\projects\nswag\src\NSwag.Commands\NSwagCommandProcessor.cs:line 56
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========`

**Comment by mhartvig** [comment]
Installing NSwag.Commands made it work, but it's not something that I needed before.

**Comment by RicoSuter** [comment]
Strange, do you have an older veraion installed on the project? Eg NSwag.AspNetCore?

**Comment by mhartvig** [comment]
I'm getting different behaviors on my machine, need to verify on another machine but for now it seems that it's required to have nswag studio installed which it wasn't before.

Don't use time on this issue, I will return monday with an update.

**Comment by RicoSuter** [comment]
The above fix will be in v13.1.2

**Comment by mhartvig** [comment]
Verified on another machine, seems to be working so it must be something on my end. No need for nswag studio, just needed to change the build parameter to '$(NSwagExe_Core30) run nswag.json /variables:Configuration=$(Configuration) /runtime:NetCore30'

**Comment by pdlk** [comment]
> Verified on another machine, seems to be working so it must be something on my end. No need for nswag studio, just needed to change the build parameter to '$(NSwagExe_Core30) run nswag.json /variables:Configuration=$(Configuration) /runtime:NetCore30'

@mhartvig  Have you found what the issue was on the machine? Experience the same problem even after remove and install only new version packages. Without NSwag.Command there is 
`System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER))
File name: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=3.0.0.0.....`
exception.

**Comment by mhartvig** [comment]
> > Verified on another machine, seems to be working so it must be something on my end. No need for nswag studio, just needed to change the build parameter to '$(NSwagExe_Core30) run nswag.json /variables:Configuration=$(Configuration) /runtime:NetCore30'
> 
> @mhartvig Have you found what the issue was on the machine? Experience the same problem even after remove and install only new version packages. Without NSwag.Command there is
> `System.IO.FileLoadException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Invalid pointer (0x80004003 (E_POINTER)) File name: 'Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=3.0.0.0.....`
> exception.

No I didn't as the issue wasn't on my main machine. Have you looked at https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#jsonnet-support ?
