### ISSUE TITLE
Generated client missing namespace

### ISSUE THREAD

**Issue by skironDotNet** [RicoSuter/NSwag#2436]
Object ProblemDetails has no namespace included. 

![nswag](https://user-images.githubusercontent.com/2981715/65909840-11349d00-e38f-11e9-9650-9f196466bfa1.png)

**Comment by RicoSuter** [comment]
I think dto schemas are not generated with namespace because they are in the same namespace. There was no change regarding this so you probably either dont generate dto classes or you excluded this one from being generated

**Comment by RicoSuter** [comment]
And feel free to create a pr with additional tests

**Comment by skironDotNet** [comment]
Well to clarify, and I'm sorry I didn't initially. [ProblemDetails] comes from Microsoft.AspNetCore.Mvc
Also previous version of NSwag didn't use that object or otherwise was generating different client because nothing has changes in our implementation, I just installed NSwag v13.1.2 today and noticed that client doesn't build (missing namespace) so definitely it's a bug on the new NSwag version.

Previous version I used was 13.0.6

Thanks

**Comment by skironDotNet** [comment]
One more I just noticed reviewing code changes, none of out endpoints returned 404 until today, so I guess things did change in our implementation, but as far as NSwag generated client, **Microsoft.AspNetCore.Mvc.ProblemDetails** class appeared for the first time only for 404, so I don't know if previous v13.0.6 was good or not, maybe was also buggy and we just never had a chance to trigger that case.

**Comment by skironDotNet** [comment]
It turned out that **ProblemDetails** is generated reference by the Swagger, so it's not up to NSwag to know the namespace I guess. So not an NSwag bug, rather Swagger, or neither, myabe it's just the way it is and nothing can be done about it... 

Here is the part of **swagger.json**
![image](https://user-images.githubusercontent.com/2981715/65980739-5d3e1b00-e43d-11e9-929f-2af5e19a27a0.png)

**Comment by RicoSuter** [comment]
If you generate the spec with nswag then the details schema is also part of the swagger spec
