### ISSUE TITLE
Enhancement Request: Generated Client class should expose Http Response Code

### ISSUE THREAD

**Issue by rpatrick00** [RicoSuter/NSwag#2466]
In using the generated client code in our UI BFF, we find ourselves needing to know the Http Response Code returned by the service call (e.g., was it a 400, a 500, or a 503).  I cannot find any easy way to extend the code to expose this information.

**Comment by RicoSuter** [comment]
Have you tried the wrap responses setting?

**Comment by rpatrick00** [comment]
No, is there some example or doc that describes how to go about doing this?

**Comment by rpatrick00** [comment]
Sorry, that resolves my problem.  Thanks!
