### ISSUE TITLE
Generating API clients during build

### ISSUE THREAD

**Issue by Pzixel** [RicoSuter/NSwag#2471]
I'm using your library for a long time and I'm very happy about it. However, my process is somewhat dissatisfying.

Currently when I make changes to API, i run it, go to the SwaggerUI, then download fresh `swagger.json`, then I replace my old one and finally compile my `<Exec Command="$(NSwagExe_Core21) run nswag.nswag" />` project to regenerate clients.

It's all tedious and error-prone. I'd like to just press `build` and have all stuff regenerated for me. I played with roslyn codgen for some time and I've got just it (for different goals although).

I wonder if it's possible with `nswag`. If not, maybe I could be in help since I have some experience on the matter (see Solidity.Roslyn and RemoteClient.Roslyn repos) so I would be glad to help.

But overall I hope there is some magic I could write in `csproj`s to make it work. I wish instead of formentioned flow I had

1. change `MyCompany.Foo.Api`
2. build `MyCompany.Foo.Api.Client`
3. publish new nuget package

So i'd like to eliminate "running api & downloading swagger" steps from the process. Is it possible?

**Comment by RicoSuter** [comment]
You can fonfigure the nswag.json so that it generates the swagger.json on build and then as a second step regenerate the clients

**Comment by kewur** [comment]
you can also use the NSwag.MSBuild package and add it as a target that runs before "PrepareForBuild".

**Comment by Pzixel** [comment]
Could you be in more details? I think I read all the docs but I can't find examples.
