### ISSUE TITLE
How to set PropertyNameHandling in NSwagStudio?

### ISSUE THREAD

**Issue by blackkamil** [RicoSuter/NSwag#2483]
I have NSwagStudio v13.1.2 and I'm using ASP.NET Core via API Explorer to generate code to CSharpClient and after generated I have diffrent name of tables with lowercase.

I've read other post and I think I must change PropertyNameHandling on CamelCase, but in this version NSwagStudio there isn't this such option on the tab ASP.NET Core via API Explorer.

Is there any way to generated code without change to lowercase?

**Comment by RicoSuter** [comment]
ASP.NET Core via API Explorer => You don't set it in the NSwag UI/config, you set it in the AddOpenApiDocument(...) call...
