### ISSUE TITLE
[Typescript]  Generate generic interface 

### ISSUE THREAD

**Issue by paddyfink** [RicoSuter/NSwag#2485]
Hello,

I have controller with this method ` public Task<Response<Client>> GetClient(int id)`.

nswag generate these DTO in the typescript client : 
```
export interface Response {
    failed: boolean;
    errors?: string[] | null;
}

export interface ResponseOfClient extends Response {
    result?: Client| null;
}
```

Is possible to configure nswag to generate a generic interface like this instead?:
```
export interface Response<T> {
    failed: boolean;
    errors?: string[] | null;
    result?: T| null;
}

```

**Comment by RicoSuter** [comment]
This is currently not possible because it cannot be described with Swagger/Open API/JSON Schema. 
See https://github.com/RicoSuter/NJsonSchema/issues/23

**Comment by hexxone** [comment]
For anyone still having this problem, I found a way to work around this, albeit it requires manual tweaking for each Case.

1. Create a new `index.d.ts` where you manually declare the C# generics you need

2. Manually Add all wrongly generated Generics to `ResponseOfFoo,ResponseOfBar,ResponseOfFooBar` to `openApiToTypeScriptClient.excludedTypeNames` in your `.nswag`-file. I know this can be tedious depending on your project size but in my case this part will probably not change a lot in the future... And there may be a way to grab these automatically if you really need to.

3.  Tell NSwag to use your custom Generics from Step 1 by adding the relative path of the file to `openApiToTypeScriptClient.extensionCode` in your `.nswag`-file

4. after NSwag Client generation, call [MakeGenericAgain](https://www.nuget.org/packages/MakeGenericAgain/). I simply do this in my `.csproj` like so: 
```
  <PropertyGroup>
    <RunPostBuildEvent>OnBuildSuccess</RunPostBuildEvent>
  </PropertyGroup>

  <Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(NO_RECURSE)' != 'true' ">
    <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="NO_RECURSE=true" Command="$(NSwagExe_Net60) run ./nswag.nswag /variables:Configuration=$(Configuration)" />
  </Target>
  
  <Target Name="MakeItGenericAgain" AfterTargets="NSwag" Condition=" '$(NO_RECURSE)' != 'true' "> 
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool run makeGenericAgain -f &quot;./Client/csharp/Client.cs&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool run makeGenericAgain -f &quot;./Client/controller/Client.cs&quot;" />
    <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool run makeGenericAgain -f &quot;./Client/ts/index.ts&quot;" />
  </Target> 
```

And if you have noticed, you can basically do the same thing for C#.
Hope this helps - Cheers :)

**Comment by awdorrin** [comment]
how can I convert the variables in an array of the following class:
export class SelectOptionOfString implements ISelectOptionOfString {
    label?: string;
    value?: string | undefined;
}
to an array of the following class:
export interface SelectOption<T> {
  label: string;
  value: T;
}
in typescript?
