### ISSUE TITLE
Required string query parameters are displayed as Nullable

### ISSUE THREAD

**Issue by VictorAteMetric** [RicoSuter/NSwag#2494]
I am using latest version of Nswag (V13.xx) along with OpenApiDocument.

The  string query parameters are displayed as Nullable on Swagger document when using both [Required] [FromQuery] attributes or only the [Required]  attribute. Below is the code sample: 

` public ActionResult<List<Dictionary<string, string>>> Get([Required] [FromQuery] string format)
   {
....
}`

Is there another way to make Nswag to no display the string query parameter as Nullable?

Thanks

**Comment by daniel-white** [comment]
Same for reference type route parameters

**Comment by RicoSuter** [comment]
Use [BindRequired] and not [Required]

**Comment by RicoSuter** [comment]
Where should we document this?

**Comment by VictorAteMetric** [comment]
Thanks RicoSuter  for your help.

I think a good place to document this will be https://github.com/RicoSuter/NSwag/wiki/WebApiOpenApiDocumentGenerator

**Comment by RicoSuter** [comment]
The web api gen is deprecated and replaced by 
https://github.com/RicoSuter/NSwag/wiki/AspNetCoreOpenApiDocumentGenerator

**Comment by VictorAteMetric** [comment]
RicoSuter ,
Ok. Thanks. I think the link you provided is a good place to document this.

Thanks

**Comment by RicoSuter** [comment]
Updated wiki - please also improve the wiki if you have time and it makes sense, etc.
