### ISSUE TITLE
OAuth 2 flow with empty scopes produces invalid specification

### ISSUE THREAD

**Issue by cmann-andagon** [RicoSuter/NSwag#2497]
According to the OpenApi specification, it is possible to specify an OAuth 2 security scheme without specifying any scopes. In this case, the specification should contain `scopes: {}`. See https://swagger.io/docs/specification/authentication/oauth2/.

I have used the follow configuration for the security scheme but the scopes object is removed:
```
settings.GeneratorSettings.DocumentProcessors.Add(
    new SecurityDefinitionAppender("oauth2", new OpenApiSecurityScheme
    {
        Description = "My oauth flow",
        Type = OpenApiSecuritySchemeType.OAuth2,
        Flow = OpenApiOAuth2Flow.Password,
        TokenUrl = "api/token",
        Scopes = new Dictionary<string, string>(),
    }));
```

The resulting section in the swagger.json looks like this:
```
"securitySchemes": {
  "oauth2": {
    "type": "oauth2",
    "description": My oauth flow",
    "flows": {
      "password": {
        "tokenUrl": "api/token"
      }
    }
  }
}
```

**Comment by RicoSuter** [comment]
Use this ctor: 
https://github.com/RicoSuter/NSwag/blob/adcab5d05b26e5b2d8025afdb73c9b836c606889/src/NSwag.Generation/Processors/Security/SecurityDefinitionAppender.cs#L36

Or better this new method: 
https://github.com/RicoSuter/NSwag/blob/adcab5d05b26e5b2d8025afdb73c9b836c606889/src/NSwag.AspNetCore/Extensions/NSwagSwaggerGeneratorSettingsExtensions.cs#L38

**Comment by cmann-andagon** [comment]
I have tried the constructor of `SecurityDefintionAppender` without effect. I cannot use the extension method as I am still working with the old asp.net WebApi2.

According to the OpenApi 3 specification, the scopes property is not nullable:

https://github.com/OAI/OpenAPI-Specification/blob/603c3a560df134daaee86bf8dba2eafd9863d00e/schemas/v3.0/schema.json#L1562-L1567

I would expect that an empty dictionary is therefore preserved when generating the JSON. The issue might be located in the default value handling here:

https://github.com/RicoSuter/NSwag/blob/49c5fc5184ab21347e4297fc49b98d704cc666cd/src/NSwag.Core/OpenApiSecurityScheme.cs#L161-L162

I only noticed this because I used a linter (speccy) to validate the generated JSON and it listed this as a violation of the OpenApi 3 specification.

**Comment by RicoSuter** [comment]
Did you try with an empty string list?

**Comment by cmann-andagon** [comment]
Sorry for the late response. Yes, I tried with an empty string list:

```
settings.GeneratorSettings.DocumentProcessors.Add(
    new SecurityDefinitionAppender("oauth2", new List<string>(), new OpenApiSecurityScheme
    {
        Description = "My REST API",
        Type = OpenApiSecuritySchemeType.OAuth2,
        Flow = OpenApiOAuth2Flow.Password,
        TokenUrl = "api/token",
        Scopes = new Dictionary<string, string>(),
    }));
```

which gives me:

```
"components": {
  ...
  "securitySchemes": {
    "oauth2": {
      "type": "oauth2",
      "description": "The aqua REST API supports authentication using OAuth2. Only the grant type password is supported.",
      "flows": {
        "password": {
          "tokenUrl": "api/token"
        }
      }
    }
  }
},
"security": [
  {
    "oauth2": []
  }
],
```

I got an additional security section inside my swagger.json but the scopes inside the OAuth flow inside the securitySchemes are still removed. The expected swagger.json would be:

**Comment by RicoSuter** [comment]
Not sure if this is supported, its probably best to implement a custom operation processor, add it to the document and transform each operation as needed

**Comment by CNBoland** [comment]
I'm running into this, too. I'm working with my API in Postman. Postman validates the OpenAPI definition and is complaining about the missing `scopes` property.

I setup a sample [here](https://dotnetfiddle.net/vFGDK5) to check serialization. With default serialization setting, the `NSwag.OpenApiOAuthFlow.Scopes` property renders correctly as an empty object.

Could the problem be a serializer setting or logic decision that is preventing the empty Scopes dictionary from being serialized?

**Comment by RicoSuter** [comment]
> Could the problem be a serializer setting or logic decision that is preventing the empty Scopes dictionary from being serialized?

I think there could be a "converter" which hides empty collection which might affect this one...
