### ISSUE TITLE
nswag not generating proxy service in asp.net zero

### ISSUE THREAD

**Issue by claudioallphi** [RicoSuter/NSwag#2498]
I'm facing a problem wher i'm trying to create a proxyservice in asp.net zero. I'm running the refresh.bat file which starts nswag and in order should create a proxyservice.

The bat-file gets executed without any errors, but still won't generate the necessary proxyservice.
I don't understand why it wont generate anything and that there's no way for me to see whats happening.

**Comment by claudioallphi** [comment]
I solved the issue, forgot to put class public

**Comment by rahulsoni19** [comment]
I am facing same issue..please let me know what you did
