### ISSUE TITLE
How to pass code generation options in VS "Add new OpenAPI service reference" dialog

### ISSUE THREAD

**Issue by epignosisx** [RicoSuter/NSwag#2500]
I couldn't find any example of specifying code generation options in this modal:

![image](https://user-images.githubusercontent.com/697377/68071747-ef468580-fd53-11e9-8a4d-02f8b63c4a98.png)

Since this is using NSwag underneath, I was wondering if you know how MS implemented passing options. For example I tried a few without success:

```
GenerateClientInterfaces=true
```
```
/GenerateClientInterfaces=true
```
```
GenerateClientInterfaces:true
```
```
/GenerateClientInterfaces:true
```

**Comment by RicoSuter** [comment]
Please document this here: 
https://github.com/RicoSuter/NSwag/wiki/ServiceProjectReference

**Comment by dougbu** [comment]
The options supported in that field are passed directly on the `dotnet dotnet-nswag.dll openapi2csclient` or `dotnet dotnet-nswag.dll swagger2tsclient` command line. Anything those commands support should be fine.

I'm not sure whether the field remains in VS but editing the .csproj will always work e.g.
``` msbuild
<OpenApiReference Include="../nswagApiExplorerString.json" Options="/GenerateDtoTypes:false" />
```
or
``` msbuild
<OpenApiReference Include="../nswagApiExplorerString.json">
    <Options>/GenerateDtoTypes:false</Options>
</OpenApiReference>
```

**Comment by epignosisx** [comment]
Thanks for the quick response! It worked.

**Comment by RicoSuter** [comment]
Can you update the wiki if it was not clear enough?

**Comment by epignosisx** [comment]
I couldn't find an existing page touching this topic to extend. Is there one or should I create a new one?

**Comment by RicoSuter** [comment]
Its this one but we need to rename it i think 
https://github.com/RicoSuter/NSwag/wiki/ServiceProjectReference
