### ISSUE TITLE
swag studio throwing error on generate outputs

### ISSUE THREAD

**Issue by EllinaExt** [RicoSuter/NSwag#2506]
I am using NSwag Studio (v13.1.3.0) for generating cSharp client output for the webapi developed using asp.net core 2.2.

On Generate outputs, I am getting below error

![image](https://user-images.githubusercontent.com/11975581/68215793-d7962800-0005-11ea-8c68-ec754edeadf0.png)

Also, I noticed NJson schema version 10.0.27.0(Newtonsoft.Json v9.0.0.0) however in the web api I am using 12.0.2 version of Newtonsoft.Json. Is this the issue ? any idea? 
Any Idea?

**Comment by RicoSuter** [comment]
Looks like your spec is wrong, can you post the swagger spec you are using?

**Comment by EllinaExt** [comment]
here is Json, I am using

{
  "swagger": "2.0",
  "info": {
    "title": "Tests",
    "description": "No Description provided",
    "termsOfService": "No TermsOfService provided"
  },
  "paths": {
    "/api/Tests/{TestId}": {
      "get": {
        "tags": [
          "Tests"
        ],
        "operationId": "GetTest",
        "consumes": [],
        "produces": [
          "application/vnd.Test+json"
        ],
        "parameters": [
          {
            "name": "TestId",
            "in": "path",
            "required": true,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "Fields",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Sort",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Page",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "PageSize",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "Test-Authorization",
            "in": "header",
            "description": "Authentication token",
            "required": false,
            "type": "string"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "OAuth2 token",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/Tests": {
      "get": {
        "tags": [
          "Test"
        ],
        "operationId": "GetTests",
        "consumes": [],
        "produces": [
          "application/vnd.test+json"
        ],
        "parameters": [
          {
            "name": "TestIds",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Number",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Name",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Fields",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Sort",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Page",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "PageSize",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Authentication token",
            "required": false,
            "type": "string"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "OAuth2 token",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    },
    "/api/BulkTests": {
      "post": {
        "tags": [
          "test"
        ],
        "operationId": "Bulktests",
        "consumes": [
          "application/vnd.bulktestrequest+json"
        ],
        "produces": [
          "application/vnd.bulktest+json"
        ],
        "parameters": [
          {
            "name": "Fields",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Sort",
            "in": "query",
            "required": false,
            "type": "string"
          },
          {
            "name": "Page",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "PageSize",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "filterTestDto",
            "in": "body",
            "required": false,
            "schema": {
              "$ref": "#/definitions/FilterTestDto"
            }
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "Authentication token",
            "required": false,
            "type": "string"
          },
          {
            "name": "Authorization",
            "in": "header",
            "description": "OAuth2 token",
            "required": false,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "401": {
            "description": "Unauthorized"
          },
          "400": {
            "description": "Bad Request"
          },
          "404": {
            "description": "Not Found"
          }
        }
      }
    }
  },
  "definitions": {
    "FilterTestDto": {
      "type": "object",
      "properties": {
        "testIds": {
          "type": "string"
        },
        "number": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    }
  }
}

**Comment by RicoSuter** [comment]
Can you also post the full excpetion message + stacktrace from this window?

**Comment by EllinaExt** [comment]
I figured it out. Swag is expecting a version in Info section. Thanks @RicoSuter for your time and effort.
