### ISSUE TITLE
[OpenApi 3] generated swagger.json doesn't respect InputFormatter

### ISSUE THREAD

**Issue by jeremyVignelles** [RicoSuter/NSwag#2519]
# What I want to achieve:
Read a POST body into a raw string in my API method. For that, I'm using an InputFormatter that can transform text/plain request into a string parameter.

# Observed results:

The API works fine, but the swagger.json generates a content-type of application/json, which makes swagger-ui send the request with this Content-Type header (which cannot be parsed).

When I set my SchemaType to `Swagger2`, the Swagger UI can handle the API correctly.

# Expected result:
Swagger UI should be able to read raw strings from the input, and the C# client should be able to pass a raw string as the POST request body.

# Sample code : 
https://github.com/jeremyVignelles/TestNSwagNetCoreApp/tree/feature/openapi-raw-inputformatter

**Comment by RicoSuter** [comment]
I think you need this:
https://github.com/RicoSuter/NSwag/pull/2353

You can copy it into your proj and use it

I hope to merge/finish the pr soon

**Comment by jeremyVignelles** [comment]
Thanks, I updated my sample code with your suggestion, but with the attribute, the swagger.json contains the mime type I'm expecting, but still contains `application/json` first.

![image](https://user-images.githubusercontent.com/3399355/68842703-2196a200-06c7-11ea-9eb4-e3fb285b1ea9.png)

In my real-world application, I also put a `[Consumes]` attribute. Wouldn't it be possible to use only this attribute, instead of adding your `OpenApiBodyParameterProcessor`?

**Comment by acds** [comment]
@RicoSuter I'm on package version 13.1.3, is this expected anytime soon....

I assume this is needed to also get the swagger UI to work properly for`plain.text` input.

**Comment by RicoSuter** [comment]
Its in 13.1.6

https://github.com/RicoSuter/NSwag/commit/7eca48175cf6df3564059df3c91aa61a4a8b25af

**Comment by acds** [comment]
@RicoSuter - Thanks! 

_As an aside there seem to be some issues with `Microsoft.AspNetCore.Mvc.Versioning.Versioning 4.1.0` a switchback to `4.0.0` resolved the issue - but tend to upgrade across the board when I can - albeit staying 3.0 compatible packages just now so avoiding 3.1 dependencies) 
Error:_
```
System.TypeLoadException: Method 'ApplyAsync' in type 'Microsoft.AspNetCore.Mvc.Routing.ApiVersionMatcherPolicy' from assembly 'Microsoft.AspNetCore.Mvc.Versioning, Version=4.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.
```

Whist using the `[OpenApiBodyParameter("text/plain")]` works...it would be more preferable (and ignorance on my part of the implications) if NSwag were somehow able to leverage the `Microsoft.AspNetCore.Mvc` version of the `[Consumes("text/plain")]` for compatibly with other libraries - it at least then eases the migration?
