### ISSUE TITLE
Why AddSwaggerDocument is not added as part of Nswag aspnetcore2openapi  tool

### ISSUE THREAD

**Issue by anishmarokeyGitHub** [RicoSuter/NSwag#2529]
I have gone through the command "aspnetcore2openapi " to understand the code. As per my understanding of the code, we need to add AddSwaggerDocument  in individual API and install nswag in all API to produces json. But my suggestion would be if you able to **add below code in OpenApiGeneratorCommandBase,** who ever generate json as part of command they can u generate json. Host and DocumentName should pass as command argument.

Is there any better approach is there without installing package in all API and generate json?

https://github.com/RicoSuter/NSwag/blob/93f0970c5b631b9646cf7ce8053ec28ce8ff13e7/src/NSwag.Commands/Commands/Generation/AspNetCore/AspNetCoreToOpenApiGeneratorCommandEntryPoint.cs#L67-L69

```csharp
var webHost = ((IWebHostBuilder)method.Invoke(null, method.GetParameters().Length > 0 ? new object[] { new string[0] } : new object[0]));

webHost.ConfigureServices(o => o.AddSwaggerDocument(doc =>
{
    doc.DocumentName = "v1";
    doc.PostProcess = d => d.Host = "http://localhost/abc";
}));
return webHost.Build();
```

**Comment by anishmarokeyGitHub** [comment]
Any Update ?

**Comment by RicoSuter** [comment]
You should set all options in AddOpenApiDocument(...) which is then picked up by the CLI generator.
