### ISSUE TITLE
Neither OpenApiIgnoreAttribute nor SwaggerIgnoreAttribute hide class properties

### ISSUE THREAD

**Issue by charliefoxtwo** [RicoSuter/NSwag#2532]
In a clean implementation in ASP Net Core 2.2, I am unable to hide specific model properties from Swagger. I have tried various implementations of `[OpenApiIgnore]` and `[SwaggerIgnore]` on class properties, and neither seem to work for me. Am I missing a step here?

Class and output below.
```
public class Foo
{
    public int Bar { get; set; }

    [OpenApiIgnore]
    [SwaggerIgnore]
    public int Biz { get; set; }

    [OpenApiIgnore]
    public int Baz { get; set; }

    [SwaggerIgnore]
    public int Buz { get; set; }

    [OpenApiIgnore]
    public int Bez { [OpenApiIgnore]get; [OpenApiIgnore]set; }

    [SwaggerIgnore]
    public int Byz { [SwaggerIgnore]get; [SwaggerIgnore]set; }
}
```

![image](https://user-images.githubusercontent.com/30303272/69103452-4ddd5600-0a1a-11ea-8008-ecf2101e4ee6.png)

**Comment by RicoSuter** [comment]
Use [JsonIgnore] to hide properties

**Comment by charliefoxtwo** [comment]
But I _do_ need to serialize the property - I just don't want to deserialize that property from a JSON body. Unless I'm mistaken, `[JsonIgnore]` also disables serialization of the property, which isn't what I want for my use case.

Is simply hiding a property from Swagger not what OpenApiIgnoreAttribute is for?

**Comment by RicoSuter** [comment]
OpenApiIgnoreAttribute Is used to hide operations or controllers but i’d have expected that it also works for properties.. need to check

**Comment by RicoSuter** [comment]
I think you’d need this PR
https://github.com/RicoSuter/NJsonSchema/pull/1040#issuecomment-557099101

**Comment by charliefoxtwo** [comment]
Yup, that's it! Fixed in the latest version. Thanks!
