### ISSUE TITLE
Powershell generator for NSwag?

### ISSUE THREAD

**Issue by amithegde** [RicoSuter/NSwag#2534]
I found myself needing a way to generate PowerShell client for Swagger Spec so wanted to start a conversation here to explore the possibilities.

**Comment by RicoSuter** [comment]
Aren't there already PowerShell generators or are they not "good" enough?

**Comment by amithegde** [comment]
Ended up using AutoRest. I was evaluating which generator to use. Noticed NSwag produced most concise TypeScript client and was wondering if we can use NSwag for all client generation purposes.
