### ISSUE TITLE
Iconsistent behaviour of C# codegen in AspNetCore and WebApi. 

### ISSUE THREAD

**Issue by guffy1234** [RicoSuter/NSwag#2550]
Hi 

There are two inconsistencies between NSwag.Generation.AspNetCore and NSwag.Generation.WebApi

First issues is already reported here. NSwag.Generation.WebApi required explicit [FromBody] when NSwag.Generation.AspNetCore properly (imho) assumes that object type of POST/PUT operations taken from body by default.

Similar problem described here: https://github.com/RicoSuter/NSwag/issues/1464
"Same problem, used [FromBody] to fix de issue.

_Originally posted by @smariussorin in https://github.com/RicoSuter/NSwag/issues/1464#issuecomment-418074344_"

Second issue is that NSwag.Generation.WebApi doesn't produce 
 "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
for 4xx result types if you don't explicitly declare it with the Type parameter of the attribute.
[ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status404NotFound)]
Also ProducesErrorResponseTypeAttribute doesn't help here.

For same case NSwag.Generation.AspNetCore properly generates reference to ProblemDetails

**Comment by RicoSuter** [comment]
NSwag.Generation.WebApi and NSwag.Generation.AspNetCore are completely different implementations... NSwag.Generation.WebApi is deprecated.
