### ISSUE TITLE
CS Client default version for URL based versioning

### ISSUE THREAD

**Issue by Shazib** [RicoSuter/NSwag#2553]
Hi,

Apologies if this issue has already been covered, i could not find an answer

My API uses URL Versions e.g /api/v1/User/{id}

When generating the CS client, every function takes version as a parameter

UserAsync( int id, string version, CancellationToken cancellationToken )

Is there an option to have this version be a member variable that we can define it once per client rather than providing it to every call?

Thanks

**Comment by RicoSuter** [comment]
I generally use a spec where the versions are inlined into the paths and not exposed as parameter. Eg you’d have a spec for v1, v2 etc. you can enable this in the versioned api explorer settings. Is this an option?

**Comment by Shazib** [comment]
I ended up using this approach, thanks.

Closing the issue but perhaps the option may be useful for other scenarios where every API call has the same parameter (e.g some kind of token)
