### ISSUE TITLE
How to extend Swagger UI to support basic authorization?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [RicoSuter/NSwag#2554]
Hi there,

sorry for the basic question but i'm totally lost. I'm trying to use Swagger UI with a Web API that uses basic authorization. I know that i have to add a HTTP header for basic authorization but how do i do that in NSwag? I'm currently trying to copy & paste & adjust various code samples from the internet for my `Startup.cs` but all these examples are based on OAuth or JWT. Anyone can help?

My current findings:

Basic authorization in repo NSwag.AzureFunctionsV2 (does not work obviously as classes are missing)
https://github.com/Jusas/NSwag.AzureFunctionsV2#advanced-usage

Some example configurations but those are not targeting basic authentification
https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware#enable-api-key-authentication

So lonG

**Comment by RicoSuter** [comment]
Did you try using this enum value:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/OpenApiSecuritySchemeType.cs#L21
?

**Comment by ViRuSTriNiTy** [comment]
Not relevant anymore for me, using OIDC with implicit flow now
