### ISSUE TITLE
NSwag Studio: Feature Request for handling of API version Header Param when generating C# clients

### ISSUE THREAD

**Issue by Kevweir** [RicoSuter/NSwag#2555]
When NSwag Studio encounters a header parameter it currently adds that parameter to every method that has it defined.  In my case I'm using a header parameter to define the API version and was hoping to avoid passing it on EVERY method call.  The scenario I'm describing is of course quite common with versioned API's.
Would it be possible for NSwag Studio to provide an option of generating class level public properties for initializing header parameters instead of method parameters?.  Similar to BaseUrl, the default would be used but could be overridden by the calling program.   This would allow for much cleaner API calls.   

Thanks for your consideration.

**Comment by Kevweir** [comment]
Or another possible idea is to allow the headers parameters to be optional parameters and also adding a new public method to the generated client to accept a dictionary of key value pairs that could be used to add new header values to the request....

**Comment by RicoSuter** [comment]
I think there is a setting to ignore a parameter: Ignore the version parameter and then set it automatically on each request with one of the extension points. Would this work?

**Comment by Kevweir** [comment]
Thanks for response.  Hopefully someone else can benefit if they see this.

I ended up doing the following to accomplish what I wanted:
1) I created both BASE and OPTIONS classes and the C# generated client now inherits from the BASE class.  The class names were entered into NSwag Studio.
2) I used the "ignore parameters" option in NSwag Studio to prevent my API version header parameter from being passed to every method.
3) I instructed NSwag Studio to not generate the BaseUrl property but left the "Use the base URL for the request" turned on
3) I checked the options CreateHttpClientAsync and CreateHttpRequestMessageAsync respectively to get more control over both the HttpClient and RequestHeaders in the BASE class.   Those two methods were added to the BASE class.
4) Two additional NSwag studio options were also turned OFF:
  - Inject HttpClient via constructor
 -  Dispose the HttpClient
5) I also added a Dispose method to the BASE class so calling programs can use this method when they're done working with the client.  The Dispose method simply makes a call to HttpClient.Dispose().  

The BASE class now has the following responsibilities:
- The constructor accepts the OPTIONS class mentioned above which contains properties for things like the BaseUrl, API version, identity server token endpoint details and so on.  The BASE class constructor also NEW's up a HttpClient to be used for the lifetime of the client.
- The CreateHttpClientAsync method has the responsibility of retrieving a Bearer token from the identity server endpoint.  This method also adds that Bearer token to the HttpClient.   If the calling program makes multiple calls to the client this method checks to see if the token was previously set.  If true it just exits immediately.
- The CreateHttpRequestMessageAsync only has one responsibility and that's to create the HttpRequestMessage and add a header for the API version header parameter mentioned earlier.  In my case X-Version 2.0.   

Taking the steps outlined above has led to the following benefits:
1) I can regenerate the C# client anytime there is a change to the API and models and I don't have to touch or modify the generated Client in anyway.  
2) The NSwag generated method calls no longer include the API version header parameter on every single call.  The API version is now added to the Request Header where I think it belongs.  This was my original motivation for posting the feature request.
3) Programs that use the client are now dramatically simplified due to the clean implementation of the client.  Example below:

// Import the namespace of generated C# client
using ToDo.API.Client;

// Set options for our client
Options clientOptions = new Options
{
	DiscoveryEndpoint = "https://localhost:44328",
	Clientid = "client",
	ClientSecret = "secret",
	Scope = "todo:write todo:read todo:admin",
	ApiUrl = "https://localhost:44397",
	ApVersion = "2.0"
};

// Create and initialize the client
var client = new Client(clientOptions);

// Retrieve a list of to do tasks
var tasks = await client.TasksGetAllAsync();

foreach (var task in tasks)
    {
      Console.WriteLine($"Task Description: {task.Description}");
    }

// All done
client.Dispose();

**Comment by Kevweir** [comment]
BTW, I'm using Swagger.AspNetCore, middleware and SwaggerUI to generate and consume the OpenAPI spec document.  I then import that doc into NSwag studio to do the last mile effort of generating the Clients.
Perhaps I should have used your whole toolchain as I'm sure it would have made things easier.  I had to go through a lot of clawing and scratching with swagger which was both disappointing and unproductive.  In hindsight I suppose I had unrealistic expectations and was under the impression more could be inferred from the design of the API and the XML commenting.  I suppose this highlights the problem as many vendors (I.e. Microsoft) treat good documentation as an afterthought which of course complicates the life of toolchain creators like yourself.

**Comment by AdamDiament** [comment]
For future googlers/ai-bot scrapers: The value in "IgnoreParameters" should be the parameter name you define in your definition file, not the generated C# name. For example - the header name X-Custom-Header rather than x_Custom_Header that NSwag studio generates. Might seem obvious to most, but wasn't to me!
