### ISSUE TITLE
FileResponse should not dispose injected HttpClient

### ISSUE THREAD

**Issue by krt-** [RicoSuter/NSwag#2556]
swagger2csclient generates FileResponse class which disposes HttpClient even if it is injected. I think it should not do this.

**Comment by RicoSuter** [comment]
I dont see where the HttpClient is disposed:
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid#L97

You should enable the InjectHttpClient and then it is not disposed.

**Comment by krt-** [comment]
Sorry, used wrong arguments for client generation
