### ISSUE TITLE
CSharpClientGenerator Dto's generation

### ISSUE THREAD

**Issue by orihomie** [RicoSuter/NSwag#2557]
CSharpClientGenerator generates Dto's even when GenerateDtoTypes set to false. What am I doin wrong?

```csharp
var settings = new CSharpClientGeneratorSettings
{
	ClassName = "OsagoApiClient",
	GenerateDtoTypes = false,
	WrapDtoExceptions = false,
	WrapResponses = false,
	GenerateOptionalParameters = true,
	CSharpGeneratorSettings =
	{
		Namespace = "GenerateClientBySwagger",
	},
	OperationNameGenerator = new CustomOperationName() { }
};
```

**UPD**
I mean why does they generate method signatures like
> public async ....(SomeMethodsQuery query...)

Didnt they supposed to generate something like:
> public async ....(HttpContent query....)

**Comment by RicoSuter** [comment]
The idea of this setting is that you can provide DTO classes yourself. The contract is still the same and it hides HTTP abstractions (avoid leaky abstractions).
