### ISSUE TITLE
Servers can't be setted

### ISSUE THREAD

**Issue by cemtopkaya** [RicoSuter/NSwag#2559]
![image](https://user-images.githubusercontent.com/261946/70088841-1a104c00-1628-11ea-8a00-38734958fcd8.png)

Commentation and the way of working are different!

**Comment by RicoSuter** [comment]
Servers.Clear();
Servers.Add(...);

**Comment by obarlik-defacto** [comment]
services.AddOptions<OpenApiDocumentMiddlewareSettings>()
                .Configure<IConfiguration>((settings, config) =>
                {
                    settings.PostProcess = (doc, req) =>
                    {
                        doc.Info.Title = GetAppNameDisplay(appName);
                        doc.Info.Version = "v1";

                        if (!Debugger.IsAttached && !EnvironmentHelper.IsUnitTesting)
                        {
                            BaseUrlProvider bup = req.HttpContext.RequestServices.GetRequiredService<BaseUrlProvider>();

                            doc.Servers.Clear();
                            doc.Servers.Add(new OpenApiServer
                            {
                                Url = bup.BaseUrl,
                                Description = "API Server"
                            });
                        }
                    };
                });
