### ISSUE TITLE
CSharpClientGenerator generates duplicated parameters if one of their names is capitalized

### ISSUE THREAD

**Issue by asierad** [RicoSuter/NSwag#2560]
I'm trying to generate a client for an API that has parameters with similar names, one goes in the query string and the other in the header.

The names are almost identical, except one is capitalized and the other isn't.

After wondering why the feature added in https://github.com/RicoSuter/NSwag/issues/476 wasn't kicking in I realized that the capitalized parameter is the issue.

This can be reproduced with a slight variation of this test https://github.com/RicoSuter/NSwag/blob/35a7272d33f12d68941c9945d1db9feaa93105f9/src/NSwag.CodeGeneration.CSharp.Tests/ParameterTests.cs#L10

The code goes like this.

```c#
            var document = new OpenApiDocument();
            document.Paths["foo"] = new OpenApiPathItem
            {
                {
                    OpenApiOperationMethod.Get, new OpenApiOperation
                    {
                        Parameters =
                        {
                            new OpenApiParameter
                            {
                                Kind = OpenApiParameterKind.Query,
                                Name = "foo"
                            },
                            new OpenApiParameter
                            {
                                Kind = OpenApiParameterKind.Header,
                                Name = "Foo"
                            },
                        }
                    }
                }
            };

            //// Act
            var generator = new CSharpClientGenerator(document, new CSharpClientGeneratorSettings());
            var code = generator.GenerateFile();
```

Then this operation gets generated in the code: `public System.Threading.Tasks.Task FooAsync(object foo, object foo)` which is clearly invalid because of the duplicate parameter.

NSwag is a great tool, I hope this bug report helps.

Thanks in advance.

**Comment by hastarin** [comment]
I just ran afoul of this issue for the Grafana API. :(
