### ISSUE TITLE
File upload action results in malformed swagger.json and unclickable "Execute" button

### ISSUE THREAD

**Issue by G3Kappa** [RicoSuter/NSwag#2562]
Given the following controller action:

```csharp
[HttpPost("upload")]
public async Task<ActionResult> Upload(IFormFile file)
{
    return Ok();
}
```

NSwag generates an invalid swagger.json, as indicated by [this StackOverflow thread](https://stackoverflow.com/questions/58934503/swagger-ui-execute-button-not-working-when-file-is-uploading):

```swagger
"parameters": [
          {
            "type": "file",
            "name": "file",
            "in": "formData",
            "schema": {
              "type": "string",
              "format": "binary",
              "nullable": true
            },
            "nullable": true
          }
]
```

_Structural error at paths./api/Attachment/upload.post.parameters.0
should NOT have additional properties
additionalProperty: type, nullable_

_Structural error at paths./api/Attachment/upload.post.parameters.0.in
should be equal to one of the allowed values
allowedValues: path, query, header, cookie_

This breaks the `Execute` button, which will stop working as soon as a file is selected in the file browser.

**Comment by RicoSuter** [comment]
Looks like a Swagger UI problem and you should report this bug in their repository...

**Comment by G3Kappa** [comment]
Whoops, my bad.
