### ISSUE TITLE
CsharpClientGenerator support for HTTP Clients with custom Base Address/URL

### ISSUE THREAD

**Issue by shinsey-st** [RicoSuter/NSwag#2563]
I'm trying to setup a system that integrates the Polly library with NSwag generated clients so that we can express reliability policies around the client calls. One of the things we want to do is use an [HTTP client factory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-2.1#typed-clients) to set some properties such as the base address for API requests. In CsharpClientGeneratorSettings there is a property UseBaseUrl, which, if set to false, creates a client that doesn't take a base address via the constructor anymore, but only an HTTP client. 

My problem is that if I pass my HttpClient from the client factory with its configured base address, that setting gets ignored because the client is still looking at its BaseUrl property to generate request URLs and my configured one appears to be ignored or overridden.

Is there a way given the existing implementation to get the behavior I would expect here, which is that I can pass an HttpClient with a base address to the generated C# client which would then use that address to make requests?

**Comment by RicoSuter** [comment]
Set UseBaseUrl to false

**Comment by shinsey-st** [comment]
If I set that to false, regenerate my clients, and make a request with a configured HttpClient, the BaseAddress is missing and the request fails. As far as I can tell, the URL for each request is assembled using a URL builder that concatenates several properties together. If UseBaseUrl is false, it is true that it doesn't concatenate the BaseUrl property but it also seems true that it doesn't include the BaseAddress from the HttpClient, either. 

I can drop into a debugger and break on this line in the generated client.

`var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);`

client_ has a BaseAddress property set to the expected value but request_ does not contain it and the URL is only a relative path without a base URL.

**Comment by shinsey-st** [comment]
Okay, after a lot of digging I discovered that this is a weird issue related to the precise formatting of the BaseAddress value. It's the same problem described here in the selected answer.

https://stackoverflow.com/questions/23438416/why-is-httpclient-baseaddress-not-working
