### ISSUE TITLE
NSwag.AspNetCore Swagger document generation not using Name property from HTTP verb attribute as Operation ID

### ISSUE THREAD

**Issue by TheMagnificent11** [RicoSuter/NSwag#2565]
I'm using version `13.1.6` the `NSwag.AspNetCore` NuGet package and the Swagger document generation is not correctly setting Operation ID of the API endpoints (the framework of my website project is `netcoreapp2.2`).

It is using the `{controller name}_{HTTP method type}` convention instead of honouring the `Name` property on the HTTP verb attribute.

Here is a sample of my code and generated Swagger document.

**Controller**
```
    [ApiController]
    [Route("[controller]")]
    public class UsersController : Controller
    {
        [HttpPost(Name = "CreateUser")]
        [ProducesResponseType(200)]
        [ProducesResponseType(400, Type = typeof(ValidationProblemDetails))]
        public async Task<IActionResult> Post([FromBody]RegistrationRequest request)
        {
            ...
        }
    }
```

**Startup**
```
    public class Startup
    {
        public static void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            ...
            app.UseOpenApi();
            app.UseSwaggerUi3();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller=Home}");

                routes.MapRoute(
                    name: "single",
                    template: "{controller=Home}/{id}");
            });
        }

        public void ConfigureServices(IServiceCollection services)
        {
            ...
            services
                .AddMvc(options =>
                {
                    options
                        .Conventions
                        .Add(new KebabCaseRouteTokenReplacementControllerModelConvention());
                })
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            ...
            services.AddSwaggerDocument(options =>
            {
                options.Title = "My API";
                options.Version = "v1";
            });
        }
    }
```

**Swagger JSON**
```
{
...
  "paths": {
       /users": {
      "post": {
        "tags": [
          "Users"
        ],
        "operationId": "Users_Post",
        ...
     }
   }
  ...
}
```

Based on the `Name` property on the `HttpPostAttribute`, I would have expected the `operationId` in the JSON to be `CreateUser`, but it is `Users_Post`

**Comment by Leon99** [comment]
@TheMagnificent11 did you manage to solve this? I have the same issue.

Swashbuckle used the Name property to generate operationId. Is there a way to achieve the same or customize the default generation in any way?

**Comment by RicoSuter** [comment]
> Is there a way to achieve the same

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Annotations/OpenApiOperationAttribute.cs#L19

> or customize the default generation in any way?

You can implement a custom operation processor and set the operation ids however you want.

But it might make sense to also consider the attribute Name when defined out of the box.

**Comment by Leon99** [comment]
Thanks @RicoSuter. Just out of curiosity, what's the reason to require an additional attribute to define the operationId instead of using the ASP.NET's standard HttpXxxAttribute that always present anyway (like Swashbuckle does)?

**Comment by RicoSuter** [comment]
Main reason was probably that I didnt know about the Name property. Current solution gives you more flexibility (name must not be the same as the operation id) but it’s mor cumbersome. Changing it now might be a major breaking change for some. Do you know for what this name is used other then by Swashbuckle?

**Comment by Leon99** [comment]
> Do you know for what this name is used other then by Swashbuckle?

Nope. From reading https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-3.1#route-name, it looks like it's purely to make the job easier for the routing middleware by supplying a unique ID for different method overloads, although the description is rather vague and I might be misreading it.

> Current solution gives you more flexibility (name must not be the same as the operation id) but it’s mor cumbersome. Changing it now might be a major breaking change for some.

Not sure I need that flexibility. Looks like, just like Swagger, ASP.NET requires that name to be application-unique, so, technically, there is no need to have them differ.
What do you think about introducing a setting to base the operationId on the Name property (to avoid introducing a breaking change)?

**Comment by RicoSuter** [comment]
@pranavkm do you know for what the “meaning” of this name is?

**Comment by pranavkm** [comment]
It's just a unique identifier for a route. You could use it to [look up a route by name](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.urlhelperextensions.routeurl?view=aspnetcore-3.1#Microsoft_AspNetCore_Mvc_UrlHelperExtensions_RouteUrl_Microsoft_AspNetCore_Mvc_IUrlHelper_System_String_System_Object_). You could possibly use it as a fallback for operation ids if it's present, that seems like a pretty reasonable gesture.

**Comment by Leon99** [comment]
@RicoSuter would you accept a PR to enable using the route name for operationId via a new setting to enable that behavior?

**Comment by TBG-FR** [comment]
> @RicoSuter would you accept a PR to enable using the route name for operationId via a new setting to enable that behavior?

Thank you for your constribution ! Where do I find this setting ? I'd like to use names from the HTTP attribute

**Comment by flashgordon2016** [comment]
> > @RicoSuter would you accept a PR to enable using the route name for operationId via a new setting to enable that behavior?
> 
> Thank you for your constribution ! Where do I find this setting ? I'd like to use names from the HTTP attribute

You can enable it like this in Program.cs: 
```c#
public class Program {
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddOpenApiDocument(settings =>
        {
            settings.UseRouteNameAsOperationId = true;
        });
     }
 }
```
