### ISSUE TITLE
OpenAPI/Swagger missing TokenResponse on my generated contracts

### ISSUE THREAD

**Issue by dkboon01** [RicoSuter/NSwag#2568]
My nswagstudio client is not generating TokenResponse requestTokeResponse for the endpoints that I have.  What triggers NSwagStudioclient to generate this parameter?

**Comment by RicoSuter** [comment]
Can you provide the code of the controller and more information in general?

**Comment by dkboon01** [comment]
I must have solved this sorry for not closing this issue sooner.
