### ISSUE TITLE
BUG: NSwag Generator Does Not Use All API Explorer Metadata 

### ISSUE THREAD

**Issue by Kevweir** [RicoSuter/NSwag#2569]
The NSwag generator seems to have the same issue as the Swagger generator
See: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/412

In my case I'm trying to populate my header parameter DEFAULT VALUE with the API version and have spent the past few hours attempting to do so.

I tried using both IDocumentProcessor and  IOperationProcessor because I store the API version information in multiple locations with the OpenApiDocument.

However, I was surprised to find that when these processors execute none of the OpenApiDocument values, where I store the API version, has been populated yet or is simply not accessible through the context

I tried getting the version information from the following properties:
document.DocumentName
document.Info.Version
document.ApiGroupNames

Thanks for your consideration.

**Comment by RicoSuter** [comment]
Please provide sample code (controllers etc)

**Comment by Kevweir** [comment]
I'm using the following Nuget packages:

```
using Microsoft.AspNetCore.Mvc.Versioning;`    // version 4.1.0
using NSwag.AspNetCore;   // version 13.1.6

```
Versioning is configured as follows:

```
options.DefaultApiVersion = new ApiVersion(1, 0);
options.AssumeDefaultVersionWhenUnspecified = false;
options.ApiVersionReader = new HeaderApiVersionReader("X-Version");
options.ReportApiVersions = true;
```

The X-Version parameter is being created correctly in the OpenAPI Spec but the DEFAULT value is missing for the API version:

 
![OpenAPI Spec Sample](https://user-images.githubusercontent.com/57464683/70312310-022bfa00-17d9-11ea-92b5-111ca67ce2fc.PNG)

I would like to have the default value appear in the SwaggerUI instead of entering it every time but AspNetCoreOpenApiDocumentGenerator is not writing the default value for API version to the OpenAPI spec document.


![Capture](https://user-images.githubusercontent.com/57464683/70312543-79618e00-17d9-11ea-9811-944057bad784.PNG)

**Comment by RicoSuter** [comment]
The easiest way would be to PostProcess and add the default to all parameters with this name in the document.

**Comment by Kevweir** [comment]
Thanks for response.  The point is I shouldn't have to.   In my humble opinion the default behavior would be to populate the default value automatically when the document is generated.

**Comment by Kevweir** [comment]
I wrote my own IOperationProcessor to solve the problem but it took over a day to figure out.   

```
public class APIVersionParameterOperationProcessor : IOperationProcessor
    {
        public bool Process(OperationProcessorContext context)
        {
            const string Header = "Header";
            const string XVersion = "X-Version";

            var headerParameters = 
                from parms in context.OperationDescription.Operation.Parameters
                where parms.Kind.ToString() == Header && parms.Name == XVersion && parms.Default == null
                select parms;

            if (headerParameters.Count() > 0)
            {
                foreach (var parameter in headerParameters)
                {
                    // We need to Cast to the base class of context to get at the useful API GroupName (API Version)
                    parameter.Default = ((AspNetCoreOperationProcessorContext)context).ApiDescription.GroupName;
                }
            }

            // return false to exclude the operation from the document
            return true;
        }
    }
```

**Comment by RicoSuter** [comment]
I agree, either the default is currently not read at all or it is not being reported by api explorer. I think to remember that it was the latter, but not sure.

**Comment by Kevweir** [comment]
You may include my code in samples if you feel there is value to do so...
