### ISSUE TITLE
Honoring RouteTokenTransformerConvention with the CLI

### ISSUE THREAD

**Issue by arnederuwe** [RicoSuter/NSwag#2575]
Hi,

We implemented a KebabCaseParameterTransformer class to transform our ```WebApiMethods``` to ```web-api-methods``` to honour both our C# and url naming conventions. We register it like this:
```
services.AddControllers(opts => {  


    opts.Conventions.Add(new RouteTokenTransformerConvention(new KebabCaseParameterTransformer())); 

}); 
```

This works fine with ```services.AddOpenApiDocument();``` the url convention is correctly reflected in the generated swagger file.
We use the CLI to generate a TypeScript client as a part of our build process though, and there the ```KebabCaseParameterTransformer```, isn't executed, which makes perfect sense ofc. Resulting in a broken TypeScript client because all the url's are wrong.

Is there another way to customize this sort of thing when generating a swagger file with the CLI? Perhaps a custom DLL that can be invoked with some methods that implement certain interfaces?

**Comment by RicoSuter** [comment]
how fo you generate the spec via cli? If its using the document provider/api explorer then it should produce the same outputs

**Comment by arnederuwe** [comment]
We generate based on the api's DLL (we reference the assembly in the assemblyPaths config variable)
I don't think it's possible to generate based on the api explorer, as we are doing the generation process in our build steps (in azure pipelines for example)

**Comment by RicoSuter** [comment]
If sou use the aspnetcore generator with a dll or csproj you can do that

**Comment by arnederuwe** [comment]
Yes you can, after reading your docs I realised I was using the deprecated generator for my web API, switching to `AspNetCoreToOpenApi` resolved the issue
