### ISSUE TITLE
property 'required' of response header in OAS 3 yaml files returns error on code generation

### ISSUE THREAD

**Issue by sbarendr** [RicoSuter/NSwag#2576]
We have a OAS 3 yaml file with the following response header:

    X_Pagination_Page:
      required: true
      schema:
        type: integer
        description: Current page.
        example: 3

I download the latest NSwag studio for windows and when I try to generate client code, I get the following error:

Error converting value "true" to type 'System.Collections.Generic.ICollection`1[System.String]'

The same happens when I change 'true' into 'false'

Is this property not supported in the current version?

**Comment by RicoSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/78686137-fb320700-78f2-11ea-819a-ba02e7909dec.png)

it's supported... can you check with the latest version?

**Comment by MelvLee** [comment]
I tried it with NSwagStudio v13.3.0 and I still get the error. It can be reproduced with the following yaml

```
openapi: 3.0.0
info:
  title: NSwag issue with required field in header
  version: 13.3.0
paths:
  {}
components:
  headers:
    X_Pagination_Page:
      required: true
      schema:
        type: integer
        description: Current page.
        example: 3
```
According to the error message 'Could not cast or convert from System.String to System.Collections.Generic.ICollection`1[System.String]' a string could not be converted to a collection, so I changed the yaml to the following:

```
openapi: 3.0.0
info:
  title: NSwag issue with required field in header
  version: 13.3.0
paths:
  {}
components:
  headers:
    X_Pagination_Page:
      required:
      - true
      schema:
        type: integer
        description: Current page.
        example: 3
```
but this is not correct according to the OpenApi specs

**Comment by RicoSuter** [comment]
Strange, because this required should be handled correctly with json i think it could be a problem with json to yaml conversion. Can you try to convert it to json externally and try with json instead?

**Comment by MelvLee** [comment]
I have converted the yaml with https://www.json2yaml.com/ and https://onlineyamltools.com/convert-yaml-to-json and pasted the json into NSwagStudio, but I get the same error. Below is how the json looks like

```
{
  "openapi": "3.0.0",
  "info": {
    "title": "NSwag issue with required field in header",
    "version": "13.3.0"
  },
  "paths": {
  },
  "components": {
    "headers": {
      "X_Pagination_Page": {
        "required": true,
        "schema": {
          "type": "integer",
          "description": "Current page.",
          "example": 3
        }
      }
    }
  }
}
```

Changing the boolean into an array of booleans gives no error

**Comment by RicoSuter** [comment]
Maybe “headers” is not correctly supported/typed in the component model class.

**Comment by RicoSuter** [comment]
Here headers must be of type JsonSchema

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/OpenApiComponents.cs#L103

In this required is an array of string values with required property names. Should this be a dictionary of openapi headers according to the spec?

**Comment by RicoSuter** [comment]
See https://swagger.io/specification/#componentsObject

Needs to be fixed

**Comment by jorismathijssen** [comment]
Hey all, we are currently experiencing the same problem. Has there been any updates?

**Comment by ChrisJiang** [comment]
Same here, any update?

**Comment by biltongza** [comment]
I see there has been a commit that fixes this but it's not in the latest release. Is there a beta with this fix that I can try?

**Comment by RicoSuter** [comment]
It seems the spec is invalid as required must be an array of strings, no?

**Comment by biltongza** [comment]
I'm not sure. Navigating the OAS2 spec is kinda annoying because the site's links are broken. 
https://swagger.io/specification/v2/#schemaObject

That says there's a properties field, but I can't find anything more on it. I'm really not sure how an array of strings would map to a "required" field though?

**Comment by ncjvd** [comment]
@RicoSuter 

The components object examples has a required:true https://swagger.io/specification/#componentsObject
The header object https://swagger.io/specification/#header-object
follows structure of a Parameter object https://swagger.io/specification/#parameter-object
which has a "required" boolean.
Also says here that it is a boolean: https://swagger.io/docs/specification/describing-parameters/#header-parameters

This "Simple Model" structure from the picture doesn't seem to apply to headers I suppose?

**Comment by delasource** [comment]
This is still a problem.

I am using directus (headless cms) which outputs an [openapi spec](https://docs.directus.io/reference/system/server.html) that NSwag/JsonConvert is unable to use.


```
Newtonsoft.Json.JsonSerializationException: Error converting value True to type 'System.Collections.Generic.ICollection`1[System.String]'. Path 'paths./utils/hash/generate.post.requestBody.content.application/json.schema.properties.string.required', line 1, position 12431.
 ---> System.ArgumentException: Could not cast or convert from System.Boolean to System.Collections.Generic.ICollection`1[System.String].

```
