### ISSUE TITLE
JSonSerializationException because of 'required' on headers

### ISSUE THREAD

**Issue by kimvw** [RicoSuter/NSwag#2577]
An error occurs whilst generating a CSharp Client. It seems NSwagStudio is trying to interpret the required attribute as being of the given type.

Version: 13.1.6.0.

Yaml file: https://raw.githubusercontent.com/lvbag/BAG-API/master/Technische%20specificatie/Yaml's/20191209-1-lvbag-individuele-bevragingen-20180601/generated-specification/v1/verblijfsobjecten.yaml

Specific Exception:
_Newtonsoft.Json.JsonSerializationException: Error converting value "true" to type 'System.Collections.Generic.ICollection`1[System.String]'. Path 'components.headers.api_version.required', line 1, position 80476. ---> System.ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.ICollection`1[System.String]._

The problem seems to be on line 2413, the attribute required. The construction seems valid to me. I don't know for sure if this is an issue in NSwagStudio, but I thought I'd report it anyway.

**Comment by kimvw** [comment]
Closed because it's a duplicate of #2576 .

**Comment by sbarendr** [comment]
It seems like the tool is trying to interpret the required boolean as the other form of the required attribute, i.e. where a collection of the required attributes of an object is given, the attributes that should be required.
