### ISSUE TITLE
Add partial methods prior to serialization and deserialization to allow ignoring of required fields

### ISSUE THREAD

**Issue by michsco** [RicoSuter/NSwag#2580]
**CONTEXT**
We generate clients that get used against multiple instances of our swagger services (e.g. pre-prod and production). The client is generated against the pre-production environment, which means there may be new values in the responses that will fail to deserialize. To address this, we want to change the `JsonSerializerSettings` to ignore required fields during deserialization.

**ISSUE**
There are existing partial methods:
* `PrepareRequest(HttpClient, HttpRequestMessage, StringBuilder)`: Runs *after* deserialization of the request body (if any) before the URL is built.
* `PrepareRequest(HttpClient, HttpRequestMessage, string)`: Runs *after* deserialization of the request body (if any) and the final URL is built.
* `ProcessResponse(HttpClient, HttpResponseMessage)`: Runs *after* the response is received, but *before* deserialization of the response body.

If we implement the `ProcessResponse` method, we can alter the `JsonSerializerSettings` for the deserialization of the response, but there isn't a second place where we can *undo* the `JsonSerializerSettings` (we still want to enforce required fields when serializing the request).

**REQUEST**
Can we add two additional partial methods?

* `void BeforeRequestSerialization<T>(T body, JsonSerializerSettings settings)`: Runs immediately prior to calling `JsonConvert.SerializeObject(...)`.
* `void BeforeResponseDeserialization<T>(string json, JsonSerializerSettings settings)`: Runs immediately prior to calling `JsonConvert.DeserializeObject<...>(....)`.

**Comment by RicoSuter** [comment]
Have you tried ExposeJsonSerializerSettings?

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/CSharpClientGeneratorSettings.cs#L100

**Comment by michsco** [comment]
I am trying to come up with a solution that doesn’t require changes to the callers for each operation.

With that in mind, it’s not possible to have two different serialization settings for the request and response, even if the serialization settings are exposed. I thought about changing the serialization settings after the response comes back (eg ProcessResponse), but a second operation call wouldn’t be able to change them back (ie require the fields) before the request is serialized.

Michael
Sent from Outlook<https://aka.ms/qtex0l> on iOS

________________________________

**Comment by michsco** [comment]
@RicoSuter -- if I were to create a PR with a new partial method to solve this, I assume you would accept it?

**Comment by RicoSuter** [comment]
Cant you change this with a customized template? Does it make sense to add this as settings and bake it into the project?

**Comment by michsco** [comment]
Can I use the customized template as a consumer of NSwag without making any underlying changes? I haven't been able to find documentation showing how to do this.

**Comment by RicoSuter** [comment]
Yes, see https://github.com/RicoSuter/NSwag/wiki/Templates

But currently extension data is not exposed to these templates (needs PR).

**Comment by michsco** [comment]
I think this last comment was meant for a different issue. There's no extension data required here.
