### ISSUE TITLE
Use additional C# attributes on NSwag DTO Objects

### ISSUE THREAD

**Issue by michsco** [RicoSuter/NSwag#2581]
We are creating a metadata driven system that makes use of the generated DTO objects from NSwag. If this were a purely C# project, I'd just add custom Attributes to the various properties.

Is there a way to do something similar with NSwag based on an Open API document? It's straightforward for us to add additional metadata into the Open API document, but it isn't clear what configuration I would need to add to the generation process to add additional attributes to the DTO objects.

**Comment by MarkFl12** [comment]
I'd love to hear how to do this as well. There's plenty of attributes that people might want pulled through.

**Comment by RicoSuter** [comment]
You’d implement own schema, operation or document processors to add the additional metadata to the spec (eg x-my-property). And then use custom code generation templates to render the additional attributes. 

Only problem is that the  template model classes do not expose additional metadata (eg ExtensionData) yet.

**Comment by michsco** [comment]
I figured the ExtensionData was the way to get it into the swagger document.

How difficult would it be to expose this? I’d be willing to give it a shot myself if it isn’t going to make it high on the backlog.

Michael
Sent from Outlook<https://aka.ms/qtex0l> on iOS

________________________________

**Comment by MarkFl12** [comment]
Is there a guide on how to do this anywhere?

**Comment by RicoSuter** [comment]
We'd need to expose the ExtensionData for example here: 
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Models/PropertyModel.cs

Then you could overwrite this template and use them:
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/Templates/Class.Property.Annotations.liquid

**Comment by michsco** [comment]
@RicoSuter -- I assume if I were to create a PR with these solutions that you would accept it? If so, I'll include it as part of the project plan.

**Comment by RicoSuter** [comment]
Sure, i think it only needs this additional property in the model class. The rest must be changed by the lib consumer

**Comment by michsco** [comment]
Is there documentation on how to make the changes in the lib consumer?

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NSwag/wiki/Templates

But first we need to expose the extension data in the model class (PR).

**Comment by michsco** [comment]
This issue was resolved with PR #2616 .
