### ISSUE TITLE
Add support for C# 8 IAsyncEnumerable

### ISSUE THREAD

**Issue by Jrubzjeknf** [RicoSuter/NSwag#2582]
NSwag currently generates from this REST API method signature:

`public IAsyncEnumerable<MyDataType> GetNormCodes(string kpiCode)`

the following datatype definition in its swagger.json:

```
...
   "IAsyncEnumerableOfMyDataType": {
      "type": "object",
      "x-abstract": true
    }
...
```

Support for IAsyncEnumerable would be awesome, as web APIs will be using it more in the future.

**Comment by Jrubzjeknf** [comment]
For now, I can work around it by using this attribute above my API method:

`[ProducesResponseType(typeof(IEnumerable<MyDataType>), StatusCodes.Status200OK)]`

**Comment by RicoSuter** [comment]
Or for properties use `[JsonSchemType(typeof(IEnumerable<MyDataType>))]`

**Comment by cypressious** [comment]
Is the fix already available in a release?

**Comment by RicoSuter** [comment]
Yes i think so v13.2.0

**Comment by cypressious** [comment]
I'm using 13.2.0 and I had to add `[ProducesResponseType(typeof(IEnumerable<Foo>), StatusCodes.Status200OK)]` to get it to work.

**Comment by foriequal0** [comment]
`DefaultReflectionService.GetDescription()` returns `JsonTypeDescription` with `JsonObjectType.Object` for `IAsyncCollection<T>`, unlike `ObservableCollection<T>` that returns `JsonObjectType.Array` for even after the patch https://github.com/RicoSuter/NJsonSchema/commit/f9dde7b39e21ddc388c8755586435eabe6e4680c

Here is where the difference starts.
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/DefaultReflectionService.cs#L205
Even `DefaultReflectionService.IsArrayType()` returns true for `IAsyncCollection<T>`, `jsonContract` which is created by [`Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract`](https://github.com/JamesNK/Newtonsoft.Json/blob/9.0.1/Src/Newtonsoft.Json/Serialization/DefaultContractResolver.cs#L1119) is `JsonObjectContract`. `IAsyncEnumerable<T>` doesn't extends other interfaces, unlike `ObservableCollections<T>` which eventually implements. Therefore, `CreateContract` returns `JsonObjectContract` for `IAsyncEnumerable<T>` while returns `JsonArrayContract` for `ObservableCollections<T>`.

I could make a workaround for it by setting a custom `ContractResovler`
```csharp
        class AsyncCollectionContractResolver : CamelCasePropertyNamesContractResolver
        {
            // https://stackoverflow.com/questions/5461295/using-isassignablefrom-with-open-generic-types
            private static bool IsAssignableFromGenericType(Type genericType, Type givenType)
            {
                var interfaceTypes = givenType.GetInterfaces();

                foreach (var it in interfaceTypes)
                {
                    if (it.IsGenericType && it.GetGenericTypeDefinition() == genericType)
                        return true;
                }

                if (givenType.IsGenericType && givenType.GetGenericTypeDefinition() == genericType)
                    return true;

                var baseType = givenType.BaseType;
                if (baseType == null) return false;

                return IsAssignableFromGenericType(baseType, genericType);
            }

            protected override JsonContract CreateContract(Type type)
            {
                if (IsAssignableFromGenericType(typeof(IAsyncEnumerable<>), type))
                {
                    return base.CreateArrayContract(type);
                }

                return base.CreateContract(type);
            }
        }

        public void ConfigureServices(IServiceCollection services)
        {
            ...
            services.AddSwaggerDocument(settings =>
            {
                settings.SerializerSettings = new JsonSerializerSettings
                {
                    ContractResolver = new AsyncCollectionContractResolver(),
                };
            });
        }
```

**Comment by RicoSuter** [comment]
Ah shit, can you create a PR?
