### ISSUE TITLE
Multiple Request Body Examples in Swagger-UI

### ISSUE THREAD

**Issue by craig-gordon** [RicoSuter/NSwag#2583]
According to [this page](https://swagger.io/docs/specification/adding-examples/), Swagger-UI has supported multiple examples since version 3.23.0.

It apparently should look like this: ![Multiple Examples](https://user-images.githubusercontent.com/28714962/70951105-79128f80-2030-11ea-9178-bcc4d6b0469f.png)

I am trying to utilize this functionality with NSwag. I am able to specify a custom example using an <example> XML comment, but I cannot find a way to specify multiple examples, nor any instances online of using NSwag to do so. Any help here would be appreciated.

**Comment by RicoSuter** [comment]
What are the necessary (custom) properties?

You can add custom stuff this way: https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by craig-gordon** [comment]
I tried implementing a multi-example schema using a Schema Processor. I created a custom ExamplesAttribute class that takes in an array of types, and in the Schema Processor I pass serialized instances of those types in an array to SchemaProcessorContext.Schema.Example. Unfortunately, this just causes the Example box to display an array of examples, rather than triggering the Examples dropdown as shown in the first post's image.

Correct me if I'm wrong, but I'm not seeing a way to programmatically hook into Swagger UI 3's multiple examples interface (without custom UI logic), which you can see here:
![multiple examples](https://user-images.githubusercontent.com/28714962/71035396-614b1200-20e9-11ea-9a69-25cc2a2323c9.png)

**Comment by RicoSuter** [comment]
I think you need to set the “examples” property with the ExtensionData property

**Comment by craig-gordon** [comment]
I did a lot of digging and experimentation and still have been unable to trigger the Examples dropdown shown in the first post's image.

I believe the issue is that the "Examples" field on OpenApiMediaType does not have a setter, unlike the "Example" field.

![examples no setter](https://user-images.githubusercontent.com/28714962/71116234-ba767c80-21a1-11ea-887d-2082d00da8b5.png)


I confirmed using Swagger-Editor that setting this Examples field _does_ trigger the Examples dropdown.

![pet multi examples](https://user-images.githubusercontent.com/28714962/71116158-8c913800-21a1-11ea-8762-875b50933406.png)
![pet multi examples dropdown](https://user-images.githubusercontent.com/28714962/71116130-7c795880-21a1-11ea-890f-8c9d81a6431f.png)

If you agree that Examples should have a setter, I can submit a PR to include the setter on this field.

**Comment by RicoSuter** [comment]
This property is set to a dictionary so it should correctly serialize.. you can directly add examples..

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/OpenApiMediaType.cs#L50

**Comment by craig-gordon** [comment]
Ah, of course, you're right. I added the examples to the dictionary and the dropdown appears now.

I do think the Summary comment for the Examples field should be changed, but that's a minor thing.

Thank you for the very prompt replies & assistance!

**Comment by JohanSpannare** [comment]
Is there any final solution for this that can be shared? :)
