### ISSUE TITLE
Use a custom json based content type

### ISSUE THREAD

**Issue by mirroj** [RicoSuter/NSwag#2586]
Hello,

In our project, we are using a custom content type to version our REST api. Something like `application/myapp.api.v1+json`. We have run into serveral issues with nswag because of this.

There are many places in the code, where the `application/json` content type is hardcoded. If I'm correct it cannot be overriden by any settings.

If I specify only the custom content type in the swagger yml like this
```
    post:
      consumes:
        - application/myapp.api.v1+json 
```
The generated post method contains input parameters of type `System.IO.Stream` instead of a strongly typed object. It's a bit panful. I believe it's determined in this code [OpenApiParameter.cs#L208-L258](https://github.com/RicoSuter/NSwag/blob/dc80568236dd4d2984ea6e034c616d61ce07057c/src/NSwag.Core/OpenApiParameter.cs#L208-L258)

To overcome this. I thought we can specify both, the `application/json` and our custom content type like this
```
    post:
      consumes:
        - application/myapp.api.v1+json 
        - application/json   
```
This works for the input parameters but we ran into second issue. The accept header is by default set to `application/json`. I would expect that the first of the consumes collection is taken into account. The code [OperationModelBase.cs#L242-L245](https://github.com/RicoSuter/NSwag/blob/85ae862fd6d68173a201a79e0ad06e0be2ec5de1/src/NSwag.CodeGeneration/Models/OperationModelBase.cs#L242-L245) forces the `application/json`. 

What about removing the lines [OperationModelBase.cs#L242-L245](https://github.com/RicoSuter/NSwag/blob/85ae862fd6d68173a201a79e0ad06e0be2ec5de1/src/NSwag.CodeGeneration/Models/OperationModelBase.cs#L242-L245) (and L258-L261) so the logic is only dependend on the order of content types?

Or do you have any other ideas how to overcome this? 

Thank you

**Comment by FelixS90** [comment]
We have the same problem using [JSON API](https://jsonapi.org/format/). Also related to #2112. 

Why not checking for _application/<any_vendor_extension>+json_ in
```C#
[JsonIgnore]
        public bool IsBinaryBodyParameter
        {
            get
            {
                if (Kind != OpenApiParameterKind.Body || IsXmlBodyParameter)
                {
                    return false;
                }

                var parent = Parent as OpenApiOperation;
                if (parent?.ActualConsumes?.Any() == true)
                {
                    var consumes = parent.ActualConsumes;
                    return consumes?.Any() == true &&
                           consumes.Any(p => p.Contains("*/*")) == false && // supports json
                           consumes.Any(p => p.Contains("application/json")) == false;
                }
                else
                {
                    var consumes = parent?.RequestBody?.Content;
                    return consumes?.Any() == true &&
                           consumes.Any(p => p.Key.Contains("*/*") && !p.Value.Schema.IsBinary) == false && // supports json
                           consumes.Any(p => p.Key.Contains("application/json") && p.Value.Schema?.IsBinary != true) == false;
                }              
            }
        }
```
instead of _application/json_?

**Comment by RicoSuter** [comment]
Seems reasonable as long as it makes it more specific/correct. Can you create a PR?

**Comment by FelixS90** [comment]
I will try to file a PR today.
