### ISSUE TITLE
Custom swagger provider

### ISSUE THREAD

**Issue by SebastianStehle** [RicoSuter/NSwag#260]
Hi,

I have some normal services, but also a controller with dynamic models, that are created from metadata at runtime. I would like to create a swagger specification for this controller, but I am a little bit lost. Which is the main try point, is there an interface I have to implement?

**Comment by rsuter** [comment]
A Swagger spec describes a model with a fixed structure (also see JSON Schema). If the schema is dynamic, you cannot describe it with Swagger / JSON Schema... Can you provide a sample or describe your scenario a little bit more in detail?

**Comment by rsuter** [comment]
You can provide a custom operation or document processor to generate custom schemas for an operation or the document: https://github.com/NSwag/NSwag/wiki/OwinMiddleware#enable-oauth2-authorization

**Comment by RicoSuter** [comment]
You can change the type with the [JsonSchemaType(typeof(Person))] attribute...
