### ISSUE TITLE
ERROR ReferenceError: '_observableMergeMap' is not defined

### ISSUE THREAD

**Issue by ravimittal16** [RicoSuter/NSwag#2602]
we have just upgraded the dependencies to @angular 7 and upgraded the nswag package to version **"nswag": "13.1.2"**, everything works flawlessly on dev mode but it failing on prod build.
`ERROR ReferenceError: '_observableMergeMap' is not defined` is coming on console.

Please suggest

`import { mergeMap as _observableMergeMap, catchError as _observableCatch } from 'rxjs/operators';
import { Observable, throwError as _observableThrow, of as _observableOf } from 'rxjs';
import { Injectable, Inject, Optional, InjectionToken } from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpResponseBase } from '@angular/common/http';`

**Comment by RicoSuter** [comment]
Probably rxjs is not properly installed.

**Comment by ravimittal16** [comment]
Thanks @RicoSuter, 
Luckily, We are able to resolved the issue by upgrading the version of `@angular-devkit/build-angular.`
