### ISSUE TITLE
Missing documentation on MSBuild

### ISSUE THREAD

**Issue by michsco** [RicoSuter/NSwag#2605]
There is a link for the MSBuild targets in the root README.md that links to [here](https://github.com/RicoSuter/NSwag/wiki/MSBuild), but the wiki page doesn't contain any content.

**Comment by TheXenocide** [comment]
Searching for other tickets, but stumbled on this. I think the link is supposed to point here: https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild

**Comment by portlandtn** [comment]
I think I fixed this issue, using the link that @TheXenocide provided, but I may have done this wrong.
