### ISSUE TITLE
Is there a way to generate non-required properties as "nullable" by default?

### ISSUE THREAD

**Issue by dennismeissel** [RicoSuter/NSwag#2610]
I'm using 3rd party API (FastAPI), that generates properties without telling if it's nullable.

So if I have **openapi.json** with non-required schema-property like this:

```json
"Topic": {
  "title": "Topic",
  "type": "object",
    "properties": {
      "first_id": {
        "title": "First_Id",
        "type": "string"
      }
  }
}
```

I get C# code with `Newtonsoft.Json.Required.DisallowNull` by default:

```c#
[Newtonsoft.Json.JsonProperty("first_id", 
        Required = Newtonsoft.Json.Required.DisallowNull, 
        NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
public string First_id { get; set; }
```

Is it possible to get `Newtonsoft.Json.Required.Default` by default?

**Comment by RicoSuter** [comment]
This is because "nullable" is false by default. There is currently no way to change that I think - the only way is to preprocess the spec and add `"nullable": true` where needed.

**Comment by dennismeissel** [comment]
Ok, thank you for the information :)
