### ISSUE TITLE
SwaggerException.Response is empty

### ISSUE THREAD

**Issue by rpatrick00** [RicoSuter/NSwag#2619]
We have a webapp that is using our service's NSwag generated client.  This has all been working for months with NSwag 12.0.13 on Dotnet Core 2.2.  This week I updated our service and webapp to NSwag 13.2.0 on Dotnet Core 3.1 and now the client is no longer working as it previously did.

In my test case, I am calling a service API with a payload that returns:

```
HTTP/1.1 400 Bad Request
Date: Sat, 11 Jan 2020 17:20:25 GMT
Content-Type: application/json; charset=utf-8
Server: Kestrel
Content-Length: 157
Cache-Control: no-store,no-cache
Pragma: no-cache

{"errors":[{"id":"CAP-0001","message":"Cases search does not support searching for all cases"},{"id":"CAP-0007","message":"Tenant name must not be empty."}]}
```

In the webapp, we are doing the following to get the payload from the SwaggerException and deserialize it as our type (instead of using the client's generated types):

```
    private RestResponse<T> GetErrorsFromException<T>(SwaggerException ex)
    {
      RestResponse<T> restResponse = JsonConvert.DeserializeObject<RestResponse<T>>(ex.Response);
      restResponse.StatusCode = ex.StatusCode;
      return restResponse;
    }
```

This was working perfectly in 12.0.13.  We have upgraded to 13.2.0 and now, the exception's Response object is null/empty.  From debugging the generated client, I see that the ReadObjectResponseAsync<T>() method is getting the data, deserializing it, and storing it as an Object but the Text field is now empty.  It seems like that is intentional since the second argument in the following line is string.Empty:

```
return new ObjectResponseResult<T>(typedBody, string.Empty);
```

So my question is what should I do to fix this so that I avoid breaking changes going forward?

**Comment by RicoSuter** [comment]
You can set LoadExceptionResponse (or similar) to true on the client to have the old behavior (disabled for performance reasons

**Comment by rpatrick00** [comment]
Thanks!
