### ISSUE TITLE
Axios Template generate Typescript Client with error

### ISSUE THREAD

**Issue by nunonux** [RicoSuter/NSwag#2628]
When using NSwagStudio (v13.2.1.0) to generate a TypeScript client with template set to Axios and Dto Type Style set to Interface, it generates the api with an error.

![image](https://user-images.githubusercontent.com/17728684/72527835-26a7d700-3859-11ea-8307-51ef74036f06.png)

If I switch the  template to Fetch it generates it correctly. So how can I resolve this issue (I tried to google about it and search in the issues but found nothing that might help me).

**Comment by RicoSuter** [comment]
Seems like the Axios template cannot handle type Interface.

**Comment by nunonux** [comment]
For now I'm using it with the DTO Type Style as Class, to resolve the issue

**Comment by tukhfatov** [comment]
Fixed with v13.2.5. Please try to use the latest version
