### ISSUE TITLE
Property that contains symbol creates an invalid property

### ISSUE THREAD

**Issue by uniquelau** [RicoSuter/NSwag#2629]
Property that contains a special character e.g. `"property?": false`, results in an invalid class property that contains a symbol.

`[Newtonsoft.Json.JsonProperty("can_rent?"]`
`public bool Can_rent? { get; set; }`

Perhaps invalid symbols could be removed or replaced with a safe character?

`public bool Can_rent_`

**Comment by RicoSuter** [comment]
Must be added to this list here:
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema.CodeGeneration.CSharp/CSharpPropertyNameGenerator.cs#L21

Same for TypeScript.
Can you create a PR?

**Comment by uniquelau** [comment]
Sure, I will add a PR this weekend, thank's for pointing me in the right direction.

**Comment by RicoSuter** [comment]
I just had to work in the project and fixed it. 
But i still dont understand why you would put a "?" in a property name :-) - but ok.

**Comment by uniquelau** [comment]
@RicoSuter Thanks! Re: "why" - completely agree, but it's out of my control!

**Comment by RicoSuter** [comment]
NSwag v13.2.2 will be released soon

**Comment by jlongo62** [comment]
This is still an issue in:
 Generated using the **NSwag toolchain v13.6.1.0** [(NJsonSchema](url) v10.1.21.0 (Newtonsoft.Json v12.0.0.2)) (http://NSwag.org)

I am using the Ambari Swagger json file and it is riddled with # characters in method names.
Is there a work-around or fix ?
I tried to  include the entire json file. I can email it, if you guys can fix it.

### Json

 "paths": {
    "/actions": {
      "get": {
        "tags": [ "Actions" ],
        "summary": "Get all action definitions",
        "description": "",
        **"operationId": "ActionService#getActionDefinitions",**
        "produces": [ "text/plain" ],
        "parameters": [

###  Results in:

public async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<ActionResponseSwagger>> **ActionService#getActionDefinitionsAsync**(string fields, string sortBy, int? page_size, string from, string to, System.Threading.CancellationToken cancellationToken)
        {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append("actions?");

**Comment by RicoSuter** [comment]
This would need to be fixed in the OperationNameGenerators
