### ISSUE TITLE
MediaType missing in NSwag.AspNet.WebApi.JsonExceptionFilterAttribute

### ISSUE THREAD

**Issue by phibsi** [RicoSuter/NSwag#2635]
Hey all,

the JsonExceptionFilterAttribute returns the StringContent as text/plain.
But it should be application/json.

https://github.com/RicoSuter/NSwag/blob/d9f1820bb93e7415b721ba367c88f6f1e65dd37e/src/NSwag.AspNet.WebApi/JsonExceptionFilterAttribute.cs#L73

The StringContent-constructor needs a third parameter: "application/json":
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.stringcontent.-ctor?view=netframework-4.8#System_Net_Http_StringContent__ctor_System_String_System_Text_Encoding_System_String_

**Comment by RicoSuter** [comment]
Can you create a PR?
