### ISSUE TITLE
When I Use NSWag+ ocelot + consul, all http method become OPTIONS.

### ISSUE THREAD

**Issue by swpuzhang** [RicoSuter/NSwag#2639]
When I Use NSWag+ ocelot + consul, all http method become OPTIONS.
I have three Service(Account money reward) and One Gateway,I register SwaggerRoute On Gateway.
This is regester SwaggerRoute Codes:
app.UseOpenApi();
            app.UseSwaggerUi3(options =>
            {
                var apis = Configuration.GetSection("Services").Get<string[]>();
                apis.ForEach(p =>
                {
                    options.SwaggerRoutes.Add(new SwaggerUi3Route(p, $"/swagger/{p}/swagger.json "));
                });
            });

this is my configs:
{
  "urls": "http://*:5000",
  "Serilog": {
    "MinimumLevel": {
      "Default": "Debug"
    }
  },
  "Services": [ "Account", "Money", "Reward" ],
  "AllowedHosts": "*"
}

Ocelot Config:
{
  "ReRoutes": [
    {
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/api/Account/{url}",
      "DownstreamScheme": "http",
      "ServiceName": "Account",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/api/Account/{url}",
      "UpstreamHttpMethod": [
        [ "GET", "POST", "DELETE", "PUT" ]
      ],
      "ReRoutesCaseSensitive": false
    },
    {
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/api/Reward/{url}",
      "DownstreamScheme": "http",
      "ServiceName": "Reward",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/api/Reward/{url}",
      "UpstreamHttpMethod": [
        [ "GET", "POST", "DELETE", "PUT" ]
      ],
      "ReRoutesCaseSensitive": false
    },
    {
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/swagger/Account/swagger.json",
      "DownstreamScheme": "http",
      "ServiceName": "Account",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/swagger/Account/swagger.json",
      "UpstreamHttpMethod": [
        [ "GET", "POST", "DELETE", "PUT" ]
      ],
      "ReRoutesCaseSensitive": false
    },
    {
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/swagger/Money/swagger.json",
      "DownstreamScheme": "http",
      "ServiceName": "Money",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/swagger/Money/swagger.json",
      "UpstreamHttpMethod": [
        [ "GET", "POST", "DELETE", "PUT" ]
      ],
      "ReRoutesCaseSensitive": false
    },
    {
      "UseServiceDiscovery": true,
      "DownstreamPathTemplate": "/swagger/Reward/swagger.json",
      "DownstreamScheme": "http",
      "ServiceName": "Reward",
      "LoadBalancerOptions": {
        "Type": "RoundRobin"
      },
      "UpstreamPathTemplate": "/swagger/Reward/swagger.json",
      "UpstreamHttpMethod": [
        [ "GET", "POST", "DELETE", "PUT" ]
      ],
      "ReRoutesCaseSensitive": false
    }

  ],

  "GlobalConfiguration": {
    "BaseUrl": "http://localhost:5000",
    "RequestIdKey": "OcRequestId",
    "ServiceDiscoveryProvider": {
      "Provider": "Consul",
      "Host": "127.0.0.1",
      "Port": 8500,
      "ConfigurationKey": "Ocelot",
      "PollingInterval": 1000
    }
  }
}

**Comment by RicoSuter** [comment]
What do you mean with they become options? In the generated specs?

**Comment by RicoSuter** [comment]
What do you mean with they become options? In the generated specs (ie they dont reflect the controller methods)?

**Comment by swpuzhang** [comment]
![41L5M5Q {7K{H70}4JG~3ML](https://user-images.githubusercontent.com/16497599/72691733-97edcf80-3b62-11ea-99fd-8aa4d2bd9d2c.png)
![)DJHHPEECH@$O6QLZN0I8HJ](https://user-images.githubusercontent.com/16497599/72691741-9fad7400-3b62-11ea-9f6b-3310395e8206.png)

**Comment by swpuzhang** [comment]
![41L5M5Q {7K{H70}4JG~3ML](https://user-images.githubusercontent.com/16497599/72691804-19ddf880-3b63-11ea-9645-649317ae0cc7.png)








![)DJHHPEECH@$O6QLZN0I8HJ](https://user-images.githubusercontent.com/16497599/72691807-206c7000-3b63-11ea-9674-be6f0406ded2.png)

**Comment by swpuzhang** [comment]
![41L5M5Q {7K{H70}4JG~3ML](https://user-images.githubusercontent.com/16497599/72691829-4134c580-3b63-11ea-826e-d2362a5c2689.png)


this is request:
![)DJHHPEECH@$O6QLZN0I8HJ](https://user-images.githubusercontent.com/16497599/72691843-56115900-3b63-11ea-89e2-31f619fb47ca.png)

**Comment by RicoSuter** [comment]
Ah i think this is normal browser behavior and if not this has to be fixed in the Swagger UI project..

**Comment by swpuzhang** [comment]
I have tested Swashbuckle,  Swashbuckle can execute correctly.  So I don't know whether it's a bug

**Comment by RicoSuter** [comment]
Did you compare the two swagger specs (NSwag and Swashbuckle) did you see a difference which might lead to this difference? Or maybe Swashbuckle is using a (newer?) version of Swagger UI which has fixed this issue?
