### ISSUE TITLE
Generating both CancellationToken and Optional parameters results in incorrect order

### ISSUE THREAD

**Issue by bdemolder** [RicoSuter/NSwag#2642]
Hi,

This might be known already or I am wrong about enabling these both at same time...

But If you leave them both on false:
`Method(int? param1, int param2)`

If you only enable CancellationTokens:
`Method(int? param1, int param2, CancellationToken cancellationToken)`

If you only enable OptionalParams:
`Method(int param2, int? param1 = null)`

If you enable both:
`Method(int param2, int? param1 = null, CancellationToken cancellationToken)`

This last one does not compile as default params should always be last in the param list?

Package info:
Using on build:
`<package id="NSwag.MSBuild" version="13.2.0" targetFramework="net472" developmentDependency="true" />`

If you need any other inf, please ask, if it is fixed in 13.2.2, sorry about that, could not really find release notes, but will try updating tomorrow... Or if this is weird to combine... Then you may close this issue!

**Comment by RicoSuter** [comment]
Maybe we should generate

```
Method(int param2, int? param1 = null)
Method(int param2, int? param1 = null, CancellationToken cancellationToken = default(CancellationToken))
```

or will this lead to compile errors (ambiguous method)?

**Comment by bdemolder** [comment]
Sorry to get back to you so late..

I don't think that would pose any problems:

![image](https://user-images.githubusercontent.com/22233289/72786933-1fa11000-3c2f-11ea-820f-6220a40078a2.png)

![image](https://user-images.githubusercontent.com/22233289/72786864-fd0ef700-3c2e-11ea-952f-399c7d5a3ad2.png)

However, I do not know implications further on of course... but it seems to give enough flexibility as you see in the above example.

And according to:
https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken.none?view=netcore-3.1
And 
https://github.com/dotnet/corefx/issues/495

This is for .net core 3.1, but if you see .Net Framework, it is the same for those as well.

Default(CancellationToken) is same as CancellationToken.None... or New CancellationToken()

**Comment by bdemolder** [comment]
And I do not know which is better to do:

Only set that default value in case the optional parameters is on, or always setup a default value for cancellation token.
