### ISSUE TITLE
CSharpController Claims Authentication [Question/Advice]

### ISSUE THREAD

**Issue by uniquelau** [RicoSuter/NSwag#2644]
We are implementing a solution, that uses a JWT token authentication.

We are facing a problem that perhaps other people have experienced, in that we cannot pass the `ControllerBase.User` (Claims Principle) from the generated Controllers into our interfaces.

I am currently seeing:

+ Generated controllers do not include [Authorize] attribute
+ User object not passed into interfaces

If any one has had a similar situation and has any advice it would be much appreciated.

**Comment by RicoSuter** [comment]
Good question. The main idea is that the interfaces are decoupled from the actual implementation (avoid leaky abstraction) that means it should not know about http etc. But then how do you solve security? And yeah what should you generate to support flexible authorization (i.e. authorize attributes)? What would be the right solution?

**Comment by uniquelau** [comment]
So, we ended going down the route of using the Abstract controllers which works well, an this allows us to decorating our controllers with the correct [Authorize] tags.

I will spend some time looking at the code gen side of things (as discussed on the other ticket) and if I get anywhere I'll put together a PR. Thanks again, much appreciated. Lau
