### ISSUE TITLE
Misleading "Unexpected token while deserializing object: EndObject."

### ISSUE THREAD

**Issue by flidr** [RicoSuter/NSwag#2649]
I'm trying to parse an invalid swagger file (missing mandatory responses):

```json
{
   "swagger":"2.0",
   "info":{
      "description":"",
      "version":"1.0.0",
      "title":"aaa"
   },
   "host":"localhost:8000",
   "basePath":"",
   "schemes":[
      "http"
   ],
   "paths":{
      "/a/b":{
         "get":{
            "operationId":"GetOrders"
         }
      }
   }
}
```

What I got is samewhat misleading error: Unexpected token while deserializing object: EndObject. Path 'paths['/a/b'].get', line 17, position 10.'. When I add responses it's parsed ok.

**Comment by RicoSuter** [comment]
Is this a bug or expected? Isnt responses a required field?

**Comment by flidr** [comment]
IMHO I consider it as a bug. Based on the error text I would assume the json is badly formatted or something pretty low-level.
If it misses a required field, it should be explicit about this, so user has a chance to fix the input.
