### ISSUE TITLE
How to convert File to FileParameter in Typescript?

### ISSUE THREAD

**Issue by ranouf** [RicoSuter/NSwag#2662]
Hi,

I tried to find the information in the issues, wiki and stackoverflow but I didn't find it. 

In my Api, there is a DTO with a IFormFile, which generate using nswastudio a function asking for a FileParameter.

```
export interface FileParameter {
    data: any;
    fileName: string;
}
```

When a file is selected with input type=file, I don't know how to convert the File to a FileParameter.

How could I do that?

Thanks

**Comment by ranouf** [comment]
Any update?

**Comment by RicoSuter** [comment]
Did you try with https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer

**Comment by mathiasthejsen** [comment]
@ranouf Did you find a solution for this?

**Comment by Znow** [comment]
Also experiencing this issue, what is the solution?!

**Comment by spectacularbob** [comment]
This worked for me
`public uploadFile(file: File) {
   let fileParameter: FileParameter = { data: file, fileName: file.name };
   //Pass it to your service
}
`

**Comment by 1988gadocansey** [comment]
> This worked for me
> 
> ```
> public uploadFile(file: File) {
>     let fileParameter: FileParameter = { data: file, fileName: file.name };
>     //Pass it to your service
> }
> ```

This saved me. Almost a week try to fix this blob issue from nswag fileparameter

**Comment by ranouf** [comment]
Thanks for your help:)
