### ISSUE TITLE
Swagger UI does not work correctly behind Ingress

### ISSUE THREAD

**Issue by vChriSch** [RicoSuter/NSwag#2675]
Hi Guys,

we have the Problem that our Swagger UI does not work correctly behind an  Ingress Controller.

For now it's working like this:
Ingress is configured that "_someServiceName_" is routed to _localhost:5001_. This means 
_someUrl.com/someServiceName/swagger_ should be routed to _localhost:5001/swagger._

When I call now someUrl.com/someServiceName/swagger the Index.html is shown with 

> Failed to load API definition.
> Not Found /swagger/v1/swagger.json

When I use this code:

` app.UseSwaggerUi3(o =>
                        {
                          o.TransformToExternalPath = (s, request) => { return $"/someServiceName/{s}"; };
                        });`

then the html page is shown like expected. BUT! when I try to execute a call the generated URL is not correct. Instead of **someUrl.com/someServiceName/api/foo** the URL's are generated like **someUrl.com/api/foo** which does not work.

I tried to set the basePath like this:
`settings.PostProcess = document => { document.BasePath = "/someServiceName"; }` and also ` app.UseSwaggerUi3(o => o.Path = "/someServiceName");`

My Expectation is that now the BaseUrl should be **someUrl.com/someServiceName** and not **someUrl.com**.

How can I get this working that the swagger.json is found in the HTML Page and that the executed requests are using the correct URL?

Not sure if its the same like **Swagger UI not working while API service behind reverse proxy #1892** but we are not in a Beta Phase and need to getting this working.

Tried also the Solution from @OculiViridi 

Thanks

**Comment by RicoSuter** [comment]
Swagger 2.0 or OpenAPI 3.0? Try Servers property instead of BasePath with full URL

**Comment by RicoSuter** [comment]
Try PostProcess in UseOpenApi() instead

**Comment by vChriSch** [comment]
@RicoSuter thanks for your hints it's working now on localhost and behind Ingress with following code:
```csharp
app.UseOpenApi(o =>
   {
        o.PostProcess = (document, request) =>
              {
                   string documentBaseUrl = document.BaseUrl;
                   document.Servers.Clear();
                   document.Servers.Add(new OpenApiServer(){ Description = "Default" , Url = $"{documentBaseUrl}/someServiceName"}); 
               };
  });
app.UseSwaggerUi3(o => { o.TransformToExternalPath = (s, request) => { return $"/someServiceName/{s}"; }; });

services.AddSwaggerDocument();
```

Is that your preferred solution?

**Comment by RicoSuter** [comment]
I think this looks right.

**Comment by vChriSch** [comment]
Ok. Then we can close this
