### ISSUE TITLE
DateType uses sortable format string in C#

### ISSUE THREAD

**Issue by adamjones1** [RicoSuter/NSwag#2680]
According to [the spec of OpenAPI](https://swagger.io/docs/specification/data-models/data-types/#string), dates should be the full-date notation defined by RFC 3339, ie. `yyyy-MM-dd`.

However, the serialisation called on "dateType"s (as determined in the nswag.json) that gets generated in C# is:
```
myDate.ToString("s", System.Globalization.CultureInfo.InvariantCulture)
```
which includes a time component. Can this please be fixed to instead generate:
```
myDate.ToString("yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture)
```

**Comment by adamjones1** [comment]
Sorry to be clear, this is just when sending dates as arguments in a URL query string.

**Comment by RicoSuter** [comment]
format=“date”?

**Comment by adamjones1** [comment]
Yep! Schema of the parameter is string, format date, but what ends up in the query string for it when you make calls has a time component.

**Comment by adamjones1** [comment]
Ah, apologies - I've realised I wasn't using the latest version of NSwag and this issue has already been fixed in a newer version. Closing the issue.

**Comment by RicoSuter** [comment]
Ah good.
