### ISSUE TITLE
NswagStudio not start

### ISSUE THREAD

**Issue by BallJirdos** [RicoSuter/NSwag#2684]
After updating the latest version of NswagStudion did not start. After several attempts, there was no message. I trying to reinstall or install to another folder or older version of NswagStudio, but it didn't help. I use W10  and I tried installator MSI, zip, and choco. Is there any log file with error message?

**Comment by RicoSuter** [comment]
Delete AppData/RicoSuter/NSwag

**Comment by BallJirdos** [comment]
Folder not found

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/issues/1313#issuecomment-389698033

**Comment by BallJirdos** [comment]
Great, it is fixed, thanks.
