### ISSUE TITLE
Short generated as int, is that Ok?

### ISSUE THREAD

**Issue by paulovila** [RicoSuter/NSwag#2700]
I have a dto class in netcore31 that has a property of type **short**
```csharp
public class MyDto {
    public short Version { get; set; }
}
```
the generated code is **int**
```csharp
   [Newtonsoft.Json.JsonProperty("Version", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public int Version
        {
            get { return _version; }
            set 
            {
                if (_version != value)
                {
                    _version = value; 
                    RaisePropertyChanged();
                }
            }
        }
```

Is this correct?

**Comment by RicoSuter** [comment]
I think we dont differentiate between short/int in the spec - the spec has no predefined way to specify this as a "format"

**Comment by paulovila** [comment]
If Entity Framework recognised a Short,  then the client should use a Short.

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NJsonSchema/blob/master/src/NJsonSchema/Generation/DefaultReflectionService.cs#L78

You cannot expect a 1:1 conversion with openapi as it is language independent and cannot describe everything 100% of your language (c#).

**Comment by paulovila** [comment]
I understand your point, the Swagger documentation do not distinguish between _int32_/_int64_/_short_. The problem with the C# generation lowering it's standards by the lower common denominator, is that it leads to misinterpretation of the contract. If the client knew that it is _short_ the overflow would occur first in the client (before it occurs in the server).
