### ISSUE TITLE
Is there a way to make client methods virtual?

### ISSUE THREAD

**Issue by jonlin** [RicoSuter/NSwag#2704]
I'm running into issues with Mocking the client because the methods aren't virtual and the generated interface isn't working for me because we have a partial class that handles authentication and disposing of the custom HttpClient, and the generated interface doesn't extend IDisposable.

Is there an option or any other way to make the generated client's methods virtual so it can be mocked?

**Comment by RicoSuter** [comment]
Currently there is no option for that specifically.. you need to override the template and add the virtual modifier. The question is whether we should add this by default or if we should add an option. But maybe you can change the access modifier from “public” to “public virtual”?

**Comment by jonlin** [comment]
I tried changing the "typeAccessModifier" config to "public virtual" but I got an error when generating that said: the modifier 'virtual' is not valid for this item.

It looks like "virtual" is getting added to the POCO objects and not the client methods themselves.

How do I override the template? Is that hard?

**Comment by RicoSuter** [comment]
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L92

https://github.com/RicoSuter/NSwag/wiki/Templates

**Comment by TwoUnderscorez** [comment]
@RicoSuter Any updates?
Could you please provide a more detailed explanation?
Also, how does one provide a custom template?

Your help and effort are much appreciated.

**Comment by jeremyVignelles** [comment]
I think that what he meant was this line from the wiki:

> To override templates, create a template directory, put the overridden templates into it and point to it with the TemplateDirectory setting.

Then, you can take the Client.Class.liquid from the repo, and add `virtual` after `{{ operation.MethodAccessModifier }}` at the line he pointed.

**Comment by TwoUnderscorez** [comment]
Ah, thank you!
I didn't realize that that was the name of the setting in the nswag.json. (`templateDirectory`)
I think this issue can be closed now.
