### ISSUE TITLE
Client.Method.Annotations template missing

### ISSUE THREAD

**Issue by sandord** [RicoSuter/NSwag#2712]
I'm generating C# clients using the `CSharpClientGenerator` class.

After upgrading from NSwag 12.3.0 to 13.2.3 however, I'm getting the following `InvalidOperationException`:

    Could not load template 'Client.Method.Annotations' for language 'CSharp'.

I'm using DotLiquid 2.0.314, the same version as NSwag is referencing.

Generating Angular and Fetch clients works just fine.

The output gets as far as this:

    ...
    partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);
    partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
    partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
    partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

    /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
    /// <summary></summary>
    /// <param name="id"></param>
    /// <exception cref="ApiException">A server side error occurred.</exception>

**Comment by sandord** [comment]
Thanks!

**Comment by RicoSuter** [comment]
Should be in the new release now.

**Comment by sandord** [comment]
Indeed and it works great.
