### ISSUE TITLE
Force generation of a given type.

### ISSUE THREAD

**Issue by MaximeMorin** [RicoSuter/NSwag#2713]
We are currently using NSwagStudio to generate clients for our .Net Core 3.1 project using the API Explorer.  

We have an issue where a given enum is not generated because it isn't used by the API at first glance.  (The data is returned encrypted; that's probably why the API Explorer can not detect the dependency.)

Is there a way to force the generation of a given type?  We found attributes for excluding items, but none to actually force them.

**Comment by RicoSuter** [comment]
Can you provide a sample?

**Comment by MaximeMorin** [comment]
I will try to generate an example on Monday, mean while, you can pretty much create a new project with a dummy REST API, add a random class/enum and generate.  The random class/enum won't be generated.  I would like that random class/enum to be generated.  (Maybe with an attribute)

**Comment by RicoSuter** [comment]
Only classes/types which are publicly exposed by the api are generated.

**Comment by RicoSuter** [comment]
Otherwise you’d need to generate and add it manually in postprocess or with a document processor

**Comment by MaximeMorin** [comment]
Do you think it would be feasible to create a new annotation, say [OpenApiInclude(<typeGoesHere>)] on the public/exposed API method?  It could also be an annotation directly on the extra file (without the type).  When generating it would also check for that annotation and generate the extra file?

**Comment by RicoSuter** [comment]
You can try [KnownType(typeof...)] on another type or controller (?)

**Comment by MaximeMorin** [comment]
That's interesting; I will try that on Monday, thanks for the hint.

**Comment by MaximeMorin** [comment]
Nice call, KnownType on a class/type already returned by a controller works.  I tried on the controller directly and it didn't work.

`[KnownType(typeof(<otherType>))]
public class AModelReturnedByAnAPI
{}`

In my case, I can add the KnownType attribute on my model containing the encrypted data.

Thanks!
