### ISSUE TITLE
ActualSchema.ToJson adds "additionalProperties": false

### ISSUE THREAD

**Issue by heikomilke** [RicoSuter/NSwag#2716]
When I iterate over Operations and ToJson on ActualParameters the wrong default is used when adding additionalProperties to the output.

```
            foreach (var op in swagger.Operations)
            {
                var b = op
.Operation.ActualParameters
.SingleOrDefault(predicate => predicate.Kind == OpenApiParameterKind.Body);
                Console.WriteLine(b.ActualSchema.ToJson());
            }
```

This will add `"additionalProperties": false` for body parameter that did not specify additionalProperties.

By definition the default for additionalProperties is `true`. Pls fix.

**Comment by RicoSuter** [comment]
> By definition the default for additionalProperties is true. Pls fix.

In C# the default is false as you cannot just add more properties to a C# class. If there is a property with JsonExtensionDataAttribute then it will be true: 

https://www.newtonsoft.com/json/help/html/SerializationAttributes.htm
