### ISSUE TITLE
Documentation for SwaggerToTypeScriptClientGenerator is missing

### ISSUE THREAD

**Issue by jaworek** [RicoSuter/NSwag#2722]
It seems that someone edited out all documentation for `SwaggerToTypeScriptClientGenerator`.
Is is possible to revert back to older revisions to have it available for users?

https://github.com/RicoSuter/NSwag/wiki/SwaggerToTypeScriptClientGenerator#extended-classes-and-extension-code

**Comment by kveard** [comment]
Any chance of getting this documentation back?  We are trying to integrate NSWAG into our Angular2 App and could use some guidance and documentation.

**Comment by RicoSuter** [comment]
I'm wondering more and more whether it's a good idea to keep the wiki open...
