### ISSUE TITLE
Axios client doesn't handle errors properly

### ISSUE THREAD

**Issue by Tyrrrz** [RicoSuter/NSwag#2726]
Axios throws errors on 4xx/5xx status codes by default, so when using the generated client the actual API errors are never properly processed.

**Comment by tukhfatov** [comment]
You inject the instance of Axios through the constructor, with your custom error handler.  Check it here https://github.com/axios/axios#interceptors

**Comment by Tyrrrz** [comment]
Sure. But by default NSwag generates a client that doesn't handle the errors at all, even though the generated code _attempts to_

**Comment by tukhfatov** [comment]
As I understood there are more maintainers for Angular and C# clients and it will be faster if you will implement error handler and raise pull request.

**Comment by Tyrrrz** [comment]
Yeah that's fine. I'll get around to it eventually.

**Comment by MariuszKogut** [comment]
Came across this issue today. It can also be resolved by
``axios.defaults.validateStatus = () => true``

(Further details: https://github.com/axios/axios#handling-errors)

In this way the promise will be resolved and NSwag is responsible for handling the result. I think this is the easiest solution. At least it works fine for me.
