### ISSUE TITLE
Error on Generic name with TypeScript Generate code

### ISSUE THREAD

**Issue by andmattia** [RicoSuter/NSwag#2781]
Today I try to refresh my TS proxy and NSwag generate a broken file.

this is the generate code

```ts
   getAuditLogs(input: GetAuditLogsInput): ng.IPromise<PagedResultDto`1OfOfAuditLogListDtoAndApplicationAnd_0AndCulture=neutralAndPublicKeyToken=null> {
```

**Comment by RicoSuter** [comment]
Can you provide some sample code (controllers etc) to repro this?

**Comment by andmattia** [comment]
Hi @RicoSuter 

thanks for your quick response.

I investigate on our API Server and I found a change that broken the NSwag.

So I look in  our solution and we have a 2 methods that return same object name with different implementation.  To solve this issue we put

```cs
Configuration.Modules.AbpWebApi().HttpConfiguration
                .EnableSwagger(c =>
                {
                    c.SingleApiVersion("v1", "web.Api");
                    c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
                    c.UseFullTypeNameInSchemaIds();
                    //c.SchemaId(x => x.FullName);
                    c.DescribeAllEnumsAsStrings();
                })
```
We are in a .NET solution 4.6.x and we are moving to .NETCore so we try to use 

``` cs
     c.SchemaId(x => x.FullName);
```
In this way the Swagger UI works fine but NSwag doesn't work, so we rollback with

``` cs
     c.UseFullTypeNameInSchemaIds();
```
with this configuration swagger and also NSwag works.
