### ISSUE TITLE
AspNetCoreToOpenApi generates application/json content-type for Stream parameter

### ISSUE THREAD

**Issue by cguedel** [RicoSuter/NSwag#2793]
For a method containing a stream parameter, e.g:

`public async Task UploadFile([FromBody] Stream stream)`

The generator produces the following open api spec for the requestBody parameter:

```
"requestBody": {
          "x-name": "stream",
          "description": "Stream",
          "content": {
            "application/json": {
              "schema": {
                "type": "string",
                "format": "byte",
                "nullable": false
              }
            }
          },
          "required": true,
          "x-position": 7
        }
```

I would actually expect this to be `application/octet-stream`. Checking the code in NSwag, I think it's checking the JsonSchema.IsBinary property. This is only true when either the type is `File` or it's `string` and the format is `binary`. 

Could the fix be in `NSwag.Generation.AspNetCore.Processors.OperationParameterProcessor.AddBodyParameter` changing `JsonFormatStrings.Byte` to `JsonFormatStrings.Binary`?

**Comment by rmarineau** [comment]
I am also running into this same issue and would be interested in what the resolution is.

**Comment by RicoSuter** [comment]
You should use the [OpenApiBodyParameter] where you can specify the mime type and which hides the other body params.


https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Annotations/OpenApiBodyParameterAttribute.cs

**Comment by cguedel** [comment]
Thanks, this works!
