### ISSUE TITLE
Extension Class Add error

### ISSUE THREAD

**Issue by andmattia** [RicoSuter/NSwag#2801]
I use Nswag to generate a AngualrJs TypeScript class. I've a problem parsing my response. My api service wrap the results with

```json
{
   "result":"[ ...]",
   "targetUrl":null,
   "success":true,
   "error":null,
   "unAuthorizedRequest":false,
   "__abp":true
}
```
So I need to add a custom base class 
```typescript
      export class ClientBase {
        
        protected transformResult(url: string, response: ng.IHttpResponse<any>, processor: (response: ng.IHttpResponse<any>) => any) {
            // TODO: Return own result or throw exception to change default processing behavior, 
            // or call processor function to run the default processing logic
    
            var data = JSON.parse(response.data);

            // Un wrap response from ABP
            response.data = JSON.stringify(data.result);

            console.log("Service call: " + url);
            return processor(response); 
        }
    }
```
``` json
"extensionCode": "service.extensions.ts",
```
Now all request are pocressed by transformResult but my TS file add ClientBase at the end of file generated and TS not compile because say me that class are used before the declaration. I check on the NSWAG config file without a valid solution.

**Comment by mattgrande** [comment]
@andmattia - Did you ever find a fix for this? I've been having the exact same issue.

**Comment by mattgrande** [comment]
Okay, I figured it out. For me, there were two issues:

1. I had a `configurationClass` that was actually an interface.
2. There were comments above my base class, which is apparently a no-no.

@RicoSuter - Both of these issues are present in your documentation, here: https://github.com/RicoSuter/NSwag/wiki/TypeScriptClientGenerator#inject-an-authorization-header

Would you like me to issue a PR to fix that?

**Comment by RicoSuter** [comment]
A PR is always appreciated. The wiki can just be updates and does not need prs

**Comment by mattgrande** [comment]
Thanks! I've updated the wiki. Feel free to close this.

**Comment by olsti** [comment]
Had the issue of duplicated imports in the baseApiClass and wanted to share the solution 
just in case someone has the same issue:
Imports from the extension-class can be ignored -> 
"An import can be filtered out in the generated code with the // ignore comment:"
https://github.com/RicoSuter/NJsonSchema/wiki/TypeScriptGenerator#extended-classes-and-extension-code

And the BaseClassName needs to be set, it's not optional when using extension-code
