### ISSUE TITLE
Generated C# client does not correctly encode query parameters for objects

### ISSUE THREAD

**Issue by goldsam** [RicoSuter/NSwag#2807]
Given the following openapi segment:

```json
"paths": {
  "/batches": {
    "get": {
      "parameters": [
          {
            "name": "filterSortPage",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/getBatchListParameters"
            },
            "style": "form",
            "explode": true
        }
      ]
    }
  },
}
```

where `getBatchListParameters` is an object defining several query parameters, the generated C# Client code for formatting this object as a query parameter string looks like this:

```csharp
// ...
var urlBuilder_ = new System.Text.StringBuilder();
urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/batches?");
urlBuilder_.Append(System.Uri.EscapeDataString("filterSortPage") + "=").Append(System.Uri.EscapeDataString(ConvertToString(filterSortPage, System.Globalization.CultureInfo.InvariantCulture))).Append("&");
urlBuilder_.Length--;    
// ...
```

I was expecting the query string to consist of this object's properties where they query parameter names are consistent with my openapi spec (or the generated `Newtonsoft.Json.JsonProperty` annotations).

**Comment by RicoSuter** [comment]
How is this specified in OpenAPI?

**Comment by Mainian** [comment]
The default serialization method is style: form and explode: true

https://swagger.io/docs/specification/serialization/#query
