### ISSUE TITLE
Bug in Class Extensions: unidentified classes when adding suffix or prefix to the class name 

### ISSUE THREAD

**Issue by AbuDawood** [RicoSuter/NSwag#2849]
Hi @RicoSuter 
I am reporting a bug in the classes' extending operation.

It works perfectly when the app uses the default class name i.e. {controller}

If I use pure auto-generated classes' names the extended codes don't appear in the target classes. and when I use the class name as it will be in the generated file (e.g. {controller}Service => securityService) an exception says that the target class not found.

I tried to substitute pure controller names by the class output names and vice versa in different locations with no success! (e.g. extension ts file, declaring the protected methods and so on)

**Comment by RicoSuter** [comment]
Maybe you can create a PR in NJS/NSwag to repro this? 
Maybe better in NJsonSchema as this is where the root cause is probably.

**Comment by AbuDawood** [comment]
Sorry for the delay, Please let me know if I am correct

Finally, the correct convention to extend the auto-generated classes with prefixes and/or suffixes is to use the class

```
  { prefixIfExists} + {classname} + {suffixIfExists} extends generated.{classnameOnly} {

}
```
Example:

![image](https://user-images.githubusercontent.com/28667792/94975950-395b5c80-050b-11eb-9f68-e38eece47f3b.png)


```
class FilesApplicationsManagerService extends generated.FilesApplicationsManager {
}
```
