### ISSUE TITLE
Open swagger.json input file from local hard drive

### ISSUE THREAD

**Issue by astrohart** [RicoSuter/NSwag#2850]
Suggest add functionality to open a swagger.json input file from the local hard drive of the computer on which NSwagStudio is running.

This one site that I am trying to get its Swagger file from, it utilizes ReDoc to generate its API docs.  There is a Download button to download the swagger.json but the browser turns it into a blob url like blob:http://docs.nomics.com/20e254a4-9755-47c1-94da-b7e146bdb136.

This can't be fed in to NSwagStudio.  It would be great to have the File -> Open dialog box be able to support opening a downloaded swagger.json video straight from my local disk.

**Comment by RicoSuter** [comment]
It already supports relative (to nswag.json) or absolute file paths

**Comment by astrohart** [comment]
It’s not that.  I’ll explain when I have a chance to post some figures.

It’s about the swagger.json file that comes from a site whose API is documented.  Being able to import a API spec from the file menu is what I am asking. 

Regards,
 
Brian C. Hart, Ph.D.

**Comment by astrohart** [comment]
My point is, if i have a swagger.json file downloaded from a website, and I open NSwag Studio, and then click File -> Open, the open dialog does not list *.json files as a supported file extension in the filter drop-down. Not a big deal -- I can just type ```*.json``` into the file name box, and then I can see my swagger.json.   And it will open.  

My point is, that this is non-intuitive.

**Comment by RicoSuter** [comment]
Open is for loading nswag config files not specs directly

**Comment by RicoSuter** [comment]
An option would be that you can also open spec files with open and then it creates a new document with the spec as reference/input

**Comment by uniquelau** [comment]
Ahha! That's really useful to know, so the nswag file supports this:

```
"documentGenerator": {
    "fromDocument": {
      "url": "../my-local-swagger-file.oas3.yml",
      "output": null,
      "newLineBehavior": "Auto"
    }
  },
```

**Comment by astrohart** [comment]
Still, I think it’s not that horrible a change to make the File -> Open dialog support swagger.json files.  I’m a very experienced UI/UX developer on the Windows desktop, and this feature is, in my mind, a no brainer.

**Comment by RicoSuter** [comment]
Sure, please create a pr for the ui project.. i agree its a no brainer and in no case a breaking change etc.
