### ISSUE TITLE
How to single-out codegen for just one document

### ISSUE THREAD

**Issue by kant2002** [RicoSuter/NSwag#2852]
I my API project I generate 2 OpenAPI documents (One private API, second is public API). 
Previously I build clients using AutoRest, but it is a pain now so I decide take a look. 
Is there a way how to single out code gen for just on OpenAPI JSON file when use <OpenApiProjectReference>? I using CSharpCodegen.

**Comment by RicoSuter** [comment]
single out?

**Comment by kant2002** [comment]
I mean I have 2 documents described using Swashbuckle in same WebAPI. I call them `v1` and `private-v1`,
I want to generate 2 different clients in separate projects. I though that I can add `<OpenApiReference>` and somehow tell NSwag that I want to generate API only for `v1` document.
Does that make my question more clear?

**Comment by kant2002** [comment]
@RicoSuter did my question make sense or should I paraphrase?

**Comment by RicoSuter** [comment]
I think in <OpenApiReference> you can specify which input file to use and then the client only for this is generated..
