### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' (Version=3.1.2.0) in  NSwag.AspNetCore v 13.5.0

### ISSUE THREAD

**Issue by dmitry-pavlov** [RicoSuter/NSwag#2856]
I ma getting this error when I am opening in browser API Explorer 

> Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

- NSwag.AspNetCore v 13.5.0
- .NET Core 3.1

![image](https://user-images.githubusercontent.com/1560778/82765228-7c027f00-9e1d-11ea-8a1f-5f28bab889a8.png)

**Comment by dmitry-pavlov** [comment]
`   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.<>c__DisplayClass5_0.<GetJsonSerializerSettings>b__0()
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.GetJsonSerializerSettings(IServiceProvider serviceProvider)`

**Comment by dmitry-pavlov** [comment]
Might be related to https://github.com/dotnet/aspnetcore/issues/8254

**Comment by maxberghammer** [comment]
Same Problem here :(

**Comment by RicoSuter** [comment]
Can you create a PR against a sample project in this repo to repro this?

**Comment by RicoSuter** [comment]
I don't see that in my .net core 3.1 projects...

**Comment by SeppPenner** [comment]
@maxberghammer @RicoSuter The main reason seems to be the missing `services.AddControllers()` as described here: https://github.com/RicoSuter/NSwag/issues/1961#issuecomment-515631411 (As @dmitry-pavlov already pointed out). I had the same problem today and after adding this one line, it worked :D

**Comment by statler** [comment]
Is this expected to work now? I continue to get this exception, even on a simple project. The solution from #1961 has no effect. Refer attached.

I can continue from the exception, but parameter models are not resolved in controllers.

System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

[DataSourceLoadOptionsProblem_withnewton.zip](https://github.com/RicoSuter/NSwag/files/5485146/DataSourceLoadOptionsProblem_withnewton.zip)

**Comment by RicoSuter** [comment]
It seems that we need to catch this error when Newtonsoft is not available and fall back to System.Text.Json (this should be there but probably it stops before it can fall back?).

**Comment by statler** [comment]
Also, this error gets thrown in .Net Core 3 where the Microsoft.AspNetCore.Mvc.MvcJsonOptions library is not even available regardless of whether you include NewtonsoftJson and specify .AddNewtonsoftJson(). It seems like it is thrown by the core libraries though

I think the issue of the parameter models is a different issue to do with the modelbinders, and that this error is safely ignorable, but it would be great not to have it raised if it is irrelevant.

**Comment by vgb1993** [comment]
I updated to latest version and now I get the sameerror when I launch the project:

> Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.


```
  <ItemGroup>
    <PackageReference Include="Autofac" Version="5.0.0" />
    <PackageReference Include="Autofac.AspNetCore.Multitenant" Version="3.0.0" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="6.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="9.3.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="MicroElements.Swashbuckle.FluentValidation" Version="4.0.0" />
    <PackageReference Include="MicroElements.Swashbuckle.FluentValidation.WebApi" Version="0.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="5.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SpaServices.Extensions" Version="5.0.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.8.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.0" />
    <PackageReference Include="NetCore.AutoRegisterDi" Version="2.1.0" />
    <PackageReference Include="NSwag.Annotations" Version="13.4.2" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.2.2" />
    <PackageReference Include="NSwag.Generation.AspNetCore" Version="13.2.2" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.4.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="SqlKata" Version="2.2.0" />
    <PackageReference Include="SqlKata.Execution" Version="2.2.0" />
  </ItemGroup>
```

Any clues?

**Comment by vgb1993** [comment]
I created a simple repo, it still breaks with this configuration and the CommonExceptions check activated.

Startup
`        public void ConfigureServices( IServiceCollection services )
        {
            services.AddControllers().AddNewtonsoftJson();
            services.AddOpenApiDocument();
        }

        public void Configure( IApplicationBuilder app, IWebHostEnvironment env )
        {
            app.UseOpenApi();
            app.UseSwaggerUi3();
            app.UseRouting();
            app.UseEndpoints( endpoints =>
            {
                endpoints.MapControllers();
            } );
        }`


Program
`        <Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.0" />

    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />

    <PackageReference Include="NSwag.Annotations" Version="13.9.4" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.9.4" />
    <PackageReference Include="NSwag.Generation.AspNetCore" Version="13.9.4" />
    
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
  </ItemGroup>

</Project>`

**Comment by LUISURBM** [comment]
System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=5.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'
After upgraded .Net Core 3.1 to 5.0

And 

        public void ConfigureServices( IServiceCollection services )
        {
            services.AddControllers();
        }

I am ignoring exception as it is not blocking my app, any help please is welcome.

**Comment by dgancho** [comment]
Any update here? I have similar exception in Startup in a FunctionApp on v3.10.0

```
public class Startup : FunctionsStartup
{
   public override void Configure(IFunctionsHostBuilder builder)
     {
         builder.Services.AddMvcCore().AddJsonOptions(o =>
         {
             o.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
             o.SerializerSettings.NullValueHandling = NullValueHandling.Ignore;
         });
   }
}
```

Could not load type 'Microsoft.AspNetCore.Mvc.MvcJsonOptions' from assembly 'Microsoft.AspNetCore.Mvc.Formatters.Json, Version=3.1.10.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by RicoSuter** [comment]
In AspNetCoreOpenApiDocumentGenerator.cs we have

![image](https://user-images.githubusercontent.com/2603405/104889744-ecdb4600-596e-11eb-9e9b-2af7cfe68b64.png)

I wonder why this exception bubbles up?
Should fallback to System.Text.Json...

**Comment by jeremyVignelles** [comment]
@RicoSuter :
Seems like it tries to load the System.Text version, unless I'm missing something, this is not Newtonsoft :
> Microsoft.AspNetCore.Mvc.MvcJsonOptions

**Comment by jeremyVignelles** [comment]
Sorry for the last post. After a bit of thinking, I think that you get an `IOption<MvcJsonOptions>` at [line 70](https://github.com/RicoSuter/NSwag/blob/2d620e58396939cff27d5a463b6ebd0b4a7af62d/src/NSwag.Generation.AspNetCore/AspNetCoreOpenApiDocumentGenerator.cs#L70) but the type inside the generic is probably not full resolved until you call `.Value` on it, which could explain why it throws outside the cach.

**Comment by RicoSuter** [comment]
Oh yes, maybe we need a trycatch around that as well so that the fallback works as expected...

**Comment by dmitry-pavlov** [comment]
Any chance to get rid of adding `Microsoft.AspNetCore.Mvc.NewtonsoftJson` package when selected `System.Text.Json` as `JSON Library` @RicoSuter ? 

![image](https://github.com/RicoSuter/NSwag/assets/1560778/332fc4d3-7208-40eb-8f55-7f7e94b70018)

**Comment by RicoSuter** [comment]
@dmitry-pavlov is this still a problem with the v14 previews?

**Comment by dmitry-pavlov** [comment]
Yeah, now it's gone in v14 preview. Cool 👍 Thanks @RicoSuter !
