### ISSUE TITLE
Process is terminated due to StackOverflowException.

### ISSUE THREAD

**Issue by guaicaiboshi** [RicoSuter/NSwag#2866]
I encountered a Process is terminated due to StackOverflowException when using version 13.6.0 again. There is no problem for me to put the generated json into the validation tool.As shown in figure: **Process is terminated due to StackOverflowException.**.My josn generated about 20,000 lines, and I tried to use 2,000 lines without reporting an error

**Comment by guaicaiboshi** [comment]
"JToken": {
				"type": "array",
				"items": {
					"$ref": "#/components/schemas/JToken"
				}
			}, 
Circular reference leads to

**Comment by robsiera** [comment]
FYI, I too encountered this error after I added this code to one of my dto's.  

public IDictionary<string, JToken> IgnoredData
{
   return Debugger.IsAttached ? OrphanData : null;
}
private IDictionary<string, JToken> OrphanData;


I guess the JObject creates Circular references

**Comment by RicoSuter** [comment]
Maybe you can create a PR in njsonschema with a test to repro this? I think jobject should be treated as object and you should not der a SO
