### ISSUE TITLE
Non-nullable properties being treated as nullable.

### ISSUE THREAD

**Issue by kb3eua** [RicoSuter/NSwag#2887]
My .NET Core Web API has action methods that return EntityFrameworkCore models generated by `Scaffold-DbContext` (database-first).  I then have NSwag setup to generate corresponding TypeScript for the Angular clients and interfaces for the models.

My problem is that all fields in my TypeScript interface were being flagged as optional:
``` ts
{
  clientId?: number | undefined;
  eventName?: string | undefined;
}
```
Setting the `-DataAnnotations` flag of `Scaffold-DbContext` fixed most of my issues because it added `[Required]` to most of my model properties (`string`s), but not to the `int` properties because `int` is non-nullable so it theoretically shouldn't need it, so now NSwag generates TypeScript like so:
``` ts
{
  clientId?: number
  eventName: string
}
```

Is there anyway we can modify NSwag to recognize non-nullable primitives like `int` and `bool` and treat them as Required even in the absence of a `[Required]` attribute?

**Comment by vchirikov** [comment]
https://github.com/RicoSuter/NJsonSchema/blob/cd4342c0936ba6811aa76f5053c6c3b7c8be232e/src/NJsonSchema/JsonSchemaProperty.cs#L94

So fix for this is:
```cs
var tsSettings = new TypeScriptGeneratorSettings();
tsSettings.SchemaType = SchemaType.OpenApi3;
```

**Comment by kb3eua** [comment]
@vchirikov Where would I set that?  At first glance I think this actually gives me the behavior that I want... wish there was a better way to get what I want while still staying on OpenApi3:
```cs
services.AddOpenApiDocument(options =>
{
    options.SchemaType = NJsonSchema.SchemaType.Swagger2;
});
```
I'm using the MSBuild package to run my `nswag.json` file to generate my TypeScript at compile time.
