### ISSUE TITLE
openApiToCSharpController: Generates invalid ActionResult when returning a file

### ISSUE THREAD

**Issue by gastonmuijtjens** [RicoSuter/NSwag#2900]
I'm trying to generate controller classes using `NSwag.AspNetCore` and `NSwag.MSBuild` based on my OpenAPI Spec file. However, when trying to specify a file download endpoint (`format: binary`), I'm facing the following issue when the setting `"useActionResultType": true` is specified:

## Expected behavior
The following controller method should be generated:
```csharp
public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.FileResult> DownloadCSVFile()
{
    // [...]
}
```

## Actual behavior
However, the following invalid controller method is generated:
```csharp
public System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<FileResult>> DownloadCSVFile() 
{
   // [...]
}
```

There are two issues here:
- First of all, it generates an `ActionResult` of `FileResult`, which is not valid on runtime. Rather, it should just return `FileResult`. I did not find a workaround.
- Secondly, the namespace of `FileResult` is not provided here. A workaround is to specify the namespace within the `additionalNamespaceUsages` setting.

Please fix this issue, such that I do not have to specify the endpoints manually.

### api-spec.nswag
```json
{
  "runtime": "NetCore31",
  "defaultVariables": null,
  "documentGenerator": {
    "fromDocument": {
      "json": "",
      "url": "api-spec.yml",
      "output": null
    }
  },
  "codeGenerators": {
    "openApiToCSharpController": {
      "controllerBaseClass": "Microsoft.AspNetCore.Mvc.ControllerBase",
      "controllerStyle": "Abstract",
      "controllerTarget": "AspNetCore",
      "useCancellationToken": false,
      "useActionResultType": true,
      "generateModelValidationAttributes": true,
      "routeNamingStrategy": "None",
      "basePath": "/api/v1/",
      "className": "{controller}",
      "operationGenerationMode": "MultipleClientsFromFirstTagAndOperationId",
      "additionalNamespaceUsages": [],
      "additionalContractNamespaceUsages": [],
      "generateOptionalParameters": false,
      "generateJsonMethods": false,
      "enforceFlagEnums": false,
      "parameterArrayType": "System.Collections.Generic.IEnumerable",
      "parameterDictionaryType": "System.Collections.Generic.IDictionary",
      "responseArrayType": "System.Collections.Generic.IEnumerable",
      "responseDictionaryType": "System.Collections.Generic.IDictionary",
      "wrapResponses": false,
      "wrapResponseMethods": [],
      "generateResponseClasses": true,
      "responseClass": "SwaggerResponse",
      "namespace": "Example.Controllers",
      "requiredPropertiesMustBeDefined": true,
      "dateType": "System.DateTimeOffset",
      "jsonConverters": null,
      "anyType": "object",
      "dateTimeType": "System.DateTimeOffset",
      "timeType": "System.TimeSpan",
      "timeSpanType": "System.TimeSpan",
      "arrayType": "System.Collections.Generic.List",
      "arrayInstanceType": "System.Collections.Generic.List",
      "dictionaryType": "System.Collections.Generic.IDictionary",
      "dictionaryInstanceType": "System.Collections.Generic.Dictionary",
      "arrayBaseType": "System.Collections.ObjectModel.Collection",
      "dictionaryBaseType": "System.Collections.Generic.Dictionary",
      "classStyle": "Poco",
      "generateDefaultValues": true,
      "generateDataAnnotations": true,
      "excludedTypeNames": [],
      "excludedParameterNames": [],
      "handleReferences": false,
      "generateImmutableArrayProperties": false,
      "generateImmutableDictionaryProperties": false,
      "jsonSerializerSettingsTransformationMethod": null,
      "inlineNamedArrays": false,
      "inlineNamedDictionaries": false,
      "inlineNamedTuples": true,
      "inlineNamedAny": false,
      "generateDtoTypes": true,
      "generateOptionalPropertiesAsNullable": false,
      "templateDirectory": null,
      "typeNameGeneratorType": null,
      "propertyNameGeneratorType": null,
      "enumNameGeneratorType": null,
      "serviceHost": null,
      "serviceSchemes": null,
      "output": "Controllers/ControllerGenerated.cs"
    }
  }
}
```

### OpenAPI Spec
```yaml
paths:
  /demo:
    get:
      operationId: 'DownloadCSVFile'
      summary: Returns an example in CSV format
      responses:
        '200':
          description: A CSV file
          content:
            text/csv:
              schema:
                type: string
                format: binary
```

## Technical information
- OpenAPI version: 3.0.3
- NSwag NuGet version: 13.6.0
- .NET Core version: 3.1

**Comment by ahmeturun** [comment]
we've faced the same issue as you, we were trying to create our own FileResult action(to write the stream directly into the response body). and weirdly even though the signature of the genereted controller action is wrapped in ActionResult you can return your custom actionresult.

generated controller action:
`public abstract System.Threading.Tasks.Task<Microsoft.AspNetCore.Mvc.ActionResult<FileResult>> Export([Microsoft.AspNetCore.Mvc.FromBody] ExportParametersReport body);`

Action implementation:
`public override async Task<ActionResult<OpenApi.FileResult>> Export([FromBody] ExportParametersReport dto)
...
...
return new StreamingFileResult()`

custom action result:
`public class StreamingFileResult : Microsoft.AspNetCore.Mvc.FileResult`

**Comment by gastonmuijtjens** [comment]
@RicoSuter Any update on this?

**Comment by jeremyVignelles** [comment]
@gastonmuijtjens : Probably not, but if you really would like this to be fixed, you can come on gitter so I can help you getting started to debug that in the NSwag project and see what's going on. If you make the PR yourself, it would make life easier for Rico.

**Comment by gastonmuijtjens** [comment]
@RicoSuter @jeremyVignelles I opened a pull request (#3020) which includes a fix for this issue.
