### ISSUE TITLE
IOperationProcessor generates PascalCase properties instead of camelCase

### ISSUE THREAD

**Issue by skylyn** [RicoSuter/NSwag#2920]
I have the following code attempting to generate example values for responses in our API. However, even though all other property definitions are camelCase, the examples generated by the IOperationProcessor are PascalCase. I've even tried explicitly setting the contract resolver on the context object as seen below, but that seems to have no affect.

```
    public class MigrationProcessor : IOperationProcessor
    {
        public bool Process(OperationProcessorContext context)
        {
            const int migrationStatusCode = (int)HttpStatusCode.BadRequest;
            context.SchemaGenerator.Settings.SerializerSettings = new JsonSerializerSettings
            {
                ContractResolver = new CamelCasePropertyNamesContractResolver()
            };
            var response = context.OperationDescription.Operation.Responses[migrationStatusCode.ToString()].Content.FirstOrDefault().Value;

            var migrationExample = new OpenApiExample
                {
                    Value = new MigrationRequiredProblem("username")
                };
            var manualMigrationExample = new OpenApiExample
                {
                    Value = new ManualMigrationRequiredProblem()
                };

            response.Examples.Add("Migration Required", migrationExample);
            response.Examples.Add("Manual Migration Required", manualMigrationExample);

            return true;
        }
    }
```

Here's an example of the swagger output. Notice the `Type` in the 400 example generated from the IOperationProcessor vs `type` generated normally.
![image](https://user-images.githubusercontent.com/4708347/85312643-f4d01780-b46b-11ea-9b48-49d92fb0a2cc.png)

I also tried explicitly setting the `JsonSerializerSettings` in Startup, and that affects all the other examples, but it has no affect on the examples generated by the IOperationrProcessor.

Please let me know if there's something I'm missing to get the IOperationProcessor to generate examples in the same way the rest of the examples are generated.

**Comment by RicoSuter** [comment]
Settings mist not be mutated within the processor, this leads to unexpected behavior. Change the settings when not in use by a generator.

**Comment by skylyn** [comment]
I only added the settings in the processor because of this problem and to show it in one block of code. With or without the SerializerSettings update in this processor the result is the same. All other generated response objects are camelCase, IOperationProcessor generated objects are PascalCase.

Note also that the MigrationRequiredProblem inherits the `Type` property from the parent object which is used in the 401 example in the screenshot, so there's no difference in the property itself.

If I add 
```
services.AddSwaggerDocument(settings =>
            {
                settings.SerializerSettings = new JsonSerializerSettings
                {
                    ContractResolver = new DefaultContractResolver()
                };
});
```
to my startup, all other generated objects will also  show in PascalCase, but adding the `CamelCasePropertyNamesContractResolver` explicitly is the same as not specifying `SerializerSettings` - IOperationProcessor generated objects are still PascalCase while everything else is camelCase.

**Comment by RicoSuter** [comment]
I think it uses the default serializer internally (not camel case) so probably its best if you assign the Value a JObject with the correctly named properties.
