### ISSUE TITLE
Support "scopes" config for ui.initOAuth()

### ISSUE THREAD

**Issue by ulrichb** [RicoSuter/NSwag#2922]
Swagger UI recently implemented automatic scopes selection for the "authorize" modal, see https://github.com/swagger-api/swagger-ui/pull/6037 (released with version 3.26.1).

Example:
```js
      ui.initOAuth({
        /* ... */
        scopeSeparator: " ",
        scopes: "openid profile email phone address",
        /* ... */
      })
```

Please expose this setting in the C# API (probably within `OAuth2ClientSettings`).

**Comment by justinbhopper** [comment]
@RicoSuter I believe this ticket can be closed now that support was added via #3608
