### ISSUE TITLE
ERROR: The system cannot find specified file

### ISSUE THREAD

**Issue by BeckhamL** [RicoSuter/NSwag#2926]
I am getting this error when I try to generate outputs. I have re-installed and installed with no success. Any suggestions on how to fix this?

![image](https://user-images.githubusercontent.com/17030246/85791262-899e7380-b6ff-11ea-8dae-2200dd198069.png)

**Comment by RicoSuter** [comment]
Please try to download the .zip archive and not use the msi installer, does it work then?

**Comment by BeckhamL** [comment]
It turns out my PC didn't have .NET core. Once I install .NET core 2.1 everything worked perfectly.
