### ISSUE TITLE
How to add JWT Bearer Authorization to Swagger and ASP.NET Core

### ISSUE THREAD

**Issue by maikebing** [RicoSuter/NSwag#2929]
![image](https://user-images.githubusercontent.com/3445167/86113565-fd73be00-bafb-11ea-99cf-4d3cfe9e2c47.png)

**Comment by KANekT** [comment]
@maikebing worked in https://github.com/jasontaylordev/CleanArchitecture

**Comment by maikebing** [comment]
Thank you so much.  @KANekT
