### ISSUE TITLE
CSharpClientGenerator does not render DateFormatConverter when using a ref to non-complex type

### ISSUE THREAD

**Issue by mhartigh** [RicoSuter/NSwag#2939]
Properties with type "string" and having format "date" are decorated with [Newtonsoft.Json.JsonConverter(typeof(DateFormatConverter))]. But for properties using $ref this does not work. Below the example of the described behaviour. I have tried this with v13.6.2.

Json:
`{
  "swagger": "2.0",
  "info": {
    "title": "Title for the test API",
    "description": "...",
    "version": "v2"
  },
  "basePath": "/test",
  "schemes": [
    "https"
  ],
  "externalDocs": {
    "url": "http://",
    "description": "...",
    "x-amf-title": "..."
  },
  "paths": {
    "/test": {
      "get": {
        "operationId": "test",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "x-amf-mediaType": "application/json",
            "schema": {
              "example": {},
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "Relatie": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "DatumVanaf": {
                        "$ref": "#/definitions/DatumVanaf"
                      },
                      "DatumTm": {
                        "description": "Just a date description",
                        "example": "2018-01-01",
                        "type": "string",
                        "format": "date"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "definitions": {
    "DatumVanaf": {
      "description": "Just some description",
      "example": "2014-01-03",
      "type": "string",
      "format": "date"
    }
  }
}`

Part of the output:

    `public partial class Relatie 
    {
        [Newtonsoft.Json.JsonProperty("DatumVanaf", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTimeOffset? DatumVanaf { get; set; }
    
        /// <summary>Just a date description</summary>
        [Newtonsoft.Json.JsonProperty("DatumTm", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTimeOffset? DatumTm { get; set; }
    
    
    }`

Is there a way to get this to work?

**Comment by prrrtpieptoet** [comment]
I ran into the same issue. I feel it may have something to do with the ref not being a complex type, but I'm not sure.

**Comment by RicoSuter** [comment]
> I feel it may have something to do with the ref not being a complex type, but I'm not sure

Yes, I think it's not correctly resolved because it is not complex... needs to be fixed in NJsonSchema

**Comment by prrrtpieptoet** [comment]
I found out a bit more: resolving only seems to fail when the referenced root level schema has a property "format": "date" and only when the referencing property and referenced schema have the same name.

Debugging the code, I see the property is resolved during the second invokation of base.VisitAsync(obj).ConfigureAwait(false);
on line 104 in NJsonSchema.JsonSchemaReferenceUtilities.VisitAsync(object obj).

In that method, the property is resolved on line 86 in NJsonSchema.Visitors.VisitAsync() by a recursive invokation of this method. 

I just didn't get to the part where resolving actually fails...yet.
