### ISSUE TITLE
C# client code returns default(T)! while result is not nullable

### ISSUE THREAD

**Issue by jeremyVignelles** [RicoSuter/NSwag#2944]
The implementation of NRT works great so far, but I've been bothered by the C# generated code :

```cs
public async System.Threading.Tasks.Task<ApiModel> GetModelAsync(System.Threading.CancellationToken cancellationToken)
{
    // --- snip ---
    try
    {
        using (var request_ = new System.Net.Http.HttpRequestMessage())
        {
            // --- snip ---    
            var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
            try
            {
                // --- snip ---
                if (status_ == "200") 
                {
                    var objectResponse_ = await ReadObjectResponseAsync<ApiModel>(response_, headers_).ConfigureAwait(false);
                    return objectResponse_.Object;
                }
                else
                if (status_ != "200" && status_ != "204")
                {
                    var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false); 
                    throw new ApiException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", (int)response_.StatusCode, responseData_, headers_, null);
                }
    
                return default(ApiModel)!; // <-------------- HERE
            }
            finally
            {
                if (response_ != null)
                    response_.Dispose();
            }
        }
    }
    finally
    {
    }
}
```

The corresponding API:

```cs
[HttpGet("Model")]
[ProducesResponseType(typeof(ApiModel), 200)]
public ApiModel GetModel()
{
    return new ApiModel
    {
        Message = "Hello world!"
    };
}
```

The method explicitely returns `default(T)!`, which might not be an expected value (`null` while the expected output is not nullable).
Moreover, 204 is not an expected return code in my case, so that code should never be triggered.

Should the `if`/`else if`... change?
Should the unexpected status code exception be thrown outside the `else if` or in a `else` ?

I think that all the expected cases must be handled in the previous `if`/`else if`, and that is something remains there, it should throw because it's unexpected, but I'm pretty sure that if it is done that way, there must be a hidden reason, burried into all the options combination, so please tell me :) 

Another remark lies here:

```cs
var objectResponse_ = await ReadObjectResponseAsync<ApiModel>(response_, headers_).ConfigureAwait(false);
return objectResponse_.Object;
```

Due to the use of generics in ReadObjectResponseAsync, there are places where `!` is used, because we can't know if `T` is nullable or not.
Should we use `return objectResponse_.Object ?? throw new ...;` instead, to make sure that no nullable references are returned ?

**Comment by RicoSuter** [comment]
> Should we use return objectResponse_.Object ?? throw new ...; instead

Seems a good idea, no?

Can you create a proposal PR?
