### ISSUE TITLE
Wrong OperationIDs with .NET Core 3.1 Project

### ISSUE THREAD

**Issue by AHorak** [RicoSuter/NSwag#2953]
This prefix should not be exported:
![grafik](https://user-images.githubusercontent.com/13638288/87295128-09e91500-c505-11ea-9553-f6f1c4a17953.png)

![grafik](https://user-images.githubusercontent.com/13638288/87295414-68ae8e80-c505-11ea-8dc7-44078f4a6c59.png)

How can this be avoided?

**Comment by AHorak** [comment]
I have tried the Attribute 
[OpenApiOperation("GetApiLevel")]
that **works**, but i don't want to set it for all opreations by hand.

**Comment by AHorak** [comment]
If the XML-Documentationm is read, this problem is not relevant any more

**Comment by RicoSuter** [comment]
> This prefix should not be exported:

This is on purpose, but you can change the operation id generator...
