### ISSUE TITLE
400 BadRequest is not a server side issue

### ISSUE THREAD

**Issue by phil-harmoniq** [RicoSuter/NSwag#2964]
I have created a controller that is decorated with `[SwaggerResponse(HttpStatusCode.BadRequest, typeof(RegisterResponse))]` but the generated code states that 400 is a server-side error:

```
else
if (status_ == "400") 
{
    var objectResponse_ = await ReadObjectResponseAsync<RegisterResponse>(response_, headers_).ConfigureAwait(false);
    throw new ApiException<RegisterResponse>("A server side error occurred.", (int)response_.StatusCode, objectResponse_.Text, headers_, objectResponse_.Object, null);
}
```

**Comment by jeremyVignelles** [comment]
Setting the default message depending on the response code doesn't seem easy to do, but you should be able to put xml comments on your method :

`<response code="400">Bad Request</response>`

See #1746

**Comment by phil-harmoniq** [comment]
That doesn't seem to have any affect. I tried some of the ones of the suggestions and still don't know what I'm doing wrong. Here is what I currently have:

```
/// <response code="400">Bad Request</response>
[AllowAnonymous]
[HttpPost("register")]
[ProducesResponseType(typeof(RegisterResponse), (int)HttpStatusCode.OK)]
[ProducesResponseType(typeof(RegisterResponse), (int)HttpStatusCode.BadRequest)]
public async Task<ActionResult<RegisterResponse>> Register(
    [FromBody] RegisterRequest request)
{
    // ...
}
```

**Comment by phil-harmoniq** [comment]
Nevermind, I noticed I forgot to add `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to my `.csproj`. Now I can set my own messages. However I still feel like 4** errors should say its a client side error by default
