### ISSUE TITLE
Custom JsonConverters missing in generation

### ISSUE THREAD

**Issue by Vizzr** [RicoSuter/NSwag#2969]
Hi,

We expose our generated client to another layer that uses the generated models to return to a client.
Therefore we need our custom JsonConverters to be exposed in the generated client.

I added the Custom Converter in the jsonConverters, but that did not help.

```
      "jsonConverters": [
        "Newtonsoft.Json.Converters.StringEnumConverter",
        "*Namespace*.IsoDateConverter"
      ],
```

The following example describes the StringEnumConverter (which already worked by default without defining it in jsonConverters).
In our model:
```
        [JsonConverter(typeof(StringEnumConverter))]
        public WebhookRole Role { get; set; }
```
generates to:
```
        [Newtonsoft.Json.JsonProperty("role", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public WebhookRole Role { get; set; }
```
_______
However, our custom JsonConverter does not work.
In our model:
```
        [JsonConverter(typeof(*Namespace*.IsoDateConverter))]
        public DateTime DateOfBirth { get; set; }
```
generates to:
```
        [Newtonsoft.Json.JsonProperty("dateOfBirth", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime DateOfBirth { get; set; }
```

In the example above, you can see that there is no `[Newtonsoft.Json.JsonConverter(typeof(*Namespace*.IsoDateConverter))]`.

We do see that the Custom Converter was added to the SerializerSettings:
```
        private Newtonsoft.Json.JsonSerializerSettings CreateSerializerSettings()
        {
            var settings = new Newtonsoft.Json.JsonSerializerSettings { Converters = new Newtonsoft.Json.JsonConverter[] { new Newtonsoft.Json.Converters.StringEnumConverter(), new *Namespace*.IsoDateConverter() } };
            UpdateJsonSerializerSettings(settings);
            return settings;
        }
```

How do I solve this issue so that our model has the *Namespace*.IsoDateConverter in the generated client code?

Thanks in advance.

**Comment by RicoSuter** [comment]
NSwag translates your code into an OpenAPI spec - it cannot understand the procedural nature of custom converters - so you need to manually transform the spec so that it correctly describes what your IsoDateConverter is doing... and then the generators need to produce the right code based on the spec - independent of how you actually implemented it in C#.

**Comment by sagar-sk15** [comment]
@Vizzr  Did you solve the issue? if yes, can you shade some lights?
