### ISSUE TITLE
How to ignore controller being generated?

### ISSUE THREAD

**Issue by francisminu** [RicoSuter/NSwag#2971]
Hi,

We make use of Nswag to generate the controller file - with controller class, controller interface and the request and response models. Is there any way we can avoid the controller class and interface creation and have just the request and response models in the generated class?

-Thanks in advance!

**Comment by jeremyVignelles** [comment]
As far as I know, there's no way to do that yet, even in the client classes.

**Comment by francisminu** [comment]
@jeremyVignelles  I could see that in the Client there is an option to not chose 'Generate Client CLasses' and that will not create the controller and just creates the request and response DTo's. @RicoSuter any inputs?

**Comment by jeremyVignelles** [comment]
Then why are you using the controller generator if you don't generate any controller ? Just generate a client without the client class with that option then

**Comment by francisminu** [comment]
I hadn't worked earlier with the Client Generation and was expecting a lot more details to be created along with Models. I was able to get just the request and response DTO's created with the ClientGeneration. Thank you for your inputs, that is what led me to check  the Client Generation in detail.
