### ISSUE TITLE
[Generated CSharp Clients]The body of POST request is empty

### ISSUE THREAD

**Issue by jack2gs** [RicoSuter/NSwag#2976]
Hi,

When the generated CSharp clients are used, the POST actions didn't work. Inside the controller, the the body of the request is always empty. Any idea on this? Are there extra settings that should be done?

Thanks,
Jack

**Source code:** https://github.com/jack2gs/NSwagDemo

.Net Core: **3.1**
Routing: Attribute based Routing. Seems alright, the action method in the controller can be always invoked.

The package used:
```xml
 <PackageReference Include="NSwag.MSBuild" Version="13.6.2">
```

**Comment by jeremyVignelles** [comment]
Please share a sample code (minimal project, hosted on github) so that we can try to see what's going on.
Obviously if any POST request resulted in a broken C# clients. Others would have noticed, so we need to find what's specific to your use case.

**Comment by jack2gs** [comment]
Hi @jeremyVignelles , 

Thanks for replying! :)

The sample code: https://github.com/jack2gs/NSwagDemo. 

Thanks,
Jack

**Comment by jack2gs** [comment]
Sorry, found the issue. The contract class should have 'set' methods for properties. Close the issue now. Thanks!
