### ISSUE TITLE
Understanding the need for SetCompatibilityVersion

### ISSUE THREAD

**Issue by xantari** [RicoSuter/NSwag#2997]
In the following documentation: https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware

It states the following:

_If you are using .NET Core >= v2.1 with new API Explorer based generator, you may need to set the CompatibilityVersion_

What issue is this trying to solve? When is it required? I seem to run just fine without specifying this.

**Comment by jeremyVignelles** [comment]
This is only relevant for .net core 2.x apps, see : https://docs.microsoft.com/en-us/aspnet/core/mvc/compatibility-version?view=aspnetcore-3.1

**Comment by xantari** [comment]
OK, so technically the documentation should be updated to say this instead:

If you are using .NET Core >= v2.1 and < 3.0 with new API Explorer based generator, you may need to set the CompatibilityVersion

**Comment by jeremyVignelles** [comment]
Indeed, but the wiki is open, you could edit that yourself ;)

**Comment by xantari** [comment]
Done :-)
