### ISSUE TITLE
Can we reference the NJsonSchema project as a git submodule for easier debugging?

### ISSUE THREAD

**Issue by kendallb** [RicoSuter/NSwag#3001]
Currently the NSwag project uses NJsonSchema as a set of nuget pacakages, but the problem with that is it makes it much harder to develop UI code and corresponding code generation code as it's split up. In order for me to debug and fix the oneOf issues for our client generation, I had to manually remove all the NJsonSchema nuget packages from the project and then reference my versions of NJsonSchema directly so they would be compiled and linked into the project for easier debugging.

I believe it should be possible to reference the NJsonSchema as a project within the NSwag git project, such that it's code would get pulled down into a sub-directory under the main NSwag code tree, then those projects can be reference directly and not via nuget packages?

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by jeremyVignelles** [comment]
Having NJS as a submodule would make it harder to release NJS independently from NSwag.

The solution that Rico uses is not perfect, but is quite convenient to work with for that use case :
https://github.com/RicoSuter/dnt#switch-to-projects

We need to document the developer workflow somewhere...

**Comment by kendallb** [comment]
I fail to see why it would make it harder to release NJS independently from NSwag? It's a sub-module, which means it still has it's own full git repo, but that git repo gets pulled down under the NSwag code tree so you can rely on it being in a known location for the project references.

The caveat, and perhaps what you are thinking is that NSwag would be building against whatever is current in NJS, rather than the latest nuget package releases?

**Comment by jeremyVignelles** [comment]
If it is a project reference instead of a package reference, the nuget packaging will try to build a package for NJS as well. If you publish only the NSwag part on NuGet, I'm not sure about what would happen for the NJS dependency.

I think that it could be error-prone, and I'm happy with the current solution (switch-to-projects). You only need to clone the projects side-by-side and it avoids the complexity of managing (nested (there are Namotion projects) ) submodules

**Comment by kendallb** [comment]
Ok fair enough. I manually did what Rick's DNT tool does, so I might take a look at using that in the future :)
