### ISSUE TITLE
Upgrade Guide?

### ISSUE THREAD

**Issue by kylekarpack** [RicoSuter/NSwag#3022]
I am looking to upgrade our NSwag from 8.6.0 to 13.x.x due to performance issues in version 8. Unfortunately, our API is a little scattered and includes WebAPI controllers and models for which we would like to generate Swagger and TypeScript clients and classes. Version 8.6.0 somehow picked all these up, but version 13.7.0 does not appear to do so.

The command I am running is:
```
nswag webapi2swagger /assembly:"./bin/Web.dll" /output:swagger.json /DefaultUrlTemplate:"api/{controller}/{action}"
```
When using version 8.6.0, this generates about 25,000 lines in swagger.json and includes everything that we need. When using version 13.7.0, this only generates about 9,000 lines. It looks like maybe version 8 was able to resolve entities that reference each other while version 13 does not.

Is there a way to complete this upgrade without rewriting lots of code? Is the omission of self-referencing entities a known issue or expected behavior?

**Comment by kylekarpack** [comment]
Here is a minimal repro of the issue. In this, after `yarn install` and building the project, if you execute:
```
yarn nswag
```
It will generate two different swagger outputs, `swagger8.json` and `swagger13.json`. The former includes the `Business` in the generated swagger, but the latter does not. I would expect the `Business` to be included since it is a part of the `Request` object that is in the response for the `public Request Get()` API.

Solution:
[WebApplication1.zip](https://github.com/RicoSuter/NSwag/files/5104957/WebApplication1.zip)

Output files:
[output.zip](https://github.com/RicoSuter/NSwag/files/5104966/output.zip)

**Comment by kylekarpack** [comment]
I think I have found the issue here. NSwag v8.6.0 ignores the `[JsonIgnore]` attribute, while NSwag 13.7.0 respects it. Is there a way to use `[JsonIgnore]` to prevent serializing a property, while still including it in the Swagger and generated TypeScript?

**Comment by jeremyVignelles** [comment]
I don't think so. The code that is generated is the code that needs to be sent to the server.

Why would you include a property that is ignored in the serialization process anyway?

**Comment by kylekarpack** [comment]
They're not included in the serialization process, but we have a lot of legacy TypeScript code that is using these generated objects, since version 8.6.0 generated them.

**Comment by RicoSuter** [comment]
I think there is no easy way to fix that from 8 -> 13 is quite a big step with lots of breaking changes (major versions).

**Comment by kylekarpack** [comment]
Thank you for taking a look. Please feel free to close this ticket if no upgrade guide is planned.

**Comment by RicoSuter** [comment]
If the diff is that big and stuff is missing then there might be a bigger underlying problem or you relied on some bug or wrong spec parsing which has been fixed. Do you have any specifics?

**Comment by kylekarpack** [comment]
I think there are variety of ways that we relied on bugs and incorrect spec parsing, the biggest single one being https://github.com/RicoSuter/NSwag/issues/3022#issuecomment-677897205. We also have a strange inheritance structure for our controllers that 8.6.0 was able to figure out properly, but 13.x.x thinks contains duplicate routes.

Our TypeScript code is also tied to the 8.6.0 AngularJS typescript clients, and we have hundreds of clients created without injecting the `$q` service. I could not figure out a way to get the 13.x.x clients to look like the 8.6.0 ones, so I think the jump of several major versions is just going to be too far for us to go. Unfortunately, the 8.6.0 version is extremely slow, so we're stuck with this as a part of our build for the time being.

**Comment by bbarry** [comment]
I would strongly recommend taking it 1 major version at a time at least.

The first version of the change log was added with version 10 (3+ years ago now). 

9.0 breaking changes is here: https://github.com/RicoSuter/NSwag/releases/tag/NSwag-Build-781

10-13 are linked in the change log https://github.com/RicoSuter/NSwag/blob/master/CHANGELOG.md

**Comment by RicoSuter** [comment]
You should be able to register a custom contract resolver and include these properties. But probably this would be just the beginning..
