### ISSUE TITLE
.NET 5 NSwagExe MSBuild Property

### ISSUE THREAD

**Issue by thenadz** [RicoSuter/NSwag#3026]
We're working on preparing our codebase for .NET 5 release in November. Is there a planned naming convention for NSwagExe MSBuild properties following .NET 5 removing "Core"/"Framework"? Maybe `NSwagExe_Net5`?

**Comment by RicoSuter** [comment]
Didnt think about this yet, but `NSwagExe_Net5` make sense.

**Comment by MarkFl12** [comment]
Now that that the release candidate is out, is there any news on support for .NET 5?

**Comment by RicoSuter** [comment]
Can't you reference and use the current version of NSwag.AspNetCore?

**Comment by MarkFl12** [comment]
I'm using NSwag.MSBuild to generate a client for my API and it's giving me
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```
when i try and build.

**Comment by thenadz** [comment]
> Can't you reference and use the current version of NSwag.AspNetCore?

OpenAPI generation works just fine in .NET 5 build, VS 2019 preview using NSwagExe_Core31. Using just-released VS preview and nightly build of dotnet SDK, RC2 preview.

**Comment by MarkFl12** [comment]
Is that different from RC1? What command are you using to make that work?

**Comment by RicoSuter** [comment]
I would expect that NSwag.AspNetCore still works as it “hosted” by a .net 5 process, however NSwag.MSBuild might fail because it’s a .net core 3.1 process loading .net 5 dlls/projects

**Comment by thenadz** [comment]
It's different from RC1 in the sense that it's a RC2 nightly build. I would not expect any of those differences to be relevant to NSwag behavior.

```
<Target Name="GenerateSwaggerDoc" AfterTargets="Build" Condition=" '$(RuntimeIdentifier)' != 'linux-arm64' ">
  <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
  <Exec Command="$(NSwagExe_Core31) run nswag.json /variables:Configuration=$(Configuration)" />
</Target>
```

**Comment by thenadz** [comment]
Yeah -- that is an interesting point. Depending on the assemblies being loaded and their target arch you could run into something funny.

**Comment by RicoSuter** [comment]
> I would expect that NSwag.AspNetCore still works as it is “hosted” by a .net 5 process

Of course only if they didnt break an api which nswag relies on (eg api explorer). Maybe there is also more metadata we can/should support. But for that we’d need to check the changes

**Comment by vip32** [comment]
not sure when we can expect the new NSwagExe_Net5, any update?

**Comment by softwaretirol** [comment]
Any idea when the .NET 5 support will be given? Can we support it?... Would like to create a PR for that issue

**Comment by ViRuSTriNiTy** [comment]
@RicoSuter Please have a look at the PR. This is imho important as many projects using NSwag want to make the change to .NET 5. Thank you in advance.

**Comment by phil-harmoniq** [comment]
Updating to the newest version of Visual Studio breaks existing projects that use `$(NSwagExe_Core31)`:

.csproj
```
  <Target Name="NSwag" BeforeTargets="PrepareForBuild" Condition="'$(GenerateCode)'=='True' And '$(Configuration)'!='Release' ">
    <Exec Command="$(NSwagExe_Core31) run nswag.json /variables:Configuration=$(Configuration)" />
  </Target>
```

build output
```
error MSB3073: The command " run nswag.json /variables:Configuration=Debug" exited with code 9009
```

**Comment by RicoSuter** [comment]
Why is that? Because its built by net 50 or because you just installed net 50?

**Comment by phil-harmoniq** [comment]
It seems the newest version of Visual Studio (16.8.0) defaults to using the .NET 5.0 SDK even if you are using a `netcoreapp3.1` project.

**Comment by thenadz** [comment]
@phil-harmoniq VS default behavior is to use the latest SDK available on the system & VS 16.8 to the best of my knowledge cannot be installed without .NET 5 so makes sense. You can override the SDK used by VS — don’t recall off hand how, but should be easily googled.

**Comment by RicoSuter** [comment]
NSwag v13.9.0 released with .NET 5.0 support - please test and report any problems.

**Comment by vocko** [comment]
Seems to working fine, managed to build in VS 16.8.1, console using `dotnet build -f net5.0` and also in docker image `mcr.microsoft.com/dotnet/sdk:5.0`

Pasting this for reference, the dll name was giving me a hard time `NSwagExe_Net50` vs `NSwagExe_Net5` mentioned above.
```
<Target Name="NSwag" AfterTargets="Build">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Net50) run nswag.json /variables:Configuration=$(Configuration) /runtime:Net50" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```

Thanks guys for a quick upgrade.

**Comment by Kobus-Smit** [comment]
Same problem as @phil-harmoniq  here:

VS 2019 16.8.3
TargetFramework: netcoreapp3.1

![image](https://user-images.githubusercontent.com/11263864/103530389-6f79f500-4edb-11eb-9aa3-4e287021a37b.png)

It seems `$(NSwagExe_Core31)` is empty.

I've tried the `global.json` workaround (in the project's root dir) but that did not work for me.
![image](https://user-images.githubusercontent.com/11263864/103530181-18742000-4edb-11eb-896b-0292279dfe1e.png)

Command line works:
![image](https://user-images.githubusercontent.com/11263864/103530541-b962db00-4edb-11eb-8570-b8cdad814a12.png)

Any ideas @RicoSuter ?

**Comment by jeremyVignelles** [comment]
@Kobus-Smit Did you install the NSwag.MSBuild nuget package?

**Comment by Kobus-Smit** [comment]
Yes I did.

**Comment by jeremyVignelles** [comment]
Then please open a new issue with your whole csproj. This issue is about .net 5

**Comment by Kobus-Smit** [comment]
Is it not related to Phil's:

Updating to the newest version of Visual Studio breaks existing projects
that use $(NSwagExe_Core31) even if you never changed your target framework

It seems the newest version of Visual Studio (16.8.0) includes .NET 5.0 SDK
and defaults to it even if you are using a netcoreapp3.1 project. I did not
install .NET 5 manually. However, I noticed if I try to build the project
using using the CLI (dotnet build) it seems to work fine.

**Comment by RicoSuter** [comment]
Did you try $(NSwagExe_Net50) with your .net core 3.1 proj?

**Comment by Kobus-Smit** [comment]
My issue was resolved in https://github.com/RicoSuter/NSwag/issues/3240. Somehow had an outdated `NSwag.MSBuild` PackageReference.

**Comment by RicoSuter** [comment]
Ok, thanks for the heads up. @thenadz can we close the issue?

**Comment by thenadz** [comment]
@RicoSuter Yep -- looks good to me! Thanks!
