### ISSUE TITLE
Can't compile generated code after upgrade to 13.7 from 13.5

### ISSUE THREAD

**Issue by joshmouch** [RicoSuter/NSwag#3029]
After upgrading from 13.5 to 13.7, the generated code won't compile.  Here is an example of the bad code:

```
if (status_ == "401") 
                        {
                            string responseText_ = ( response_.Content == null ) ? string.Empty : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            >>>>> throw new ApiException("Unauthorized", status_, responseText_, headers_, null);  <<<< ERROR IS ON THIS LINE
                        }
```

And the error is:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'string' to 'int'

```

As a workaround, I did a search and replace and replaced `, status_` with `, (int)response_.StatusCode,`

**Comment by jeremyVignelles** [comment]
Hi,

Do you have your own template? Your own exception class? It seems that the generated exception class [here](https://github.com/RicoSuter/NSwag/blob/d37fa821a555012dbc6af33e559414c351d8b3f1/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid#L189) has the valid parameters.

For the record, in 13.7, the status_ variable is now treated as an `int`, while it was a string before.

**Comment by joshmouch** [comment]
@jeremyVignelles ,

No, but I didn't realize that Client.Class.liquid was overwritten.  My mistake.  Thanks!
