### ISSUE TITLE
Please add functionality to restrict "aspNetCoreToOpenApi" to a list of specified ControllerNames

### ISSUE THREAD

**Issue by vandermg** [RicoSuter/NSwag#3033]
Would you be able to add functionality to the "aspNetCoreToOpenApi" document generator to restrict generation to a supplied list of Controller Names, similar to what is available for the "webApiToOpenApi" document generator?

**Comment by jeremyVignelles** [comment]
Please see [this answer](https://github.com/RicoSuter/NSwag/issues/2765#issuecomment-660072902)

**Comment by vandermg** [comment]
Awesome. Thank you!  I will give it a try.
