### ISSUE TITLE
Add autofocus for input field generated by OpenApiSecurityScheme

### ISSUE THREAD

**Issue by Saibamen** [RicoSuter/NSwag#3040]
Please add `autofocus` for input field generated by `OpenApiSecurityScheme` to focus input after clicking `Authorize` button

**Comment by RicoSuter** [comment]
Isnt this a request for the Swagger UI project?

**Comment by Saibamen** [comment]
This project?
https://github.com/swagger-api/swagger-ui

**Comment by RicoSuter** [comment]
Yep

**Comment by Saibamen** [comment]
https://github.com/swagger-api/swagger-ui/issues/6395

**Comment by Saibamen** [comment]
PR https://github.com/swagger-api/swagger-ui/pull/6483 released in Swagger UI v3.35.2, but I forgott to add `autoFocus` to two more forms...

Added in https://github.com/swagger-api/swagger-ui/pull/6527, but not yet released

**Comment by Saibamen** [comment]
3.36.0 released: https://github.com/swagger-api/swagger-ui/releases/tag/v3.36.0

**Comment by Saibamen** [comment]
@RicoSuter: When new version of NSwag with latest SwaggerUI will be released?
