### ISSUE TITLE
All type are FileResponse!

### ISSUE THREAD

**Issue by iPazooki** [RicoSuter/NSwag#3054]
After updating NSwag to the latest version (v13.7.1.0) it generates all types as `FileResponse`

![FileResponse](https://user-images.githubusercontent.com/1321544/92994489-7d51d780-f4f2-11ea-9db5-32c867ca4676.jpg)

**Comment by g4mb10r** [comment]
MAJOR ISSUE!  PLEASE RESOLVE!!!!

**Comment by RicoSuter** [comment]
v13.7.2

**Comment by onionhammer** [comment]
Thanks for the quick turnaround on this :)
