### ISSUE TITLE
Generate models with action uri and method type?

### ISSUE THREAD

**Issue by bigdnf** [RicoSuter/NSwag#3060]
I’m playing with generating c# client and models with nswag and I’m wonder is it possible to generate models with additional uri and method type property?
I’m thinking about having one generic api client that have model as input – read all data from this model (uri and method type as not serializable) and send request. With this I could only generate models and have rest in my code. Is this something I could do (maybe with some custom code) or this is not possible?

**Comment by RicoSuter** [comment]
Maybe you can do that by customizing the Class.liquid root template with your completely own implementation producing this.

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/wiki/Templates

**Comment by bigdnf** [comment]
Thanks I will go this route

**Comment by RicoSuter** [comment]
Probably you can overwrite Client.Class.liquid like this

```
your method
{% template %}
```
