### ISSUE TITLE
OpenApiBodyParameterAttribute is ignored in WebApi projects

### ISSUE THREAD

**Issue by Basssiiie** [RicoSuter/NSwag#3068]
Hello, right now the [OpenApiBodyParameterAttribute](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Annotations/OpenApiBodyParameterAttribute.cs) for specifying request body MIME-type is recognized by the [OperationParameterProcessor](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation.AspNetCore/Processors/OperationParameterProcessor.cs) for ASP.NET Core but ignored/not implemented by the [OperationParameterProcessor](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Generation.WebApi/Processors/OperationParameterProcessor.cs) for WebApi. 

Is this intended behaviour or an oversight? Took me a while to figure out why this attribute was not having any effect in my ASP.NET Framework WebApi project.

Thanks for the great work!

**Comment by RicoSuter** [comment]
> Is this intended behaviour or an oversight?

It's more an oversight, or better, the ASP.NET (legacy) part is still in the project but we will not put much more effort in improving and fixing it - you should migrate and use ASP.NET Core at this point...

**Comment by Basssiiie** [comment]
@RicoSuter Thank you for your reply. I'm aware of ASP.NET Core and all our new projects are on ASP.NET Core, unfortunately legacy ASP.NET projects are not gonna go away any time soon... :(

I hope there is still time for this feature, since I could not find another way to specify different request MIME-types on specific endpoints (in my case `multipart/form-data` on a POST request), but I would understand as well if it is not worth it anymore.
