### ISSUE TITLE
Example Request Value for POST not displayed correctly

### ISSUE THREAD

**Issue by kisalay19** [RicoSuter/NSwag#3069]
I have an API using **NSwag** swagger library where I have implemented a **POST** method `public ActionResult<UpdateResponse> UpdateNumber([FromBody] NumberUpdateRequest numberUpdateRequest)`. While viewing the same in the Swagger page the Example request body is shown as below :

```csharp
{
  "transactionId": "string",
  "subscriberId": "string",
  "customerId": [
    0
  ]
}
```

When I update my library to point to **Swashbuckle**, the example request body is Swagger UI is displayed as expected below :

```csharp
{
  "transactionId": "string",
  "subscriberId": "string",
  "customerId": [
    0
  ],
  "customerFilters": {
    "addressId": "string",
    "addressStatus": "string"
  }
}
```

My Request model for **POST** method is as below :

```csharp
[Serializable]
    public class NumberUpdateRequest
    {
        public string TransactionId { get; set; }
        public string SubscriberId { get; set; }
        public List<decimal> CustomerId{ get; set; }
        public CustomerFilter CustomerFilters{ get; set; }

    }

    [DataContract]
    public class CustomerFilter
    {
        [DataMember]
        public string AddressId { get; set; }
        [DataMember]
        public string AddressStatus { get; set; }
    }
```

Any idea what is missing in **NSwag** which is not showing the expected behavior as in **Swashbuckle**?

**Comment by RicoSuter** [comment]
Can you post the generated spec? I'm pretty sure the CustomerFilter is missing...

The question is why. Are you using the AspNetCore generator? If yes it uses Newtonsoft's contract resolver to reflect the properties and then probably the datacontract stuff is not working as expected and at runtime it would also not serialize the CustomerFilter...

**Comment by kisalay19** [comment]
@RicoSuter I am pastign below parts of generated spec..

``csharp
...
"/api/CustomerAsset": {
      "post": {
        "tags": [
          "CustomerAsset"
        ],
        "operationId": "CustomerAsset_UpdateNumber",
...
"requestBody": {
          "x-name": "numberUpdateRequest",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NumberUpdateRequest"
              }
            }
          },
          "required": true,
          "x-position": 1
        },
...
"components": {
    "schemas": {
    ...
    "NumberUpdateRequest": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "transactionId": {
            "type": "string",
            "nullable": true
          },
          "subscriberId": {
            "type": "string",
            "nullable": true
          },
          "customerId": {
            "type": "array",
            "nullable": true,
            "items": {
              "type": "number",
              "format": "decimal"
            }
          },
          "customerFilters": {
            "nullable": true,
            "oneOf": [
              {
                "$ref": "#/components/schemas/CustomerFilter"
              }
            ]
          }
        }
      },
      "CustomerFilter": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "addressId": {
            "type": "string",
            "nullable": true
          },
          "addressStatus": {
            "type": "string",
            "nullable": true
          }
        }
      }
    }
```

As you see in the spec the schema is being read correctly. Also have a look below into my `Startup.cs` :

```csharp
...
services.AddMvc(options =>
            {
                options.EnableEndpointRouting = false;  
            }).SetCompatibilityVersion(CompatibilityVersion.Latest)
           .AddNewtonsoftJson(options =>
           {
               options.SerializerSettings.Converters.Add(new StringEnumConverter());
               options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
           });
...
```

Attached the snap too.

![Untitled](https://user-images.githubusercontent.com/32225001/94549172-74416400-026f-11eb-9231-60fd42cdf4ba.png)

**Comment by RicoSuter** [comment]
Probably setting AllowReferencesWithProperties to true would fix this: 

See https://github.com/RicoSuter/NSwag/issues/2986

**Comment by kisalay19** [comment]
Great @RicoSuter that worked.. Thanks 👍
