### ISSUE TITLE
This is a awesome tool but I guess it will be better if BaseUrl came from constructor not from some internal variable

### ISSUE THREAD

**Issue by PMoneda** [RicoSuter/NSwag#3074]

**Comment by jeremyVignelles** [comment]
I think it does, what do you need?
Please do not put all your issue in the title, and be more precise about what you're trying to achieve and with which options

**Comment by RicoSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/94377993-f9b8fd00-0125-11eb-89bd-db94c918dd10.png)

**Comment by PMoneda** [comment]
Thank you @RicoSuter my bad to don't read all interface haha
