### ISSUE TITLE
DayJS integration - generated Typescript Client is missing import statement

### ISSUE THREAD

**Issue by edesr1988** [RicoSuter/NSwag#3083]
When selecting DayJS as DateTimeType the client is generated but missing the import statement for dayjs. The dayjs types are used correctly in the rest of the generated file.

It seems like the UseDayJS property in TypescriptFrameworkModel does not have the correct value. @RicoSuter maybe you can give a hint where to have a look into?

**Comment by RicoSuter** [comment]
Should be fixed but not released, right?
https://github.com/RicoSuter/NSwag/pull/3081
