### ISSUE TITLE
Inheritance in schema generation from interfaces

### ISSUE THREAD

**Issue by plettb** [RicoSuter/NSwag#3085]
I'm a relative newbie to the world of Swagger/OpenApi, so please bear with me.  This feels like a newbie question, but....

I try to follow best practices when writing my code, and that has me writing controllers that return, for example, collections of interfaces.  Here's an example:
```csharp
    public ActionResult<IEnumerable<IMyClass>> GetObjects()
```

However, when I do that, only the properties of the specific interface make it into the schema, NOT those inherited from other interfaces.  So, in the above example, I have the following:
```csharp
    public interface IMyClass : IBase
    {
        string Name { get; }
    }
```
```csharp
    public interface IBase
    {
        int Id { get; }
    }
```
Sadly, the schema that gets generated looks like this.  Note how it's missing the "Id" property.
```json
  "components": {
    "schemas": {
      "IMyClass": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "name": {
            "type": "string",
            "nullable": true
          }
        }
      }
    }
  }
```

Is there any way to solve this, apart from returning the class rather than the interface?

Thanks a lot!

**Comment by jeremyVignelles** [comment]
Not sure about which best practice you're talking about, but when dealing with APIs (and serialization/deserialization in general), I thin it's better to only use concrete type DTO (objects that are created only for the purpose of being serailized/deserialized)

I'm really looking forward C#9 records for that.

IMHO, inheritance does only make things harder when deserializing.

In your case, if you specify an interface as a return type, you will still serialize the whole concrete object, including properties that were not in the interface, because that's how json serializers work.

**Comment by plettb** [comment]
> Not sure about which best practice you're talking about, but when dealing with APIs (and serialization/deserialization in general), I thin it's better to only use concrete type DTO (objects that are created only for the purpose of being serailized/deserialized)
> 
> I'm really looking forward C#9 records for that.
> 
> IMHO, inheritance does only make things harder when deserializing.
> 
> In your case, if you specify an interface as a return type, you will still serialize the whole concrete object, including properties that were not in the interface, because that's how json serializers work.

As a rule, returning interfaces from methods is better in that it doesn't expose all the innards of an object.  Now when it comes to serialization, you do have a point because as you noted, serialization exposes everything anyway.  So, I suppose at the end of the day it becomes a bit philosophical.

If inheritance of interfaces can't be handled by Swagger/OpenAPI, then I'll certainly move to using DTOs exclusively.  However I'd still much prefer if NSwag could handle interfaces regardless.
