### ISSUE TITLE
Parse Yaml in code?

### ISSUE THREAD

**Issue by nojaf** [RicoSuter/NSwag#3087]
Hello, we are currently using NSwag Studio to generate C# Controllers based on our open api yaml file.
This works like a charm and I'm very grateful for this tool!

I would also want to generate Azure ARM templates based on my Yaml file and I'm currently hacking the liquid templates a bit to achieve this. It works but I was wondering if it is possible to just parse the yaml file and take it from there with maybe some other templating engine?
Would this be possible? Is the parsing engine also available on NuGet?

**Comment by RicoSuter** [comment]
I think you're looking for `OpenApiYamlDocument.FromYamlAsync` (NSwag.Core.Yaml)?

https://apimundo.com/organizations/nuget-org/nuget-feeds/public/packages/NSwag.Core.Yaml/versions/latest?tab=types&type=NSwag.OpenApiYamlDocument

**Comment by nojaf** [comment]
Many thanks, exactly what I'm looking for.
