### ISSUE TITLE
INotifyPropertyChanged and inheritance

### ISSUE THREAD

**Issue by codingdna2** [RicoSuter/NSwag#3093]
Hi, 
I'm having issues with DTO's generated with Class Style = 'INPC' and inheritance.

I found out that every entity has it's own event:
`public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;`
and when I change a property of a base class, the method `RaisePropertyChanged` find the event null (not subscribed by anyone), while the subscriber in fact had subscribed the derived class event.

```c#
protected virtual void RaisePropertyChanged([System.Runtime.CompilerServices.CallerMemberName] string propertyName = null)
{
    var handler = PropertyChanged;
    if (handler != null) 
        handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
}
```

I guess the event should be `virtual` or (as for `Prism`) included in a base class.
Thanks in advance for any help,
D.

EDIT: As a workaround, I've switched to `Prism`.

**Comment by RicoSuter** [comment]
We’d need to exclude this code in case there’s a base class

**Comment by codingdna2** [comment]
I've tried to look at source code but it's kind of overwhelming. 
If I understand well the correct repo is `NJsonSchema` and the template to modify is `Class.Inheritance.liquid`.

This is as it's now:
```
{% if RenderInpc -%}
{% if HasInheritance %}: {{ BaseClassName }}, System.ComponentModel.INotifyPropertyChanged{% else %}: System.ComponentModel.INotifyPropertyChanged{% endif %}
{% elsif RenderPrism -%}
{% if HasInheritance %}: {{ BaseClassName }}{% else %}: Prism.Mvvm.BindableBase{% endif %}
{% else -%}
{% if HasInheritance %}: {{ BaseClassName }}{% endif %}
{% endif -%}
```
and if I'm not wrong, this is how it should be:
```
{% if RenderInpc -%}
{% if HasInheritance %}: {{ BaseClassName }}{% else %}: System.ComponentModel.INotifyPropertyChanged{% endif %}
{% elsif RenderPrism -%}
{% if HasInheritance %}: {{ BaseClassName }}{% else %}: Prism.Mvvm.BindableBase{% endif %}
{% else -%}
{% if HasInheritance %}: {{ BaseClassName }}{% endif %}
{% endif -%}
```

**Comment by RicoSuter** [comment]
That would be my expected change yes, can you create a PR?

**Comment by RicoSuter** [comment]
I wonder why this has not been reported by anyone yet...

**Comment by codingdna2** [comment]
Sure but I'm still unsure about liquid syntax...

**Comment by RicoSuter** [comment]
I'd use `{% if HasInheritance == false %}`

**Comment by codingdna2** [comment]
Thanks! What's the minus sign at the end of some statements? `-%}`

**Comment by RicoSuter** [comment]
i think this defines whether the following new line is rendered or not...

**Comment by codingdna2** [comment]
I'm not sure how to test it correctly without changing all the references in my project... I've run the availables test but I guess I should write one?

**Comment by RicoSuter** [comment]
I'd just write a synthetic test checking that the output in NJS is correct... PR looks good to me.
