### ISSUE TITLE
Open Api Documentation in yaml

### ISSUE THREAD

**Issue by Decoster** [RicoSuter/NSwag#3104]
Hi,
Is there a way to generate the open api documentation in yaml instead of json (link to the json available in the ui)  ?
If not, would you consider the option to support it?
Thanks,

**Comment by MihaMarkic** [comment]
I'm looking for it as well, since a code generator I would use is based on yaml files.

**Comment by MihaMarkic** [comment]
Looks like there is already an issue for it #2331

**Comment by RicoSuter** [comment]
app.UseOpenApi(p => p.Path = "/swagger/{documentName}/swagger.yaml");
            app.UseSwaggerUi3(p => p.DocumentPath = "/swagger/{documentName}/swagger.yaml");

Next version.
