### ISSUE TITLE
Typescript Client - generates weird interface when type: string and enum properties are present.

### ISSUE THREAD

**Issue by danyhoron** [RicoSuter/NSwag#3120]
The swagger was generated using [hapi-swagger](https://github.com/glennjones/hapi-swagger).

Here's the `"swagger": "2.0",` definition:

```json
"ChangeUserPasswordPayload": {
  "type": "object",
  "properties": {
    "username": {
      "type": "string"
    },
    "password": {
      "type": "string"
    },
    "passwordConfirmation": {
      "type": "string",
      "enum": [
        {
          "ref": {
            "path": [
              "password"
            ]
          }
        }
      ]
    },
    "oldPassword": {
      "type": "string"
    }
  },
  "required": [
    "username",
    "password",
    "passwordConfirmation",
    "oldPassword"
  ]
},
```

And here's what nswag generated:

```typescript
export interface ChangeUserPasswordPayload {
    username: string;
    password: string;
    passwordConfirmation: ChangeUserPasswordPayloadPasswordConfirmation;
    oldPassword: string;
}

export enum ChangeUserPasswordPayloadPasswordConfirmation {
      ____ref_______path_________password____________ = "{
    "ref": {
      "path": [
        "password"
      ]
    }
  }",
}
```

**Comment by bbarry** [comment]
The hapi schema appears to be incorrect.

```json
 [
  {
    "ref": {
      "path": ["password"]
    }
  }
]
```

is very odd for an enum element; the enum element is supposed to have a list of primitive values that are allowed as values of the member.  What the generated code is doing here is representing the stringified json object as an enum member. I think that is about as accurate as can be done...

OAS 3 does allow ref enums, but that value is still wrong (would be something like `"$ref": "#/components/schemas/Password"` but that is clearly not what you are trying to do anyway...


Neither Swagger 2.0, nor OAS 3.0 support expressing most higher level validations involving `B` validating against something based on a value in `A`.  The best you can do for such validations is describe them within either the `description` member or extension members.

**Comment by danyhoron** [comment]
@bbarry thank you for clarifying it.
