### ISSUE TITLE
Typescript angular client status codes not ok

### ISSUE THREAD

**Issue by xaviergxf** [RicoSuter/NSwag#3140]
Hi,

  Is there a way to get the status code of the typescript angular client when the status code is a 400? 

Thanks

**Comment by xaviergxf** [comment]
Sorry, i found the argument wrapDtoExceptions. Shouldn't we have more documentation explaining what each of the arguments do? And shouldn't some of the arguments be by default true, like wrapDtoExceptions (Is always good to have the status on the error)?

**Comment by jeremyVignelles** [comment]
Feel free to contribute to the documentation.

As for the defaults, maybe you're right, but such changes are breaking changes, and we need to keep it as backwards compatible as possible, so that everyone is able to migrate from an older version without much trouble.
