### ISSUE TITLE
Poco object parameters default value in swagger autogenerated documentation

### ISSUE THREAD

**Issue by Red1408192** [RicoSuter/NSwag#3146]
Hi, anyone have any idea how to fill automaticaly those fileds in the swagger documentation?

![image](https://user-images.githubusercontent.com/48690547/98356393-cff7cd80-2023-11eb-834e-174808bdf051.png)

The object is read from the body offcourse, i've already tried to use C# Default value as follow:

```     
        [JsonProperty("userId", Required = Required.Always)]
        [DefaultValue(1)]
        public int UserId { get; set; }
        [JsonProperty("clientIssuerId", Required = Required.Always)]
        [DefaultValue(1)]
        public int ClientIssuerId { get; set; }```

**Comment by jeremyVignelles** [comment]
You must use a [Document Processor](https://github.com/RicoSuter/NSwag/wiki/Document-Processors-and-Operation-Processors#operation-processors) for that. You'll have access to the whole ApiDocument structure, which lets you tweak the document. You'll have to know what you're looking for though.

**Comment by Red1408192** [comment]
> You'll have to know what you're looking for though.

That's a main issue unfortunately

**Comment by jeremyVignelles** [comment]
Maybe this link is helpful : https://github.com/RicoSuter/NSwag/blob/889142b3dc01feb07d13200440d119fa8f7d5944/src/NSwag.Core.Tests/Serialization/ExampleSerializationTests.cs#L55

**Comment by Red1408192** [comment]
OpenApiExample does not exist as an attribute, if is so that must be used

**Comment by Red1408192** [comment]
```
        [JsonProperty("userId", Required = Required.Always)]
        ///<summary></summary>
        ///<example>10000015</example>
        public int UserId { get; set; }
        [JsonProperty("clientIssuerId", Required = Required.Always)]
        ///<summary></summary>
        ///<example>4</example>
        public int ClientIssuerId { get; set; }
```
Can be used to set the default value, but my team is looking for a solution that is a- more dynamic and remotely controlled and b- more clean

**Comment by Red1408192** [comment]
The solution was to use the "NJsonSchema.Annotations"
```
    public class ForceCloseShiftRequest
    {
        [JsonProperty("userId", Required = Required.Always)]

        [JsonSchemaExtensionData("example", 10000015)]
        public int UserId { get; set; }
        [JsonProperty("clientIssuerId")]

        [JsonSchemaExtensionData("example", 4)]
        public int? ClientIssuerId { get; set; }
    }
```
will produce the desired output:
![image](https://user-images.githubusercontent.com/48690547/98392935-e1a79800-2058-11eb-8d3c-3bd377b515fe.png)

**Comment by jeremyVignelles** [comment]
Great, thanks for sharing your solution.
Any reason why you put a line break between the two attributes that relate to the same property?

**Comment by Red1408192** [comment]
For highlighting

**Comment by RicoSuter** [comment]
It's important to note that 

    [JsonSchemaExtensionData("example", 10000015)]

will define an example value and 

    [DefaultValue(1)]

defines the default value for a property in the spec (both are valid and different use cases).

However I would expect that Swagger UI displays the default value in the UI when no example is defined... is this not the case?
If this is not the case we maybe should raise in issue in the Swagger UI project?

**Comment by Red1408192** [comment]
This line of code:
```
    public class MarkShiftAsPrintedRequest
    {
        [DefaultValue(10000015)]
        public int UserId { get; set; }

        [DefaultValue(null)]
        public int? ClientIssuerId { get; set; }
    }
```
Will define the schema's default values:
![image](https://user-images.githubusercontent.com/48690547/98572135-8faf7e00-22b5-11eb-98f5-8a9250a0ddf7.png)

but not the example value:
![image](https://user-images.githubusercontent.com/48690547/98572190-a35ae480-22b5-11eb-900f-1e0137e42446.png)

So, in this case is to raise an issue to swagger? I thought it was a Nswag operation

**Comment by RicoSuter** [comment]
Its fine as is. Its just that i would expect that swagger ui uses the default value if there is no example value. But in the end you found a solution to your problem. Can we close?
