### ISSUE TITLE
NET5.0 ETA?

### ISSUE THREAD

**Issue by onionhammer** [RicoSuter/NSwag#3154]
Hi, just wondering when net5.0 support will be landing in nuget; currently the MSBuild variable NSwagExe_Core31 only works when using that version of the SDK, and there is no corresponding net5 version

**Comment by jeremyVignelles** [comment]
Please be patient and wait for https://github.com/RicoSuter/NSwag/pull/3115 to be merged

**Comment by onionhammer** [comment]
Closed in favor of #3115
