### ISSUE TITLE
NSwagStudio v13.9.0 (Build 1114) - Create local Copy - 401 Unauthorized

### ISSUE THREAD

**Issue by erinloy** [RicoSuter/NSwag#3159]
Upgraded to NSwagStudio v13.9.0 (Build 1114) and received "401 Unauthorized" exception when refreshing the specification via the "Create local Copy" button.  Multiple URLs/projects.

Uninstalled and installed NSwagStudio v13.8.2 (Build 1113), and issue is not present.

Note: URL is localhost, pointed at a Swashbuckle-integrated .NET 4.x web app being debugged by Visual Studio, web server settings have Windows authentication enabled, and anonymous authentication disabled.

Possibly related?
https://github.com/RicoSuter/NJsonSchema/pull/1057

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NJsonSchema/issues/1279

Fix in the next hours.
