### ISSUE TITLE
Bug: In 13.9, HttpClient is disposed in FileResponse regardless of "Dispose HttpClient" setting

### ISSUE THREAD

**Issue by rbedell99** [RicoSuter/NSwag#3162]
In 13.9 (nswag and nswag studio), the HttpClient is disposed of in FileResponse, even when "Dispose HttpClient" setting is not selected. This was supposedly fixed by commit https://github.com/RicoSuter/NSwag/pull/3016/commits/a2c09f2d8b629f0af1cd89904eeb4a51714d1e90 for bug https://github.com/RicoSuter/NSwag/issues/2981, but the issue is still occuring.

![image](https://user-images.githubusercontent.com/20542305/98966263-af6ebe00-24d0-11eb-89b5-169e3c315962.png)
![image](https://user-images.githubusercontent.com/20542305/98966372-ce6d5000-24d0-11eb-8313-9d9158d13c73.png)

![image](https://user-images.githubusercontent.com/20542305/98966577-0f656480-24d1-11eb-96ac-f9ce372c08ba.png)

This should be passing in null instead of client, according to the PR fix.
![image](https://user-images.githubusercontent.com/20542305/98966602-15f3dc00-24d1-11eb-81bf-16d9ed69c348.png)
![image](https://user-images.githubusercontent.com/20542305/98966720-391e8b80-24d1-11eb-9b72-6c162997d08e.png)

**Comment by rbedell99** [comment]
@jeremyVignelles  Any thoughts on why this still doesn't work correctly in 13.9? Your fix looks correct. I assume DisposeHttpClient isn't set correctly somewhere else in the code.

**Comment by jeremyVignelles** [comment]
Probably. This needs investigation, but I don't have any idea yet. You should clone the repo and try to debug.

**Comment by RicoSuter** [comment]
I'm not sure whether liquid supports "!" or whether you need to use "== false"

**Comment by RicoSuter** [comment]
Indeed i think "!var" is not allowed as i used "== false" everywhere...

**Comment by jeremyVignelles** [comment]
Sorry then, not sure I tested that properly 🤔
Could you fix that @rbedell99 ?

**Comment by RicoSuter** [comment]
It's already fixed...
I wonder why there are no exceptions - no idea what liquid actually does with this - at least it doesnt throw an exception.

Will release v13.9.1 now...

**Comment by rbedell99** [comment]
Seriously impressive, I appreciate the dedication and quick turn around!

**Comment by RicoSuter** [comment]
Ref: https://github.com/RicoSuter/NSwag/pull/3164

**Comment by rbedell99** [comment]
Verified that this issue is fixed in v13.9.1. 
Thanks!
