### ISSUE TITLE
NSwag NPM package v13.9.1 appears to be missing Net50 binaries 

### ISSUE THREAD

**Issue by fholger** [RicoSuter/NSwag#3166]
I'm in the process of upgrading a project to Net50 and very happy to see that NSwag already supports Net50 :)

However, the current NPM package appears to be missing the necessary binaries to run with the Net50 runtime. Executing with `/runtime:Net50` produces the error

```
NSwag NPM CLI
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-/path/to/project/node_modules/nswag/bin/binaries/Net50/dotnet-nswag.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
child_process.js:655
    throw err;
    ^

Error: Command failed: dotnet "/path/to/project/node_modules/nswag/bin/binaries/Net50/dotnet-nswag.dll" run nswag.json /runtime:Net50
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:652:15)
    at /path/to/project/node_modules/nswag/bin/nswag.js:55:19
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 66830,
  stdout: null,
  stderr: null
}
```
And sure enough, that `binaries/Net50` folder does not exist. Could it be because Net50 has not been added to the `build/01_Build.bat` script?

**Comment by RicoSuter** [comment]
> Could it be because Net50 has not been added to the build/01_Build.bat script?

Yes 🤦‍♂️

**Comment by RicoSuter** [comment]
@jeremyVignelles you see, already time for a new release 😏

**Comment by fholger** [comment]
v13.9.3 is working for me, thanks!

**Comment by devinrhode2** [comment]
![CleanShot 2021-11-11 at 15 55 25](https://user-images.githubusercontent.com/539816/141367757-382b0584-891e-4a18-9658-3a07c9d9b9a3.png)
I think Net50 folder disappeared again :(

**Comment by RicoSuter** [comment]
Yep, got lost in the Nuke CI migration... 
Hopefully fixed in this PR: 
https://github.com/RicoSuter/NSwag/pull/3713
