### ISSUE TITLE
NSwag NPM package v13.9.2 appears to be missing Net50 binaries

### ISSUE THREAD

**Issue by jpflick** [RicoSuter/NSwag#3170]
Just update NSwag NPM CLI to version 13.9.2.0. 

Appears to still be missing NET50 binaries. Had to copy folder from NSwagStudio to get CLI working.

**Comment by GrahamTheCoder** [comment]
Looks like the fix for https://github.com/RicoSuter/NSwag/issues/3166 didn't work

**Comment by Prokleta-Kuja** [comment]
Fixed in 13.9.3

**Comment by GrahamTheCoder** [comment]
Yep net50 works for me. I tried a few combinations of setting runtime, but this is the one that worked:
* Specify runtime as an argument to nswag, e.g. `nswag run ./GenerateTypescriptApi.nswag.json /runtime:Net50`
* In your json config file, set `"runtime": "default",`.

Thanks!
