### ISSUE TITLE
"is null" not supported in MSBUILD 14.0

### ISSUE THREAD

**Issue by Doomic** [RicoSuter/NSwag#3183]
https://github.com/RicoSuter/NSwag/blob/e1f7657efe3ac8b4b4f79ffac482e0c0aee21ff1/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.ConvertToString.liquid#L47

I am making use of Unchase swagger connected service plugin (build upon NSwag). Works perfect in my VS2019... Today i want to check-in my changes into TFS. But the build engine is set there to MSBUILD14.0 (VS2015). 
And my only issue with the generated code is this "is null" statement in the ConvertToString template file.

Wondering; why is choosen for this "is null" statement?
on most other locations is just see the "x == null"... but you could also write it in this case as "return result ?? string.Empty".
Is it possible to write it like that? in that case the generated code works out of the box.

it is introduced in V13.7.0 on august 3 2020

**Comment by jeremyVignelles** [comment]
Somewhere else, Rico said that this line of code should be changed for this specific reason. If it wasn't already, you should make a PR to change that 🙂

**Comment by RicoSuter** [comment]
With all the PRs in this area this probably has not been changed. Can you create a PR to use `return result == null ? "" : result;`

**Comment by Doomic** [comment]
Had to dig into the github workflow for the first time. But looks like i did it..
Thank you for the fast reponse, i will look foward to see evrything updated.

**Comment by jeremyVignelles** [comment]
Congratulations 🙂
About the GitHub workflow, we usually reference the issue in the commit, inside the pr, this way : `Fixes #...`.

By doing that, you can leave the issue open for others to find it, and it will automatically be closed when the PR is merged 🙂

Please reopen this issue

**Comment by Doomic** [comment]
ok it should now be open.
i dont understand what you are saying about adding the "Fixes #...". Should i add it as comment to the https://github.com/RicoSuter/NSwag/pull/3184
Or will you place it there as comment when you accept the PR?

**Comment by jeremyVignelles** [comment]
In the PR message, you mentionned `#3183`, but without the `Fixes ` keyword before it, it will not automatically close this issue. you can edit the PR message to change that if you want.

**Comment by Doomic** [comment]
Ok thank you, i updated it.

**Comment by RicoSuter** [comment]
🙂 thanks for the PR! Will create a new release tomorrow.
