### ISSUE TITLE
SwaggerUI not start on default .NET Core 3.1 ASP.NET project

### ISSUE THREAD

**Issue by OculiViridi** [RicoSuter/NSwag#3196]
I'm using `NSwag v13.9.4` on a **.NET Core v3.1 ASP.NET** project.
I've followed your sample available [here](https://github.com/RicoSuter/NSwag/tree/master/samples/WithMiddleware/Sample.AspNetCore31).

Every time I launch the application, I get the following error:

![image](https://user-images.githubusercontent.com/42179710/100548800-17622a00-326f-11eb-828e-6408640725a5.png)

I've already checked my settings in:

- launchSettings.json
- appSettings.json
- Startup.cs
- Program.cs
- Controllers configuration

This is my Startup.cs:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // Add MediatR
    services.AddMediatR(typeof(CakeCreateModel).GetTypeInfo().Assembly);

    // Add DbContext
    services.AddDbContext<BakeryDbContext>(options =>
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            options.UseSqlServer(Configuration.GetConnectionString("BakeryDbContext"),
                opt => opt.MigrationsAssembly(typeof(BakeryDbContext).Assembly.GetName().Name)
                    .EnableRetryOnFailure(
                        maxRetryCount: 5,
                        maxRetryDelay: TimeSpan.FromSeconds(30),
                        errorNumbersToAdd: null)
            );
        }
        else
        {
            throw new Exception("Sorry! There's no alternatives for database at the moment...");
        }
    });

    services.AddControllers();

    // Add OpenAPI/Swagger document generator middleware
    services.AddOpenApiDocument();

    // Add AutoMapper
    services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());
}

// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseHttpsRedirection();

    // Add OpenAPI/Swagger middlewares
    app.UseOpenApi();
    app.UseSwaggerUi3();

    app.UseRouting();

    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints.MapControllers();
    });
}
```

I'm not able to figure out where can be the problem...

**Comment by jeremyVignelles** [comment]
This is not an issue with NSwag, but an issue with ASP.net core, because the server didn't reply.

Did you check your antivirus/your firewall to see if the port was not blocked?
Did you check with a blank ASP.net core project ?

**Comment by OculiViridi** [comment]
> Did you check your antivirus/your firewall to see if the port was not blocked?

In Windows Firewall I've added a rule for TCP 5000-5001 ports, but no changes.
Antivirus software is disabled.

> Did you check with a blank ASP.net core project ?

Yes, and I get the same behaviour.

**Comment by jeremyVignelles** [comment]
Did you accept the dev certificate? did you try another port?
Anyway, this is more a question for stackoverflow than this site.

**Comment by ViRuSTriNiTy** [comment]
Just click on "Detaggli" and show us whats displayed there. The current screenshot shows the default error page without the details, anchient Internet Explorer named this Feature "friendly error messages".

**Comment by OculiViridi** [comment]
@ViRuSTriNiTy 
> Just click on "Detaggli" and show us whats displayed there. The current screenshot shows the default error page without the details. Anchient Internet Explorer named this Feature "friendly error messages".

"Dettagli" only shows generic (useless) stuff, like: check your cable, check your internet connection, check proxy settings... the cable is in, the internet connection works and I've no proxy. 👍 

It's not IE, it's the new Edge, derived from Chromium project.

@jeremyVignelles 
> Did you accept the dev certificate? did you try another port?

Yes, I've accpted the first time I run the application, in the question message box pop-up.
I' tried to change the port in launchSettings.json, but nothing happened and/or changed.

**Comment by ViRuSTriNiTy** [comment]
> "Dettagli" only shows generic (useless) stuff,

My bad, I thought this word stands for details ^^

**Comment by OculiViridi** [comment]
> > "Dettagli" only shows generic (useless) stuff,
> 
> My bad, I thought this word stands for details ^^

It actually means "Details", but unfortunately there's no useful details inside...
Any other idea about why HTTP is working and HTTPS is not?

**Comment by jeremyVignelles** [comment]
No, this is not the right place to ask. Please go on stackoverflow or another generic asp.net core help forum and close this issue.
