### ISSUE TITLE
Is using `nswag run aspNetCoreToOpenApi` as part of an MSBuild task expected to execute any part of the program?

### ISSUE THREAD

**Issue by StingyJack** [RicoSuter/NSwag#3215]
I have some code in my `public Startup(IConfiguration configuration)` function that relies on environment variables being present or else it throws an exception. When debugging these are supplied via launchSettings.json.  I added the following task to the proj file to get the client generation to run after the compilation is completed and my nswag.json file has `"noBuild": true,`

``` xml
  <Target Name="NSwag" BeforeTargets="AfterBuild" Condition="'$(Configuration)'=='Debug'">
    
    <Exec ConsoleToMSBuild="true" ContinueOnError="true" Command="$(NSwagExe_Core31) run nswag.json /variables:SolutionDir=$(SolutionDir),Configuration=$(Configuration)" >
      <Output TaskParameter="ExitCode" PropertyName="NSwagExitCode" />
      <Output TaskParameter="ConsoleOutput" PropertyName="NSwagOutput" />
    </Exec>

    <Message Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' == '0'" Importance="low" />
    <Error Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' != '0'" />
  </Target>
```

When the build executes, I can see that `nswag run` is getting the correct parameters, but fails with one of the Environment variable not found Exceptions thrown in the Startup function. I didnt expect nswag.exe to try to run the code, just to reflect or inspect it. Do I have the wrong expectation?

**Comment by jeremyVignelles** [comment]
Yes, with the aspnetcore2openApi generator (see its documentation in the wiki), NSwag builds the asp.net host (initializes the startup, service provider...) but does not actually launch the server.
This is because it uses the ApiExplorer feature of asp.net core to detect the controller the same way asp.net core does.

The legacy generator did use reflection, but that's not the case anymore.

**Comment by StingyJack** [comment]
I can move the code to run later in the startup sequence I think. Do you know at what point it stops building the host?

**Comment by jeremyVignelles** [comment]
It invokes the CreateWebHostBuilder method, builds it, does its stuff with the ApiExplorer and exits.

**Comment by StingyJack** [comment]
I had moved it a few places and it still was executing so I added some logging to find out what was specifically being called in my case, and it reported these (in case it saves time for someone else).

CreateHostBuilder method beginning and returning
Startup method beginning
Startup method finishing
ConfigureServices method beginning
ConfigureServices method completing

**Comment by jeremyVignelles** [comment]
The Startup.Configure() method is also called.

**Comment by StingyJack** [comment]
I was surprised about that as its actually not called (for me), and is where I moved the code that was having a wobbly in Startup() to.

**Comment by RicoSuter** [comment]
NSwag via CLI does not execute Configure() only ConfigureServices() - Configure() is only called when the spec is served via HTTP...

**Comment by jeremyVignelles** [comment]
I thought it needed to know the endpoints conventions/configurations. I thought it was configured in the Configure() method.

**Comment by RicoSuter** [comment]
Because the Configure() method is not called - I'd expect that conventions and configs are done outside - in the ConfigureServices().

**Comment by jeremyVignelles** [comment]
In case someone need it here, I copy/paste my answer from #3262 here:

If you need to do something special depending on whether you're under NSwag or not, you could, for example, define an environment variable when building with NSwag.

I personnally use this hack:

```cs
if (Assembly.GetEntryAssembly() != typeof(Startup).Assembly)
{// This is true when the API is being generated with NSwag
   // Do something special for NSwag
}
```
Just reverse the condition if you want something special except for NSwag
