### ISSUE TITLE
NSwag REST client service returning a result

### ISSUE THREAD

**Issue by i12code** [RicoSuter/NSwag#3238]
First off, thank you for the great product.  I'm new to NSwag.  I posted a question about an issue on Stackoverflow [here ](https://stackoverflow.com/questions/65486689/nswag-generated-service-has-no-return-logic) with all code but no one offered an answer. :(  Please help.  Here's my problem.

I have a WebAPI service with the following method

`   public async Task<IActionResult> Login(LoginDto dto)`

At the end of the method, the method returns the following which token and Id when all is well.

`return Ok(new { Token = GenerateJwtTokenFromClaims(claims), Id=user.Id });`

I created REST client (C#) using NSwag Studio.  The issue is the service.cs that is generated returns nothing for status code 200.

```

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            return;
                        }

```

Thus I get an error when trying to retrieve the returning value.  Is there something I have to do to generate the necessary code get the value from the service call?  Thanks in advance.  

![image](https://user-images.githubusercontent.com/13510371/103319101-738eaa00-49e5-11eb-8725-a255f28d5979.png)

**Comment by jeremyVignelles** [comment]
Don't use anonymous type as the ApiExplorer (and thus Nswag) is unable to know the type of what is returned. Create a type (for example `ResultModel` and type your method as `Task<IActionResult<ResultModel>>`

If you want to type the error results as well, you should have a look at the `ProducesResponseType` attribute

**Comment by i12code** [comment]
Thank you Jeremy.  I did try that yesterday.  I'm from asmx/wsdl world so I did suspect that the return type is an issue.  I tried the following with signature and class below.  But I get compiler error:  `CS0308	The non-generic type 'IActionResult' cannot be used with type arguments.`  

I know that this is now getting outside of realm of NSwag.  But if anything comes to your mind as how to fix it, please share. Thanks again.

`public async Task<IActionResult<LoginDtoResponse>> Login(LoginDto dto)`


```
 public class LoginDtoResponse
    {
        public string Token { get; set; } = string.Empty;

        public string Id { get; set; } = string.Empty;
    }
```

**Comment by jeremyVignelles** [comment]
Sorry, I meant `ActionResult<ResultModel>`. See https://docs.microsoft.com/en-us/aspnet/core/web-api/action-return-types?view=aspnetcore-5.0#actionresultt-type

**Comment by i12code** [comment]
You rock Jeremy.  Worked.  Thank you.

```
                       if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<LoginDtoResponse>(response_,                 headers_).ConfigureAwait(false);
                            return objectResponse_.Object;
                        }
```
