### ISSUE TITLE
NSwag.MSBuild: $(NSwagExe_Core31) is null in latest Visual Studio

### ISSUE THREAD

**Issue by Kobus-Smit** [RicoSuter/NSwag#3240]
Updating to the newest version of Visual Studio breaks existing projects that use $(NSwagExe_Core31) even if you never changed your target framework.

VS 2019 16.8.3
TargetFramework: netcoreapp3.1

![image](https://user-images.githubusercontent.com/11263864/103530389-6f79f500-4edb-11eb-9aa3-4e287021a37b.png)

It seems `$(NSwagExe_Core31)` is empty.

I've tried the `global.json` workaround (in the project's root dir) but that did not work for me.
![image](https://user-images.githubusercontent.com/11263864/103530181-18742000-4edb-11eb-896b-0292279dfe1e.png)

Command line works:
![image](https://user-images.githubusercontent.com/11263864/103530541-b962db00-4edb-11eb-8570-b8cdad814a12.png)

[Extensions.API.csproj.txt](https://github.com/RicoSuter/NSwag/files/5764564/Extensions.API.csproj.txt)

[nswag.json.txt](https://github.com/RicoSuter/NSwag/files/5764568/nswag.json.txt)

_Originally posted by @Kobus-Smit in https://github.com/RicoSuter/NSwag/issues/3026#issuecomment-753921187_

**Comment by AdrianSanguineti** [comment]
@Kobus-Smit, it looks that in your `Extensions.API.csproj`, you are referencing version `NSwag.MSBuild 13.0.5` (released more than 2 years ago)

```xml
<PackageReference Include="NSwag.AspNetCore" Version="13.9.4" />
    <PackageReference Include="NSwag.CodeGeneration.CSharp" Version="13.9.4" />
    <PackageReference Include="NSwag.MSBuild" Version="13.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```
Instead of the latest version `13.9.4` that also matches the `NSwag.AspNetCore` and `NSwag.CodeGeneration.CSharp` package versions your also referencing.

`NSwag.MSBuild 13.0.5` does not provide properties for `NSwagExe_Core31` or `NSWageExe_Net50` in its [NSwag.MSBuild.props](https://github.com/RicoSuter/NSwag/blob/4fc3de094c457cdc2532fc336f6b83058738843d/src/NSwag.MSBuild/NSwag.MSBuild.props) file:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NSwagExe>"$(MSBuildThisFileDirectory)../tools/Win/NSwag.exe"</NSwagExe>
    <NSwagExe_x86>"$(MSBuildThisFileDirectory)../tools/Win/NSwag.x86.exe"</NSwagExe_x86>
    <NSwagExe_Core10>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore10/dotnet-nswag.dll"</NSwagExe_Core10>
    <NSwagExe_Core11>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore11/dotnet-nswag.dll"</NSwagExe_Core11>
    <NSwagExe_Core20>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore20/dotnet-nswag.dll"</NSwagExe_Core20>
    <NSwagExe_Core21>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore21/dotnet-nswag.dll"</NSwagExe_Core21>
    <NSwagExe_Core22>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore22/dotnet-nswag.dll"</NSwagExe_Core22>

    <NSwagDir>$(MSBuildThisFileDirectory)../tools/Win/</NSwagDir>
    <NSwagDir_Core10>$(MSBuildThisFileDirectory)../tools/NetCore10/</NSwagDir_Core10>
    <NSwagDir_Core11>$(MSBuildThisFileDirectory)../tools/NetCore11/</NSwagDir_Core11>
    <NSwagDir_Core20>$(MSBuildThisFileDirectory)../tools/NetCore20/</NSwagDir_Core20>
    <NSwagDir_Core21>$(MSBuildThisFileDirectory)../tools/NetCore21/</NSwagDir_Core21>
    <NSwagDir_Core22>$(MSBuildThisFileDirectory)../tools/NetCore22/</NSwagDir_Core22>
  </PropertyGroup>
</Project>
```

[NSwag.MSBuild.props v13.9.4](https://github.com/RicoSuter/NSwag/blob/ec246e4a18e45d24eb879e8ee70d6b701383fa42/src/NSwag.MSBuild/NSwag.MSBuild.props):

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NSwagExe>"$(MSBuildThisFileDirectory)../tools/Win/NSwag.exe"</NSwagExe>
    <NSwagExe_x86>"$(MSBuildThisFileDirectory)../tools/Win/NSwag.x86.exe"</NSwagExe_x86>
    <NSwagExe_Core21>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore21/dotnet-nswag.dll"</NSwagExe_Core21>
    <NSwagExe_Core22>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore22/dotnet-nswag.dll"</NSwagExe_Core22>
    <NSwagExe_Core30>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore30/dotnet-nswag.dll"</NSwagExe_Core30>
    <NSwagExe_Core31>dotnet "$(MSBuildThisFileDirectory)../tools/NetCore31/dotnet-nswag.dll"</NSwagExe_Core31>
    <NSwagExe_Net50>dotnet "$(MSBuildThisFileDirectory)../tools/Net50/dotnet-nswag.dll"</NSwagExe_Net50>

    <NSwagDir>$(MSBuildThisFileDirectory)../tools/Win/</NSwagDir>
    <NSwagDir_Core21>$(MSBuildThisFileDirectory)../tools/NetCore21/</NSwagDir_Core21>
    <NSwagDir_Core22>$(MSBuildThisFileDirectory)../tools/NetCore22/</NSwagDir_Core22>
    <NSwagDir_Core30>$(MSBuildThisFileDirectory)../tools/NetCore30/</NSwagDir_Core30>
    <NSwagDir_Core31>$(MSBuildThisFileDirectory)../tools/NetCore31/</NSwagDir_Core31>
    <NSwagDir_Net50>$(MSBuildThisFileDirectory)../tools/Net50/</NSwagDir_Net50>
  </PropertyGroup>
</Project>
```

I can only reproduce your problem in Visual Studio 2019 16.8.3 in a .NET Core 3.1 project, when I explicitly target `NSwag.MSBuild 13.0.5`. Using `NSwag.MSBuild 13.9.4`, all properties include `$(NSwagExe_Core31)` resolve correctly as expected. There's no bug here for NSwag.MSBuild as far as I can tell.

**Comment by Kobus-Smit** [comment]
Ah of course, after updating to `NSwag.MSBuild 13.9.4` it works just fine. Dunno how that old version ended up in there. Thanks @AdrianSanguineti !

**Comment by Tri125** [comment]
Same issue with NSwag.MSBuild 13.7.0.

The build for my solution started to failed after I update VS2019 from 16.7.x  to 16.8.4. Seems like a bug from VS.
