### ISSUE TITLE
Use custom C# DataAnnotation attributes on NSwag DTO Objects based on Data Type format

### ISSUE THREAD

**Issue by csehatt741** [RicoSuter/NSwag#3246]
Is it possible to generate custom DataAnnotations on DTO object based on Data Type format?

"Country": {
  "type": "string",
  "format": "country",
  "description": "Country"
}

It seems JsonSchemaProperty.ActualSchema.Format could be used in Class.Property.Annotations.liquid, but JsonSchemaProperty is a private field of PropertyModel.

**Comment by RicoSuter** [comment]
Added the property to the model so you can use it in the custom template.
