### ISSUE TITLE
CSharp client generator - Add the ability to define PrepareRequest and ProcessResponse methods using the Async Pattern

### ISSUE THREAD

**Issue by francozuca** [RicoSuter/NSwag#3247]
### Current behaviour
**PrepareRequest** and **ProcessResponse** methods are currently being generated as below:
```csharp
partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);
```
### What's the problem with it?
On our current implementation, we are getting the response content using **ReadAsStringAsync**, and we are forced to use **GetAwaiter().GetResult()** instead of **await**, because the method is not **async**:
```csharp
partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response)
     //...
     var responseString = response.Content.ReadAsStringAsync().GetAwaiter().GetResult();
     //...     
}
```

### What's the solution we propose? (PR #3247)
We propose to make the following changes:

1. Add a boolean property **GeneratePrepareRequestAndProcessResponseAsAsyncMethods** to **NSwag.CodeGeneration.CSharp.CSharpClientGeneratorSettings** as following:
```csharp
/// <summary>
/// Gets or sets a value indicating whether to create PrepareRequest and ProcessResponse as async methods, or as partial synchronous methods.
/// If value is set to true, PrepareRequestAsync and ProcessResponseAsync methods must be implemented as part of the client base class (if it has one) or as part of the partial client class.
/// If value is set to false, PrepareRequest and ProcessResponse methods will be partial methods, and implement them is optional.
/// </summary>
public bool GeneratePrepareRequestAndProcessResponseAsAsyncMethods { get; set; }
```
2. Add a boolean property **GeneratePrepareRequestAndProcessResponseAsAsyncMethods** to **NSwag.CodeGeneration.CSharp.Models.CSharpClientTemplateModel** as following;
```csharp
/// <summary>
/// Gets or sets a value indicating whether to create PrepareRequest and ProcessResponse as async methods, or as partial synchronous methods.
/// If value is set to true, PrepareRequestAsync and ProcessResponseAsync methods must be implemented as part of the client base class (if it has one) or as part of the partial client class.
/// If value is set to false, PrepareRequest and ProcessResponse methods will be partial methods, and implement them is optional.
/// </summary>
public bool GeneratePrepareRequestAndProcessResponseAsAsyncMethods => _settings.GeneratePrepareRequestAndProcessResponseAsAsyncMethods;
```
3. Modify the **Client.Class.liquid** template as following: 
```
...
{% if GeneratePrepareRequestAndProcessResponseAsAsyncMethods == false %}
    partial void PrepareRequest({{ HttpClientType }} client, System.Net.Http.HttpRequestMessage request, string url);
    partial void PrepareRequest({{ HttpClientType }} client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
    partial void ProcessResponse({{ HttpClientType }} client, System.Net.Http.HttpResponseMessage response);
{% endif -%}
...
{% if GeneratePrepareRequestAndProcessResponseAsAsyncMethods == true %}
                await PrepareRequestAsync(client_, request_, urlBuilder_);
{% else -%}
                PrepareRequest(client_, request_, urlBuilder_);
{% endif -%}
                
                var url_ = urlBuilder_.ToString();
                request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

{% if GeneratePrepareRequestAndProcessResponseAsAsyncMethods == true %}
                await PrepareRequestAsync(client_, request_, url_);
{% else -%}
                PrepareRequest(client_, request_, url_);
{% endif -%}
...
{% if GeneratePrepareRequestAndProcessResponseAsAsyncMethods %}
                    await ProcessResponseAsync(client_, response_);
{% else -%}
                    ProcessResponse(client_, response_);
{% endif -%}
...
```
### The result of this modification
- If **GeneratePrepareRequestAndProcessResponseAsAsyncMethods** is set to false, then PrepareRequest and ProcessResponse are still generated as they currently do: partial methods without implementation, and called synchonously. Then the developer can implement that partial methods if needed.
- If **GeneratePrepareRequestAndProcessResponseAsAsyncMethods** is set to true, then PrepareRequest and ProcessResponse partial methods **are not** generated, and the calls to those methods are awaited as following:
```csharp
await PrepareRequestAsync(client_, request_, urlBuilder_);
await PrepareRequestAsync(client_, request_, url_);
await ProcessResponseAsync(client_, response_);
```
- Also, if **GeneratePrepareRequestAndProcessResponseAsAsyncMethods** is set to true, the developer **must implement these three methods**, whether on the base class (if there is one) or as method on a partial class that extends the generated client.

Thanks to @CorrenSoft that was working with me on this enhancement proposal.

**Comment by francozuca** [comment]
Implementated in #3248.

**Comment by svrooij** [comment]
I wish that this was supported in Visual Studio 2022, when using the build-in wizard it just generated the methods as synchronously. And no options to change it.

**Comment by LockTar** [comment]
> I wish that this was supported in Visual Studio 2022, when using the build-in wizard it just generated the methods as synchronously. And no options to change it.

By default visual studio generates synchronous methods. But you can still use the visual studio property window on the open api spec file.
![image](https://user-images.githubusercontent.com/1568453/192481115-2083a8b3-aa13-45ca-b54c-bc983c943b52.png)

Or alter you project file directly to:
`<OpenApiReference Include="OpenAPIs\My.OpenApi.json" ClassName="MyServiceClient" Options="/UseBaseUrl:false /GenerateClientInterfaces:true /GeneratePrepareRequestAndProcessResponseAsAsyncMethods:true" Namespace="MyNamespace" CodeGenerator="NSwagCSharp" />`

**Comment by Naweap** [comment]
@LockTar I'm personally still facing this issue. The async functions are not placed into my client's class.
I added the `generatePrepareRequestAndProcessResponseAsAsyncMethods": true` attribute to the nswag configuration file and upgraded the NuGet packages to latest version. How did you come up with a compilable code?

**Comment by DavidPx** [comment]
@Naweap I experienced the same problem at first.  I had to delete the generated `.cs` file and only then was it generated with the `async` prepare methods.

And for the record, this was in a .Net 4.8 project so my project file had this entry:

```
<None Include="..\openapi.json">
    <Link>OpenAPIs\openapi.json</Link>
    <Namespace>MyNamespace</Namespace>
    <ClassName><uClient</ClassName>
    <CodeGenerator>NSwagCSharp</CodeGenerator>
    <Options>/GeneratePrepareRequestAndProcessResponseAsAsyncMethods:true</Options>
</None>
```

But because this is a 4.8 project my c# version is limited to 7.3, so I was unable to implement partial methods that return Tasks.

**Comment by Naweap** [comment]
> @Naweap I experienced the same problem at first. I had to delete the generated `.cs` file and only then was it generated with the `async` prepare methods.
> 
> And for the record, this was in a .Net 4.8 project so my project file had this entry:
> 
> ```
> <None Include="..\openapi.json">
>     <Link>OpenAPIs\openapi.json</Link>
>     <Namespace>MyNamespace</Namespace>
>     <ClassName>MyClient</ClassName>
>     <CodeGenerator>NSwagCSharp</CodeGenerator>
>     <Options>/GeneratePrepareRequestAndProcessResponseAsAsyncMethods:true</Options>
> </None>
> ```
> 
> But because this is a 4.8 project my c# version is limited to 7.3, so I was unable to implement partial methods that return Tasks.

Following the same procedure fixed my issue as well. Thanks!

**Comment by Medfar-DavidFrancis** [comment]
@Naweap 
> The async functions are not placed into my client's class.

This seems to be by design due to [limitations on partial methods](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/classes#1569-partial-methods)
> **C# Specifications - 15.6.9 Partial methods**
> Partial methods shall not define access modifiers; they are implicitly private. Their return type shall be `void`, and their parameters shall not be output parameters.

You'll need to manually add these three methods to the non-generated partial class

```
private Task PrepareRequestAsync(HttpClient client, HttpRequestMessage request, StringBuilder urlBuilder, CancellationToken cancellationToken = default(CancellationToken))
{
    return Task.CompletedTask;
}

private Task PrepareRequestAsync(HttpClient client, HttpRequestMessage request, string url, CancellationToken cancellationToken = default(CancellationToken))
{
    return Task.CompletedTask;
}

private Task ProcessResponseAsync(HttpClient client, HttpResponseMessage request, CancellationToken cancellationToken = default(CancellationToken))
{
    return Task.CompletedTask;
}
```

`ProcessResponseAsync` is the only one that passes the cancellation token (at least on the version I'm using), but included it on all just to be safe.
