### ISSUE TITLE
Problem generating Client Code

### ISSUE THREAD

**Issue by e-simo** [RicoSuter/NSwag#3262]
Hello,

I am new to NSwag and i have recenly used to generate client code for an .net core 3.1 api I have followed the sample provided at https://github.com/RicoSuter/NSwag/tree/master/samples/WithMiddleware.
In my project i have NLog configured and at seems this is causing an issue. Below you may find the error appearing during the build process.

![nswag_error](https://user-images.githubusercontent.com/47154664/105047522-bb47a500-5a6a-11eb-9670-ec6871154ef5.jpg)

When you remove the log configuraiton altogether the client code is generated perfectly.

Could somebody please provide some insights?

Thank you!

**Comment by jeremyVignelles** [comment]
The generator actually executes parts of your program, but you might not want to initialize your NLog when used in the context of NSwag. See also #3215

**Comment by e-simo** [comment]
> The generator actually executes parts of your program, but you might not want to initialize your NLog when used in the context of NSwag. See also #3215

**Comment by e-simo** [comment]
@jeremyVignelles Thanks for the response. Currently i configure NLog in CreateHostBuilder, i can move it to ConfigureService as well but based on #3215, they NLog config will be called again by nswag. Any suggestion how to tackle it?

**Comment by jeremyVignelles** [comment]
You could, for example, define an environment variable when building with NSwag.

I personnally use this hack:

```cs
if (Assembly.GetEntryAssembly() != typeof(Startup).Assembly)
{// This is true when the API is being generated with NSwag
   // Do something special for NSwag
}
```
Just reverse the condition if you want something special except for NSwag

**Comment by e-simo** [comment]
Thank you, I will try it!

**Comment by RicoSuter** [comment]
@jeremyVignelles nice solution, maybe we ahould add that to the wiki?

**Comment by jeremyVignelles** [comment]
That's a hack, I'd prefer the NSwag executable to define an env variable like NSWAG=1. That way, we could differenciate the other ways that could explain why it's not the entry assembly (for example : Startup may be in a library and not in the executable, or it might be running by a bootstrapper project, or maybe it's run under a unit test runner...

Otherwise, I'm fine with documenting the hack

**Comment by InDieTasten** [comment]
So what about that environment variable. Is this being tracked?

**Comment by jeremyVignelles** [comment]
Not yet, could you open a new issue for that and link it here?
