### ISSUE TITLE
TypeScript Client Generator - Add Validation logic to Support Subset of System.ComponentModel.DataAnnotations attributes

### ISSUE THREAD

**Issue by kevin-weir** [RicoSuter/NSwag#3270]
Good Day Rico

You already support the generation of some DataAnnotation properties in the OpenAPI document.   Would it be possible to have validation code generated, for the TypeScript client, that recognizes those validation properties?
 
Much appreciated
Kevin Weir

**Comment by RicoSuter** [comment]
Not on my prio list as the value is not that big (should be validated on the server anyway) and the effort is very high.

**Comment by kevin-weir** [comment]
Ok.  Thanks for your consideration.
