### ISSUE TITLE
CSharpCodeGenerator generates cast from HttpStatusCode to int, but why?

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [RicoSuter/NSwag#3277]
Hi there,

I'm using the CSharpCodeGenerator to generate clients. The resulting code contains the following lines

```
var status_ = (int)response_.StatusCode; <- cast from HttpStatusCode to int
if (status_ == 403)
{
```

which results in the need to cast the int back to HttpStatusCode in my code. 

First question that comes to mind: what's the reasoning behind the cast?

Also is it possible to change the generated code somehow to work with the HttpStatusCode enum directly? 

So lonG

Daniel

**Comment by SebastianStehle** [comment]
My guesses:

1. OpenAPI uses integer for status codes itself, so it is easier to handle them in the code generator like this.
2.  Nobody stops you from using undefined status codes and returning any number as a result. Then the code generator would not be able to handle these cases.

**Comment by jeremyVignelles** [comment]
Before #2959 It was actually a cast to int, that was converted to a string. I simplified by only using `int` all the way down, but did not consider keeping HttpStatusCode.

OpenApi, on the other hand, [uses string](https://swagger.io/specification/#patterned-fields-1) and can be defined as `2XX` which is not clearly supported by NSwag yet.

SebastianStehle has a good point about the undefined status code, but I don't know how it would fit in `StatusCode` in the first place, so I don't know if that works either.

**Comment by ViRuSTriNiTy** [comment]
Ok, fair enough. I guess I have to live with the need for casts. Thanks.
