### ISSUE TITLE
CSharpClientGenerator hides actual `ProblemDetails` by generating `Response was null which was not expected` 

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [RicoSuter/NSwag#3281]
Hi there,

I'm using the CSharpCodeGenerator to generate clients for an protected API. This means that an request to that API needs to send a bearer token for authentication. Now when this token is missing the API returns HTTP 401 and the client tries to deserialize *nothing* returned and returns `null`. This in return means that `objectResponse_.Object == null` is always true and the client throws an "Response was null which was not expected." exception hiding the actual `ProblemDetails` code which is never reached.

Here is the problematic section in each client generated:

```
if (status_ == 401)
{
    var objectResponse_ = ...
    if (objectResponse_.Object == null) <- this is always true as nothing is returned on 401 ...
    {
        throw new NSwagException("Response was null which was not expected.", ...);
    }

    // ... hence we cannot get to this line of code that would return an specific exception message
    throw new NSwagException<ProblemDetails>("Menu items could not be retrieved due to unauthorized access.", ...);
}
```

I haven't found a solution yet how to ensure that Object is not null on 401. I have tried to setup serializing options somehow to return a non-null value but to no avail.

I really would like to get to the `ProblemDetails` exception with the actual message rather than the generic one which doesn't hold any valuable info. Any ideas? 

Also, what is the reasoning behind this sanity check for null? Why is it not expected? I though it's my own responsibility to handle return values safely.

So lonG
Daniel

**Comment by jeremyVignelles** [comment]
If you don't need to return anything for 401, you need to use `[ProducesResponseType]` properly. I don't remember the syntax right now, but please have a look at the asp.net core documentation.
This will change the generated openapi document to declare that no content is expected on 401 (which is currently declared as returning a ProblemDetails).
The check is here to make sure that what is received is in line with what is declared in the spec, which you seem to violate on the server side.
Another way to fix that is to actually produce a ProblemDetails by using the default asp.net core mechanism

**Comment by ViRuSTriNiTy** [comment]
@jeremyVignelles Thanks for the hint pointing me in the right direction. I'm aware of this attribute but it just doesn't work as documented in this case.

The issue is reported [here](https://github.com/dotnet/aspnetcore/issues/7874#issuecomment-708226673) already and seems it is still open.

So, to get the desired behavior I have to change

```
[ProducesResponseType(StatusCodes.Status401Unauthorized)]
public ActionResult<IEnumerable<...>> ...
```

to 

```
[ProducesErrorResponseType(typeof(void))]
[ProducesResponseType(StatusCodes.Status401Unauthorized)]
public ActionResult<IEnumerable<...>> ...
```

Now the generated code does not include the `Response was null which was not expected.` exception section anymore. 👍
