### ISSUE TITLE
Api display error

### ISSUE THREAD

**Issue by Alan-Lun** [RicoSuter/NSwag#3293]
## Swagger Display

```json
"data": [
    {
      "userId": 68267599263309460,
    },
    {
      "userId": 68267599263309460,
    }
  ]
```

## F12 Api NetWork
```json

"data":[
{
"userId":68267599263309460
},
{
"userId":68267599263309459
}
]
}
```

## Example

``` CSharp
    <PackageReference Include="NJsonSchema" Version="10.3.4" />
    <PackageReference Include="NSwag.AspNetCore" Version="13.10.2" />
    <PackageReference Include="NSwag.Core" Version="13.10.2" />
```

``` CSharp
[HttpGet]
        public ActionResult<TestLong> Get()
        {
            var data = new TestLong();
            data.Data = new List<long>();
            data.Data.Add(68267599263309460);
            data.Data.Add(68267599263309459);
            return this.Ok(data);
        }
```
``` CSharp
public class TestLong
    {
        public List<long> Data { get; set; }

    }
```

**Comment by jeremyVignelles** [comment]
No explanation, no error message... What is the issue?

Please reopen with proper explanations.

**Comment by Alan-Lun** [comment]
API expected display 68267599263309460 and 68267599263309459

But Swagger View display 68267599263309460 and 68267599263309460 

image url : 
https://imgur.com/OFsB4Jw

**Comment by jeremyVignelles** [comment]
Likely a rounding issue with javascript, the number type there is not stored as an integer type. Can you confirm that the value you see in the "network" tab of your browser is correct?

I wouldn't recommend the number type for big integer like this, I would use string to make sure it is parsed correctly.

Apart from that, if the API response is correct in the "network" tab of the developer tools, you need to post an issue on the swagger-ui project, not this one. If the value is incorrect, report a bug to aspnetcore
