### ISSUE TITLE
Generate schema in YAML?

### ISSUE THREAD

**Issue by paulps** [RicoSuter/NSwag#3296]
Sorry for bothering you but I don't how  I can change the format of the schema to YAML.  I believe that I should use the package https://www.nuget.org/packages/NSwag.Core.Yaml/ but I have no idea how.

**Comment by RicoSuter** [comment]
Use the static method ToYaml to serialize an OpenApiDocument to YAML: 
https://apimundo.com/organizations/nuget-org/nuget-feeds/public/packages/NSwag.Core.Yaml/versions/latest?tab=types

**Comment by paulps** [comment]
Thanks for the answer. But how I should expose the endpoint in YAML? Where is the place in the pipeline where I should use this static method. Should I use a Document Processor?
