### ISSUE TITLE
Schema members not set to required

### ISSUE THREAD

**Issue by bartios** [RicoSuter/NSwag#3302]
In an OpenAPI document, schema/object members can be set to be required and nullable seperately. I want all members to be required by default and have nullability set based on the code I have in my .NET Core project. I have not found an option for the AspNetCoreOpenApiDocumentGenerator to do this. I have searched in the docs and found that you can set required and allow null with 
`[JsonProperty(Required = Required.AllowNull)]`
And required, not nullable with one of the following two options
`[JsonProperty(Required = Required.Always)]`
`[Required]`

I thought there should be some setting to have the default be set to required or something, could you tell me if I have missed a generator option or something else or if I do indeed have to mark every member of the objects used in my API with an annotation.

**Comment by RicoSuter** [comment]
I think if you want to change the defaults, you'd need to change them in the newtonsoft config within ASP (ie provide a custom contract resolver). NSwag/NJsonSchema just uses the newtonsoft.json contract resolver (from config) and does not change defaults on top of that.

**Comment by bartios** [comment]
Thanks for the quick reply, decided that I was just being lazy and should annotate my DTOs. For future people using JsonProperty annotations, don't forget to [add NewtonsoftJson in startup](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/formatting?view=aspnetcore-5.0#add-newtonsoftjson-based-json-format-support) otherwise the annotations won't work for model validation in your controllers!
`services.AddControllers().AddNewtonsoftJson()`

**Comment by RicoSuter** [comment]
Fyi: Depending on the configured serializer in saps.net core, nswag will choose either newtonsoft or system.text.json rules. Ie if stj is configured then nswag will ignore newtonsoft attributes
