### ISSUE TITLE
Dictionary<string, double?>  generating from NSwagStudio to Dictionary<string, double>

### ISSUE THREAD

**Issue by CJM3407** [RicoSuter/NSwag#3308]
I found a previous issue that seemed to be resolved (https://github.com/RicoSuter/NSwag/issues/2116)

But I have been on NswagStudio v13 + for a while and it still isn't just working for me.  I am using the OpenAPI/Swagger Specification tab, and trying to generate a CSharp Client.  I have tried multiple properties with no success.  Some references seem to suggest OpenAPI3 vs Swagger2, but inside of NSwagStudio I can only find the Output Type choice on the Assembly based tabs.  I want to use my swagger.json reference (https://..../swagger/v1/swagger.json.  

Additional information: I was previously using a list of KeyValuePairs<int, double?> and that was generating its own class type that was like Int32AndNullableDoubleKeyValuePair.  We decided as a team we didn't want that nasty auto generated class name.  But the point of me mentioning this is that: it respected the nullable double but the dictionary is just not working.

Any ideas?

**Comment by RicoSuter** [comment]
How does the generated spec look for this dictionary?

**Comment by CJM3407** [comment]
`        [Newtonsoft.Json.JsonProperty("temperatureRatings", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.IDictionary<string, double> TemperatureRatings { get; set; }
`

**Comment by RicoSuter** [comment]
![image](https://user-images.githubusercontent.com/2603405/108402538-f54cc800-721d-11eb-8f5b-12091ca00119.png)

**Comment by RicoSuter** [comment]
What is the original property from which the spec is generated?

**Comment by CJM3407** [comment]
`public Dictionary<string, double?> TemperatureRatings { get; set; }`

What would I need to add to target the double part of the dictionary?

**Comment by CJM3407** [comment]
One Question for a potential problem.  I am using Swashbuckle.AspNetCore.  Is that a problem?  Should I be using NSwag (I realized I got to this github through google searches) and I thought this was originally for NswagStudio.  But I can't find that ItemsCanBeNull attribute, and that made me realize i wasn't potentially using the correct nuget library

**Comment by RicoSuter** [comment]
> I am using Swashbuckle.AspNetCore

ah yes, that explains a lot. With that i can search in nswag spec generator for a very long time...

The additional properties generated by swashbuckle is missing the nullable part... nswag/njs would generate the spec as you’d expect.

**Comment by CJM3407** [comment]
Ok thanks.  Sorry for the confusion.  And thanks for the help.
