### ISSUE TITLE
NSwagStudio new version no longer generates a Constructor with BaseUrl

### ISSUE THREAD

**Issue by CJM3407** [RicoSuter/NSwag#3315]
I am not 100% if the owner of this repo is also responsible for NSwagStudio, but I figured I would ask this here first.

In my attempt to figure out a Dictionary of nullable properties I updated my NSwagStudio.  

The new version of NSwagStudio apparently stopped generating the BaseUrl property into the Generated client constructor.  This is negatively impacting my logic because I was using Unity and ParameterOverrides to set the BaseUrl.  I am using the generated interface, so we can Unit test the logic around the generated client logic.  And because that interface has nothing for the Base URL.  I cannot set the Base URL while resolving interface.  

I really want to avoid editing the Generated class too much (using the nswag configuration file to get as close to correct).  Side note: I currently have to do a find and replace on all DisallowNulls to AllowNulls.  

Any ideas?  Was this intended to remove the base url from the constructor?

**Comment by CJM3407** [comment]
`using (var http = new HttpClient())
                {
                    var emsClient = Container.Resolve<IXmsnAssetClient>(new ResolverOverride[]
                    {
                        new ParameterOverride("baseUrl", Properties.Settings.Default.XmsnAssetBaseUrl),
                        new ParameterOverride("httpClient", http)
                    });
                    var response = func(emsClient).GetAwaiter().GetResult();
                    return response;
                }
`

**Comment by RicoSuter** [comment]
Can you provide the version you used before?

**Comment by CJM3407** [comment]
I am honestly not sure.  I am currently at 13.10  but i think it was some where in the 12  or early v13

**Comment by RicoSuter** [comment]
The current default is a property on the client (BaseUrl) and not an injected parameter anymore... mainly because you should either set the base URL on the HttpClient or it is already defined internally (generated) from the OpenAPI spec...

**Comment by CJM3407** [comment]
Ok, I didn't realized there was an option to use the baseaddress uri on http client.  I seem to have it working once I unchecked the "Use the base URL for the request"
Thank you
