### ISSUE TITLE
openApiToTypeScriptClient - command line reads nswag.json but doesn't respect it

### ISSUE THREAD

**Issue by doruxan** [RicoSuter/NSwag#3323]
Hi!

I'm running nswag.exe from a react script. I'm sure it reads the nswag.json file because if I change the name, cli crashes. But I can't make it apply my preferences.

Here is my nswag.json;

`{
    "runtime": "WinX64",
    "defaultVariables": null,
    "documentGenerator": {
      "fromDocument": {
        "url": "http://redocly.github.io/redoc/openapi.yaml",
        "output": null,
        "newLineBehavior": "Auto"
      }
    },
    "codeGenerators": {
      "openApiToTypeScriptClient": {
        "className": "{controller}Client",
        "moduleName": "",
        "namespace": "",
        "typeScriptVersion": 2.7,
        "template": "Fetch",
        "promiseType": "Promise",
        "httpClass": "HttpClient",
        "withCredentials": false,
        "useSingletonProvider": false,
        "injectionTokenType": "OpaqueToken",
        "rxJsVersion": 6.0,
        "dateTimeType": "Date",
        "nullValue": "Undefined",
        "generateClientClasses": true,
        "generateClientInterfaces": true,
        "generateOptionalParameters": false,
        "exportTypes": true,
        "wrapDtoExceptions": false,
        "exceptionClass": "ApiException",
        "clientBaseClass": "AuthorizedApiBase",
        "wrapResponses": false,
        "wrapResponseMethods": [],
        "generateResponseClasses": true,
        "responseClass": "SwaggerResponse",
        "protectedMethods": [],
        "configurationClass": "IConfig",
        "useTransformOptionsMethod": false,
        "useTransformResultMethod": false,
        "generateDtoTypes": true,
        "operationGenerationMode": "MultipleClientsFromPathSegments",
        "markOptionalProperties": true,
        "generateCloneMethod": false,
        "typeStyle": "Class",
        "enumStyle": "Enum",
        "useLeafType": false,
        "classTypes": [],
        "extendedClasses": [],
        "extensionCode": null,
        "generateDefaultValues": true,
        "excludedTypeNames": [],
        "excludedParameterNames": [],
        "handleReferences": false,
        "generateConstructorInterface": true,
        "convertConstructorInterfaceData": false,
        "importRequiredTypes": true,
        "useGetBaseUrlMethod": false,
        "baseUrlTokenName": "API_BASE_URL",
        "queryNullValue": "",
        "useAbortSignal": false,
        "inlineNamedDictionaries": false,
        "inlineNamedAny": false,
        "templateDirectory": null,
        "typeNameGeneratorType": null,
        "propertyNameGeneratorType": null,
        "enumNameGeneratorType": null,
        "serviceHost": null,
        "serviceSchemes": null,
        "output": "src/clients/GkBankClient.ts",
        "newLineBehavior": "Auto"
      }
    }
  }`

this is my script:

`"scripts": {
    "generate-clients": "curl.exe --output src/clients/apiswag.json --url http://localhost:8080/swagger.json && nswag openapi2tsclient /input:src/clients/apiswag.json /output:src/clients/GkClient.ts"
  },`

**Comment by jeremyVignelles** [comment]
And what exactly doesn't work? what did you expect and what did you get?

**Comment by doruxan** [comment]
"codeGenerators": {
            "openApiToTypeScriptClient": {
                "className": "{controller}Client",
                "generateClientInterfaces": true,
                "clientBaseClass": "AuthorizedApiBase",
                "configurationClass": "IConfig",
                "operationGenerationMode": "MultipleClientsFromPathSegments",
            }
        }

these are the thing s I've changed

**Comment by doruxan** [comment]
This was beacuse I did not include nswag.json in my command.
