### ISSUE TITLE
Reverse proxy handling doesn't recognize lower cased X-Forwarded-* header keys

### ISSUE THREAD

**Issue by sandord** [RicoSuter/NSwag#3360]
My Proxy is emitting all lower-case header keys. However, the [NSwag.AspNetCore.HttpRequestExtension.GetBasePath](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/HttpRequestExtension.cs#L46) method expects the `X-Forwarded-*` header keys to be written using proper case.

So in my case this means that the `x-forwarded-host` header which my reverse proxy (Envoy) is sending, is not recognized.

I've tried to force the proxy to emit proper case header keys but it doesn't seem to be possible.

I guess the right fix for this would be performing a case-insensitive comparison in `GetBasePath`. I don't see any dangers in that but perhaps I missing something?

**Comment by sandord** [comment]
As a workaround, the following can be used:

    app.UseSwaggerUi3(options =>
    {
        options.TransformToExternalPath = (internalUiRoute, request) =>
        {
            static string GetBasePath(HttpRequest request)
            {
                const string forwardedProtoHeader = "X-Forwarded-Proto";
                const string forwardedPrefixHeader = "X-Forwarded-Prefix";
                const string forwardedHostHeader = "X-Forwarded-Host";
    
                var prefix = TryGetFirstHeader(request.Headers, forwardedPrefixHeader);
    
                if (prefix != null)
                    return "/" + prefix.Trim('/');
    
                var host = TryGetFirstHeader(request.Headers, forwardedHostHeader);
                string basePath;
    
                if (host != null)
                {
                    var proto = TryGetFirstHeader(request.Headers, forwardedProtoHeader) ?? "http";
                    basePath = new Uri($"{proto}://{host}").AbsolutePath;
                }
                else
                {
                    basePath = "";
                }
    
                if (request.PathBase.HasValue)
                {
                    basePath = basePath.TrimEnd('/') + "/" + request.PathBase.Value;
                }
    
                return ("/" + basePath.Trim('/')).TrimEnd('/');
            }
    
            static string? TryGetFirstHeader(IHeaderDictionary headers, string name)
            {
                var values = headers.Where(n => string.Equals(n.Key, name, StringComparison.OrdinalIgnoreCase)).ToList();
    
                return values.Any() ? (values.First().Value.FirstOrDefault() ?? "").Split(',').Select(s => s.Trim()).First() : null;
            }
    
            return '/' + (GetBasePath(request).TrimEnd('/') + '/' + internalUiRoute?.TrimStart('/')).Trim('/');
        };
    });

**Comment by RicoSuter** [comment]
Thanks for posting a solution. I think we should fix it directly in NSwag and use case insensitive behavior: 
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/HttpRequestExtension.cs#L38

Do you have the time to create a PR to fix this?

**Comment by sandord** [comment]
> Thanks for posting a solution. I think we should fix it directly in NSwag and use case insensitive behavior:
> https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.AspNetCore/HttpRequestExtension.cs#L38
> 
> Do you have the time to create a PR to fix this?

Sure thing. I've filed a PR: #3367.

**Comment by sandord** [comment]
Ooh I see I didn't read your comment properly. So, I'll update the `GetServerUrl` method soon as well.

**Comment by sandord** [comment]
> Ooh I see I didn't read your comment properly. So, I'll update the `GetServerUrl` method soon as well.

Done.

**Comment by sandord** [comment]
I guess the help-wanted label can be removed now.

**Comment by RicoSuter** [comment]
Thanks for the PRs.
