### ISSUE TITLE
code duplicates ``ObjectResponseResult``

### ISSUE THREAD

**Issue by Ma3yTa** [RicoSuter/NSwag#3362]
OpenAPI 3.0.1 JSON [openapi.json.txt](https://github.com/RicoSuter/NSwag/files/6129688/openapi.json.txt)
```xml
<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
		<PackageReference Include="NSwag.ApiDescription.Client" Version="13.10.8">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<OpenApiReference Include="OpenAPIs\openapi.json" Namespace="Contacts.Client">
			<SourceUri>https://api.hubspot.com/api-catalog-public/v1/apis/crm/v3/objects/contacts</SourceUri>
			<ClassName>ContactsClient</ClassName>
			<OutputPath>ContactsClient.cs</OutputPath>
			<Options>/GenerateClientInterfaces:false</Options>
			<CodeGenerator>NSwagCSharp</CodeGenerator>
		</OpenApiReference>
	</ItemGroup>
```

**Comment by jsmale** [comment]
I have the same issue with a swagger.json generated by NSwag 13.10.8, then using openapi2csclient to generate the C# client.

**Comment by RicoSuter** [comment]
If you use `<ClassName>ContactsClient</ClassName>` without `{controller}` (not `<ClassName>{controller}Client</ClassName>`) NSwag will generate multiple ContactsClient classes.

Either you use the `{controller}` placeholder or you change the OperationGenerationMode from "MultipleClientsFromOperationId" to e.g. "SingleClientFromOperationId":

![image](https://user-images.githubusercontent.com/2603405/114523621-bc8d0600-9c44-11eb-85c5-b7d2671eee5d.png)
