### ISSUE TITLE
Is there a way to set camelCase convention for a non-mvc app?

### ISSUE THREAD

**Issue by bzuillsmith** [RicoSuter/NSwag#3372]
I'm trying to understand how make the csharp client use camelCase property names. I have an ASP.net application from which we generate the Open API doc and clients. We do this with the MSBuild NSwag package. It looks like if you add `AddMvc().AddJsonOptions(...)` then you can get it to use the camelCase convention with System.Text.Json. But there is no mention of `AddControllers().AddJsonOptions(...)` and taking a glance at the related NSwag code, it requests Mvc options from the service container. I'd rather not add MVC to my app just to make it work. Am I missing something? Is there an alternative?

**Comment by jeremyVignelles** [comment]
Did you try it? It should work as long as the API explorer is present.

**Comment by bzuillsmith** [comment]
I did. I don't totally understand what nswag is doing. Is it calling my startup file and then trying to read from the registered services? I've got the following in `ConfigureServices` but it seems to have no effect on my generated client.

    ...
    services.AddControllers()
            .AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.Converters.Add(new Converter1());
                options.JsonSerializerOptions.Converters.Add(new Converter2());
                options.JsonSerializerOptions.Converters.Add(new Converter3());
                options.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
            });


            services.AddOpenApiDocument();
            ...

**Comment by bzuillsmith** [comment]
It's very possible I'm just missing something obvious. You mentioned an "ApiExplorer". What is that? I see one reference to something like that in the docs here https://github.com/RicoSuter/NSwag/wiki/AspNetCore-Middleware where you can call 

    .AddMvcCore()
    .AddVersionedApiExplorer(options =>
    {
        options.GroupNameFormat = "VVV";
        options.SubstituteApiVersionInUrl = true;
    });

**Comment by bzuillsmith** [comment]
Been trying things for a few hours. No idea what I'm missing.

My MsBuild target:

    <Target Name="NSwag" BeforeTargets="AfterBuild" Condition="'$(TF_BUILD)'!='True'">
      <Exec ConsoleToMSBuild="true" ContinueOnError="true" Command="$(NSwagExe_Net50) run nswag.json /variables:Configuration=$(Configuration)">
        <Output TaskParameter="ExitCode" PropertyName="NSwagExitCode" />
        <Output TaskParameter="ConsoleOutput" PropertyName="NSwagOutput" />
      </Exec>

      <Message Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' == '0'" Importance="low" />
      <Error Text="$(NSwagOutput)" Condition="'$(NSwagExitCode)' != '0'" />
    </Target>

Key parts (I think of my nswag.json):


    "runtime": "Net50",
    "defaultVariables": "CSharpOutputPath=my\\client\\project\\folder",
    "documentGenerator": {
      "aspNetCoreToOpenApi": {
        "project": "My.Project.csproj",
        "msBuildProjectExtensionsPath": null,
        "configuration": "$(Configuration)",
        "runtime": "",
        "targetFramework": "",
        "noBuild": true,
        "verbose": true,
        "workingDirectory": null,
        "requireParametersWithoutDefault": true,
        "apiGroupNames": null,
        "defaultPropertyNameHandling": "CamelCase",
        ...
        "aspNetCoreEnvironment": "Development",
        "createWebHostBuilderMethod": null,
        "startupType": null,
        "allowNullableBodyParameters": true,
        "output": "openapi.json",
        "outputType": "OpenApi3",
        "newLineBehavior": "Auto",
        "assemblyPaths": [],
        "assemblyConfig": null,
        "referencePaths": [],
        "useNuGetCache": false
      }
    },
    "codeGenerators": {
      "openApiToCSharpClient": {
        "jsonLibrary": "SystemTextJson",
        "generateClientClasses": true,
        "generateClientInterfaces": true,
        "exposeJsonSerializerSettings": false,
        "generateUpdateJsonSerializerSettingsMethod": true,
        "generateJsonMethods": true,
        "jsonSerializerSettingsTransformationMethod": null,
        ...
      }
    }

**Comment by jeremyVignelles** [comment]
I'm not sure about setting STJ casing convention, but I don't think MVC vs controllers make a difference.
I'm just realizing... Your asking about the client code, so it should be a property of the client code generator, nothing to do with your server.
Did you try NSwagStudio to see all options there? I think there is an option, but I don't remember where.

**Comment by bzuillsmith** [comment]
Ah, of course. Thanks for pointing that out. I feel silly now. I have a fair amount of code (models and converters) that is shared across the backend and frontend. But of course there is no reason for nswag to know or assume these things are shared. I just got lost in it that I couldn't see that obvious point.

So then, client converters appear to be easy to specify, but I still can't find any client option for camelCase serialization. I see references to `GenerateUpdateJsonSerializerSettingsMethod` so I'll look into that next I guess. Perhaps it will take a partial class that sets it via this method or something?

**Comment by bzuillsmith** [comment]
Ok, I figured out what set me on the path of thinking my server-side service configuration would affect my clients. See @RicoSuter's response [here](https://github.com/RicoSuter/NSwag/issues/1809) almost the same question. Maybe things have changed in the spec that no longer make this answer valid?

Aside from that, the following got things working for me the way I want.

1. Set `GenerateUpdateJsonSerializerSettingsMethod` to `false`.
2.  Create a custom base class that has the update method in it (see below)
3.  Set ClientBaseClass to a custom class I create

The base class is extremely simple:

    public abstract class ClientBase
    {
        protected void UpdateJsonSerializerSettings(System.Text.Json.JsonSerializerOptions settings)
        {
            settings.PropertyNamingPolicy = System.Text.Json.JsonNamingPolicy.CamelCase;
        } 
    }

Doesn't seem too hard now that I've done it, but I definitely expected there to be a simple setting. It seems like a common use case and based on #1809 I may be missing some other path for getting this done. I'd appreciate feedback on this.

**Comment by jeremyVignelles** [comment]
STJ support is quite new, so there might be some rough edges.
If there's something you want to be improved, please make a proposal and/or open a PR

**Comment by bzuillsmith** [comment]
For sure. Just wanted to be sure I wasn't missing anything. Seems like I've got stuff working.
