### ISSUE TITLE
C# client generator code bug

### ISSUE THREAD

**Issue by dmandreev** [RicoSuter/NSwag#3381]
Due to logic in /src/NSwag.CodeGeneration.CSharp/Models/CSharpClientTemplateModel.cs
line 173-176
```
                    parameterCode = _settings.CSharpGeneratorSettings.JsonLibrary == CSharpJsonLibrary.NewtonsoftJson ?
                        "new Newtonsoft.Json.JsonSerializerSettings { Converters = " + parameterCode.Substring(2) + " }" :
                        parameterCode.Substring(2);
```
generated code contains

var settings = w Newtonsoft.Json.JsonSerializerSettings();

e.g. "new" substringed to __w

**Comment by jeremyVignelles** [comment]
I don't understand what you mean, how this code could generate `var settings = w Newtonsoft.Json.JsonSerializerSettings();` ?

Did you select Newtonsoft.Json as the JSON library ?

We would need a way to reproduce the issue, please add more info.

**Comment by dmandreev** [comment]
I'll try create repro asap

**Comment by dmandreev** [comment]
Sorry, missed JsonLibrary= CSharpJsonLibrary.NewtonsoftJson after 13.10.1.0>13.10.8.0 update

**Comment by dmandreev** [comment]
Rico, i checked twice and noticed that bug is exist if i update NJsonSchema to v 10.4.0 repro is here https://github.com/dmandreev/nswagbug

**Comment by RicoSuter** [comment]
Is this still an issue?

**Comment by dmandreev** [comment]
After updating NJsonSchema to 10.4.1.0, and NSwag to 13.10.9.0, bug is now doesn't reproduce.

Thank you for your support!
