### ISSUE TITLE
 Enum generation - underlying int values doesn't match the original enum

### ISSUE THREAD

**Issue by aunikitin** [RicoSuter/NSwag#3382]
Hello, notice that generated enum doesn't match the original one.
How can I fix this behaviour?
![image](https://user-images.githubusercontent.com/38141491/112751523-fc6ab100-8fe7-11eb-8f0b-b52db84cfcb4.png)
![image](https://user-images.githubusercontent.com/38141491/112751546-202df700-8fe8-11eb-99da-bcb5080920e7.png)

**Comment by jeremyVignelles** [comment]
With string enums, there is no way to know the int value of the enums in the OpenApiSpec. Use number enums if you want the int value to match

**Comment by aunikitin** [comment]
@jeremyVignelles thank u for reply.
Does the usage of StringEnumConverter in Json Serializer become cause of this behaviour?

**Comment by jeremyVignelles** [comment]
That's very likely. I think Nswag is inspecting the service provider to detect how things are serialized

**Comment by RicoSuter** [comment]
> I think Nswag is inspecting the service provider to detect how things are serialized

NSwag checks whether there is a global StringEnumConverter registered in the serializer configs, it checks each property whether it has the converter attribute and also whether there is an attribute on the enum type itself.
