### ISSUE TITLE
Change generators minimal supported versions to .NET 4.6.1 and .NET Standard 2.0

### ISSUE THREAD

**Issue by lahma** [RicoSuter/NSwag#3384]
## Background

* .NET 4.6.1 is the oldest supported full framework version, this has API parity with .NET Standard 2.0 even though has binding redirect problems why separate target for full framework is needed
* Microsoft has stated that we should forget < .NET Standard 2.0 and use 2.0 or later
* .NET Core < 3.1, except for 2.1 is no longer supported
* If there still are people targeted against earlier versions I would argue they can probably live with the latest version that still supported said old versions

## Benefits

* Core gets cleaner, less ifdefs
* Performance improves, things like `DynamicApis.XPathEvaluate` can be changed to use direct invocation which is quite a lot faster
    * Also other such DynamicApis implementations can be removed/replaced with invoking the actual API

## Actions to take

* Remove all < NET Standard 2.0 targets from projects, make sure netstandard2.0 is present for libraries
* Remove all < NET 4.6.1 targets from projects, replace with net461 where lower was supported
* Remove supported from exe projects for anything lower than netcoreapp3.1or is netcoreapp2.1

Will you accept a PR which changes these targets? This would make optimization story a lot easier too.

**Comment by lahma** [comment]
If this is accepted I would then apply the same logic to dependencies (NJsonSchema, Namotion.Reflection).

**Comment by lahma** [comment]
@RicoSuter can you please share your thoughts about this, are there pressing reasons to retain the old frameworks and targets? Say if v14 would drop support for older and if there are depending projects they could continue using v13?

**Comment by Numpsy** [comment]
For what it's worth:

The projects i'm using NSwag in that are in active development at this point are .NETCore3.1 and up, but there are some older things using 2.1, and I don't think 

> .NET Core < 3.1 is no longer supported

is actually true, because 2.1 is still under LTS support until August?

2.2 and 3.0 are out of support though, and 2.2 has been a source of some security warnings from tools like Whitesource (because MS aren't fixing CVEs in it as they still are for 2.1, so there are no fixed Nuget packages about to upgrade to)

**Comment by lahma** [comment]
Thanks @Numpsy , I stand corrected, 2.1 is indeed supported until August 21, 2021 . I've updated the description to make exception for 2.1 and as it's netstandard2.0 should be fine too.

**Comment by RicoSuter** [comment]
I try to keep support for older frameworks as long as possible because I know that there are many ppl still using that - even if it's not supported... same applies for Web API (full .net). If there is not really a very good reason I'd keep the targets for now...

**Comment by lahma** [comment]
This change sadly is prerequisite for https://github.com/RicoSuter/NJsonSchema/pull/1346 . Not sure if it's a good reason that our code generation (OpenAPI->TS+C# client) with custom build of NSwag including Fluid drops from 35 seconds to 7 seconds 🙂 Also open possibility for other optimizations as old template engine isn't hiding everything as it's taking 80% of time..

I can probably run my custom fork until time is right, I understand both sides of the issue. At some point I think < netstandard2.0 should be dropped as legacy.

**Comment by RicoSuter** [comment]
Can we drop support of old TFMs only for the *.CodeGeneration packages (and eg keep NJsonSchema, NSwag.Core as is)?
The Fluid/DotLiquid is only used in these packages... and they are mostly not directly used in "legacy apps"

**Comment by Numpsy** [comment]
fwiw, my usage/experience, such as it is, is that the runtimes we have to support for end products can be quite restricted or have to support older versions, but build tools are much more flexible.

example:
I'm working on a product at the moment that uses nswag.msbuild to generate C# client libraries for various things, and one of those is used in some Powershell commandlets and has a requirement to support Powershell 5.1 (so it can't just rely on the newer versions), so it needs to support that.

However, the runtime required to run the code generator in the first place matters much less - so if it required a new version of .NETCore but was much faster and the created code itself still works with old runtimes, then that's a  nice gain.

Just my trivial position ;-)

**Comment by RicoSuter** [comment]
@Numpsy exactly, that's what i wanted to say... code generation is build time so there we do not need to support very old stuff. But e.g. NJsonSchema (schema validation) is also used at runtime and should support older runtimes...

**Comment by lahma** [comment]
If this is the case that would be helpful, so this issue would target code-generation related items. I tweaked the NJsonSchema PR not to change the main project's targets, only code generation is affected there now.

What I see on NSwag side now (I'm using directory project references instead of nuget packages on my local branch) is that now it's possible to reduce the impacted csproj area. 

Still affected:

* NSwag.AspNet*
* NSwag.Commands
* NSwag.ConsoleCore
* NSwag.Generation*

The current diff can be found [here](https://github.com/RicoSuter/NSwag/compare/master...lahma:fluid?expand=1).
