### ISSUE TITLE
Generated C# client does not make enum nullable

### ISSUE THREAD

**Issue by nHellweg** [RicoSuter/NSwag#3394]
Given the below schema the enumVal is not marked as nullable even though it is not required. I found the issue in version 13.10.1.0 using the openapi2csclient command on the cli tool. Based on this previous issue (https://github.com/RicoSuter/NSwag/issues/1851) I am assuming this would be a bug and not expected behavior and might possibly be related to a difference in swagger 2.0 and openapi 3.0.0. Any help would be appreciated.

```
openapi: 3.0.0
info:
  title: Test Swagger
  description: This endpoint doesnt create a nullable enum
  version: 1.0.0
paths:
  /test:
    post:
      tags:
        - test
      operationId: test
      summary: Test Swagger
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestPayload'
        description: Test Swagger
        required: true
      responses:
        '200':
          description: Successful operation
        
  
components:
  schemas:

    TestPayload:
      type: object
      properties:
          stringVal:
            type: string
          enumVal:
            $ref: '#/components/schemas/TestEnum'
      required: ['stringVal']
    TestEnum:
      type: string
      enum:
        - Value1
        - Value2
        - Value3
```

**Comment by nHellweg** [comment]
It looks like the same unit test that was used in the issue (https://github.com/RicoSuter/NSwag/issues/1851) replicates the issue if you just switch `var generator = new CSharpGenerator(schema, new CSharpGeneratorSettings { SchemaType = SchemaType.Swagger2});` to `var generator = new CSharpGenerator(schema, new CSharpGeneratorSettings { SchemaType = SchemaType.OpenApi3 });`

**Comment by RicoSuter** [comment]
required and nullable are not the same in OAI 3 - to make it nullable you need to also add `nullable: true` - optional properties are not generated as nullable in OAI 3 - maybe there is a config to make them nullable, try: 

![image](https://user-images.githubusercontent.com/2603405/113996474-7fe19900-9857-11eb-8d6e-2d30b2fd8e35.png)

**Comment by nHellweg** [comment]
@RicoSuter  Sorry for taking so long on this. It does seem like that property solves my problem. Sorry for the misunderstanding.
