### ISSUE TITLE
where is the physical location of swagger file generated by Nswag?

### ISSUE THREAD

**Issue by aim-for-better** [RicoSuter/NSwag#3396]
Hi everyone,

I used the NSwag to generate the swagger.json, I can access the URI https://localhost/swagger/v1/swagger.json.
**However**, I **can not** find this swagger.json file in my local machine.
Could you please help find the file's location?
Another question is: will Nswag generate this file in build phase?
Thanks

**Comment by jeremyVignelles** [comment]
With the NSwag middleware, it's generated when requested and stays only in memory.
You can generate the swagger.json on your file system by using NSwag studio or the NSwag CLI.

If you want to generate that file at build time, there is NSwag.MSBuild which basically runs the NSwag CLI when the project is built, but you can run the CLI the way you want.

**Comment by aim-for-better** [comment]
> With the NSwag middleware, it's generated when requested and stays only in memory.
> You can generate the swagger.json on your file system by using NSwag studio or the NSwag CLI.
> 
> If you want to generate that file at build time, there is NSwag.MSBuild which basically runs the NSwag CLI when the project is built, but you can run the CLI the way you want.

@jeremyVignelles  Thanks.
