### ISSUE TITLE
OpenApiGenerateDocumentsOnBuild broken in v13.10.09

### ISSUE THREAD

**Issue by cm-andrews** [RicoSuter/NSwag#3403]
OpenApi documents are no longer being correctly generated on build in v13.10.09 #3402 

Reverting to v13.10.08 fixes the issue immediately. Did the syntax change?

`<OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>`

**Comment by Numpsy** [comment]
I just tried updating to the latest version myself and noticed that nuget listed the ```Microsoft.Extensions.ApiDescription.Server``` package as being uninstalled, which might explain it? (that package doesn't seem to be referenced by the newly added .NETCore 3.1 and net50 TFMs)

**Comment by cm-andrews** [comment]
Thanks, adding the `Microsoft.Extensions.ApiDescription.Server` fixes the issue for me as well.

**Comment by axelgenus** [comment]
I faced the same issue updating to 13.10.9 today and I solved as @Numpsy suggested.

**Comment by RicoSuter** [comment]
Should we add this package to NSwag.AspNetCore?

**Comment by cm-andrews** [comment]
That would solve the Problem, yes

**Comment by axelgenus** [comment]
@RicoSuter this is a revision bump and should not introduce breaking changes but adding the `Microsoft.Extensions.ApiDescription.Server` manually to the main project seems more streamlined IMO. Also it does not add hardcoded dependencies on unnecessary packages.

**Comment by Numpsy** [comment]
> 
> 
> Should we add this package to NSwag.AspNetCore?

It already is a dependancy in the .NET 4.5.1 and netstandard 1.6/2.0 TFMs of ```NSwag.AspNetCore```, but not in the newly added .NETCore 3.1/.NET 5.0 targets (so the different behaviour that people are seeing would be beacuse because 3.1+ consumers would previously pick up the netstandard2.0 version and get ```Microsoft.Extensions.ApiDescription.Server``` indirectly and will now pick the newer targets and won't).

if nothing else, it seems a bit inconsistent?

**Comment by RicoSuter** [comment]
Created a PR: https://github.com/RicoSuter/NSwag/pull/3411
I think it's fine to add as it's only an extension package

**Comment by Numpsy** [comment]
I usually agree with minimizing the dependencies and you can argue that that one is only optional, but then I believe that ```Microsoft.Extensions.ApiDescription.Server``` is a build time only thing anyway, and doesn't add any runtime dependencies?

**Comment by RicoSuter** [comment]
Yes, the package doesnt contain any DLL refs, only build targets and tools
https://apimundo.com/organizations/nuget-org/nuget-feeds/public/packages/Microsoft.Extensions.ApiDescription.Server/versions/5.0.5?tab=nuspec

I think it's fine to add them.
