### ISSUE TITLE
How does schema validation work in Asp.Net Core pipeline?

### ISSUE THREAD

**Issue by serefarikan** [RicoSuter/NSwag#3406]
Hi, I've been going through the NSwag code as well as NJsonSchema code but I cannot figure out how NJsonSchema's validation is wired into asp.net core request processing. 

I'm assuming at some point validation is taking place so that json payload that is not compatible with a schema won't be allowed to go through, but how and where that is taking place, I have no idea yet. 

I could not see any references to validation in NSwag documentation/readme, so I'd gladly create a pull request for documentation if someone can help me find my way in the code base(s)

**Comment by RicoSuter** [comment]
> but I cannot figure out how NJsonSchema's validation is wired into asp.net core request processing.

Validation is currently not done when using NSwag... it's currently only used for OpenAPI spec and client code generation.

For validation I recommend to use the regular ASP.NET Core model binding validation process..

**Comment by serefarikan** [comment]
@RicoSuter many thanks. May I ask you to briefly expand your response? 

I was referring to data validation, which NJsonSchema is capable of performing, as per its documentation, but you say:

> it's currently only used for OpenAPI spec and client code generation.

can you very briefly explain what do you mean by that? How is schema validation used in these two tasks? 

Great work btw, I'm trying to wrap my head around how to use it ;)

**Comment by RicoSuter** [comment]
The NJsonSchema JSON Schema validation feature is not used in NSwag at all. The toolchain only uses the NJS for generating DTO schemas (part of the openapi specs) and generate client code (DTO classes).

**Comment by serefarikan** [comment]
Thanks a lot for the explanation. Closing this issue now.
