### ISSUE TITLE
How Nswag to control the property position in swagger file?

### ISSUE THREAD

**Issue by aim-for-better** [RicoSuter/NSwag#3410]
The question is as bellow:
1. Now NSwag generated swagger spec is ask bellow 
```
{
 "swagger": "",
 "info": {},
  "host": "",  // The host is at the third position
 "schemes": ""
}
```

2. How should I do ? Or where should I config to get the bellow result:
```
{
  "swagger": "",
  "host": "",   // The host is at the second position
 "info": {},
 "schemes": ""
}
```

The difference is the position of `host` property
Thanks

**Comment by RicoSuter** [comment]
The order is controlled with the newtonsoft attribute (Order): 
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/OpenApiDocument.cs#L60

**Comment by aim-for-better** [comment]
> The order is controlled with the newtonsoft attribute (Order):
> https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core/OpenApiDocument.cs#L60

Yes, I also found it from source code, but how can I control this when i using this package? Where I can override this order property?  Thanks

**Comment by RicoSuter** [comment]
I think you cannot change that dynamically from "outside", ie. without changing NSwag.Core

**Comment by aim-for-better** [comment]
> postprocess the generated JSON and reorder.

Thanks
