### ISSUE TITLE
Generation TypeScript In Vue3; Use Axios

### ISSUE THREAD

**Issue by WangJunZzz** [RicoSuter/NSwag#3413]
use NSwag.CodeGeneration.TypeScript
 use Axios
 use vue3
 but , I have a question, How do I add a request header and set baseurl？

**Comment by denu5** [comment]
you can add a custom axios client that is using interceptors to set headers, where you also configure a custom base url

**Comment by WangJunZzz** [comment]
@denu5  Have a demo?

**Comment by CoderTonyB** [comment]
> use NSwag.CodeGeneration.TypeScript
> use Axios
> use vue3
> but , I have a question, How do I add a request header and set baseurl？

Did you ever get an answer on this?  Pulling my hair out...

`this.instance = axios.create({ baseURL: import.meta.env.VITE_API_URL?.toString() })
		this._initializeResponseInterceptor()
		this._initializeRequestInterceptor()
		this.apiClient = new ApiClient(import.meta.env.VITE_API_URL?.toString(), this.instance)`

When I do this, which should inject my instance, I get an error from the super() call in the nswag generated error handler
