### ISSUE TITLE
GeneratePrepareRequestAndProcessResponseAsAsyncMethods generates invalid client code

### ISSUE THREAD

**Issue by jclijmans** [RicoSuter/NSwag#3428]
Generating CSharp client code with generatePrepareRequestAndProcessResponseAsAsyncMethods true results in invalid code.

The generated client code does not have a definition for the partial methods PrepareRequestAsync and ProcessResponseAsync

This error was introduced by PR [#3248 ](https://github.com/RicoSuter/NSwag/pull/3248) that implements the async pattern

It introduced an error in  src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid where there is no else for the statement
{% if GeneratePrepareRequestAndProcessResponseAsAsyncMethods == false -%}
on line 87

**Comment by RicoSuter** [comment]
Can you create a PR to fix that?

**Comment by jclijmans** [comment]
I created the PR, hopefully it's ok.
I also noted that there was a unittest failing in the current code of master. In SystemTextJsonTests the test WhenSystemTextOptionsIsUsed_ThenOptionsAreConverted fails.

I did not update that test because I'm not sure what is going on

**Comment by jclijmans** [comment]
For later reference :
Partial methods cannot have return values and can thus must have void as return type.
This means for an async method you would have async void, something you definitely don't want.

So the only option is to define the partial method definitions in the custom class.
