### ISSUE TITLE
Add the ability to inject custom items in the constructor.

### ISSUE THREAD

**Issue by wrwoodman** [RicoSuter/NSwag#3438]
I would like to request an enhancement to the code generation in NSwagStudio.  In particular, I would like to be able to specify additional objects to be injected into the constructor with the expectation that it is declared in the base class.

The impetus behind this was the need to inject a security class into the call so that a bearer token could be retrieved and added to the call.  I then wanted to wire everything up in the DI engine so that the lifetimes are managed by the DI engine.  In order to achieve this, I had to add my class to the constructor of the generated code and have it set the value for the base class.

```
public ConsumerAdapterClient(System.Net.Http.HttpClient httpClient, IClientCredentialProvider clientCredentialProvider)
{
	base.ClientCredentialProvider = clientCredentialProvider;
	_httpClient = httpClient;
	_settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings);
}
```
In the code shown above, the IClientCredentialProvider class was added to the constructor after code generation.  It then expects to have a base class property that will accept the assignment of the passed-in object.  The reason I want this is so that code does not need to be manipulated after it is generated and would therefore reduce maintenance points.

Thank you for your consideration.

**Comment by wrwoodman** [comment]
I found a workaround and think it provides a better solution than what I suggest above.  See [this question](https://stackoverflow.com/questions/67236829/how-can-i-do-dependency-injection-without-newing-a-class-instance-and-providi) on SO for a complete discussion.
Thanks

**Comment by RicoSuter** [comment]
There is an option to inject a configuration object, you can use this to be injected via DI etc.

**Comment by LockTar** [comment]
I had the same problem. I needed to inject the `IClientCredentialsTokenManagementService` from [AccessTokenManagement](https://docs.duendesoftware.com/accesstokenmanagement/workers/) in my constructor.

I think there are two options to solve this:

1. Use the configuration object (with optional interface)
2. Use a wrapper class (I like this one more)

Option 1 sample:
See the [documentation for the configuration class](https://github.com/RicoSuter/NSwag/wiki/CSharpClientGenerator#provide-configuration-object).

Use the `ClientBaseClass` and `ConfigurationClass` options when generating the client.
In example when generating via Connected Services in Visual Studio in your project file:
`<Options>/UseBaseUrl:false /GenerateClientInterfaces:true /GeneratePrepareRequestAndProcessResponseAsAsyncMethods:true /ConfigurationClass:IFooConfiguration /ClientBaseClass:FooBase</Options>`

This will result in a client like this:
```C#
public partial class MyClient : FooBase, IMyClient
```

With constructor:
```C#
public MyClient(IFooConfiguration configuration, System.Net.Http.HttpClient httpClient) : base(configuration)
{
    _httpClient = httpClient;
    Initialize();
}
```

You can then create the classes like this:
```C#
public interface IFooConfiguration
{
    IClientCredentialsTokenManagementService TokenManagementService { get; }
}

public class FooConfiguration : IFooConfiguration
{
    public FooConfiguration(IClientCredentialsTokenManagementService tokenManagementService)
    {
        TokenManagementService = tokenManagementService;
    }

    public IClientCredentialsTokenManagementService TokenManagementService { get; }
}

public class FooBase
{
    protected IClientCredentialsTokenManagementService TokenManagementService { get; init; }

    public FooBase(IFooConfiguration fooConfiguration)
    {
        TokenManagementService = fooConfiguration.TokenManagementService;
    }
}
```

The `TokenManagementService` property can than be used in your partial class of the client like this:
```C#
public partial class MyClient
{
    private Task PrepareRequestAsync(HttpClient client, HttpRequestMessage request, StringBuilder urlBuilder, CancellationToken cancellationToken = default(CancellationToken))
    {
        return Task.CompletedTask;
    }

    private async Task PrepareRequestAsync(HttpClient client, HttpRequestMessage request, string url, CancellationToken cancellationToken = default(CancellationToken))
    {
        // Get access token for client and set on my client
        ClientCredentialsToken token = await TokenManagementService.GetAccessTokenAsync("my.client");

        if (token.AccessToken == null)
        {
            throw new InvalidOperationException("Access token is null");
        }

        client.SetBearerToken(token.AccessToken);
    }

    private Task ProcessResponseAsync(HttpClient client, HttpResponseMessage request, CancellationToken cancellationToken = default(CancellationToken))
    {
        return Task.CompletedTask;
    }
}
```

Option 2:
Create a wrapper class. 
```C#
public class MyClientWrapper : MyClient, IMyClient
{    
    public MyClientWrapper(HttpClient httpClient, IClientCredentialsTokenManagementService tokenManagementService)
        : base(httpClient)
    {
        TokenManagementService = tokenManagementService;
    }
}
```

Adjust the partial class to define a property:
```C#
public partial class MyClient
{
    protected IClientCredentialsTokenManagementService TokenManagementService { get; init; }

    private Task PrepareRequestAsync(HttpClient client, HttpRequestMessage request, StringBuilder urlBuilder, CancellationToken cancellationToken = default(CancellationToken))
    {
        return Task.CompletedTask;
    }

    private async Task PrepareRequestAsync(HttpClient client, HttpRequestMessage request, string url, CancellationToken cancellationToken = default(CancellationToken))
    {
        // Get access token for client and set on my client
        ClientCredentialsToken token = await TokenManagementService.GetAccessTokenAsync("my.client");

        if (token.AccessToken == null)
        {
            throw new InvalidOperationException("Access token is null");
        }

        client.SetBearerToken(token.AccessToken);
    }

    private Task ProcessResponseAsync(HttpClient client, HttpResponseMessage request, CancellationToken cancellationToken = default(CancellationToken))
    {
        return Task.CompletedTask;
    }
}
```

Adjust injectection of the IHttpClientFactory to connect the interface to the wrapper and not the actual client:
```C#
builder.Services.AddHttpClient<IMyClient, MyClientWrapper>()
    .ConfigureHttpClient((serviceProvider, httpClient) =>
    {
        httpClient.BaseAddress = new Uri(myOptions.BaseUrl);
    });
```
