### ISSUE TITLE
"Try it out" doesn't work with JSON bodies that don't validate against the schema

### ISSUE THREAD

**Issue by GeorgDangl** [RicoSuter/NSwag#3451]
I've noticed this in one of our apps, where we use Swagger UI 3 with the generated `swagger.json`. For POST actions that have a JSON body, clicking in the `Execute` button doesn't do anything. 

You can try it out here:  
https://avacloud-api.dangl-it.com/swagger/index.html?url=/swagger/swagger.json#/AvaConversion/AvaConversion_ConvertToAva  
Just enable "Try it out", then remove the body and try just sending an empty JSON object like `{}`. Clicking on the `Execute` button doesn't do anything, it neither shows a validation error nor does it log anything to the console.

After a bit of debugging (with the prettified `swagger-ui-bundle.js`), it looks like this here is the error: https://github.com/swagger-api/swagger-ui/blob/master/src/core/utils.js#L495

So, at first glance, this looks like desired behavior. However, it worked in previous versions, and it also works in the latest official SwaggerUI. Ideally, it would just let me send the requests (since some of the required properties are actually just auto-generated read only properties, and thus aren't really required for POSTing JSON), or at least show the errors somehow.

**Comment by jeremyVignelles** [comment]
SwaggerUI is bundled with NSwag but is a third-party project. Is the code the same upstream?do we need an update?

If that's the same code upstream, you need to ask to the swaggerUI repo directly

**Comment by GeorgDangl** [comment]
I tried with the latest SwaggerUI, and that worked fine locally for me. I did both checkout their source code directly and serve it via their script, and I also just tried the latest bundle from SwaggerUI. In both cases, it worked for me.

So I _think_ it might just be an update required for SwaggerUI, but I didn't find anything in their releases that would indicate such a bug exists. I think the latest one that's bundled in NSWag is from around February or so, so not too old.

I also searched the original SwaggerUI repo, but from what I understood, the validation can't be disabled. However, I've been unable to really figure out why the validation fails for the bundled version, and why it works with the latest version...

**Comment by jeremyVignelles** [comment]
If you could clone this project and try to update the swagger UI dependency and eventually make a PR, that'd be great 👍

**Comment by GeorgDangl** [comment]
Sure, I will😀 Should be ready sometime this evening.

**Comment by RicoSuter** [comment]
@GeorgDangl Swagger UI updated...

**Comment by jeremyVignelles** [comment]
The NSwag package might not be published yet even the code has been updated, please wait 😉

**Comment by GeorgDangl** [comment]
Well, there was an update 4 hours ago on NuGet, v 13.11.0.
I just checked the dll itself, it actually still has v3.43 embedded. So, I guess I need to wait for a new version then😀

**Comment by GeorgDangl** [comment]
Just looked at the build history, figured it all out now, it’s not yet in 13.11.0.

**Comment by GeorgDangl** [comment]
For reference, looks like it's been this issue, which was resolved with SwaggerUI v3.48: https://github.com/swagger-api/swagger-ui/pull/7206

**Comment by RicoSuter** [comment]
v13.11.1

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/commits/master
Sorry for the confusion.

**Comment by GeorgDangl** [comment]
Great, thank you😀 Just tried it works, works perfectly! Thank you for reacting so quickly!
