### ISSUE TITLE
[TypeScriptClientGenerator] Is it possible to export types that are not used by any of the Web API controllers?

### ISSUE THREAD

**Issue by vladeck** [RicoSuter/NSwag#3457]
Lets say I have Web API project with a few controllers. Is there a configuration and/or C# attribute that I can use to instruct `TypeScriptClientGenerator` to export specific type even if it is not used by any of the controllers?

**Comment by RicoSuter** [comment]
See https://github.com/RicoSuter/NSwag/issues/3441

**Comment by vladeck** [comment]
Duplicate of #3441
