### ISSUE TITLE
info object version should be string instead of number according to open api spec

### ISSUE THREAD

**Issue by satuday** [RicoSuter/NSwag#3461]
according to the [open api spec](https://spec.openapis.org/oas/v3.1.0#fixed-fields-0), the version field in the info object is string type, but when output to yaml format, the version is number.

**Comment by RicoSuter** [comment]
This is a bug in the json to yaml conversion... 
There are quite some cases because it's not schema based, ie blind json to yaml conversion. 
Do you know a way to fix this (in NSwag.Core.Yaml)

**Comment by satuday** [comment]
looks like NSwag.Core.Yaml is using YamlDotNet to convert to yaml, which most likely is where the bug is in. taking a look at YamlDotNet to see if I can pin point the issue.

**Comment by satuday** [comment]
looks like this issue was reported but never got fix. https://github.com/aaubry/YamlDotNet/issues/265

**Comment by RicoSuter** [comment]
> looks like NSwag.Core.Yaml is using YamlDotNet to convert to yaml, which most likely is where the bug is in. taking a look at YamlDotNet to see if I can pin point the issue.

The problem is that it's a generic YAML -> JSON conversion and in the case of `1.0` you cannot tell from YAML only that it's a string and not a decimal and thus we get this problem... not sure how to fix this.

**Comment by satuday** [comment]
I see. I guess the issue is more fundamental with string in YAML. There seems to be a lot of [rules/caveat](https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml) on when string should be quoted. Maybe adding a `ChainedEventEmitter`  specifically targeting `OpenApiInfo` to always put quotes around `version` ?

**Comment by satuday** [comment]
another solution might be to add `[YamlMember(ScalarStyle = ScalarStyle.SingleQuoted)]` on `version`?

**Comment by satuday** [comment]
another solution is to directly serialize the document to YAML instead of converting to JSON then to YAML in [here](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Core.Yaml/OpenApiYamlDocument.cs#L81), but then you would need to still respect the `JsonIgnore` when converting to YAML, either by adding `YamlIgnoreAttribute` to the properties, or use `SerializerBuilder`  with `WithAttributeOverride`. I guess it depends on if you mind adding reference to `YamlDotNet ` in `NSwag.Core` or not.
