### ISSUE TITLE
rxjs version 7 not working with Nswag

### ISSUE THREAD

**Issue by florianraffl** [RicoSuter/NSwag#3463]
Hi there,

we`re having a problem with the new rxjs version 7 and Nswag generating our typescript client for some C# rest crud operations.
It looks like in this auto generated "getAll" method:
```
protected processGetAll(response: HttpResponseBase): Observable<Some_DTO[]> {
        const status = response.status;
        const responseBlob =
            response instanceof HttpResponse ? response.body :
            (<any>response).error instanceof Blob ? (<any>response).error : undefined;

        let _headers: any = {}; if (response.headers) { for (let key of response.headers.keys()) { _headers[key] = response.headers.get(key); }}
        if (status === 200) {
            return blobToText(responseBlob).pipe(_observableMergeMap(_responseText => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(Some_DTO.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return _observableOf(result200);
            }));
        } else if (status !== 200 && status !== 204) {
            return blobToText(responseBlob).pipe(_observableMergeMap((_responseText: string) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            }));
        }
        return _observableOf<Some_DTO[]>(<any>null);
    }
}
```
the `_observableMergeMap` method parameter has to be typed like that:
`_observableMergeMap((_responseText: string) => { ... }`

Otherwise it will throw that error:
```
Error: src/app/core/services/webapiclient.service.ts:95:74 - error TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.

95             let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
```

I also checked the nswag config and found a parameter:
```
...
"rxJsVersion": 6.0,
...
```
I also set that parameter to 7.0 but that didn't change a thing. 

So now my question is, is it possible to change the generation of the `_observableMergeMap` if the config parameter `"rxJsVersion"` is 7.0 to the typed one? 

Best regards,
Florian Raffl

**Comment by Thomas-Lederer** [comment]
+1

**Comment by RicoSuter** [comment]
Can someone create a PR with this fix?
Is this a breaking change for some users (e.g. users of older rxjs versions)?

**Comment by florianraffl** [comment]
Hi @RicoSuter,

did you mean me or my company to fix this or some of your other contributors? 
We don't have any clue where this code part is generated and where we do have to fix this. Can you help us out where to find this if you meant us? :)

Best regards,
Florian Raffl

**Comment by RicoSuter** [comment]
Ref

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Models/TypeScriptFrameworkRxJsModel.cs

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/Client.ProcessResponse.ReadBodyStart.liquid#L5

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.TypeScript/Templates/File.liquid#L29
