### ISSUE TITLE
Is there a way to set the generated method name manually?

### ISSUE THREAD

**Issue by vdurante** [RicoSuter/NSwag#3466]
I am working with an API that has the following structure:

```
GET /User/{id} -> returns user
GET /User -> returns list of users
POST /User -> create user
PUT /User -> update user
```

![image](https://user-images.githubusercontent.com/5401232/118057551-98673680-b362-11eb-9243-8c7dbd14f0c0.png)

Since it all happens in the same endpoint, NSwag fails to create the Typescript Angular service with the proper name when I use `"className": "{controller}Service"`.

Is there a way to set any way to solve this, maybe adding a attribute on C# Controller and Methods so NSwag can properly generate the Service and Methods?

**Comment by RicoSuter** [comment]
Are you using NSwag to generate the spec?

**Comment by vdurante** [comment]
@RicoSuter no! I am using Swashbuckle on dotnet core. Should I migrate to NSwag?

**Comment by RicoSuter** [comment]
The client gens by default use the MultipleClientsFromOperationIdOperationNameGenerator  to generate the "controller" and "operation" name which is then picked up in the class name ("{controller}" placeholder) and used as method names: 

https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration/OperationNameGenerators/MultipleClientsFromOperationIdOperationNameGenerator.cs#L26

This requires that the operation ID is in the form "controller_method" which is the default for the NSwag spec generator... of course you could change Swashbuckle to generate the operation IDs or use another operation name generator (or implement one yourself). 

> I am using Swashbuckle on dotnet core. Should I migrate to NSwag?

As I'm the maintainer of NSwag I cannot say no here :-)
However this is up to you, the goal is that NSwag also works if external spec generators - but my knowledge is that NSwag has some more advanced features than Swashbuckle (NRT, inheritance, etc.)

**Comment by vdurante** [comment]
@RicoSuter Thank you! I ended up following a different approach!

**Comment by m-mcdonagh** [comment]
I also ran into this issue. The name of Methods comes from the `operationId` in the OpenAPI Swagger spec. Swashbuckle gets that value from the Action's name, which can be set by [the HTTP Method's Name property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.routing.httpmethodattribute.name?view=aspnetcore-7.0#microsoft-aspnetcore-mvc-routing-httpmethodattribute-name)
