### ISSUE TITLE
TypeNameGeneratorType doesn't work for CodeGenerators

### ISSUE THREAD

**Issue by arkadiuszwojcik** [RicoSuter/NSwag#3468]
I can't make TypeNameGeneratorType property work. Looks like this propery is ignored at the moment? In file `CodeGeneratorCommandBase.cs` I can see such code:

```
// TODO: Use InitializeCustomTypes method
public void InitializeCustomTypes(AssemblyLoader.AssemblyLoader assemblyLoader)
{
   if (!string.IsNullOrEmpty(TypeNameGeneratorType))
   ....
```

Looks like `InitializeCustomTypes` is never called, also TODO comment emphasize this

Update:

I am using NSwag.MSBuild. In other place I read that it is imposible to use TypeNameGeneratorType from NSwag.MSBuild. Is it true?

**Comment by RicoSuter** [comment]
> I am using NSwag.MSBuild. In other place I read that it is imposible to use TypeNameGeneratorType from NSwag.MSBuild. Is it true?

yes, this config can only be used in C# (eg you build your own cli with the .net pkgs). Currently we do not load external dlls with implementations
