### ISSUE TITLE
FromQueryAttribute & FromRouteAttribute don't populate example of parameters

### ISSUE THREAD

**Issue by iTiamo** [RicoSuter/NSwag#3481]
When using `AspNetCoreOpenApiDocumentGenerator`, suppose you have a controller method:

```csharp
public async Task<ActionResult<IEnumerable<Entity>>> GetEntities([FromQuery] PageRequest pageRequest)
{
    ...
}
```

with class `PageRequest`:

```csharp
public class PageRequest
{
    /// <example>1</example>
    /// <description>Page to start returning entities from</description>
    [BindRequired]
    public int Page { get; set; }

    /// <example>10</example>
    /// <description>Amount of entities to return per page</description>
    [BindRequired]
    public int Size { get; set; }
}
```

I would expect the generated OpenAPI document to have a description and example for the `page` and `size` parameters.

How the OpenAPI document looks in stead:

```json
...
    "parameters": [
        {
            "name": "Page",
            "in": "query",
            "required": true,
            "schema": {
                "type": "integer",
                "format": "int32"
            },
            "x-position": 1
        },
        {
            "name": "Size",
            "in": "query",
            "required": true,
            "schema": {
                "type": "integer",
                "format": "int32"
            },
            "x-position": 2
        }
    ],
...
```

I have followed [the guide for XML documentation example definition](https://github.com/RicoSuter/NJsonSchema/wiki/XML-Documentation#define-examples) and my other parameters have examples just fine.

**Comment by iTiamo** [comment]
I noticed that `<description>` should be renamed to `<summary>`, this way the parameters do get a description property. However, the example property still is not populated. 

Any guidance?

**Comment by RicoSuter** [comment]
Maybe it's a special case where properties get converter to parameters and we currently do not read xml docs for this case...

**Comment by iTiamo** [comment]
@RicoSuter I think so too. Could you suggest a work-around to populate the OAS doc with examples anyway?

**Comment by RicoSuter** [comment]
You can implement an operation processor and add this on your side. But its simpler to wait for the next release.. 🙂 can do that tomorrow.

**Comment by iTiamo** [comment]
@RicoSuter Yes please, tomorrow would be amazing. This would greatly simply a feature I am working on as part of the CI/CD of an API.

**Comment by iTiamo** [comment]
All works fine in last release, thanks!
