### ISSUE TITLE
Upgrading from 13.11.1 to 13.11.2 changes enum outputs significantly

### ISSUE THREAD

**Issue by onionhammer** [RicoSuter/NSwag#3497]
Comparison:

![image](https://user-images.githubusercontent.com/969938/120547422-b6024b80-c3b6-11eb-9a17-919e096d77c8.png)

**Comment by RicoSuter** [comment]
Are you using STJ or newtonsoft? We had the problem that stj was not properly used and now it does.. do you have a global stj enum string converter registered?

**Comment by onionhammer** [comment]
I use system.text.json, not newtonsoft, and system string enum converter is not in the default options

**Comment by RicoSuter** [comment]
Is system string enum converter on the enum itself?
If not then the output should be numbers...

**Comment by RicoSuter** [comment]
Seems to be working as expected for me

![image](https://user-images.githubusercontent.com/2603405/120612135-295a9a80-c455-11eb-943e-225ab896d7db.png)

**Comment by onionhammer** [comment]
@RicoSuter mea culpa; I have two separate web apps in my project and one did have Json Enum Converter in the default options. I'll have to retest the app without that in the options to make sure everything still works.
