### ISSUE TITLE
Generate model with its methods

### ISSUE THREAD

**Issue by DragonDara** [RicoSuter/NSwag#3516]
Hi. I would like to ask whether it is possible to generate a model with its methods or not?

Regards,
Darkhan

**Comment by jeremyVignelles** [comment]
No, it's not possible :
OpenApi describes the shape of the data that are transmitted, not the behavior of the objects.

If you have C# at both the server and the client side, I'd suggest you to have a library that you share between both projects, and exclude those models from the code generation.

Another approach would be to separate the data models (POCO) from the behavior (static methods in an helper class, or extension methods), and share the behaviour between your client and your server
