### ISSUE TITLE
typescript: constructor doesn't populate Luxon dates

### ISSUE THREAD

**Issue by scottdallamura** [RicoSuter/NSwag#3527]
With this schema
```
openapi: 3.0.0
info:
  title: "test"
  description: "test"
  version: 1.0.0
components:
  schemas:
    Animal:
      type: object
      required:
        - name
        - species
      properties:
        name:
          type: string
          default: "Spot"
        species:
          type: string
      discriminator:
        propertyName: species
        mapping:
          dog: "#/components/schemas/Dog"
    Dog:
      allOf:
        - $ref: "#/components/schemas/Animal"
      properties:
        birthday:
          type: string
          format: date
        owner:
          $ref: "#/components/schemas/Owner"
    Owner:
      type: object
      required:
        - name
      properties:
        name: 
          type: string
```
and this command line
```
nswag openapi2tsclient /input:.\spec.yaml /output:clients.ts /dateTimeType:luxon /typeStyle:Class /convertConstructorInterfaceData:true
```

the relevant parts of the generated Dog code:
```
    constructor(data?: IDog) {
        super(data);
        if (data) {
            this.owner = data.owner && !(<any>data.owner).toJSON ? new Owner(data.owner) : <Owner>this.owner; 
        }
        this._discriminator = "dog";
    }

    init(_data?: any) {
        super.init(_data);
        if (_data) {
            this.birthday = _data["birthday"] ? DateTime.fromISO(_data["birthday"].toString()) : <any>undefined;
            this.owner = _data["owner"] ? Owner.fromJS(_data["owner"]) : <any>undefined;
        }
    }
```
you can see that `init` sets up the Luxon date, but the constructor doesn't. 

It looks like the date properties don't match this `public bool ConvertConstructorInterfaceData => _settings.ConvertConstructorInterfaceData && Properties.Any(p => p.SupportsConstructorConversion);`

**Comment by jeremyVignelles** [comment]
Kind of the same issue as #2176 and #2889

**Comment by RicoSuter** [comment]
The ctor is meant to be used with an interface where the datetime is already a luxon object, not for JSON parsed structures... that's what init() is used for...

**Comment by scottdallamura** [comment]
i see.  okay, sure, i can live with that.  so if i pass a fully-realized data with a luxon date for birthday, it's still undefined after the constructor runs.  i think this is a case of the question described in https://stackoverflow.com/questions/67931433/inability-to-set-value-of-public-class-field-from-constructor-of-super-if-that-f

... where the field is "set" in the base class constructor, but then "redefined" in the derived constructor.  so probably a separate issue.  or i'm doing something wrong.  thanks!
