### ISSUE TITLE
Whe using inheritance, NSwag Studio generates code which contains CS3016 warnings

### ISSUE THREAD

**Issue by marco-bertschi** [RicoSuter/NSwag#3528]
NSwag Studio 

![grafik](https://user-images.githubusercontent.com/25186516/123799491-92182400-d8e8-11eb-8ccd-18ea4a66cbe1.png)

When generating the code using the YAML below, on the `BaseClass` there is an attribtue `[Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "Type")]` generated which leads to a warning *CS3016	Arrays as attribute arguments is not CLS-compliant*
As we're following a strict no-warning policy this leads to devs having to add the warning by hand each time they regenerate the code. Marking the entire assembly as not-CLS compliant isn't an option either, as we're forced to adhere to this by company standards. I have not found a way of being able to add custom warnings to ignore either, so here I am reporting the issue.

In my opinion the warning should be ignorable, since the client isn't typically shown to the outside world ( or so I hope ). At least in my case, an option to ignore the warning would be very welcome

```yaml

openapi: "3.0.0"
info:
  title: Example API for CLS compliance warning
  description:
    A `[Newtonsoft.Json.JsonConverter(typeof(JsonInheritanceConverter), "Type")]` attribute
    is generated onto the `BaseClasse` which leads to a warning.

    > Warning	CS3016	Arrays as attribute arguments is not CLS-compliant

  version: "1.0.0"

components:
  schemas:
    TypeOfBaseClass:
      additionalProperties: false
      type: string
      enum:
        - DerOne
        - DerTwo

    DerivedClassOne:
      allOf:
        - $ref: "#/components/schemas/BaseClass"
        - type: object
          additionalProperties: false
          properties:
            MoreText:
              type: string
              maxLength: 10
              description: More Text

    DerivedClassTwo:
      allOf:
        - $ref: "#/components/schemas/BaseClass"
        - type: object
          additionalProperties: false
          properties:
            MoreMoreText:
              type: string
              maxLength: 10
              description: Even more Text

    BaseClass:
      additionalProperties: false
      type: object
      properties:
        Type:
          $ref: "#/components/schemas/TypeOfBaseClass"
        Identifier:
          type: string
          maxLength: 12
          description: ID
        Text:
          type: string
          maxLength: 10
          description: Text
      discriminator:
        propertyName: Type
        mapping:
          DerOne: "#/components/schemas/DerivedClassOne"
          DerTwo: "#/components/schemas/DerivedClassTwo"
      required:
        - Type
        - Identifier
        - Text


```

**Comment by RicoSuter** [comment]
JsonConverter takes an array and we need to use this attribute here... what would be the fix? Can you create a PR?

**Comment by marco-bertschi** [comment]
There's basically two ways of solving this, either add an ignore directive directly or make the warnings configurable.
I'll try to send in a PR.

**Comment by RicoSuter** [comment]
We just add an ignore to the file?
https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/File.liquid#L18

**Comment by marco-bertschi** [comment]
If that's OK for you I'm on board with that. I'll create a PR.

**Comment by marco-bertschi** [comment]
@RicoSuter #3536 is ready for review.

**Comment by paulcastro2014** [comment]
this is happening as well with CS50509 error. It's generating code that creates partial classes that inherit from Enums, which is not possible in C# as Enums are sealed classes.
