### ISSUE TITLE
Using a minor version results in broken code generation [C# Client]

### ISSUE THREAD

**Issue by rajbos** [RicoSuter/NSwag#3531]
We're running the openApiToCSharpClient code generator to generate a C# Client from an .NET 5.0 api, together with the dotnet  tool nswag.

When annotating an action with a minor version like below, we get broken code in the generated client:
``` csharp
    [ApiVersion("2.1")]
    [Route("v{version:apiVersion}/auction-requests")]
    [ApiController]
```

Code in the generated client: 
``` csharp
public async Task<Command> V2.1AuctionRequestsPostAsync()
```

The dot in the method name is breaking compilation of course. Anything we can do to prevent this? We already tried different `operationGenerationMode` settings, but all have the same issue.

Only using major versions on all controllers gets us correctly version methods, but we want to include minor versions as well.

**Comment by RicoSuter** [comment]
We'd need to fix this either in the operation name generators or here
https://github.com/RicoSuter/NSwag/blob/d69085067b2261c75f3b49a0e43a4c26aa49d743/src/NSwag.CodeGeneration/ClientGeneratorBase.cs#L228
