### ISSUE TITLE
NSwag causes project to always be rebuilt on Run

### ISSUE THREAD

**Issue by BryceBarbara** [RicoSuter/NSwag#3534]
As the title mentions, NSwag slows down the developer by triggering rebuilds even when no code has changed. 

This is due to NSwag overwriting the `(ProjectName).NSwag.Targets` file every time the `aspNetCoreToOpenApi` command runs. Overwriting the file changes the "last modified" date that Visual Studio uses to determine if a project needs rebuilding.

The problem code starts [around here](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Commands/Commands/Generation/AspNetCore/ProjectMetadata.cs#L93). The fix would be to check to see if the file actually needs to be updated before overwriting it.

**Comment by BryceBarbara** [comment]
@pranavkm I believe you might be the one who worked on this. Do you know if overwriting the file every time was required for any specific reason?

**Comment by BryceBarbara** [comment]
Nevermind, I think you guys know about it because you have the wiki article mention deleting the file after generating the stuff!

**Comment by jvert** [comment]
A reference to "the wiki article" would be great - I have spent quite a few hours tracking down this issue and I couldn't find any article.

**Comment by MarkFl12** [comment]
For anyone finding this later: I might have found a reference to the deleting the file in #3870 which show them using this in their csproj:
```
<Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">
 <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net60) run nswag.json /variables:Configuration=$(Configuration)" />
 <Delete Files="$(ProjectDir)\obj\$(MSBuildProjectFile).NSwag.targets" />
</Target>
```

And also similar in a stackoverflow here: https://stackoverflow.com/questions/72192105/how-to-configure-jason-taylors-clean-architecture-template-to-use-a-different-a

And after adding the line to my csproj and hitting rebuild, it seems to have fixed this issue completely, even having switched away to another branch, closed and re-opened visual studio etc, which is strange? I wonder if I had some config hanging around from an older version where this line was required, but now it isn't?
