### ISSUE TITLE
NSwagStudio does not support NetCore22?

### ISSUE THREAD

**Issue by NoStudioDude** [RicoSuter/NSwag#3538]
Hello, I just updated NSwagStudio to the latest version (13.11.3) and now when opening a project that was created using NetCore22 I get this exception:

![image](https://user-images.githubusercontent.com/7672691/124290083-51701300-db53-11eb-8348-510537db635e.png)

Is this supposed to happen or is it a bug in the new version?

(I did not test any other previous version and I can remember which version I was before updating)

**Comment by RicoSuter** [comment]
.NET Core 2.2 is not supported anymore as it reached end of life (unlike 2.1), ie not even supported by Microsoft anymore... you should upgrade to 3.1 immediately (security patches, etc.)

https://dotnet.microsoft.com/download/dotnet/2.2

**Comment by NoStudioDude** [comment]
I do understand that, but as of now I am not able to open any project that was created with NetCore22, shouldn't nswag be backwards compatible? 

As of now I will just manually open the project and edit to NetCore31, but I think NSwagStudio should support backwards compatibility, or atleast let us open the file to edit ;)

**Comment by ecolara3** [comment]
For anyone who needs the last build available containing NetCore2.2:

https://github.com/RicoSuter/NSwag/releases/tag/NSwag-Build-1113

**Comment by ranouf** [comment]
Hi,

I dowloaded this NSwag-Build-1113, but when I generate the files I have this error:
Application references version '13.1.6.0' of 'NSwag.Core' which is lower than the required version '13.8.2.0'.

![image](https://user-images.githubusercontent.com/1764519/187978825-2cd2ba3f-686b-4883-a3f6-4b32dc63f57f.png)

Any idea what to do?

Thanks

**Comment by lahma** [comment]
Maybe you need to upgrade to supported runtime,  like net core 3.1? 3.1 will also be EOL end of this year.

**Comment by ranouf** [comment]
It's in the todo list but not for now.

It's like the application is referencing to a newer version of Nswag.Core. Is there a way to bypass that?

**Comment by lahma** [comment]
Just use an older version,  like described earlier on this thread.

**Comment by ranouf** [comment]
I'm not sure to understand, @ecolara3  suggested to download this version:
https://github.com/RicoSuter/NSwag/issues/3538#issuecomment-1133773798

This is what I did:
https://github.com/RicoSuter/NSwag/issues/3538#issuecomment-1234590327

Is there something I missed in the thread?

**Comment by lahma** [comment]
> I did the try with a previous version, worked perfectly!

What was the version here?

**Comment by ecolara3** [comment]
> I'm not sure to understand, @ecolara3  suggested to download this version:
> https://github.com/RicoSuter/NSwag/issues/3538#issuecomment-1133773798
> ![image](https://user-images.githubusercontent.com/1764519/187984623-b6112111-9284-4df7-9c28-1cbe6d736a88.png)
> 
> 
> This is what I did:
> https://github.com/RicoSuter/NSwag/issues/3538#issuecomment-1234590327
> ![image](https://user-images.githubusercontent.com/1764519/187984671-5577ef76-ff5f-444e-bd5e-3c815fcbd16f.png)
> 
> 
> Is there something I missed in the thread?

I installed from a fresh windows 10 installation. So you might have something installed from a different version. I've only installed the version I've linked from a fresh OS, so that's the only thing I can think of. Make sure to uninstall all previous versions, qnd you have .net 2.2 runtime installed etc. 

I also have an older version of node and angular installed also. I think the last version 15 of node and angular 8 also. 

Hope this helps!

**Comment by ranouf** [comment]
Thanks, maybe there is conflict with the other SDKs, or even after uninstall Nswagstudio, there is still some previous data there which create the issue. 
But good to know, your solution is still working. I will check what I can do.
