### ISSUE TITLE
'{controller}' placeholder does not work with open api spec

### ISSUE THREAD

**Issue by umutesen** [RicoSuter/NSwag#3539]
I am trying to generate multiple clients for each controller using the `{controller}Service` class name option:

```
nswag swagger2tsclient /Input:api-swagger/api-swagger.json /Output:src/app/api/api.ts /ClassName:{controller}Service /WrapDtoExceptions:true /TypeScriptVersion:2.0 /Template:Angular /HttpClass:HttpClient /DateTimeType:Date /GenerateClientClasses:true /GenerateClientInterfaces:true /ImportRequiredTypes:true /BaseUrlTokenName:API_BASE_URL /InjectionTokenType:InjectionToken /RxJsVersion:6.0 /UseSingletonProvider:true /ExcludedParameterNames:Authorisation

```

While I expect a client for each controller, it only generates one client called `Service`, which contains all operations across all endpoints. 

The spec file looks like the following:
<img width="373" alt="Screenshot 2021-07-03 at 23 52 32" src="https://user-images.githubusercontent.com/4234033/124368526-c0379400-dc59-11eb-8af6-9a1bec967c89.png">

**Comment by RicoSuter** [comment]
What is the structure of the OperationId? With the default operation name generator the operation id needs to be in the form "controller_method" in order that this actually works.

**Comment by umutesen** [comment]
Thank you for pointing this out, the structure of operations did not include controller names - they only had method names.
