### ISSUE TITLE
Unable to download NSwag Studio Installer

### ISSUE THREAD

**Issue by calumtomeny** [RicoSuter/NSwag#3541]
I am unable to download the MSI installer for NSwagStudio.

Steps to reproduce:

- Go to: https://github.com/RicoSuter/NSwag/wiki/NSwagStudio
- Click on "Download latest NSwagStudio MSI installer"

Expected: the MSI installer downloads
Actual: `{"message":"Artifact not found or access denied."}`

**Comment by bzapata-thr** [comment]
Yes that link is broken but alternatively you can download from:
https://github.com/RicoSuter/NSwag/releases

**Comment by icnocop** [comment]
I just updated the link on https://github.com/RicoSuter/NSwag/wiki/NSwagStudio

Please try again.

Thank you.

**Comment by calumtomeny** [comment]
Great - thanks @icnocop.
