### ISSUE TITLE
Is that any way to set the "try it out" post json body

### ISSUE THREAD

**Issue by kugarliyifan** [RicoSuter/NSwag#3549]
my action like this:
[FromBodyJson,HttpPost,AllowAnonymous,ValidateRule,Produces("application/json"),Consumes("application/json")]
Task<ResultReturn<string>> Login([Required]string userName, 
            [Required]string password,
            [FromServices]LoginUserService loginService)

then I want to make the userName and password paramters post by json ,but on the swagger UI ,still post  form data with key=value,,

I user nswag version is NSwag.AspNetCore v13.9.4

**Comment by jeremyVignelles** [comment]
Create a class that contains Username and Password, and have only one parameter of that type in your method.

**Comment by kugarliyifan** [comment]
> Create a class that contains Username and Password, and have only one parameter of that type in your method.

I think I found some way to figure out :
this is my code:
https://github.com/kugarliyifan/Kugar.Core.Web.JsonTemplate/blob/master/Kugar.Core.Web.JsonTemplate/Processors/ActionParamtersToJsonBodyProcessor.cs#L19
