### ISSUE TITLE
NSwag Generated TypeScript Client Code reports many errors by ts compiler

### ISSUE THREAD

**Issue by nagkumar** [RicoSuter/NSwag#3552]
It would be good to fix generated to comply to latest typescript standards. Below are the issues reported by typescript 4.2.2.

![image](https://user-images.githubusercontent.com/332234/125372987-f2f03380-e3a1-11eb-9c62-12bf31bebe29.png)

**Comment by timritzer** [comment]
Those are linter errors not Javascript or Typescript errors. Your desired local linter rules drive that, and the generator cannot know what linter rules you have in place. 
To get rid of any linter errors, add the generated files to your linter ignore file.

If there are any actual standards based improvements to the generated code, feel free to submit PRs to improve the client templates.
