### ISSUE TITLE
Q: Using NSwag on non-AspNetCore Project

### ISSUE THREAD

**Issue by jasonterando** [RicoSuter/NSwag#3555]
Hi, I have a suite of C#/.Net Core Lambda functions that I want to publish to drive APIs via API Gateway.  I am using AWS SAM for build, local test and deploy.  This code neither requires nor uses AspNetCore.

From what I have read in the docs, NSwag equires the use of Microsoft.AspNetCore for building out OpenAPI docs. (identifying Controller classes, HttpPost/HttpGet attributes, etc.)  What I would like is to a mechanism to generate OpenAPI documentation that is completely attribute driven, and those attributes are not tied to a specific implementation (MVC or otherwise).  I had something like this in TypeScript that would use JSDoc info to generate OpenAPI docs. I would also like to use/merge in the JSON Schema generated by NJsonSchema (which is working fine).

I am guessing I need to write my own version of NSwag.Generation (instead of NSwag.Generation.AspNetCore it would be something like NSwag.Generation.Attributes or whatever).  Before I go down that rabbit hole, is this a good idea?  Has somebody already done something like this already?

**Comment by jeremyVignelles** [comment]
That would be the only way to go since you can't rely on ApiExplorer which is provided by asp.net core.
As far as I know, nobody has done that for AWS, but there has been work done for Azure functions (Have a look at issues in this repository)

**Comment by jasonterando** [comment]
Thanks, I found  [Jusas/NSwag.AzureFunctionsV2](https://github.com/Jusas/NSwag.AzureFunctionsV2).  That at least gives me a jumping-off point to investigate.  Thanks!
