### ISSUE TITLE
TS2352 After Update from NSwag v13.11.3.0 to v13.12.0.0

### ISSUE THREAD

**Issue by denhaandrei** [RicoSuter/NSwag#3566]
TS2352	(TS) Conversion of type 'null' to type 'any[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

All 'process*' generated methods start `return: _observableOf<UserTypeModel[]>(<any[]>null);`
before the update It was `return _observableOf<UserTypeModel[]>(<any>null);`

tsconfig.json settings:
```{
    "compileOnSave": true,
    "compilerOptions": {
        "alwaysStrict": true,
        "baseUrl": "./",
        "declaration": false,
        "experimentalDecorators": true,
        "lib": [
            "ES2018",
            "DOM"
        ],
        "module": "esnext",
        "moduleResolution": "node",
        "outDir": "./dist/outdir",
        "removeComments": true,
        "sourceMap": true,
        "strict": true,
        "strictNullChecks": true,
        "target": "ES2015",
        "typeRoots": [
            "node_modules/@types"
        ]
    }
}

angular 12
typescript: 4.2.4

**Comment by RicoSuter** [comment]
This has been changed in this PR: #2384
@dhwed can you or someone else propose a PR to fix this?

**Comment by dhwed** [comment]
I'm testing a fix now and will make a PR later today

**Comment by RicoSuter** [comment]
Is this fix ok?
https://github.com/RicoSuter/NSwag/pull/3567
