### ISSUE TITLE
.Net 6 support.

### ISSUE THREAD

**Issue by YvonneArnoldus** [RicoSuter/NSwag#3627]
I can run the project in VS 2022 just fine and everything works. 

Except when I tried to build for my release with:

``
dotnet publish C:\project.csproj --runtime win-x64 --configuration Release --self-contained false
``

I get the flowing error:

``
error NU1605:  error NU1605: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version.

From:
NSwag.Generation 13.13.2 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0)  
NSwag.Generation 13.13.2 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem.Primitives (>= 4.0.1) 

error NU1605: Detected package downgrade: System.Text.Encoding.Extensions from 4.3.0 to 4.0.11.

From:
NSwag.Generation 13.13.2 -> Newtonsoft.Json 9.0.1 -> System.Xml.ReaderWriter 4.0.11 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.Text.Encoding.Extensions (>= 4.3.0)  
NSwag.Generation 13.13.2 -> Newtonsoft.Json 9.0.1 -> System.Text.Encoding.Extensions (>= 4.0.11)
``

Will this be resolved by the time .Net 6 is released or should I not use NSwag in .Net 6

**Comment by Simonl9l** [comment]
Are there plans to support Minimal API (as swagger does)
https://dotnetthoughts.net/openapi-support-for-aspnetcore-minimal-webapi/

**Comment by robertsundstrom** [comment]
When will this be ready? 

The WithName and WithTags etc is not working in the latest package. Does not affect the schema.

```cs
app.MapGet("/person", () => {
    return new Person("Scott", 42);
})
.WithName("GetPerson")
.WithTags("Person"
```

**Comment by RicoSuter** [comment]
Couldnt find the WithTags extension method (?)

**Comment by RicoSuter** [comment]
Basic support for .NET 6 and minimal API is released btw.

**Comment by robertsundstrom** [comment]
@RicoSuter  Do you mean that you cannot find it? It should be there. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis?view=aspnetcore-6.0

OK. When will there be a new package? 🙂

**Comment by robertsundstrom** [comment]
@RicoSute
<img width="670" alt="Screenshot 2021-11-16 at 21 04 25" src="https://user-images.githubusercontent.com/919580/142057656-c733e63c-0937-4fc0-9c8f-8fdbeb4cbae6.png">
r

**Comment by robertsundstrom** [comment]
@RicoSuter When will this change be released? So I can set the tags that control what clients will be generated? Right now, we just have a "default" group in Swagger UI.

**Comment by RicoSuter** [comment]
@robertsundstrom hopefully tomorrow as we need to first fix the release pipelines.

**Comment by seriouz** [comment]
@RicoSuter Did you get the pipelines fixed?

**Comment by robertsundstrom** [comment]
@RicoSuter Thank you, I have noticed that the changes have been published. 😊

**Comment by 8BitAron** [comment]
Any update on when this might get published, we have a few developers on Apple Silicon and would like to use the .Net6 Runtime to build. 

no other .net SDKs are supported on M1 macs

Thanks

**Comment by lahma** [comment]
@8BitAron what version have you tried?

**Comment by 8BitAron** [comment]
@lahma on the M1 mac, we have  .net6 sdk installed, on our intel macs we have 3.1 and 6 sdks and pass in the `/runtime:NetCore31` flag to `nswag run`

**Comment by lahma** [comment]
Try with the latest release and pass `Net60`.

**Comment by YvonneArnoldus** [comment]
Any time line on this?

**Comment by RicoSuter** [comment]
NSwag supports .NET 6 - closing this issue.

**Comment by YvonneArnoldus** [comment]
For people who have the same problem, I used the worked around:
    https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1605#example-2 
 In my project file.

Not optimal but it now builds
