### ISSUE TITLE
.NET 6 Build Environment Variables

### ISSUE THREAD

**Issue by thenadz** [RicoSuter/NSwag#3630]
In keeping with the build environment naming conventions, we need `NSwagExe_Net60` and `NSwagDir_Net60` to be defined in `src/NSwag.MSBuild/NSwag.MSBuild.props`. Now that .NET 6 in in RC stage, it would be great if this could be made available sooner rather than later.

Thanks!

**Comment by pathanlan** [comment]
@RicoSuter @thenadz Looks like this exists now, this item should be closed in case others think the issue is still outstanding.
