### ISSUE TITLE
Protobuf-like compile-time code generation

### ISSUE THREAD

**Issue by hayhay27** [RicoSuter/NSwag#3636]
What if we create something like in [Grpc.Tools](https://github.com/grpc/grpc/tree/master/src/csharp/Grpc.Tools)?
This package defines Protobuf item type for project.

Yesterday I checked this idea.
[Here](https://github.com/hayhay27/NSwagCodeGeneration) working sample (checked on windows).

It can be handy with spec-first aproach

csproj bootstrap for autogeneration
```xml

  <ItemGroup>
    <PackageReference Include="NSwag.MSBuild" Version="13.13.2">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <NSwagController Include="Specs\**\*.yml">
      <ControllerStyle>abstract</ControllerStyle>
      <UseCancellationToken>true</UseCancellationToken>
    </NSwagController>
  </ItemGroup>
```

Also we can add some commands to `nswag.consolecore` like in [dotnet-grpc](https://github.com/grpc/grpc-dotnet/tree/master/src/dotnet-grpc)

**Comment by RicoSuter** [comment]
What I currently do is to run the nswag.exe on build against an nswag.json file - so the configs are there and not in the csproj... this way you can modify it easily with NSwagStudio.

**Comment by hayhay27** [comment]
@RicoSuter
I just realized how work NSwag.ApiDescription.Client )
What do you tnink about this?
<img src="https://raw.githubusercontent.com/hayhay27/MSBuildLab/master/FileProperties.png" alt="File Properties Image" width="200" />

Can we put this functionality to NSwag.ApiDescription.Client (disabled by default)?
[Here](https://github.com/hayhay27/MSBuildLab) full example

**Comment by RicoSuter** [comment]
This looks nice, can you create a PR?
