### ISSUE TITLE
CapitalizeFirst method doesn't only capitalize the first letter

### ISSUE THREAD

**Issue by adesam146** [RicoSuter/NSwag#3687]
When using the `SingleClientFromPathSegments` (& `MultipleClientsFromPathSegments`) mode, if the PathSegment in the openapi file is `<baseUrl>/createSomething` then the generated method would be called `Createsomething`.

The problem seems to stem from the fact that the method `CapitializeFirst` in  [SingleClientFromPathSegmentsOperationNameGenerator](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration/OperationNameGenerators/SingleClientFromPathSegmentsOperationNameGenerator.cs#L78) and [MultipleClientsFromPathSegmentsOperationNameGenerator](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration/OperationNameGenerators/MultipleClientsFromPathSegmentsOperationNameGenerator.cs#L77) lowers the rest of the string.
It should ideally be
```csharp
var capitalized = name.ToLowerInvariant();
return char.ToUpperInvariant(capitalized[0]) + (name.Length > 1 ? name.Substring(1) : "");
```

**Comment by RicoSuter** [comment]
Can you create a PR?

**Comment by adesam146** [comment]
No problem will do

**Comment by adesam146** [comment]
Please see PR: https://github.com/RicoSuter/NSwag/pull/3693
Thanks.
