### ISSUE TITLE
.NET Core 6 Enums generated only as numbers in Typescript client file

### ISSUE THREAD

**Issue by swadertater** [RicoSuter/NSwag#3700]
I have this in my startup but all enums generated as ints. Reverting the API to .NET Core 5 fixes this issue
```
services.AddControllersWithViews().AddJsonOptions(options =>
{
  options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
 
```

Typescript enum generated from .NET Core 5
![image](https://user-images.githubusercontent.com/15354387/140986462-9eb64cc8-c33b-4965-8b91-7ce9f4df1cf9.png)

Typescript enum generated from .NET Core 6
![image](https://user-images.githubusercontent.com/15354387/140986635-11d5bde5-9b13-4984-bef7-d993d23c24da.png)

**Comment by maxkoshevoi** [comment]
Have `swagger.json` changed?

**Comment by swadertater** [comment]
@maxkoshevoi This is for the typescript code generation, not API documentation.

**Comment by maxkoshevoi** [comment]
Api client is generated based on `swagger.json`. If `swagger.json` doesn't contain names anymore, this might be the real issue.
PS: `swagger.json` is also generated by NSwag

**Comment by swadertater** [comment]
@maxkoshevoi We use Swagger data annotation in our controllers for the api client generation. I added 
```    
[JsonConverter(typeof(StringEnumConverter))]
```
to my enum classes and that seemed to fix it. You put me on the right track! Thank you. This seemed to previously had been done within the JsonSerializerOptions in Startup, not sure why I'm having to specify the conversion within the enum class with .Net CORE 6.0. Or I'm completely misunderstanding something. Anyways,  thank you!

**Comment by rhegner** [comment]
I experience the same issue after updating to .NET 6.

Some of my enums are located in an auto-generated source file, so @swadertater workaround does not work for me. Is there another solution?

**Comment by rhegner** [comment]
> Api client is generated based on `swagger.json`. If `swagger.json` doesn't contain names anymore, this might be the real issue. PS: `swagger.json` is also generated by NSwag

Yes it is the swagger.json description generated by NSwag that changed. Change is not happening on code-generator side.

**Comment by rhegner** [comment]
Using the deprecated `DefaultEnumHandling` (and `DefaultPropertyNameHandling`) is a workaround that works better for me.

```
services.AddOpenApiDocument(doc =>
{
	doc.DefaultPropertyNameHandling = NJsonSchema.Generation.PropertyNameHandling.CamelCase;
	doc.DefaultEnumHandling = NJsonSchema.Generation.EnumHandling.String;
	// ...
});
```

**Comment by RicoSuter** [comment]
If there is a global System.Text.Json.Serialization.JsonStringEnumConverter or one attached to the property it should be picked up by the swagger generator.

**Comment by swadertater** [comment]
@rhegner The quickest fix for me was having
```
services.AddControllersWithViews().AddJsonOptions(options =>
{
  options.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter());
});
 
```
in my startup and prepending
```
[JsonConverter(typeof(StringEnumConverter))]
```
to my enum class declarations.
The latter was not needed in .NET Core 5.

**Comment by swadertater** [comment]
Sweet, sounds good. Thank you for the quick replies!
