### ISSUE TITLE
NSwag 13.14.0 and NET60

### ISSUE THREAD

**Issue by jpflick** [RicoSuter/NSwag#3712]
Cannot run NSwagStudio or command line with 13.14.0. No Net60 binaries folder in C:\Program Files (x86)\Rico Suter\NSwagStudio or C:\Users\john-dev\AppData\Roaming\npm\node_modules\nswag\bin\binaries. Not sure if that is the problem.

Error: Command failed: dotnet "C:\Users\john-dev\AppData\Roaming\npm\node_modules\nswag\bin/binaries/Net60/dotnet-nswag.dll" run nswag.json /runtime:Net60

**Comment by jpflick** [comment]
Version 13.14.1 fixes this issue for NSwagStudio. NPM package update still needs to be uploaded at time of this post.

**Comment by RicoSuter** [comment]
NPM package had a problem, NPM v13.14.2 is now live...

**Comment by jpflick** [comment]
This issue has been resolved for me. Thanks.
