### ISSUE TITLE
Bug: Code Generation fails after update

### ISSUE THREAD

**Issue by syrok0010** [RicoSuter/NSwag#3719]
After update to .Net 6 and Nswag 13.14.3.
Using MSBuild 
```
<Target Name="NSwag" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug'">
    <Copy SourceFiles="@(Reference)" DestinationFolder="$(OutDir)References" />
    <Exec Command="$(NSwagExe_Net60) run /variables:Configuration=$(Configuration)" />
    <RemoveDir Directories="$(OutDir)References" />
  </Target>
```

Get error code -1
Reverting back doesn't help

**Comment by syrok0010** [comment]
Solved it for now by using Net5 for code generation

**Comment by dasMulli** [comment]
@syrok0010 do you have a full sample? does your program only have a Main() method or a public static `CreateHostBuilder` method?

**Comment by syrok0010** [comment]
My program uses this template: https://github.com/jasontaylordev/CleanArchitecture

**Comment by jasontaylordev** [comment]
Hey @syrok0010 . I've encounterd some issues too - see https://github.com/RicoSuter/NSwag/issues/3727 for details and a workaround.

You can also review this code https://github.com/jasontaylordev/BlazorWasmHosted/tree/workaround to see NSwag / MSBuild working with .NET 6.

**Comment by syrok0010** [comment]
@jasontaylordev Thank you for the workaround. But it still doesn't work for me. Even though I still use Controllers, Program.cs, Startup.cs and the only change is .net version, I can't build my solution.
