### ISSUE TITLE
Nswag 13.14.3 always defaults to GetSystemTextJsonSettings (so JSON.Net PropertyName does not work)

### ISSUE THREAD

**Issue by simeyla** [RicoSuter/NSwag#3721]
I have been using 13.10.9 for a while and updated to 13.14.3 today for .NET 6.

I am having an issue where System.Text is being used even though I have Newtonsoft JSON enabled.

I want to use the Newtonsoft.JSON attributes (`JsonProperty`) but they are not being recognized. 
Instead the System.Text JSON `JsonPropertyName()` is being used instead.

It is effectively the [opposite of this problem](https://github.com/RicoSuter/NSwag/issues/3484), but nothing to do with that fix.

Fortunately I don't have too many places where the default naming convention isn't being used - so for now I was able to add extra System.Text attributes as needed.

        [JsonPropertyName("ue")]
        [JsonProperty("ue")]
        public bool? UsernameExists { get; set; }

I have narrowed it down to the [following line](
https://github.com/RicoSuter/NSwag/blob/259e556e2ece8552d1e7e19af9b8e8feb416c8e7/src/NSwag.Generation.AspNetCore/AspNetCoreOpenApiDocumentGenerator.cs#L100) where `AspNetCoreOpenApiDocumentGenerator` tries to get the `SerializerSettings`. Clearly if any error occurs here it will default to `GetSystemTextJsonSettings()`.

            try
            {
                return (JsonSerializerSettings)options?.Value?.SerializerSettings;
            }
            catch
            {
                // Newtonsoft.JSON not available, use GetSystemTextJsonSettings()
                return null;
            }

I copied the above function `GetJsonSerializerSettings` into my main application (.NET 6) to test it and see if there really was an exception here. It turns out the exception is :

     ''object' does not contain a definition for 'Value''

Note: `options` is a dynamic property of type:

> Microsoft.Extensions.Options.UnnamedOptionsManager`1[[Microsoft.AspNetCore.Mvc.MvcNewtonsoftJsonOptions, Microsoft.AspNetCore.Mvc.NewtonsoftJson, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]

I believe this is a [new class in .NET 6](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Options/src/UnnamedOptionsManager.cs) and is reason the error is occurring.

![image](https://user-images.githubusercontent.com/3656278/141674277-c2875dad-486b-413d-8ddf-05df45d28ac1.png)

As proof that `options.Value` is in fact of the expected type (`Newtonsoft.Json.JsonSerializerSettings`) here's the expanded view of `options` variable:

![image](https://user-images.githubusercontent.com/3656278/141674303-57d55b1d-a374-4b90-9217-2db39a6ee13a.png)

I'm not exactly sure why a dynamic object (options) cannot access Value but it doesn't seem to be able to - and instead throws an exception - causing the `[JsonProperty]` to be ignored.

**Comment by RicoSuter** [comment]
Dynamic seems to be different in .net 6, need to fix this like here: 
https://github.com/RicoSuter/NSwag/commit/bc3663e58d1ad6b1b0025defe28d5a2464f4a3cd

**Comment by RicoSuter** [comment]
v13.14.4
