### ISSUE TITLE
How to change baseUrl in angular 11

### ISSUE THREAD

**Issue by BrkCoder** [RicoSuter/NSwag#3728]
We have generate some angular services using NSwag, but we didn't succeed in changing the base url of every service request.
There is no docs regrading an angular 11 client.
Can someone provide angular 11 client consume NSwag angular service and change the baseurl from the client(aka component) ?
@RicoSuter

**Comment by vpetrusevici** [comment]
Hi. Just add this in your app.module:
```
export const API_BASE_URL = new InjectionToken<string>('API_BASE_URL'); //baseUrlTokenName
...
providers: [
        {
          provide: API_BASE_URL, 
          useValue: environment.apiUrl
        }
]
```

**Comment by BrkCoder** [comment]
thank you!!
