### ISSUE TITLE
Question about MSBuild task for NET5 and later - This thingy trigger project rebuild?

### ISSUE THREAD

**Issue by syska** [RicoSuter/NSwag#3743]
## Recommended for .NET Core/NET5 and later: ##

From: https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild

`<Delete Files="$(ProjectDir)\obj\$(MSBuildProjectFile).NSwag.targets" /> <!-- This thingy trigger project rebuild -->`

I'm missing some information here ... what does this do? What will not work if I remove it?

I will do a PR  ... i'm just one of these people that wonder ... what will not work?

I also have another thing to add here. The `noBuild` is pretty important here else it will end in a loop trying to build it again and again when using `aspNetCoreToOpenApi` and have a project referenced.

**Comment by RicoSuter** [comment]
No clue, changed back to what i use: 

```
<Target Name="NSwag" AfterTargets="PostBuildEvent" Condition=" '$(Configuration)' == 'Debug' ">
  <Exec WorkingDirectory="$(ProjectDir)" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net50) run nswag.json /variables:Configuration=$(Configuration)" />
</Target>
```

**Comment by syska** [comment]
@RicoSuter Thanks.
