### ISSUE TITLE
CS8032 error after updating some .NET nuget packages

### ISSUE THREAD

**Issue by molinch** [RicoSuter/NSwag#3766]
First of all thanks a lot for the amazing library.

The issue we have is with NSwag.Msbuild 13.14.5.
It was working perfectly fine with our project that contains OpenApi references for a while.
Today we updated some nuget packages, and there seems to be an inconsistency with microsoft.extensions.logging.abstractions 6.0.0.

Now we get an error on build:
`CSC : error CS8032: An instance of analyzer Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator cannot be created from /***/.nuget/microsoft.extensions.logging.abstractions/6.0.0/analyzers/dotnet/roslyn4.0/cs/Microsoft.Extensions.Logging.Generators.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=3.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.. [/***]`

I am not sure if there are code generators now shipped which could conflict.

**Comment by lahma** [comment]
Can you try the preview build from: https://www.myget.org/F/nswag/api/v3/index.json
It should contain a fix made recently: https://github.com/RicoSuter/NSwag/pull/3762

**Comment by molinch** [comment]
@lahma If I'm not wrong I can try with the published 13.14.7
https://github.com/RicoSuter/NSwag/compare/v13.14.7...master
I will write the results

**Comment by lahma** [comment]
@molinch I think you would need to have `13.14.7-preview-20211129-2356` from the preview feed for that fix to be included. Make sure you have "Show pre-release packages" enabled in your package manager.

**Comment by molinch** [comment]
Unfortunately still the same behavior. I will downgrade microsoft.extensions.logging to see if that helps

**Comment by molinch** [comment]
I found the root cause of the issue, for some reason nSwag msbuild builds the whole solution and then it fails with the source generators, while it should build only my project. I'm trying to find how to restrict it to just the project that contains OpenApi references

**Comment by molinch** [comment]
I am not sure what fixed it, I did hips of changes but I behaves totally fine now with latest nSwag msbuild.
If I manage to do a smaller repro sample, of former issue, and confirm it was really from nSwag I'll reopen one.

**Comment by Kirill-basic** [comment]
I have the exact same issue and cant figure out how to fix it. Molinch, do you have any ideas what fixed this in you case. I would be very thankful

**Comment by molinch** [comment]
@Kirill-basic Honestly I cannot remember, probably getting rid of obj/bin and using latest nSwag fixed it for me
