### ISSUE TITLE
Openapi file saasapi.v2.json generates non compilable C# client code

### ISSUE THREAD

**Issue by dgmagno** [RicoSuter/NSwag#3771]
Also opened in https://github.com/microsoft/commercial-marketplace-openapi/issues/24

Steps to reproduce:

1 - Create a class library solution.
2 - Run command `dotnet openapi add url https://raw.githubusercontent.com/microsoft/commercial-marketplace-openapi/main/Microsoft.Marketplace.SaaS/2018-08-31/saasapi.v2.json`

This doesn't happen with `meteringapi.v1.json`

Tested targeting `netcoreapp3.1`, `net5.0` and `net6.0` in Visual Studio 2022.

The file `saasapi.v2.json` becomes invalid if I upgrade `NSwag.ApiDescription.Client` to latest version `13.14.8` with the following error:

```
1>Newtonsoft.Json.JsonSerializationException: Required property 'scopes' not found in JSON. Path 'components.securitySchemes.AADToken.flows.clientCredentials', line 839, position 11.
```

**Comment by RicoSuter** [comment]
What version have you been using before?

**Comment by dgmagno** [comment]
I've just started using it, there was no version before. I don't know if there is a working version of `NSwag.ApiDescription.Client` and/or `saasapi.json` that generates a compilable csharp client.
