### ISSUE TITLE
OpenApiMediaType example not using SerializerSettings

### ISSUE THREAD

**Issue by marspion** [RicoSuter/NSwag#3782]
Package: NSwag.AspNetCore
Version: 13.14.8

Description: When adding custom response example via IOperationProcessor, value is serialized without consuming json serializer configuration (operations without custom examples are serialized correctly).

Set custom response example:
```csharp
public override bool Process(OperationProcessorContext context)
{
    var openApiResponse = context.OperationDescription.Operation.Responses[HttpStatusCode.OK.ToString("D")];
    var openApiJsonMediaType = openApiResponse.Content[MediaTypeNames.Application.Json];
    openApiJsonMediaType.Example = new TestEndpointResponse
    {
        Id = 5,
        EnumValue = TestEnum.ExampleEnumValue
    };

    return true;
}
```

OpenApiDocument configuration:
```csharp
services.AddOpenApiDocument(config =>
{
    var serializerSettings = new JsonSerializerSettings
    {
        ContractResolver = new CamelCasePropertyNamesContractResolver(),
        Converters = new List<JsonConverter>
        {
            new StringEnumConverter()
        }
    };
    config.SerializerSettings = serializerSettings;
});
```

Swagger endpoint preview with custom example
![endpoint-with-custom-example](https://user-images.githubusercontent.com/26922839/145039273-d3a80db1-1a66-4bf9-8577-0882a9178f82.jpg)

Swagger endpoint preview without custom example
![endpoint-without-custom-example](https://user-images.githubusercontent.com/26922839/145039291-6d965255-60b7-4297-a986-dea3d169e336.jpg)

**Comment by RicoSuter** [comment]
Serializer settings is used to generate schemas... this here is using the internal OpenAPI spec serializer. These two are not the same... you probably want to use an anonymous type or JsonProperty attributes etc.

**Comment by marspion** [comment]
If I understood correctly there is no chance to configure it "globaly" for every example object with same configuration?

**Comment by RicoSuter** [comment]
It's not a good idea to expose this serializer/config as this could completely mess up the serialization... so it's better to deserialize your object to JObject and then just assign that.

**Comment by marspion** [comment]
Ok, thank you for help!
