### ISSUE TITLE
Releases are missing msi assets since 13.15.2

### ISSUE THREAD

**Issue by AroglDarthu** [RicoSuter/NSwag#3791]
It looks like the latest releases are missing the MSI assets. See https://github.com/RicoSuter/NSwag/releases/tag/v13.15.2 and https://github.com/RicoSuter/NSwag/releases/tag/v13.15.3

v13.15.2 also mentions `Fix MSI installer (correct binary versions)` in the release notes, so would be nice to be able to grab it ;-)

**Comment by RicoSuter** [comment]
Updated https://github.com/RicoSuter/NSwag/releases/tag/v13.15.3
(v13.15.2 is broken, no artifacts there)
