### ISSUE TITLE
v13.15.5.0 fatal error when generating Csharp client

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [RicoSuter/NSwag#3795]
Error does not exist in 13.15.4.0.

![image](https://user-images.githubusercontent.com/68246095/146268025-684a0903-86aa-4818-b6ab-9786f688ac49.png)

**Comment by RicoSuter** [comment]
With v13.15.5 I can see this file in the install directory: 

![image](https://user-images.githubusercontent.com/2603405/146277408-1c8822d0-5e79-419e-a51c-61839e50f52c.png)

Please update and try again.

**Comment by ErikPilsits-RJW** [comment]
Weird, works now. Only difference was first time I did the in-app prompted upgrade, and this time downloaded and ran the installer. Oh well, guess it was a fluke.
