### ISSUE TITLE
[Question] Register NSwag Client with Net6 default DI  

### ISSUE THREAD

**Issue by rm-code** [RicoSuter/NSwag#3797]
I'm fairly new to using NSwag and created a Client Class with NSwagStudio which always turns out to include the `baseUrl` in the constructor.

```c#
public partial class Client : IClient
{
  private string _baseUrl = "";
  // ...

  public Client(string baseUrl, System.Net.Http.HttpClient httpClient)
  {
    BaseUrl = baseUrl;
    // ...
  }
```

Adding this to the DI as is, it fails (naturally) with:
`InvalidOperationException: Unable to resolve service for type 'System.String' while attempting to activate 'Services.Client'.`

So my current workaround is to use a "Wrapper" Client Class:
```c#
  public class WrapperClient : Client
  {
    public WrapperCliet(HttpClient httpClient) : base("[URL]", httpClient)
    {
    }
  }
```
But that's not ideal.

So can anybody help me with fixing the DI for Net6. Or did I maybe miss a setting when creating the Client Class?

**Comment by BobInstallaties** [comment]
if you uncheck the "Use the base URL for the request", the generation of the base url is omitted.
You can find it on the settings tab underneath the CSharp Client tab.

![image](https://user-images.githubusercontent.com/92821518/146570293-26843002-8e21-4a39-b3e3-a466f7cf0859.png)

**Comment by rm-code** [comment]
Wow ... not sure how I could've missed that. I'm pretty sure I unchecked that, but maybe I forgot to update the output. 

Thank you!
