### ISSUE TITLE
Client name generation behavior change when using `MultipleClientsFromOperationId` since v13.15.0

### ISSUE THREAD

**Issue by kapsiR** [RicoSuter/NSwag#3805]
## Prerequisites
 - OperationGenerationMode: `MultipleClientsFromOperationId`  
    > Multiple clients from the Swagger operation ID in the form '{controller}_{action}'.

 - OperationId with more than one underscore.

## Description
With [v13.15.0](https://github.com/RicoSuter/NSwag/releases/tag/v13.15.0), the generation of the client name changed when using `MultipleClientsFromOperationId`.  

#### Before
OperationId `MyController_MyRouteWith_Underscore` resulted in `MyRouteWithClient.Underscore`

#### Now
OperationId `MyController_MyRouteWith_Underscore` results in `MyControllerClient.Underscore`

## Affected code, that introduced the behavior change
`\src\NSwag.CodeGeneration\OperationNameGenerators\MultipleClientsFromOperationIdOperationNameGenerator.cs`:  
https://github.com/RicoSuter/NSwag/commit/87d7ca7ba79d939ecc7977f36953249980e1f57a#diff-82c1e6256b123bf258c020a6c95553e38db251620bb7ef7af76bef5fd91ea52bR74-R80

## Reproduced the behavior change
[SharpLab example for verification](https://sharplab.io/#v2:C4LgTgrgdgNAJiA1AHwAICYCMBYAUKgBgAJVMA6AGQEsoBHAbjzwDcBDMIgewAcBTMVsCqcoASThEAvEQBEAWQCeAYRHAwnADYb+AfUUAlThGC8A6lWAALHQFUocfgGcAxpzC8ZjXER++feAHoAoiheAHcQEkwANiJ9XlY4AHkoDQUAZW5WKAAeZ0t2AD4iAHFeYCUNKl4oYAA5VgBbXgAKJL4oAEFuKnb+QWEoLj4BIREAShZ2Iio4AA8pYf6xsTgyUXteOaSAMxaAch198a82Dmcqmvqm3kzsxdmFgEJpAFpMIgAyT5n5ohylqNBuJKDUAOZWIivIgfAD8gIGIhBnUcdygLQIMF+c3GREipAIZAAoo1uMAFGQUWiWic8KQAJwtC7VWoNZposgAFU46TUNDBNNpuECwU0CCixDKFUurJubQ63V6I0RQx4y0Gk1wZyIjl4YOatUcizVQKRa0yVWAByO4zI8WYTlatu5nTAAgUNNO02ZVzZtz1BuAi11+qujlBUAhliIhWk6CI8JDgccAG1MABdPES4mk8leBlMmXXdkBq5Cvx+IA)

**Comment by kapsiR** [comment]
There is one more case that gets lost with the new behavior: `underscorelast_` previously resulted in `underscorelast`, now it's an empty string.

@RicoSuter Do you accept a PR for this or is this an intended change?

**Comment by kapsiR** [comment]
@RicoSuter May you provide any information whether I should contribute a PR or ignore this issue? 😃

Thanks

**Comment by RicoSuter** [comment]
I think this change was not intended, right @lahma?

**Comment by lahma** [comment]
Sounds like a bug, All changes were meant to keep existing behavior, but improve processing performance (usually less LINQ).
