### ISSUE TITLE
Add override keywords on method of extended classes

### ISSUE THREAD

**Issue by rhegner** [RicoSuter/NSwag#3809]
[TypeScript 4.3 introduced the `override` keyword and the `noImplicitOverride` flag](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-3.html#override-and-the---noimplicitoverride-flag). In my project, that flag is set, so I get errors in my auto-generated extended classes, because the `init`, `fromJS`, and `toJSON` methods are lacking the `override` keyword.

Suggestion: When generating code for TypeScript >=4.3, always add the `override` keyword to methods.

**Comment by jackzhum** [comment]
I have this problem, too.

**Comment by lahma** [comment]
https://github.com/RicoSuter/NJsonSchema/pull/1489
