### ISSUE TITLE
axios CancelToken is deprecated

### ISSUE THREAD

**Issue by dariusbuinovskij** [RicoSuter/NSwag#3849]
Starting from 0.22 axios CancelToken is deprecated and should not be used in new development. Some details [here](https://axios-http.com/docs/cancellation).
Can axios template can be updated so it doesn't use deprecated features from axios?

**Comment by RicoSuter** [comment]
Can you create a PR against the templates?

**Comment by dariusbuinovskij** [comment]
Axios related work is paused for few weeks now. I shall back to it during February and then I can prepare pull request.
