### ISSUE TITLE
Do IDocumentProcessors execute before or after IOperationProcessors?

### ISSUE THREAD

**Issue by davidkeaveny** [RicoSuter/NSwag#3854]
I'm trying to tidy up my OpenAPI document by creating standard responses in the Components/Resources section (as described in https://swagger.io/docs/specification/describing-responses/#reuse). I was hoping to use an `IDocumentProcessor` implementation to register my standard responses, and then have an `IOperationProcessor` to apply the reference depending on the method (e.g. so all `GET` methods named `GetById` would automatically reference the `NotFound` response). However, it seems operation processors run before the document processor, so that approach isn't working.

The problem that I have is my OpenAPI definition is growing in size very rapidly, as each operation that returns a `ProblemDetails` or `ValidatingProblemDetails` for 4xx responses is currently generating a new inline definition in the OpenAPI document, rather than doing it once-for-all. I'm using operation processors to automatically add the appropriate `OpenApiResponse`, including the example and schema - here's a [snippet of one such endpoint](https://gist.github.com/davidkeaveny/23c2e83ec3d8b263ce63fc26f620b44a), with responses for 400, 409 and 422

What would be the recommended approach to take? Would it be better, for instance, to look at using [API Conventions](https://docs.microsoft.com/en-us/aspnet/core/web-api/advanced/conventions?view=aspnetcore-3.1#create-web-api-conventions) instead?

**Comment by RicoSuter** [comment]
> However, it seems operation processors run before the document processor, so that approach isn't working.

That's true, document processors are applied AFTER the operation processors. 

> is currently generating a new inline definition in the OpenAPI document

You could add the ProblemDetails or ValidatingProblemDetails to the schemas and reference it instead of generate many of them inline. 

> Would it be better, for instance, to look at using API Conventions instead?

I think with API Convention you can define it once and then they are automatically generated for each operation
