### ISSUE TITLE
Problematic @ts-nocheck in typescript clients

### ISSUE THREAD

**Issue by ovska** [RicoSuter/NSwag#3859]
#3815
Having `@ts-nocheck` in typescript clients by default can cause obscure and hard-to-diagnose problems.

For example, if types aren't imported (`"importRequiredTypes":false`), a completely broken client can be generated, but it doesn't cause compiler errors. It can for example manifest only when actually using the client, when the broken client return type is `any` instead of the actual type.
Another example is the `extensionCode`-feature, where an updated client that changes model properties that an extension method/property uses, the code might compile fine but would produce undefined behavior at runtime.

In my opinion, nocheck should be removed entirely. If users have tsconfigs that cause compiler errors, they should be fixed via custom templates, or creating a pull request (ie. add a new feature flag to nswag).

**Comment by jvalkeejarvi** [comment]
In my opinion having an option for TypeScript 4.3 should be added. If version is 4.3 or newer override modifier should be added to properties/methods that require it. I can make a PR if it would help.

**Comment by lahma** [comment]
I think it would make sense to:

* add TS version 4.4 to configuration file + NSwagStudio
* add new `File.Header.liquid` containing current ts-lint, es-lint, ReSharper lines, without the ts-nocheck 
   * this separate template will be escape hatch for next problem that requires altering template header 
* render it after standard `<auto-generated>` header,  `{% render "File.Header" %}`
* add override logic to `TypeScriptOperationModel.MethodAccessModifier` to check TS version OR this is a bit unclean part, should we have extra property `MethodExtraModifiers` and update templates to use it?

thoughts @RicoSuter ?

**Comment by lahma** [comment]
I did the NJsonSchema part: https://github.com/RicoSuter/NJsonSchema/pull/1489

**Comment by lahma** [comment]
NSwag side: https://github.com/RicoSuter/NSwag/pull/3898
