### ISSUE TITLE
C# client generation with requestbody as text/plain and string

### ISSUE THREAD

**Issue by Ultre00** [RicoSuter/NSwag#3860]
When generating an endpoint that has a requestBody like this:
```yaml
      requestBody:       
        required: true
        content:
          text/plain:
            schema:
              type: string
              minLength: 18
              maxLength: 18
```
The generated C# method does this:
```C#
 var content_ = new System.Net.Http.StringContent(System.Text.Json.JsonSerializer.Serialize(body, _settings.Value));
```
However this adds some extra quotes around the body since we don't want to serialize this as json. This wil make the request invalid. Is there anyway to fix this or does someone have a workaround? (Other than manually altering the generated code)

**Comment by ovska** [comment]
While not optimal, you can probably get away with doing this with some trickery in `PrepareRequest(Async)` in a partial class file, by doing some manipulation on the request if it matches your plaintext criteria.
You probably need to deserialize the content in case the serializer escaped some double quotes.

Here's an quick and dirty example:
```cs
protected ValueTask PrepareRequestAsync(
    HttpClient client,
    HttpRequestMessage message,
    StringBuilder urlBuilder)
{
    if (message.Content is StringContent existingContent &&
        existingContent.Headers.ContentType?.MediaType == "text/plain")
    {
        var payload = await JsonSerializer.DeserializeAsync<string>(
            await message.Content.ReadAsStreamAsync(),
            _settings.Value);
        message.Content = new StringContent(payload!);
        message.Content.Headers.ContentType = existingContent.Headers.ContentType;
    }
}
```
