### ISSUE TITLE
Unable to force binaries version using /runtime 

### ISSUE THREAD

**Issue by GStoynev** [RicoSuter/NSwag#3885]
Using this version of nswag on Windows 11 Pro:
```
NSwag NPM CLI
NSwag command line tool for .NET Core Net60, toolchain v13.15.9.0 (NJsonSchema v10.6.8.0 (Newtonsoft.Json v13.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\gstoynev\AppData\Roaming\npm\node_modules\nswag\bin\binaries\Net60

NSwag version: 13.15.9.0
NJsonSchema version: 10.6.8.0 (Newtonsoft.Json v13.0.0.0)
```

Like this:
`nswag version /runtime:NetCore31` results in 
![image](https://user-images.githubusercontent.com/1644199/154132582-eef0dd7e-3405-4d23-8431-5aeacfe5d3c0.png)

Using it like this:
`nswag run ".\api.nswag.json" /runtime:NetCore31`
or
`nswag run .\api.nswag.json /runtime:NetCore31`
or
`nswag run api.nswag.json /runtime:NetCore31`

Results in 
`System.InvalidOperationException: The specified runtime in the document (NetCore31) differs from the current process runtime (Net60). Change the runtime with the '/runtime:NetCore31' parameter or run the file with the correct command line binary.
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 68
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 32
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61node:child_process:903
    throw err;
    ^`

I can see that different binaries are installed:
![image](https://user-images.githubusercontent.com/1644199/154132130-b4cfa119-2909-49a8-adb0-b2e8a8476a66.png)

And I do have the 3.1 SDK installed (not sure if needed)

Am I doing something incorrectly or there is a bug around the runtime parameter?

**Comment by GStoynev** [comment]
I was able to explain it. You need to be looking at the code of nswag.js to make sense of this: 
On a machine where the installed dotnet version ("coreVersion" in the nswag.js script) matches the currently "tested" version in the loop we end up executing in the else statement and then returning. Since 6.0 is the first one we test for and my machine happens to have dotnet 6, the script never has a chance to test for and execute runtime31. I assume the author(s) had a reason for that else statement, but in my case it doesn't make much sense:
![image](https://user-images.githubusercontent.com/1644199/154153967-99e57a0c-12e8-4b3f-b8e3-5032c28b9efb.png)

**Comment by RicoSuter** [comment]
Seems to be a regression or a problem in this: 
https://github.com/RicoSuter/NSwag/pull/3862

**Comment by RicoSuter** [comment]
Can someone create a PR to improve this nswag.js file?

**Comment by ovska** [comment]
I think it has to do with the fact that #3862 reversed the order (to newest .net version first). 

@GStoynev I was able to reproduce this. Can you try to reverse the items in `nswag.js`'s `supportedCoreVersions` manually and see if it fixes it for you as well?

**Comment by GStoynev** [comment]
Yeah, that's how I fixed it for me yesterday. I didn't suggest this or issue a PR because I don't know enough to judge if the reversal "reverses" the problem - is nswag supposed to be able to execute, say, 6.0 binaries on a system that is, say, at 3.1 level?

I still don't understand authors' thought with the else if (!error) section, considering they have the defaultCmd fall-through. Can someone spell it out for me, please?

**Comment by ovska** [comment]
> is nswag supposed to be able to execute, say, 6.0 binaries on a system that is, say, at 3.1 level?

That's a good point; I'm not sure. `dotnet --version` Doesn't tell the full story either. Best would probably be to check if a runtime is actually installed using `dotnet --info`.
