### ISSUE TITLE
C# Client - Add CancellationToken parameter to PrepareRequestAsync

### ISSUE THREAD

**Issue by crackalak** [RicoSuter/NSwag#3919]
When `GeneratePrepareRequestAndProcessResponseAsAsyncMethods` is enabled, `PrepareRequestAsync` and `ProcessResponseAsync` methods are generated, but only `ProcessResponseAsync` is passed the cancellation token. 

https://github.com/RicoSuter/NSwag/blob/67cc25b63a92df49d185dfa15486ba9e60c0db39/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L286

https://github.com/RicoSuter/NSwag/blob/67cc25b63a92df49d185dfa15486ba9e60c0db39/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L295
https://github.com/RicoSuter/NSwag/blob/67cc25b63a92df49d185dfa15486ba9e60c0db39/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L313

**Comment by RicoSuter** [comment]
This seems wrong (dont see a reason why not to add it in all three). 
Can you maybe create a PR to fix this?
