### ISSUE TITLE
Suggestion: Inject IHttpClientFactory into generated c# ApiClient 

### ISSUE THREAD

**Issue by EdJohnstonG9** [RicoSuter/NSwag#3968]
I had an issue with authorization and instantiated clients not recognising a changed login status of the application using the API Client

I resolved this by carefully enhancing (hacking) the Client.Class.liquid template so that the values used for injecting a Client actually injected the Client Factory resulting in the following code in the Constructor: 

This allows better lifecycle management for the httpClient and solved getting returns for logged out clients getting returned data and vice versa.

A much better solution might be to add this as an alternative option to the following OpenAPI code tags:
      "injectIHttpClientFactory": true,
      "httpClientFactoryName": "default(string)",
then extending the template properly to automatically generate the code.

```
        private System.Net.Http.IHttpClientFactory _httpClientFactory;
        private System.Net.Http.HttpClient _httpClient => _httpClientFactory.CreateClient(default(string));
        private System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings;

        public AccountClient(System.Net.Http.IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
            _settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings);
        }
```

**Comment by EdJohnstonG9** [comment]
Thanks @ovska I hadn't realised that was a feature (too much looking at NSwag Studio, not enough RTFM)

I do still have a couple of minor issues which can be worked around.
1) Latest .net IHttpClientFactory.CreateClient method requires a String parameter and if added, the current templates create something like: 
`var client_ = new System.Net.IHttp.HttpClientFactory("ApiClient")();`
Not difficult to work around of course but ties the inject to a specific implementation or inherited interface.
2) My choice is to create multiple classes `"operationGenerationMode": "MultipleClientsFromOperationId"`  which would mean (if I understand correctly) generating a lot of partials
Again I think I could work around this by using a `clientBaseClass` rather than partials

So thanks- I will rework to use standard templates and this approach with these minor tweeks!

**Comment by ovska** [comment]
Shared base class should be the way to go here. If I recall, I've at one point used something like this on a client base class:
```cs
protected virtual ValueTask<HttpClient> CreateHttpClientAsync(CancellationToken token = default)
{
    return new(_httpClientFactory.CreateClient(""));
}
```

You can actually create clients without the name-parameter, which will just default `""` (see [HttpClientFactoryExtensions](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Http/src/HttpClientFactoryExtensions.cs#L18) and [Options.DefaultName](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Options/src/Options.cs#L19)).

If you need separately configured HttpClients, you can use something like this:
```cs
partial class ClientBase
{
    protected abstract string HttpClientName { get; }

    protected virtual ValueTask<HttpClient> CreateHttpClientAsync(CancellationToken token = default)
    {
        return new(_httpClientFactory.CreateClient(HttpClientName));
    }
}
```
```cs
class SomeClient : ClientBase
{
    protected override string HttpClientName => nameof(SomeClient);
}
```

**Comment by EdJohnstonG9** [comment]
Yup @ovska - I had got about 2/3 towards the same solution when your answer came in (with rather neater implementation I might add)

Re named clients, I think it would be confusing and poor practice to have a single API with multiple different named Clients, so would expect a simple constant in the Base should be sufficient.

But, I am back to my original issue; how to inject the singleton HttpClientFactory.
I dont think I can inject this in the Base without having to call it (and thus inject it) from the Inherited Client.
I cannot fudge the `"injectHttpClient"` as that breaks other uses of `"httpClientType"`
So I think I need a much simpler tweek to the Templates to accommodate this.

Am I missing something?

**Comment by ovska** [comment]
If you don't need any other services in every client, you can use `"configurationClass": "System.Net.Http.IHttpClientFactory"` in .nswag and create a protected constructor to your shared base class which accepts the factory as the single parameter. Nswag should generate a call to the base constructor using the configuration object, which you are then free to use, e.g. set to a protected field.

**Comment by EdJohnstonG9** [comment]
Ah- which is the answer to 'am I missing something'
Yes that is exactly what I needed. Thanks again for your time @ovska
