### ISSUE TITLE
FileNotFoundException when using an /input: path command with spaces

### ISSUE THREAD

**Issue by ebesic-bluefield** [RicoSuter/NSwag#3989]
Problem:
NSwag.exe throws a TargetInvocationException -> FileNotFoundException if the information behind /input: contains a space. 

Steps to reproduce:
Put a swagger.json in C:\Path With Spaces\data\swagger.json

Run 

`NSwag.exe openapi2csclient /className:Test /namespace:Testing2 /input:C:\Path With Spaces\OpenAPIs\swagger.json /output:C:\testdata\swaggerClient.cs`

Response: 

> System.Reflection.TargetInvocationException: Het doel van een aanroep heeft een uitzondering veroorzaakt. ---> System.IO.FileNotFoundException: Kan bestand C:\Path niet vinden.
>    bij System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    bij System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    bij System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    bij System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
>    bij System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
>    --- Einde van intern uitzonderingsstackpad ---
>    bij System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    bij System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    bij System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    bij NJsonSchema.Infrastructure.DynamicApis.FileReadAllText(String filePath)
>    bij NSwag.OpenApiDocument.<FromFileAsync>d__58.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NSwag.Commands.OutputCommandBase.<ReadSwaggerDocumentAsync>d__5.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NSwag.Commands.InputOutputCommandBase.<GetInputSwaggerDocument>d__12.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<<RunAsync>b__83_0>d.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>d__83.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NSwag.Commands.CodeGeneration.SwaggerToCSharpClientCommand.<RunAsync>d__82.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NConsole.CommandLineProcessor.<ProcessSingleAsync>d__12.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij NConsole.CommandLineProcessor.<ProcessAsync>d__11.MoveNext()
> --- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
>    bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bij NConsole.CommandLineProcessor.Process(String[] args, Object input)
>    bij NSwag.Commands.NSwagCommandProcessor.Process(String[] args)

Note:
This also happens with Visual Studio if your repository is in a user folder with a firstname and a lastname (in visual studio it shows that it returns -1)

**Comment by ebesic-bluefield** [comment]
Putting single quotes (') or double quotes (") around the path does not parse correctly (NotSupportedException)

**Comment by bellash13** [comment]
This is not an issue with the software since you need to escape white space with `"` in command line... See this 

`NSwag.exe openapi2csclient /className:Test /namespace:Testing2 /input:"C:\Path With Spaces\OpenAPIs\swagger.json" /output:"C:\testdata\swaggerClient.cs"`

**Comment by ebesic-bluefield** [comment]
> This is not an issue with the software since you need to escape white space with `"` in command line... See this
> 
> `NSwag.exe openapi2csclient /className:Test /namespace:Testing2 /input:"C:\Path With Spaces\OpenAPIs\swagger.json" /output:"C:\testdata\swaggerClient.cs"`

Huh. I was so very sure that i tested this and got a NotSupportedException, but it looks like I missed something. Thanks! Guess I can suggest this fix in the visual studio github.
