### ISSUE TITLE
System.Text.Json sometimes generated a client with mixed references

### ISSUE THREAD

**Issue by oduis** [RicoSuter/NSwag#4121]
See, screenshot. The Serializeroptions are correctly using System.Text.Json, while the Serialize itself references the old Newtonsoft.
Feel free to PM me for a repro.

![image](https://user-images.githubusercontent.com/16719086/186916099-f60fa3b2-1222-49e6-a795-376d62729fbc.png)

**Comment by b-mcbride** [comment]
Experiencing the same issue today

**Comment by b-mcbride** [comment]
@oduis Is your API specification file large?  The one I am dealing with is over 4MB and I suspect that may be the issue.

**Comment by oduis** [comment]
Mine is small, just 10kB.

**Comment by b-mcbride** [comment]
OK I think I figured it out...

If you look at https://github.com/RicoSuter/NSwag/blob/v13.15.10/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L208 it would appear that NSWAG always uses Newtonsoft when dealing with operations that consume "application/x-www-form-urlencoded".

Technically, NSWAG advertises `System.Text.Json` support as "experimental/incomplete" so this must be an example of that

**Comment by RandyWilkinson** [comment]
This issue is affecting me as well and took some time to track down.

This bug was caused by this PR:
https://github.com/RicoSuter/NSwag/pull/3309

But there is a PR with the fix already here:
https://github.com/RicoSuter/NSwag/pull/4172

@RicoSuter - Could you take a look at this PR ^^. Seems like a straightforward fix.

**Comment by olegd-superoffice** [comment]
It looks like it was fixed by #4402
@oduis can you test it with v13.18.3 or later?

**Comment by oduis** [comment]
Just tested, looks great now, thanks!
