### ISSUE TITLE
Please generate json in variable instead of StringContent constructor

### ISSUE THREAD

**Issue by dlidstrom** [RicoSuter/NSwag#4131]
In generated clients the json serialization of posted bodies is directly passed to the StringContent constructor. This removes a possibility to inspect the json that is sent. Please use a variable to hold the json before it is passed to StringContent. That would allow to see what is ultimately sent to the server. I.e.

```csharp
var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(hotels, _settings.Value);
var content_ = new System.Net.Http.StringContent(json_);
content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
request_.Content = content_;
request_.Method = new System.Net.Http.HttpMethod("POST");
request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));
```

**Comment by lahma** [comment]
Maybe you could create a PR to to split that separate variable?

**Comment by dlidstrom** [comment]
I am giving it a shot.
