### ISSUE TITLE
NSwagStudio MSI link broken?

### ISSUE THREAD

**Issue by awdorrin** [RicoSuter/NSwag#4158]
On this page https://github.com/RicoSuter/NSwag/wiki/NSwagStudio
The link for the MSI installer of NSwagStudio
brings you here: https://github.com/RicoSuter/NSwag/releases
and there is no MSI file for NSwag v13.17.0
I do see it for v13.16.1

**Comment by lahma** [comment]
I've updated the release with the missing artifacts, please try now.
