### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by gajdusep** [RicoSuter/NSwag#4194]
We are currently onboarding .NET 7 (preview) in our project and ran into problems when using `NSwagExe_Net60`:
`System.TypeLoadException: Could not load type 'System.Numerics.INumber1'` (interface added in .NET 7).

The reason for the failure is that NSwag generator runs using .NET 6 runtime and tries use reflection to load .NET 7 dll.

**Is there a plan to add .NET 7 support?**
I guess the PR would be very similar as: https://github.com/RicoSuter/NSwag/pull/3632/

Our hack to test the functionality meanwhile is to change `Microsoft.NETCore.App` and `Microsoft.AspNetCore.App` properties to current preview .NET 7 version (e.g. 7.0.0-rc.2.22472.3) in `tools\Net60\dotnet-nswag.runtimeconfig.json` in the .nuget folder.

**Comment by alsami** [comment]
Should be fixed with #4220
