### ISSUE TITLE
Question: could I include the controller xml documentation?

### ISSUE THREAD

**Issue by WeihanLi** [RicoSuter/NSwag#4215]
Hi there, could we include the controller xml documentation?
I had configured the project file to generate the xml documentation file, while it does not work for the controller documentation

**Comment by WeihanLi** [comment]
> Did you remember to include the documentation in the swagger doc

@ovska  I do generate the xml documentation file, while find no API to include the xml documentation

**Comment by StingyJack** [comment]
@WeihanLi - I get the controller documentation in the swagger doc

![image](https://user-images.githubusercontent.com/15381181/204141277-2852ad52-8183-4b55-9c9a-696efe901913.png)

And they are also on the generated client. 
![image](https://user-images.githubusercontent.com/15381181/204141340-3c6f05c1-c51e-4357-af9f-3937551dfe09.png)


Are you referring to something else? If so, can you give an example?

**Comment by WeihanLi** [comment]
Hi @StingyJack , that's documentation comment from the action method, I can get that also, while I cannot get the controller class documentation comment info

**Comment by StingyJack** [comment]
What would an aspdotnet controller be equivalent to in an Open API Spec json?  I dont think there is any place to put just the controller comments unless they were used as the beginning of each method's comments. 

Do you have an example of what you would expect the result to look like?

**Comment by WeihanLi** [comment]
![image](https://user-images.githubusercontent.com/7604648/204174352-225132cf-cc35-43df-a169-2497f4c6ec95.png)

There's a sample supported by [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore)
The swagger endpoint is https://reservation.weihanli.xyz/swagger/index.html

**Comment by StingyJack** [comment]
Found this PR that sounds like it was supposed to add support for this.  https://github.com/RicoSuter/NSwag/pull/2949   You may want to try debugging using this code as breakpoint locations

**Comment by WeihanLi** [comment]
Works for now, thank you very much @StingyJack
