### ISSUE TITLE
.Net 7.0.0 now on nuget

### ISSUE THREAD

**Issue by prom3theu5** [RicoSuter/NSwag#4219]
Hi - due to the constraint on the .net 7 packages, we can't install NSwag.AspNetCore in a project using .net 7.0.0 packages now.

![image](https://user-images.githubusercontent.com/1518610/200560079-01e9807b-3aba-4b87-966c-c64a0831c527.png)

**Comment by patrickklaeren** [comment]
Such is the life of third party dependencies, I'm sure Rico is very aware .NET 7 is GA today. So it's just a waiting game.

**Comment by prom3theu5** [comment]
Aye yeah :)

**Comment by luizfbicalho** [comment]
Is there a Preview version that we can use? @RicoSuter

**Comment by Atulin** [comment]
No previews or prereleases yet. The active branches last saw development 2 months ago, so chances are any work necessary to bring this package to .NET 7 isn't started yet.

**Comment by prom3theu5** [comment]
In actual fact I’m using this fine in a project using rc2. It’s just the version constraint states less than 7.0.0. It’s set at 7.0 which doesn’t include the final release

**Comment by Atulin** [comment]
Soo... How annoying is migration to Swashbuckle?

**Comment by prom3theu5** [comment]
I wouldn't - I'd just wait for this - Afaik, Swashbuckle doesn't support client generation or any of that jazz.

**Comment by Atulin** [comment]
That means I won't be able to migrate to .NET 7 for... however long the update takes. It's bad enough that Rider only supports .NET 7 in the EAP version, now packages that had months to prepare are also starting to fail.

**Comment by vpetrusevici** [comment]
I just added this as temporary solution. Works fine
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />

**Comment by trejjam** [comment]
Hello @Atulin, can you, please, explain to me, how your complaining about the free work of others is helpful?

Rico is managing libraries by himself really well, to my opinion. And I do not see a reason why anyone should complain about not publishing an upgrade the day a new feature/sdk is published.

___
I am not a maintainer of the library, yet I try to give to the community. Please go and fix the libraries you are using instead of writing this kind of comments. Thanks

**Comment by Atulin** [comment]
It's not helpful, it isn't meant to be helpful. It's just me venting, that despite .NET 7 having the whole cycle of pre-releases, release-candidates, the whole shebang, some tools and libraries still manage to be behind when the day of release arrives.

**Comment by coen22** [comment]
> I just added this as temporary solution. Works fine
> 
> ```
>     <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
>     <PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />
> ```

Yes, this works and everything in swagger still works too :)

I saw in the NSWag.Generations.AspCore csproj that it's only checking dotnet 5 and 6.
That is probably why nuget gets confused:
Something like this should fix it (not tested):

```
  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[7)" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="[7)" />
  </ItemGroup>
```

**Comment by trejjam** [comment]
It should be fixed soon: https://github.com/RicoSuter/NSwag/pull/4220

**Comment by Dzivo** [comment]
@coen22 i actually get an error even after updating 

```
error MSB3073: The command "dotnet "/root/.nuget/packages/nswag.msbuild/13.17.0/build/../tools/Net60/dotnet-nswag.dll" run nswag.json /variables:Configuration=Debug" exited with code 150.
```

Probably something with Net60 folder

**Comment by Jogai** [comment]
Wait for the nswag package update
