### ISSUE TITLE
Missing NSwagStudio.msi v13.18.0

### ISSUE THREAD

**Issue by aabordalo** [RicoSuter/NSwag#4237]
Hi, Rico.

First of all, thank you for your time and dedication to this project that helps programmers so much.

NSwagStudio.msi installation file is not available for download.

**Comment by lahma** [comment]
You are probably talking about the auto-update feature? I've added the missing bits to release page https://github.com/RicoSuter/NSwag/releases/tag/v13.18.0 , auto update probably requires some work from Rico...
