### ISSUE TITLE
The specified runtime in the document (Net60) differs from the current process runtime (Net70)

### ISSUE THREAD

**Issue by davidkeaveny** [RicoSuter/NSwag#4278]
I have installed `NSwag.ConsoleCore` v13.18.0 using `dotnet tool install`; when I try to run it to generate an OpenAPI document from my ASP.NET Core application based on .Net 6, I get the following error:

```
❯ nswag.exe run /runtime:Net60 open-api.nswag
NSwag command line tool for .NET Core Net70, toolchain v13.18.0.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))
Visit http://NSwag.org for more information.
NSwag bin directory: C:\Users\david.keaveny\.dotnet\tools\.store\nswag.consolecore\13.18.0\nswag.consolecore\13.18.0\tools\net7.0\any

Executing file 'C:\Src\MyProject\open-api.nswag' with variables ''...
System.InvalidOperationException: The specified runtime in the document (Net60) differs from the current process runtime (Net70). Change the runtime with the '/runtime:Net60' parameter or run the file with the correct command line binary.
   at NSwag.Commands.Document.ExecuteDocumentCommand.ExecuteDocumentAsync(IConsoleHost host, String filePath) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 68
   at NSwag.Commands.Document.ExecuteDocumentCommand.RunAsync(CommandLineProcessor processor, IConsoleHost host) in /_/src/NSwag.Commands/Commands/Document/ExecuteDocumentCommand.cs:line 48
   at NConsole.CommandLineProcessor.ProcessSingleAsync(String[] args, Object input)
   at NConsole.CommandLineProcessor.ProcessAsync(String[] args, Object input)
   at NSwag.Commands.NSwagCommandProcessor.ProcessAsync(String[] args) in /_/src/NSwag.Commands/NSwagCommandProcessor.cs:line 61
```

My `open-api.nswag` document starts off as:
```
{
  "runtime": "Net60",
  "defaultVariables": null,
  "documentGenerator": {
    "aspNetCoreToOpenApi": {
      "project": "MyProject.csproj",
      "msBuildProjectExtensionsPath": null,
      "configuration": "Release",
      "runtime": "Net60",
      "targetFramework": "Net6.0",
```

so between the file and my runtime parameters, I'm sure I'm setting the runtime correctly. Am I missing something?

**Comment by holly-hacker** [comment]
This wont be a solution for OP but perhaps it is for people that got here through googling like me.

In my case, my run command was like this:
`$(NSwagExe_Net70) run ../swagger.json /Runtime:Net70`

I got the same error as OP and finally fixed it by just swapping the parameter order:
`$(NSwagExe_Net70) run /Runtime:Net70 ../swagger.json`

The `runtime` option in the config file just got ignored for some reason.

**Comment by BrianL-STCU** [comment]
I ended up having to uninstall the global tool, then add a [_global.json_](https://learn.microsoft.com/en-us/dotnet/core/versions/selection) that set the desired runtime, then reinstall the tool again from that directory. But this also means I can only run that version for the whole machine.

**Comment by davidkeaveny** [comment]
In the end I gave up on the CLI approach, and instead used `NSwag.MSBuild` so that the clients/contracts/controllers were built automatically in a developer's IDE or on the build server.

**Comment by VisualFinesse** [comment]
For those that stumble on this in 2025...

The project I'm working on has a target framework of .NET 48 (YIKES!) and the newest nswag CLI doesn't recognize Net60. Using default runs Net90 which seems to work... Surprisingly. 

```json

{
  "runtime": "Default",

```


`npm nswag@latest`
`nswag version`
toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))

**Comment by edgett** [comment]
> For those that stumble on this in 2025...
> 
> The project I'm working on has a target framework of .NET 48 (YIKES!) and the newest nswag CLI doesn't recognize Net60. Using default runs Net90 which seems to work... Surprisingly.
> 
> {
>   "runtime": "Default",
> `npm nswag@latest` `nswag version` toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))

This did the trick in 2025 with VS Insiders, and Net90 vs Net10.
