### ISSUE TITLE
Wiki Update Request: NSwag.MSBuild

### ISSUE THREAD

**Issue by adeutscher** [RicoSuter/NSwag#4333]
This is a minor documentation issue, but the list on the wiki page for [NSwag.MSBuild](https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild) is not up to date with the properties available in [NSwag.MSBuild.props](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.MSBuild/NSwag.MSBuild.props).

I think that the list needs to be updated to include:

* NSwagExe_Core21
* NSwagExe_Net70
* NSwagDir_Core21
* NSwagDir_Net70

**Comment by RicoSuter** [comment]
Updated.
