### ISSUE TITLE
NSwag.ApiDescription.Client does not create nullable strings when Nullable is enabled

### ISSUE THREAD

**Issue by jkdmyrs** [RicoSuter/NSwag#4390]
NSwag.ApiDescription.Client nuget, version 13.18.2

**Actual:**
Given a .NET 6 project with nullable reference types enabled and a component schema with a nullable string property, the generated class does not contain a nullable string. As a result, the application can throw `NullReferenceExceptions` while dereferencing these properties, something we are trying to avoid by enabling the Nullable .NET feature.

Example:

Nullable enabled
![image](https://user-images.githubusercontent.com/22627705/229975085-85a758a4-0eb1-4762-9522-197312d411ac.png)

The component.schema definition from the openapi document
![image](https://user-images.githubusercontent.com/22627705/229974391-0099112c-72be-43dc-a35f-a67dfa736e43.png)

The generated class - the string is not marked as nullable
![image](https://user-images.githubusercontent.com/22627705/229974716-4b6d2045-513e-4462-bfaf-aab844f5ae2e.png)

**Expected**
The generated class has a nullable string property
![image](https://user-images.githubusercontent.com/22627705/229984559-45f687c7-3ddf-4fb8-91e6-4a0826590937.png)

**Comment by jkdmyrs** [comment]
@RicoSuter if you agree this is an issue that should be fixed, let me know; it's something I would be interested in attempting to fix

**Comment by Numpsy** [comment]
Do you have the option to generate nullable reference types in the client enabled? (```generateNullableReferenceTypes``` I think is the one)

**Comment by jkdmyrs** [comment]
Well that was easy. Thanks.
