### ISSUE TITLE
How to set variables when the value have '='?

### ISSUE THREAD

**Issue by czd890** [RicoSuter/NSwag#4434]
nswag run .\nswag.json /variables:"var1=value1,var2=value2-include-=char"

nswag will truncate `value2-include-=char` to `value2-include-`

**Comment by davidkeaveny** [comment]
Would it help if you escaped the `=` character? Something like:

```
nswap run .\nswag.json /variables:"var1=value1,var2=value2-include-\=char"
```

**Comment by czd890** [comment]
@davidkeaveny thanks!
