### ISSUE TITLE
npm nswag problem

### ISSUE THREAD

**Issue by MoeHamdan** [RicoSuter/NSwag#4521]
Hello

The npm package now is retuning the preview version. This should not be the case, the npm should only install stable releases. May you untag the preview version ?

**Comment by RicoSuter** [comment]
Preview packages have been tagged with "preview". Should be ok now, right?

**Comment by neilrees** [comment]
Sadly, no.  14.0.0-preview003 is still tagged `latest` 
![image](https://github.com/RicoSuter/NSwag/assets/282424/c523f828-2444-4db2-8a22-9e6e98bb9325)

**Comment by RicoSuter** [comment]
Looks good now: 

![image](https://github.com/RicoSuter/NSwag/assets/2603405/f59db6ed-09db-47dc-b817-17d47c92fb6a)

**Comment by neilrees** [comment]
Agreed, correct version now being used again
```
MSBuild version 17.7.3+8ec440e68 for .NET
  npm WARN exec The following package was not found and will be installed: nswag@13.20.0
  NSwag NPM CLI
  ,,,
```
