### ISSUE TITLE
FormData parameter rendered differently in UI with Open API 3.0 and 2.0

### ISSUE THREAD

**Issue by mihail-brinza** [RicoSuter/NSwag#4582]
I am trying to add a parameter that would allow me to upload files in the Swagger UI, and I'm using the following definition:
```csharp
context.OperationDescription.Operation.Parameters.Add(new OpenApiParameter()
{
    Type = JsonObjectType.File,
    Description = "Image to upload",
    Kind = OpenApiParameterKind.FormData,
    IsRequired = true,
    Name = "image",
});
```

When I am using OpenApi spec 2.0, it works as expected: it displays the `Choose File` button, and it correctly appends the file content.
![image](https://github.com/RicoSuter/NSwag/assets/15001000/4f3d6116-4865-48a4-9572-e54b433f2f24)

However, when enabling Open API 3.0 using: `settings.GeneratorSettings.SchemaType = SchemaType.OpenApi3`, the `Choose File` button disappears:
![image](https://github.com/RicoSuter/NSwag/assets/15001000/734c5612-c4da-49d7-a1f0-effe1ad44f6d)

The json spec generated for the parameter is identical for both versions:
```javascript
{
    "type": "file",
    "name": "image",
    "in": "formData",
    "required": true,
    "description": "Image to upload"
}
```

Is this an issue or am I doing something wrong?

I am using `.NET Framework 4.7.2` and `NSwag 13.20.0`.
Thank you

**Comment by mihail-brinza** [comment]
Hey, yes, so you need to either add a parameter in the controller as "Stream", but this would then make the parameter as a `application/octet-stream`, otherwise you need to configure the parameter as a body parameter, like so:

```csharp
context.OperationDescription.Operation.RequestBody = new OpenApiRequestBody
{
    IsRequired = true,
    Content =
    {
        ["multipart/form-data"] = new OpenApiMediaType
        {
            Schema = new JsonSchema
            {
                Type = JsonObjectType.Object,
                Properties =
                {
                    ["your parameter"] = new JsonSchemaProperty
                    {
                        Type = JsonObjectType.String,
                        Format = JsonFormatStrings.Binary,
                        IsNullableRaw = false,
                        Description = "some description",
                    }
                }
            }
        }
    }
};
```

**Comment by FunThom** [comment]
Hi @mihail-brinza,
thank you very much, it works! :-)

Best regards,
Tom
