### ISSUE TITLE
Is types2openapi command deprecated?

### ISSUE THREAD

**Issue by jkonecki** [RicoSuter/NSwag#4593]
I use types2openapi command to generate TypeScript code for a set of DTOs as part of my build process. The nice feature of this command is that it doesn't actually start my web project (which performs certain initialization on startup which I don't want to execute during build).

I've noticed that this command has been removed from NSwag 14.0.

Does it mean that the only way to generate OpenAPI spec is to use aspnetcore2openapi command (which will internally start the project)?

**Comment by patrickklaeren** [comment]
https://github.com/RicoSuter/NSwag/issues/4524
