### ISSUE TITLE
Enums not part of endpoints not genereted

### ISSUE THREAD

**Issue by jonas-lindstedt** [RicoSuter/NSwag#4641]
Before NSwag 14 (and .NET 8), we used typesToOpenApi and explicitly specified assemblyPaths/classNames in nswag.json. By doing that, we got enums generated, which was not part of the API (endpoints) also, for use in the front-end TypeScript code.

But after switching to NSwag 14 and referencing the CS project instead, everything worked, except for those enums, which never got generated.

It sort of makes sense, but it was still nice to get them generated. A workaround I did, was to include them as endpoints in a "dummy" controller, but this doesn't seem to be the cleanest solution.

Is there another better way to do this with the new version?

**Comment by lahma** [comment]
See https://github.com/RicoSuter/NSwag/issues/3441#issuecomment-1246390025

**Comment by jonas-lindstedt** [comment]
Thanks a lot! Worked like a charm. This issue can be closed.
