### ISSUE TITLE
NSwag.MSBuild (14.0.0-preview012) rewrites nswag.json file and deletes many settings

### ISSUE THREAD

**Issue by alex1ozr** [RicoSuter/NSwag#4660]
Hello!
I'm currently updating my project to .NET 8 with the latest version of NSwag (14.0.0-preview012). I am encountering an issue with configuring documentGenerator/aspNetCoreToOpenApi section in nswag.json.
I cannot set `"useHttpAttributeNameAsOperationId": true`.

Everytime I build [ClientGenerator](https://github.com/alex1ozr/DockerTests/pull/3/files#diff-dc658f928431582580a6dafdc641884468d4d3cf3d8e3d33cfb68bb69318f0db) project (yes, I use MSBuild based client generation) it automatically rewrites nswag.json and deletes many (written by me) settings from there.
Here is an [example](https://github.com/alex1ozr/DockerTests/pull/3/files#diff-540ea8f66fc1f389eafbbc8c5bc9b0e80cf21c6e31f042877459dc75cbdb04b0).

Is this behavior expected or is it a bug?
Thank you in advance for your help.

**Comment by krzyhan** [comment]
As I wrote in https://github.com/RicoSuter/NSwag/discussions/4695 the reason is that most properties are moved from command to the Schema.

Right now they can be set in the code directly.

**Comment by alex1ozr** [comment]
@krzyhan ,
I see, thank you!

**Comment by alex1ozr** [comment]
@krzyhan ,
I see, thank you!
