### ISSUE TITLE
Unrecognized pragma directive in C# clients generated by NSwag.MSBuild 14.0.0

### ISSUE THREAD

**Issue by El-Gor-do** [RicoSuter/NSwag#4673]
NSwag.MSBuild 14.0.0 generates invalid C# clients containing an unrecognized pragma directive `pragma restore disable`. This is probably caused by a typo in https://github.com/RicoSuter/NSwag/blob/4d0e6a663f71724cbf5b05c3c50904ba230bc0fa/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid#L8

The correct directive should be `#pragma warning restore 8618 // Set by constructor via BaseUrl property`

**Comment by elafarge** [comment]
I faced the same issue and opened a fix PR here: https://github.com/RicoSuter/NSwag/pull/4674 

I believed the bug was introduced by the following PR: https://github.com/RicoSuter/NSwag/pull/4634/files#diff-65b33706483249f53a8138451372e3d3276b904d815dcb71d0ed0c8786ea2e70R8

**Comment by gaelj** [comment]
In the meantime, I've fixed it by adding this in my `csproj` (to be adapted as necessary regarding Input/Output file name and AfterTargets):

```
  <Target Name="TemporaryFixPragmaInNSwag" AfterTargets="NSwagClient" BeforeTargets="BeforeBuild;BeforeRebuild">
    <PropertyGroup>
      <InputFile>Client.g.cs</InputFile>
      <OutputFile>Client.g.cs</OutputFile>
    </PropertyGroup>
    <WriteLinesToFile File="$(OutputFile)" Lines="$([System.IO.File]::ReadAllText($(InputFile)).Replace('#pragma restore disable', '#pragma warning restore'))" Overwrite="true" Encoding="Unicode" />
  </Target>
```

**Comment by anev-auror** [comment]
I am having the same problem.
