### ISSUE TITLE
NSwag Studio .NET 8 error

### ISSUE THREAD

**Issue by FNERNST** [RicoSuter/NSwag#4686]
Whenever I try to generate TypeScript clients from a .NET 8 assembly or when I generate the clients from an OpenAPI JSON file, I get an error that I'm not running it with .NET 8.0. However, i added the flag "/runtime:Net80". Is there any workaround?

Thanks in advance.

![image](https://github.com/RicoSuter/NSwag/assets/9821932/3c11f7a9-1d13-4503-8612-b7297f901d7f)

![image](https://github.com/RicoSuter/NSwag/assets/9821932/ae679428-337b-42c9-9b2e-490762c8dfb8)

**Comment by lahma** [comment]
Duplicate of #4678
