### ISSUE TITLE
Support Examples

### ISSUE THREAD

**Issue by dmccaffery** [RicoSuter/NSwag#47]
Any possibility of supporting examples for the request/response in the resulting swagger?

My preference would be that the examples be included as a ref in xml documentation, or as a strongly typed instance of the request/response object defined as an attribute (it would have to be a compile time constant, so the request and response example object would need to be a class that inherits from the actual request/response type with a default constructor that supplies values).

**Comment by rsuter** [comment]
And what should we use as property values for the samples?

**Comment by dmccaffery** [comment]
@rsuter: that's why I said the request/response example objects would need to be a class that inherits from the actual request/response objects -- so one could set default values for the properties (and thus the serializer can just serialize as is without having to generate defaults based on the property type). That's a messy way to go, as it clutters the code base with code used for nothing but examples -- maybe provide a means of referencing a separate assembly for examples and locate example types by convention? There is no good solution, which has always been my issue with attempting to automate API documentation.

The only other alternative is to use the xml docs to href an example that the resulting swagger should inline when generated -- then the examples would be maintained as raw JSON/XML/whatever on disk. The downside to this is that the examples aren't strongly typed and will likely fall out of sync with the API.

As I said, no perfect solution -- but swagger generated without examples makes it tough to use for documentation purposes -- great for code-gen, though.

**Comment by RSuter** [comment]
Maybe this solves your problem?

https://github.com/RSuter/NSwag/blob/master/src/NSwag.SwaggerGeneration.WebApi.Tests/OperationProcessors/SwaggerOperationProcessorAttributeTests.cs

**Comment by dermeister0** [comment]
See how it implemented in Swashbuckle:
https://github.com/mattfrear/Swashbuckle.Examples

**Comment by RSuter** [comment]
Ah, I see. This can be implemented with an operation processor: https://github.com/RSuter/NSwag/wiki/Document-Processors-and-Operation-Processors#operation-processors

**Comment by Rzpeg** [comment]
Is there any example of defining example request / response objects for a specific operation ? I am migrating from Swashbuckle to NSwag and this is something I can't find out.

**Comment by RSuter** [comment]
https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by davidkeaveny** [comment]
I've been able to use `IOperationProcessor` to add response samples, but where in the object model can I add request samples? The Redoc code sample shows the use of extension data, but not how to add sample request data.

**Comment by davidkeaveny** [comment]
> Is there any example of defining example request / response objects for a specific operation ? I am migrating from Swashbuckle to NSwag and this is something I can't figure out.

I'm still looking for an example of how to create an example request object; I've had no problem using an `IOperationProcessor` to create example response objects, but the Redoc example given above only shows how to use extension data, and I'm sure that example requests are part of the basic spec, not requiring extensions.

**Comment by RicoSuter** [comment]
See https://blog.rsuter.com/nswag-tutorial-implement-a-custom-operation-processor-to-define-redoc-code-samples/

**Comment by RicoSuter** [comment]
Duplicate of: https://github.com/RicoSuter/NJsonSchema/issues/1010
