### ISSUE TITLE
NSwag 14.0.1 still issues warning CS8618

### ISSUE THREAD

**Issue by vvdb-architecture** [RicoSuter/NSwag#4704]
When compiling with 14.0.1, the generated C# sdk now has the following warning:

~~~
Warning	CS8618	Non-nullable field '_baseUrl' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
~~~

That's because even though the constructor assignes `BaseUrl`:

~~~csharp
            BaseUrl = "https://";
~~~

... the compiler is unable to detect that the `_baseUrl` field is in fact initialized through this property.

The way to get rid of the warning is to assign the field directly:

~~~csharp
            _baseUrl = "https://";
~~~

Also, the warnings reported in issue https://github.com/RicoSuter/NSwag/issues/4467 are still there.

**Comment by AlbertWeinert-RWEST** [comment]
Yes, the pragme restore of 8616 must happens after the ctor. Not after the _baseUrl field

**Comment by powercode** [comment]
I think a better solution is to generate
```csharp
 public string BaseUrl
 {
     get { return _baseUrl; }
     [System.Diagnostics.CodeAnalysis.MemberNotNull(nameof(_baseUrl))]
     set
     {
         _baseUrl = value;
         if (!string.IsNullOrEmpty(_baseUrl) && !_baseUrl.EndsWith("/"))
             _baseUrl += '/';
     }
 }
```

To let the compiler null analysis know that the property setter sets the field _baseUrl.

**Comment by kvansaders** [comment]
> I think a better solution is to generate
> 
> ```cs
>  public string BaseUrl
>  {
>      get { return _baseUrl; }
>      [System.Diagnostics.CodeAnalysis.MemberNotNull(nameof(_baseUrl))]
>      set
>      {
>          _baseUrl = value;
>          if (!string.IsNullOrEmpty(_baseUrl) && !_baseUrl.EndsWith("/"))
>              _baseUrl += '/';
>      }
>  }
> ```
> 
> To let the compiler null analysis know that the property setter sets the field _baseUrl.

In my netstandard2.0 project, this gives: 'MemberNotNullAttribute' is inaccessible due to its protection level.

**Comment by rwb196884** [comment]
this is completely fucked in 14.0.3
```
Error	CS0234	The type or namespace name 'MemberNotNullAttribute' does not exist in the namespace 'System.Diagnostics.CodeAnalysis' (are you missing an assembly reference?)	
```

**Comment by adamhathcock** [comment]
14.0.3 results in the same error as @rwb196884 reducing to 14.0.2 fixes

**Comment by AlbertWeinert-RWEST** [comment]
> Yes, the pragma restore of 8616 must happens after the ctor. Not after the _baseUrl field

Or simply do this.

**Comment by nifklas** [comment]
We're also getting the error again in 14.0.3.

**Comment by mchilicki** [comment]
I also get this error in 14.0.3, on 14.0.2 it works as expected. 

> this is completely fucked in 14.0.3
> 
> ```
> Error	CS0234	The type or namespace name 'MemberNotNullAttribute' does not exist in the namespace 'System.Diagnostics.CodeAnalysis' (are you missing an assembly reference?)	
> ```
