### ISSUE TITLE
NSwagGeneratePrepareRequestAndProcessResponseAsAsyncMethods does not generate async partial methods

### ISSUE THREAD

**Issue by manolitooo** [RicoSuter/NSwag#4724]
Hi,

By having a look into [this closed issue](https://github.com/RicoSuter/NSwag/issues/3247), I'm wondering if I'm doing something incorrectly. But after diving in the NSwag code, it does not seem so. I have found out the following within [Client.Class.liquid](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.CodeGeneration.CSharp/Templates/Client.Class.liquid):

```
{% if GeneratePrepareRequestAndProcessResponseAsAsyncMethods == false -%}
    partial void PrepareRequest({{ HttpClientType }} client, System.Net.Http.HttpRequestMessage request, string url);
    partial void PrepareRequest({{ HttpClientType }} client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
    partial void ProcessResponse({{ HttpClientType }} client, System.Net.Http.HttpResponseMessage response);
{% endif -%}
```
Isn't it missing an "else" block to define the partial methods for the async case? Currently, I am getting the following error:

![image](https://github.com/RicoSuter/NSwag/assets/111123542/a0da7a8a-e83d-4480-8aac-08bdcd693b7e)

And I can confirm the generated code is missing that block of code where it is expected to be written.

Thanks in advance.

**Comment by manolitooo** [comment]
Working as expected. Sorry :).

**Comment by maurictg** [comment]
@manolitooo Do you know why the partial methods aren't created?

**Comment by manolitooo** [comment]
> @manolitooo Do you know why the partial methods aren't created?

It's invalid c#.

**Comment by smourier** [comment]
FWIW, I had the same issue and I resolved it by defining a (common to clients) base class

in settings

```
  "codeGenerators": {
    "openApiToCSharpClient": {
      "clientBaseClass": "BaseClient", 

```
And then for example (you can use Task or ValueTask, your mileage may vary depending on your other settings):

```
public abstract class BaseClient
{
    protected virtual ValueTask PrepareRequestAsync(HttpClient client, HttpRequestMessage request, string url, CancellationToken cancellationToken)
    {
        return ValueTask.CompletedTask;
    }

    protected virtual ValueTask PrepareRequestAsync(HttpClient client, HttpRequestMessage request, StringBuilder url, CancellationToken cancellationToken)
    {
        return ValueTask.CompletedTask;
    }

    protected virtual ValueTask ProcessResponseAsync(HttpClient client, HttpResponseMessage response, CancellationToken cancellationToken)
    {
        return ValueTask.CompletedTask;
    }
}
```

Now you can override this in the class you need to do it.
