### ISSUE TITLE
asp.net core minimal api support - JsonOptions

### ISSUE THREAD

**Issue by Bonuspunkt** [RicoSuter/NSwag#4732]
the generated `swagger.json` `components/schema/_type_/properties` are all in PascalCasing, while its serialized from asp.net core with camelCasing

`SystemTextJsonSchemaGeneratorSettings.SerializerOptions` should be resolved to `Microsoft.AspNetCore.Http.Json.JsonOptions` property `SerializerOptions`

**Comment by stpanzer** [comment]
+1 I would like to see this fixed as well.
