### ISSUE TITLE
Error converting value "NetCore31" to type 'NSwag.Commands.Runtime'

### ISSUE THREAD

**Issue by AvocadoFlour** [RicoSuter/NSwag#4771]
![image](https://github.com/RicoSuter/NSwag/assets/22814697/c914e06a-9881-4a7f-8aad-a3adb4be208f)

I can only critique removing backwards compatibility.
How can I fix this?

**Comment by AvocadoFlour** [comment]
This release is the last one without the error:

**Comment by bhamcane** [comment]
> This release is the last one without the issue: https://github.com/RicoSuter/NSwag/releases/tag/v13.20.0

I'm assuming you found a fix for this since you closed it. Mind sharing what you had to do to make it work?

**Comment by RicoSuter** [comment]
Please update to a .NET version with is not out of support by MS
