### ISSUE TITLE
[bug]  NSwag v14.0.4 breaks on MemberNotNullAttribute, change 'Avoid generating unused _baseUrl (C# gen)'

### ISSUE THREAD

**Issue by sommmen** [RicoSuter/NSwag#4833]
Hello,

The latest release breaks, because of the following commit:
Avoid generating unused _baseUrl (C# gen)  https://github.com/RicoSuter/NSwag/commit/202f3c2d7e413f329d66dd0e18743578151cefa0
![image](https://github.com/RicoSuter/NSwag/assets/8641495/fe888e61-b435-4ae6-95ac-7e831e587470)

```
C:\Repos\lightr\src\Lightr\Lightr\obj\docsClient.cs(573,46,573,59): error CS0122: 'MemberNotNullAttribute' is inaccessible due to its protection level
```
https://github.com/sommmen/lightr/actions/runs/8416578516/job/23043462539?pr=5

The code is public:
https://github.com/sommmen/lightr/tree/dependabot/nuget/NSwag.ApiDescription.Client-14.0.4
Api doc can be found here:
https://github.com/sommmen/lightr/blob/dependabot/nuget/NSwag.ApiDescription.Client-14.0.4/src/Lightr/Lightr/OpenAPIs/docs.json

**Comment by sommmen** [comment]
Related so:

> If your open [documentation][1] you will see that `NotNullWhenAttribute` applies to:
> 
>  - .NET	Core 3.0, Core 3.1, 5, 6, 7, 8
>  - .NET Standard 2.1
> 
> TBH I failed to build lib against `.NET Standard 2.1` also, but you try can either install nuget like [this one][2] or implement this attribute yourself ([like it is done in the runtime][3]), cause AFAIK compiler quite often relies on naming and/or duck typing.
> 
> 
>   [1]: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.codeanalysis.notnullwhenattribute?view=netstandard-2.1
>   [2]: https://www.nuget.org/packages/Nullable
>   [3]: https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/NullableAttributes.cs#L69

https://stackoverflow.com/a/61574692/4122889

My project targets `netstandard2.1` so this should work but it seems to fail for some reason.

**Comment by sommmen** [comment]
this could be a dupe or regression of https://github.com/RicoSuter/NSwag/issues/4704

**Comment by Vogel612** [comment]
Duplicates #4763 in addition

**Comment by vvdb-architecture** [comment]
Same problem in 14.0.5. Our proxies target NetStandard2.0, and it fails there as well.

**Comment by RicoSuter** [comment]
v14.0.6
