### ISSUE TITLE
AllowReferencesWithProperties alternative in v14.0.4

### ISSUE THREAD

**Issue by bonyjose** [RicoSuter/NSwag#4838]
![image](https://github.com/RicoSuter/NSwag/assets/2097150/d28abd67-0115-419f-8837-c3477d70b56f)

after upgrading my API project from 13.20.0 to 14, this property is not available, what should i be using as an alternative?

**Comment by RicoSuter** [comment]
i think its configure.Schema.AllowReferencesWithProperites

**Comment by bonyjose** [comment]
> i think its configure.Schema.AllowReferencesWithProperites
Got it, below is the correct usage if anyone else is has same issue.

![image](https://github.com/RicoSuter/NSwag/assets/2097150/d8f2c13f-85f8-49c9-8f79-29d1e529daf3)
