### ISSUE TITLE
NSwag MSBuild fails on Linux

### ISSUE THREAD

**Issue by jerone** [RicoSuter/NSwag#4929]
I've setup NSwag MSBuild to run my `nswag.json` file according to the instructions here: https://github.com/RicoSuter/NSwag/wiki/NSwag.MSBuild
This works great on Windows. 

However when I try to build the project on my Linux agent on Azure Pipelines, I'm getting the following error:
> /home/azureuser/agent/_work/24/s/&lt;project>/IntegrationTest.csproj(34,3): error MSB3073: The command "/home/azureuser/.nuget/packages/nswag.msbuild/14.0.8/buildTransitive/../tools/Net80/dotnet-nswag run nswag.json /variables:Configuration=Release" exited with code 127.

I can confirm that this folder and file exists on the agent:
![image](https://github.com/RicoSuter/NSwag/assets/55841/0bfd1523-f12f-4f0d-8bf1-4bd27cbc34f2)

However, when I try to execute these files (`.exe` or `.dll`), I'm getting the following errors:
![image](https://github.com/RicoSuter/NSwag/assets/55841/1bf6d40c-da3b-4433-a216-c6fd46200728)

Am I missing something?

**Comment by vid-tlegoff** [comment]
If you do `file dotnet-nswag.dll` you'll see that it's a dll for Windows (MS-DOS). If you want to run it you have to go through the dotnet command `dotnet dotnet-nswag.dll` (I think there's some stuff with Mono / Net Core going on to make this work). 

This is what the MSBuild target does if you use nswag with MSBuild. 

Also, be careful if you pass parameters with paths to files with Windows separators (with backslashes) you may get errors😐.
