### ISSUE TITLE
.Net8 OpenApi Enums

### ISSUE THREAD

**Issue by WeberEric** [RicoSuter/NSwag#4941]
Hi,

is there a problem with enums as endpoint parameters in .Net8; They are now exportet as strings in the specification-file.
if i rollback to .net6 they are exportet correctly as enums.

Thanks.

**Comment by WeberEric** [comment]
https://github.com/RicoSuter/NSwag/issues/4727

**Comment by massimo-lavermicocca** [comment]
The problem still exists in nswagcore cli 14.1 for project targeting .Net8
