### ISSUE TITLE
Look into complex array query parameters

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NSwag#509]
According to http://swagger.io/specification/#itemsObject complex array items are not supported and the code from https://github.com/NSwag/NSwag/issues/492 will never be called for a valid Swagger spec:

> The value MUST be one of "string", "number", "integer", "boolean", or "array".

... and thus the type is never "object" or empty (any type)

This why we may have to further look into this.

Option 1: 
- Leave as is as it does not break anything and may work correctly for some malformed Swagger specs

**Comment by aelbatal** [comment]
You may also look at [this sample](https://github.com/NSwag/NSwag/files/688180/Swagger.Swashbuckle.txt) spec generated by Swashbuckle and is valid according to the official [swagger.io editor](http://editor.swagger.io/) tool

**Comment by xtellurian** [comment]
@RicoSuter is this issue referring to parameters generated in controllers with the `[FromQuery]` attribute?

{asp net core 3}

For example, I have an object a use for paging search results:

The controller action looks like this:

```cs
 [HttpGet("api/search")]
 public async Task<IActionResult> Search([FromQuery] PaginatedResponse query)
{
    // implementation omitted
}
```

```cs
    public class PaginatedResponse
    {
        /// <summary>
        /// Gets or sets how many files to return.
        /// Defaults to 64.
        /// </summary>
        public int Take { get; set; } = 64;

        /// <summary>
        /// Gets or sets how many files to skip before returning.
        /// Defaults to 0.
        /// </summary>
        public int Skip { get; set; } = 0;
    }
```
I can't figure out a way to make these parameters camelCase in the OpenAPI definition

![image](https://user-images.githubusercontent.com/8497130/88022125-0ba08180-cb72-11ea-9b21-3bfb000e4960.png)

How can I make these camelcase?

**Comment by RicoSuter** [comment]
I think you can put [FromQuery("take")] on the properties to change the names

**Comment by jeremyVignelles** [comment]
Closing this in favor of #2708
