### ISSUE TITLE
CSharp client code generation: add ability to change PrepareRequest/ProcessResponse declaration

### ISSUE THREAD

**Issue by BlackGad** [RicoSuter/NSwag#559]
Now when generating CSharp client code u got definitions in client code:
`partial void PrepareRequest(System.Net.Http.HttpClient request, ref string url);`
`partial void ProcessResponse(System.Net.Http.HttpClient request, System.Net.Http.HttpResponseMessage response);`

It is nice behavior for overriding client code with partial logic but bad when u trying to encapsulate methods overriding in base class.

API has methods for base class definition, but base class have no idea about functions above.

So I purpose to add option to Skip functions declaration. It will allow me to define this methods in base class and process with unified logic (for example authorization)

**Comment by rsuter** [comment]
For base class extension you should use the CreateHttpRequeestMessage option

**Comment by BlackGad** [comment]
hm i see. It is strange for me that 2 different methods for similar thing :) Tomorrow will look closer, have no ability to see code now.
