### ISSUE TITLE
nswag jsonschema2csclient lack of functionality 

### ISSUE THREAD

**Issue by BlackGad** [RicoSuter/NSwag#561]
I was a little nuisance lately, sorry :)

This day I tried to integrate NSwag into VS more closelly(WPF XAML behavior for automatically generated client from swagger json) and have some progress. I came to the stage when I need to actually generate client from swagger json and I have 2 options:
1. Create custom msbuild task and generate from code (NSwag.CodeGeneration with several customizations)
2. Use jsonschema2csclient for this (but i cannot afford such level of customization like in 1 option)

Required customization in my case: 
- Extend used namespaces. I share my contract types with nuget package (package will contain client code as well). My swagger document contains few vendorExtensions (Type and Namespaces) for every swagger definition, so I collect them and add as additional namespaces.
- In my swashbuckle swagger UI I use trick for flagged enumerations - Controller method parameter definition: `IEnumerable<FlaggedEnumerationType> scope = null` it is transformed to array of strings in contract.
Unfortunately NSwag cannot guess enumeration name and generates Anonymous type by default (actually in NSwagScheme code i saw that it is even not try for arrays of string nameHint always set to null). I fixed this with ParameterNameGenerator and another vendorExtensions["Name"].

Finally question: is it possible to add some additional custom rules(that not in standard) into NSwagScheme to manage cases above? I will describe in details with documents and client generation code examples if you agree to discuss this issue.

BR

PS: When I finish will send u example. Maybe it would be useful.

**Comment by rsuter** [comment]
I think you need to build your own cmd line tool with the nswag libraries to satisfy your needs...

**Comment by BlackGad** [comment]
I wrote about sample above... Well, I implement another solution for client code generation using NSwag and roslyn. 

Idea is to use MSBuild ability to regenerate(MSBuild Generator) and dynamically include generated code using existen compilable class attributes.

Now to generate any client u just need to include nuget package into project and add special attributes for NSwag generators to any c# class. Tomorrow will upload code to show u results.

I cover Remote/Local swagger document fetch (can be extended with your doc from Assembly). Also implement ability to inject part of path from build, environment and nuget variables to manage easy document discovering from attributes. Leave places for customization (u can set custom Name/Type generators, custom places for document discovering from msbuild)

MSBuild tasks support incremental building and internal caching.

Anyway there is still a lot things to do, but I am afraid that will have lack of time to support this(do my actual work).
It would be great to see this kind of integration in your official releases so I could use 'vanilla' NSwag functionality in our projects.
I could explain u any peace of code by request.

BR

**Comment by BlackGad** [comment]
https://github.com/BlackGad/NswagAutoClientsSample smaples with quick documentation
