### ISSUE TITLE
T4 template documentation needs updated. 

### ISSUE THREAD

**Issue by SirCaliban** [RicoSuter/NSwag#656]
I'm trying to generate a client in visual studio using the sample T4  documentation. The sample "From a Swagger specification in the project" uses SwaggerDocument.FromJson. but that function has been replaced by SwaggerDocument.FromJsonAsync .

**Comment by rsuter** [comment]
Can you create a pr with the updated docs?

**Comment by Richardsonke** [comment]
I have updated code for T4 templates that seems to be working (only tested with CSharp generation).  I don't see how to create a PR for the wiki, though.

**Comment by RSuter** [comment]
You can directly edit it...

**Comment by Richardsonke** [comment]
Ok, wasn't sure if you wanted to review the changes before editing.  I also ran into an issue with the lines like this:

`<#@ assembly name="$(SolutionDir)\build\NSwag\NJsonSchema.dll" #>` 

There's no "build/NSwag" directory when just adding the nuget package, but this seems to work:

`<#@ assembly name="$(TargetDir)\NJsonSchema.dll" #>`

This way it would just reference the output directory (e.g. "bin/Debug/" or "bin/Release/").

**Comment by Richardsonke** [comment]
I did a fork of the code repo and created a wiki page with the updated content: https://github.com/Richardsonke/NSwag/wiki/T4

Do you want to review before I make the changes on the official wiki?

**Comment by RSuter** [comment]
Looks good, please update the official wiki...

**Comment by Richardsonke** [comment]
Wiki updated: https://github.com/RSuter/NSwag/wiki/T4

**Comment by RicoSuter** [comment]
T4 should not be used anymore
