### ISSUE TITLE
Exception thrown when FlattenInheritanceHierarchy set to true

### ISSUE THREAD

**Issue by DDAndyChen** [RicoSuter/NSwag#858]
The cause is a model

```
public class Test{
 public int? Id { get; set; }
 public Metadata Info { get; set; }
}
public class Metadata : Dictionary<string, string>{ }
```

The *Metadata* class will cause an exception at https://github.com/RSuter/NJsonSchema/blob/4da063f1bc4bd77d67d9db9c3bd82bc00768d388/src/NJsonSchema/Generation/JsonSchemaGenerator.cs#L448

>Unable to cast object of type 'Newtonsoft.Json.Serialization.JsonDictionaryContract' to type 'Newtonsoft.Json.Serialization.JsonObjectContract'.\r\n   at async NJsonSchema.Generation.JsonSchemaGenerator.GenerateInheritanceAsync(Type type,JsonSchema4 schema,JsonSchemaResolver schemaResolver)...

When set FlattenInheritanceHierarchy to false, it worked.

**Comment by RSuter** [comment]
Your scenario works for me (see unit tests).

**Comment by RSuter** [comment]
Sorry, referenced from the wrong repository. Commit: 

https://github.com/RSuter/NJsonSchema/commit/6bbadb0ddf412d5ad0a600f9431877046c98f477

**Comment by RSuter** [comment]
Please try again with the latest release and if the problem persisted, please provide a repro
