### ISSUE TITLE
Prerelease nuget packages with their own version numbers

### ISSUE THREAD

**Issue by akamyshanov** [RicoSuter/NSwag#879]
Are there any plans to differentiate nuget prerelease packages based on version? Ideally, prerelease packages on nuget.org. The problem now is that prerelease packages (every commit in master branch) on myget.org have absolutely the same version as stable packages on nuget.org. And even if myget.org source is used in addition to nuget.org one, there is no way to specify whether the project uses a prerelease version or a stable one (or the other way around).

PS. https://github.com/GitTools/GitVersion can be of help here.

**Comment by RSuter** [comment]
Yes, I think this is a good idea - at least have increasing numbers in the CI build...

**Comment by RicoSuter** [comment]
This is done.
