### ISSUE TITLE
DefaultUrlTemplate not picking up areas in .Net Core

### ISSUE THREAD

**Issue by NorfAlrin** [RicoSuter/NSwag#898]
Hi,

My config is defined as:

```
    app.UseMvc(routes =>
    {
        routes.MapRoute(
            "areaRoute",
             "api/{area:exists}/{controller}/{action}/{id?}");
    });
    app.UseSwaggerUi(typeof(Startup).GetTypeInfo().Assembly, new SwaggerUiSettings
        {
            DefaultUrlTemplate = "api/{area:exists}/{controller}/{action}/{id?}",
        });
```

But the generated swagger.json file outputs the routes without the area eg
`api/pet/findByTags`

Where I'm expecting
`api/staff/pet/findByTags`

**Comment by RSuter** [comment]
The placeholder {area} is not supported... how is this retrieved?

**Comment by Saibamen** [comment]
I don't have DefaultUrlTemplate...

**Comment by Saibamen** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/905878/84891179-bc12f580-b09b-11ea-94f2-62cd8ddce9b0.png)

How to change `DefaultUrlTemplate` in `UseSwaggerUi3`?

**Comment by RicoSuter** [comment]
DefaultUrlTemplate is legacy and is not available anymore. Spec can be configured in AddOpenApiDocument(, in UseSwaggerUi3( you specify the ui configs

**Comment by RicoSuter** [comment]
Closed as not relevant anymore (part of asp generator which should not be used for asp net core)

**Comment by Saibamen** [comment]
Legacy, obsolete, ok, but was replaced by...? How I can change it now?

How to map API endpoints by action name (to be able to run Swagger without duplicates) and still able to call this same action with `[POST] api/login` and [POST] api/login/auth` in Postman?

In `services.AddOpenApiDocument(settings =>` I don't have `DefaultUrlTemplate` too

In recent vesion of **NSwagStudio** (13.6.1.0) I can still see this option, so this looks like not obsolete...:

![image](https://user-images.githubusercontent.com/905878/84956242-0b3b4380-b0f9-11ea-98ce-970c56511a2d.png)

Swagger/NSwag have really bad documentation and comments like this "it is legacy, closing without helping" is really bad too. People must spend hours to research Internet and trying 50 different solutions to change simple things.

Pushing release tag **without any changelog** is really stupid IMHO. Where is changelog/braking changes here: https://github.com/RicoSuter/NSwag/releases??? I can't even check and compare commits between versions...

Please see how it is done in normal way on GitHub:
![mpchc](https://user-images.githubusercontent.com/905878/84955981-8f40fb80-b0f8-11ea-89c8-127a42ce15b2.gif)

And this is how it looks on your "OpenSource" NSwag...:
![nswag](https://user-images.githubusercontent.com/905878/84956151-e1821c80-b0f8-11ea-8655-174f911b2f9c.gif)

**Comment by RicoSuter** [comment]
For ASP.NET Core project you should use the "ASP.NET Core via API Explorer" tab and not the "old" ASP.NET generator.

**Comment by Saibamen** [comment]
http://rsuter.com/Projects/NSwagStudio/installer.php download URL not working anymore...

**Comment by RicoSuter** [comment]
Its gone until the build is through, works for me now
