### ISSUE TITLE
Assembly loader: Support custom extension classes

### ISSUE THREAD

**Issue by RicoSuter** [RicoSuter/NSwag#924]
- Swagger generator
	- [x] Document and operation processors, https://github.com/RSuter/NSwag/commit/0aad9f18f8e459f320532323ba8bd25ba3854eb1
	- [x] TypeNameGenerator
	- [x] SchemaNameGenerator
	- [ ] ReflectionService
	- [ ] TypeMappers
	- [ ] SchemaProcessors
	- [x] **All above supported via UseDocumentProvider**, see https://github.com/RSuter/NSwag/pull/1655
- Code generators: 
    - [ ] PropertyNameGenerator 
    - [ ] TypeNameGenerator 
    - [ ] EnumNameGenerator 
    - [ ] TemplateFactory

**Comment by RSuter** [comment]
https://github.com/RSuter/NSwag/commit/0aad9f18f8e459f320532323ba8bd25ba3854eb1

**Comment by RicoSuter** [comment]
assembly loader feature dropped, implement own cli if you need to customize
