### ISSUE TITLE
Single quote in operationId generates bad method names

### ISSUE THREAD

**Issue by kmpm** [RicoSuter/NSwag#982]
I have a swagger definition that a small part of is shown below.
The issue I have is when I generate a Client using "MultipleClientsFromOperationId" this operation will not work.
The method name will have a single quote in (from operationId) it which is not compilable.
I don't know if this is a "valid" definition but the I will most likely not be able to have it changed.

Could you please do some search and replace for this kind of operationId? What it generates really doesn't matter that much as long as it compiles.

```json
{
 "/{id}/HistoryAlarms": {
      "get": {
        "description": "Gets a list of plant's history alarms available to the user.",
        "operationId": "Gets a list of history plant's alarms",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "The id of the plant to fetch the alarms for.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/PagedResult[AlarmListInfo]"
            }
          }
        },
        "produces": [
          "application/json",
          "text/json"
        ]
      }
    }
}
```

**Comment by RSuter** [comment]
MultipleClientsFromOperationId assumes that the operation id is in the form "controllerName_operationName"... Have you tried MultipleClientsFromPathSegments?

**Comment by RSuter** [comment]
Related: https://github.com/RSuter/NSwag/pull/978

**Comment by kmpm** [comment]
For this issue I do have a workaround in that I download the swagger definition and fix it in the file and then generate code from that. But if I forget to do that when I regenerate the client due to changes in the API I get code that doesn't compile.

I have tried from Paths but that will in my case generate multiple methods with the same signature instead which is just as bad.

**Comment by RSuter** [comment]
> I have tried from Paths but that will in my case generate multiple methods with the same signature instead which is just as bad.

This will hopefully be fixed in the linked PR.

**Comment by RSuter** [comment]
You could also write your own command line tool with the NSwag library, load the document and generate the code... This way you can write your own OperationNameGenerator and provide to the generator....
